### ISSUE TITLE
devp2p: tx msg throughput low (50%) compared to Parity Node

### ISSUE THREAD

**Issue by Daniel600** [ethereumjs/ethereumjs-monorepo#1002]
We are using https://github.com/ethereumjs/ethereumjs-devp2p/blob/master/examples/peer-communication.js however when we sort for TX messages and compare to our Parity node - we seem to only get 50% of the TX which our parity node receives

**Comment by holgerd77** [comment]
This should have signifcantly changed with the latest changes and issue is generally pretty old, will close.
