### ISSUE TITLE
devp2p: support for RLPx version 5

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1004]
Have no deep insight on this yet, just dropping here so that it gots not forgotten.

There seems to be a newer version 5 of the `RLPx` protocol we are currently on version 4 (see [BASE_PROTOCOL_VERSION](https://github.com/ethereumjs/ethereumjs-devp2p/blob/master/src/rlpx/peer.ts#L15) setting.

Connections do still work, there needs to be an update nevertheless at some point I guess, also not really aware of the implications.

Some references (feel free to add here):

- Go Ethereum: https://github.com/ethereum/go-ethereum/pull/1821
- pydevp2p: "[WIP] Changes for RLPx version 5
" https://github.com/ethereum/pydevp2p/pull/7 (from 2015, so quite old)

Note: have labelled this "good first issue" since scope should be relatively clear once one is finding some valid specs here 😛, rather a PRO good first issue for someone with networking experience though.

**Comment by holgerd77** [comment]
This is still open and might be a good issue for getting some first exposure to the `devp2p` library (also see the note in the additional comment above) since the issue is very much targeted and small in scope, see the [CHANGELOG](https://github.com/ethereum/devp2p/blob/master/rlpx.md#version-5-eip-706-september-2017) for v5 from the specs (v5 simply and solely adds snappy compression to RLPx messages).

Nevertheless be prepared that changes on the devp2p library generally take more time to be executed upon than changes on other libraries, since it is often more fuzzy to get things tested under different conditions, eventually also write a test within our own devp2p test setup. So this might end up in a day (or two) of work.

In this case we should be on a somewhat safe side when client sync is still running with the changes and it is assured that compression is activated.

Ah, and one thing to consider here: both versions should be supported for some time, even if the version bump if somewhat old, this is just to be fair towards other clients which might not have implemented yet (if someone would drop instantly v4 support our own client would e.g. be cut off the network 😛 ).

So this would mean that an incoming `HELLO` RLPx message (RLPx version is sent there) with a `v4` should be answered with a v4 response.

**Comment by acolytec3** [comment]
I'm coming back to this one now. Had some success getting the underlying snappy library to work right.
