### ISSUE TITLE
New VM API method for Block generation VM.generateBlock()

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1018]
The [VM.runBlock()](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/vm/lib/runBlock.ts) method is meant to run on existing blocks for validation and the API is not really meant for creating a new block, there is some functionality which goes into the direction with the `generate` option, but this functionality is generally problematic by leading to a situation where the block immutability is violated or some unclean workaround needs to be added - see also exchange about this on https://github.com/ethereumjs/ethereumjs-vm/pull/974.

I would suggest to add a new API function which dedicatedly covers the case of Block generation, something like:

```typescript
VM.generateBlock(parentBlock: Block, transactions: Transaction[], options: Opts)
```

This would explicitly targets the case where a new block is just not existing yet but needs to be calculated and processed with Txs from the mempool or whereever. This would also prepare for future client functionality on block creation.

Eventually this can be implemented reusing functionality from `VM.runBlock()`.

**Comment by alcuadrado** [comment]
I don't think I understand this issue. Why would this be in the VM instead of `Block` as a factory method? What would `generateBlock` do apart from instantiating a block with the given values?

**Comment by holgerd77** [comment]
@alcuadrado before running the txs a block literally doesn't exist yet (if you don't just re-run a block but are e.g. on the top of the chain in the client and want to create/propose a new block).

So this should just take in a number of transactions and create the block which would (will) come out of this execution. Do you think this case is already sufficiently covered by the existing API, or are we talking past each other in some other way here?

**Comment by holgerd77** [comment]
I have a new name here, we can simply call this `VM.runTxs()` - instead of focusing so much on the output with the name - find this conceptually more elegant, and then return a `Block` or `BlockData` object.

Question specifically for @jochem-brouwer: you once mentioned this `BlockData` (or so) return in a thread (can't find a reference), any reason to not directly return a `Block` object here?

**Comment by jochem-brouwer** [comment]
I don't really recall this thread, but I think my point would be that just running transactions is rather limited.

Basically, creating a block is a 3-step phase:

1. First initialize the block data (not a really good name, but let me illustrate). This data has the following fields of the block header: `parentHash`, `uncleHash`, `coinbase`, `stateRoot`, `difficulty`, `number`, `timestamp`, `extraData`, `gasLimit`
2. Now, we execute on this context, transactions. So this is where we would actually dump in a list of transactions, and let VM generate the following fields of the header: `stateRoot`, `receiptTrie`, `bloom`, `gasUsed`
3. Now we have enough data to actually send a challenge to a miner. The miner should then report which `mixHash` and `nonce` we should use. 

Now we finally have a valid block. The point is, that with just `runTxs`, we do not have freedom to change on which parent block it runs on (so the initial state root), the timestamp, and the coinbase. (The other fields are also somewhat important).

**Comment by holgerd77** [comment]
Ah, I am very much ok that this includes all from the above. This was just about suggesting a name. Not sure if it's too simple, but it is generally not possible to capture everything with a name and stay simple at the same time (as `VM.runBlock` is also not called `VM.runBlockAndAttributeUncleAndMinerRewards()`). 😜

Not sure, was just an additional possibility thrown in the ring.

**Comment by holgerd77** [comment]
(actually thanks, this is a good description of everything which needs to be done, likely helpful for implementation)

**Comment by jochem-brouwer** [comment]
So a small extra remark: it would make sense to combine (1) and (2) into a method in VM. Not sure of the name yet, I don't think that `VM.runTxs` is a descriptive name here. Maybe something like `VM.buildPendingBlock(blockData, transactions)`? Here `blockData` is the header data of point (1), and transactions is a list of transactions to run. It outputs an invalid block (since we have not done any PoW). Alternatively, we can also create a new block type, but I don't think it adds much value.

For (3) we would probably create a method in `block`, something like `mine()`, which would be a Promise which either outputs a valid block, or it outputs `undefined`. The latter happens if we call some method like `stopMining()`, which stops the Promise and thus returns undefined. We can just create a very simple mine method, just start at nonce 0, check if Ethash is OK with this nonce, if OK then output a block with this nonce/mixhash, otherwise increase nonce and try again.

**Comment by holgerd77** [comment]
Thanks, yeah, that all makes a lot of sense, hadn't thought about this before that the mining part is still missing.

Some remark: if this becomes relevant, it will likely be more in a PoA scenario (there we can realistically really target to become a block producer), don't expect us to go into the mining business anytime soon. 😄

**Comment by jochem-brouwer** [comment]
Yeah I should have stated that it should not be the intention to actually become a block producer on any networks with value. Nevertheless, it would be nice if we have this feature, so people can play around a bit with it. (Geth also has a mine feature, it is CPU mining so it is not competitive at all. It is a very handy tool to create valid, private networks, for testing purposes!).

**Comment by alcuadrado** [comment]
Thanks for the description, @jochem-brouwer. This does make sense. In my experience, the current `runBlock` is only useful to validate existing ones.

> * First initialize the block data (not a really good name, but let me illustrate). This data has the following fields of the block header: `parentHash`, `uncleHash`, `coinbase`, `stateRoot`, `difficulty`, `number`, `timestamp`, `extraData`, `gasLimit`
> * Now, we execute on this context, transactions. So this is where we would actually dump in a list of transactions, and let VM generate the following fields of the header: `stateRoot`, `receiptTrie`, `bloom`, `gasUsed`
> * Now we have enough data to actually send a challenge to a miner. The miner should then report which `mixHash` and `nonce` we should use.

We do something similar in Hardhat Network now that we have some complex logic to construct new blocks. The main difference, which is extremely important to us, is being able to add one transaction at the time, and not just give the entire list of txs in the step (2). The reason for this is that we need to fill blocks as much as possible, and you don't know how many txs they fit until you execute them. 

How I think this should work:

(1) Start the block creation process with the data @jochem-brouwer mentioned.
(2) Pick the next tx from the pending one, whose gas limit is not too large, and run it. While the VM can provide a default method of picking the next tx, it's extremely important to us to be able to override it.
(3) Run the tx, and possibly repeat (2) if any other tx fits in the block. Note that this step would update `stateRoot`, `receiptTime`, `bloom`, and `gasUsed`.
(4) Send to the miner/POA signer (optional step).
(5) Seal the block with the response of the miner/POA signer.

**Comment by jochem-brouwer** [comment]
Oh wow - a really. good point, I had not considered this. Yep, we should definitely add a feature where there's an "intermediate pending block" (heh 😅 ) and one can keep adding transactions as long as the gas limit allows it. I guess we can just add this to a special `PendingBlock extends Block` class? One can just input a transaction to that block, and it will return a new `PendingBlock`, or throw if gas limit does not allow it.

**Comment by alcuadrado** [comment]
Another option, which wouldn't require creating a new Block, would be to implement it using the [builder pattern](https://en.wikipedia.org/wiki/Builder_pattern).
