### ISSUE TITLE
Full sync with multiple peers in parallel

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/ethereumjs-monorepo#1021]
Currently, full sync [only fetches blocks from one peer](https://github.com/ethereumjs/ethereumjs-vm/blob/9b1a95a56612910d769b80945cc42a78c4c2c658/packages/client/lib/sync/fullsync.ts#L134), this is far from optimal. I also wonder what happens if this peer disconnects, or a new "best peer" is found.

I am not yet sure what the best approach here is, but we should at least start fetching block headers/bodies from multiple peers in parallel, and probably keep track of the current reported head of our current peer pool. It is OK if some peers are behind this best block, we can use those peers to fetch "older" blocks.

**Comment by ryanio** [comment]
seems like a good idea to me! do we know how other clients do this?

if we do in parallel, will we need a global mutex for handling db writes?

**Comment by jochem-brouwer** [comment]
If peers only write to the DB via the `blockchain` package, then this is already fixed as it allows parallelized writes to the DB.

We'd need to do some research how other clients do this. It seems to me that regarding downloading the block bodies of the canonical chain quickly, you'd create intervals of `x` blocks and assign peers to download a certain blocks in an interval of thus `x` blocks. If this fails, another peer can take over.

**Comment by ryanio** [comment]
it looks like geth coordinates a schedule and assigns peers tasks in [eth/downloader/statesync.go](https://github.com/ethereum/go-ethereum/blob/810f9e057daccda9eb5c04721b6dd4660f001cc5/eth/downloader/statesync.go#L250). i found lots of interesting comments and notes in that file like [this](https://github.com/ethereum/go-ethereum/blob/810f9e057daccda9eb5c04721b6dd4660f001cc5/eth/downloader/statesync.go#L188).

**Comment by holgerd77** [comment]
My current understanding of the client code is that the assumptions of this issue were not correct and the client block fetcher is indeed requesting blocks from several peers in parallel.

Will close for now, please reopen if you feel this is mistaken.
