### ISSUE TITLE
Devp2p: Add DNS Discovery (EIP-1459)

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1043]
After a chat on the `geth` channel about the current connection problems we have with non-mainnet networks with Felix Lange @fjl, Felix suggested that we might want to implement DNS discovery, see [EIP-1459](https://eips.ethereum.org/EIPS/eip-1459).

The protocol seems not too difficult to implement and this would significantly improve connection pickup on sync, especially for non-mainnet connections.

Go-Ethereum is using this in parallel in addition to the classic discovery, which is still more resilient to network restrictions. I would suggest that we do the same here (and on the client we can also allow a switch to select the discovery method via a CLI option if we want to).

On first look I would think this would mean to allow to pass in several discovery objects as an array on RLPx initialization [here](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/devp2p/src/rlpx/rlpx.ts#L68). The DPTs would then all emit the same events (I think it's just `peer:new` and `peer:removed`) and the RLPx class would take the peers from both discovery entities for its connections.

Also a good PIT to do that since we need to do a breaking `devp2p` release anyhow due to the renaming to `@ethereumjs/devp2p` along the monorepo inclusion (for the devp2p library breaking releases are not that much of a big deal though anyhow compared to the other libraries).

**Comment by cgewecke** [comment]
Leaving additional implementation notes here...
+ The DNS data is stored as rlp encoded Ethereum Node Records - [examples here][1]
+ Chainsafe [recipe for decoding ENRs][2] to similar format as [PeerInfo][3] 

[1]: https://github.com/ethereum/discv4-dns-lists/blob/59641289d5ad8ebebe6169e02b1edaab74a19e47/all.goerli.ethdisco.net/nodes.json#L4
[2]: https://github.com/ChainSafe/discv5/blob/671a9ac8ec59ba9ad6dcce566036ce4758fe50a7/src/enr/enr.ts#L39-L72
[3]: https://github.com/ethereumjs/ethereumjs-monorepo/blob/e06b66e64bf23482c0e9bc29585cab37c74893b0/packages/devp2p/src/dpt/dpt.ts#L13-L18

**Comment by holgerd77** [comment]
@cgewecke short note: DNS discovery link is not working

**Comment by holgerd77** [comment]
Fixed by #1070
