### ISSUE TITLE
Client v0.1 Release Planning (PoA / Yolo v3)

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1045]
I think we have done enough preparatory tasks that we can dare some more concrete release planning on a first `v0.1` release and wrap up on the remaining TODOS as well as targeting a release date. 😄 

So from my understanding the release should contain the following properties:

1. Securely connect to PoA clique networks (signature validation)
2. Reliable sync pick-up on mainnet and the PoA networks
3. Working block execution for hardfork switches
4. Support for Yolo v3 network configuration
5. Support of the Yolo v3 EIPs
6. Once-proven connection uptime of at least 48 (24?) hours+
7. Ensure client is serving data to other peers

I think if we got this rounded up like this we have already some consistent release to offer as well as still enough to do. 😁

#### Developement Tasks

- [x] (1) `blockchain`, `block`: Finalizing PoA clique implementation #1032, some test fixes and re-activations, @everyone
- [x] (3) `client`, `devp2p`: Client HF switches along block execution, some refactor of the devp2p ETH64 [forkhash code](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/devp2p/src/eth/index.ts#L42) to better pick up HF changes, @holgerd77
- [x] (2) `devp2p`: Continuation on network improvement PRs like #1036 and/or DNS Discovery Support #1043 @cgewecke ?
- [x] (3) `common`: Add [Yolo v3](https://github.com/ethereum/eth1.0-specs/blob/master/client-integration-testnets/YOLOv3.md) configuration to `Common` (not sure where to find atm)
- [x] (5) `transaction`, other: [EIP-2718](https://eips.ethereum.org/EIPS/eip-2718) - Typed Transaction Envelope
- [x] (5) `vm`, `transaction` ?: [EIP-2930](https://eips.ethereum.org/EIPS/eip-2930) - Optional Access Lists, depends on `EIP-2718`
- [x] (6) `client`, `devp2p`: fix sync-breaking bugs in the client
- [x] (7) `client`: check for tests and real-world-behavior on data requesting `ETH` protocol requests (received `GetBlockHeaders` e.g.)

Please assign or remove yourself from tasks here freely (as well as eventually associated issues).

#### Organization

- [x] Adequate releases on all depending `EthereumJS` monorepo libraries, @holgerd77 

### Release Date

I would give out the following preliminary target date for a release for orientation and alignment:

~**Wednesday, February 17**~
Wednesday, March 10

Think this might be realistic, will adopt if it becomes foreseeable that we don't match.

**Comment by holgerd77** [comment]
Release date is outdated here. I would assume that it might be realistic for us to join Yolo v3 next week internally after having merged #1048 and then we'll likely want to do at least 1-2 weeks more of internal testing - especially on the new tx formats - before doing any releases here. Have updated accordingly (so new preliminary release date is Wednesday, March 10).

**Comment by acolytec3** [comment]
Do we still need this now that we have a separate issue targeting our 1.0 client release under #1365
