### ISSUE TITLE
Did we implement EIP-155 correctly?

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/ethereumjs-monorepo#1047]
When working on implementing EIP-2718 and EIP-2930, I came across [EIP-155](https://eips.ethereum.org/EIPS/eip-155) which was introduced in Spurious Dragon and adds checks to transaction signatures by verifying that the `v` value is some specific constant which depends upon `CHAIN_ID`. 

However, the EIP states that this **SHOULD** happen - it is not mandatory. However, in our Transaction class, it seems that it is always [mandatory](https://github.com/ethereumjs/ethereumjs-vm/blob/816e0bceb8f0ccf9dc535111146ff129b2ef3103/packages/tx/src/transaction.ts#L119).

The EIP also states that the `v` value can be of two types, where it's value depends upon the "y-parity" of the signature (not super sure what this means yet but I think that the elliptic coordinate is either in the positive or the negative quadrant). We however [just check](https://github.com/ethereumjs/ethereumjs-vm/blob/816e0bceb8f0ccf9dc535111146ff129b2ef3103/packages/tx/src/transaction.ts#L423) that it is one of the two values and it thus seems that we can produce incorrect signatures where our library says it is correct..!

Have marked this as very important since we should fix any consensus-breaking stuff ASAP.

**Comment by jochem-brouwer** [comment]
Super nit: but it also seems like we implemented [EIP-2](https://eips.ethereum.org/EIPS/eip-2) (bullet point 2) incorrectly; [this line](https://github.com/ethereumjs/ethereumjs-vm/blob/816e0bceb8f0ccf9dc535111146ff129b2ef3103/packages/tx/src/transaction.ts#L182) should read `gte` instead of `gt` (?).

**Comment by jochem-brouwer** [comment]
Actually, I think that we are correct, in the `_getMessageToSign`, we explicitly check if we meet the EIP-155 conditions - if we do not, we actually return the original message to hash instead of the EIP-155 version. 

If our client starts to import bad blocks right after the Spurious Dragon fork, then this might be an issue worth looking further into, though.

Will keep this open so some more eyes are on it.

**Comment by holgerd77** [comment]
I would rather strongly assume that we are correct here or the error is not showing up in practice, since the tx library is in very much heavy use in production.

I think "should" in the EIP just means "mandatory", on the y-parity question I am not completely sure. If you have got tx questions you can always circle in @alcuadrado since he knows the library and the mechanisms really well.

**Comment by jochem-brouwer** [comment]
I don't think the "should" in the EIP is intended to be "mandatory", as this would directly invalidate all transactions in the tx mempool once the SpuriousDragon fork happened.

I am also starting to get "re-convinced" (heh 😅 ) that we are correct, but it'd be great if @alcuadrado could give this a quick look.

**Comment by holgerd77** [comment]
Ah sorry, you are right, I assumed a somewhat different context for the "should". Anyhow. 😄

**Comment by holgerd77** [comment]
*ping* @alcuadrado: can you maybe give this a short look?

**Comment by alcuadrado** [comment]
I think the confusion about should/mandatory comes from always `_validateV`. This function is a noop if the tx decided not to opt-in to the EIP155. We can both sign and validate non-EIP155. 

The way you signal that you opted-in is by having a `v` different from `27` and `28`, which were the only valid values before EIP155.

> as this would directly invalidate all transactions in the tx mempool once the SpuriousDragon fork happened.

Is this referring to the client? I don't know how `Common` is handled there in between different HFs. As I mentioned before, I believe that Common should be used when you want to sing/validate a tx, rather than on construction. Do you recreate new txs in that case?

> If our client starts to import bad blocks right after the Spurious Dragon fork, then this might be an issue worth looking further into, though.

How would a bad block look in this case?

**Comment by jochem-brouwer** [comment]
> The way you signal that you opted-in is by having a v different from 27 and 28, which were the only valid values before EIP155.

Ah OK I was not aware of this - I thought that the `v` value was either 0 or 1. Where does this 27/28 come from? It doesn't make a lot of sense to me why you would use these (arbitrary looking) numbers, if the only thing it signals is which of the two variants the signature represents (thus a binary variable, which would normally be either 0 or 1).

> Is this referring to the client? I don't know how Common is handled there in between different HFs. As I mentioned before, I believe that Common should be used when you want to sing/validate a tx, rather than on construction. Do you recreate new txs in that case?

The comment was basically to indicate that, on the actual mainnet HF switch, if we would require everyone to switch over to the new signature scheme, then the following would happen:

Before SpuriousDragon, we would only have signatures with a `v` of 27 or 28. The EIP-155 compliant txs would get rejected in mempool, as they have invalid signatures. However, when we switch to SpuriousDragon, then the pre-EIP-155 transactions would get deleted from the pool, as suddenly all transactions are invalid. Since this is not desirable behavior, it is probably why the EIP indicates that txs *should* be signed with EIP-155, but it is also OK if this is not the case.

> How would a bad block look in this case?

It would be a SpuriousDragon block with a transaction which still has a legacy `v` field. However, I am now pretty sure that this is not the case. I actually assumed that `v` would be either 0 or 1 in legacy transactions, and not that it would be 27 or 28.

I will close here but feel free to add some comments.

**Comment by alcuadrado** [comment]
> I thought that the `v` value was either 0 or 1. Where does this 27/28 come from?

I'm afraid I don't have the answer, @jochem-brouwer. This is something that consumes everyone the first time they see it. `secp256k1`, the lib, uses `0`/`1`, but for some reason, in Ethereum you have to add `27` to that number. ([example of this](https://github.com/ethereumjs/ethereumjs-util/blob/master/src/signature.ts#L27)) Pretty sure there's a reason, I just don't know it.

> Since this is not desirable behavior, it is probably why the EIP indicates that txs _should_ be signed with EIP-155, but it is also OK if this is not the case.

Yes, that was probably the reason. Non EIP-155 are still somewhat common, especially in testing environments, as some js devtools didn't implement the EIP, because we didn't.

**Comment by gabmontes** [comment]
Guys, let me resurface this issue as I came across this while doing some tests with `ganache-cli`. It internally uses `ethereumjs-tx@2.1.2` but the current `@ethereumjs/tx` code seems similar in this regard.

The scenario I'm facing with starts with issuing a `get_ethLogs` so `ganache-cli`/`ganache-core` tries to import some blocks and replay the transactions. One of those, `0xe3bfbc0d881037378ede46078de1539066c0dbff4641ae379740aebd715721f0` at block 12563806 ` as a `v` value of `0` (I saw `1`s too) and fails to `_validateV`.

Opened https://github.com/trufflesuite/ganache-core/issues/910 and adding a reference here.

**Comment by KevinVitale** [comment]
Running into this issue with a graph-node locally deployed, connected to ganache (both v6.12.1 & v6.12.2).

```
Listening on 0.0.0.0:9545
web3_clientVersion
eth_getBlockByNumber
net_version
eth_getBlockByNumber
eth_getBlockByHash
eth_getBlockByHash
(node:1) UnhandledPromiseRejectionWarning: Error: Incompatible EIP155-based V 1 and chain id 1. See the second parameter of the Transaction constructor to set the chain id.
    at e._validateV (/app/ganache-core.docker.cli.js:42:94692)
    at e.set [as v] (/app/ganache-core.docker.cli.js:42:95123)
    at /app/ganache-core.docker.cli.js:12:125244
    at Array.forEach (<anonymous>)
    at /app/ganache-core.docker.cli.js:12:125135
    at new e (/app/ganache-core.docker.cli.js:12:125449)
    at Function.fromJSON (/app/ganache-core.docker.cli.js:12:126104)
    at /app/ganache-core.docker.cli.js:55:2315806
    at Array.forEach (<anonymous>)
    at Object.callback (/app/ganache-core.docker.cli.js:55:2315761)
    at f (/app/ganache-core.docker.cli.js:4:170132)
    at a (/app/ganache-core.docker.cli.js:55:2328023)
    at /app/ganache-core.docker.cli.js:55:2312254
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by holgerd77** [comment]
Hmm. I wonder if we are too strict here with doing the `v` validation in the constructor of a legacy transaction and should rather do this along signature verification, so this would be in `Transaction.getSenderPublicKey()`.

WDYGT? 🤔
