### ISSUE TITLE
Client: DoS attack by requesting a massive amount of blocks

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/ethereumjs-monorepo#1051]
Realized that we are susceptible for a DoS attack, because we [do not put any limit](https://github.com/ethereumjs/ethereumjs-monorepo/blob/e06b66e64bf23482c0e9bc29585cab37c74893b0/packages/client/lib/service/fullethereumservice.ts#L92) on how much other peers request. A malicious peer could request a massive amount of block hashes, which we would then try to honor and try to fetch these blocks from the DB. [The ETH protocol has soft limits on these requests](https://github.com/ethereum/devp2p/blob/master/caps/eth.md).

I am not seeing any guards in client, there might be some in devp2p though?

Also related: what if a peer requests a block which we don't have in our DB? It seems that when we try to query a block which we don't have in our DB, it throws an error. In the ETH protocol spec, it notes that "This (the response) may be empty if no blocks were available for the last GetBlockBodies query.". This seems to imply that we can also send a partial list of the requested blocks?

**Comment by holgerd77** [comment]
Pretty sure there are not any of such guards in devp2p and I would also say this is likely something rather to be determined on the client side?

The whole serving side of things is generally still underappreciated, I actually have no idea to what extend the client is properly participating in its roling of serving data to other peers? 🤔  We should likely also have a closer look here in preparation for the `v0.1` release, will add to the TODO list.

**Comment by holgerd77** [comment]
The client is likely not "hardened" yet on many fronts, will close here for now since no one felt the need to tackle for 1 1/2 years. We can do these things along the side line on development.
