### ISSUE TITLE
Trie: Add support for partial trees

### ISSUE THREAD

**Issue by danfinlay** [ethereumjs/ethereumjs-monorepo#1052]
I'd love to do some local VM state caching, and so this would require a way of storing a trusted root, and only adding things that match the root.

Maybe a set of methods like `trie.setTrustedRoot(rootHash)`, and `trie.putDataSafely('key', 'value', merkleProof)` which will throw if you try to put data that doesn't match the current trusted root.

I have no idea what precise format `merkleProof` would be. I'd love if it was a schema format supplied by an RPC method, but looks like the current RPC may lack the methods for that. Maybe ipld-ethereum has some methods we could use? @kumavis?

**Comment by jochem-brouwer** [comment]
Although there is no direct interface, partial trees are supported, you only need to write directly to DB. Example [here](https://github.com/ethereumjs/ethereumjs-monorepo/blob/bffbc0385d0aef62097fd1bffeb9abdecdaa344d/packages/vm/tests/api/state/proofStateManager.spec.ts#L114).

Not sure if we want to add an interface here?

**Comment by jochem-brouwer** [comment]
I'm pretty sure this is addressed in Trie's `fromProof` method. What you do here is first you set the root of whatever root the merkle proof should be, and then dump in the merkle proof into the `fromProof`. The key/value pairs are not necessary here.

**Comment by holgerd77** [comment]
Will close here.
