### ISSUE TITLE
Trie: Batching multiple leaf proofs

### ISSUE THREAD

**Issue by s1na** [ethereumjs/ethereumjs-monorepo#1054]
When proof for multiple leaves of the trie are required simultaneously, batching the proofs together as proposed [here](https://ethresear.ch/t/optimizing-merkle-tree-multi-queries/4912) can reduce the total overhead. A new method can be added, e.g. `proveBatch` or `proveMultiple` that accepts an array of keys and returns the batched proof. This can potentially be useful in stateless and light clients.

**Comment by jochem-brouwer** [comment]
So this essentially means that we can now create the proof to feed in `verifyRangeProof`, right? Very exciting.

**Comment by holgerd77** [comment]
> So this essentially means that we can now create the proof to feed in `verifyRangeProof`, right? Very exciting.

The above comment is hard to read, this here is an issue, what do you mean with "this" from "so this essentially..."? 🤔

**Comment by jochem-brouwer** [comment]
Yeah I actually meant the issue itself :)

**Comment by holgerd77** [comment]
I will actually close here before it gets forgotten again, this should - latest - be implemented with the completion of #2821 I guess (let me know if I am wrong here).
