### ISSUE TITLE
Trie: strictly require level to be passed in, drop level deps

### ISSUE THREAD

**Issue by mikeal** [ethereumjs/ethereumjs-monorepo#1056]
I’m seeing some nastly browser bundling issues because this package is in my dep tree and depends on modules which have ancient versions of level and there have been several breaking changes since.

These level deps are pretty massive and unnecessary deps since they only get used when a level instance is not passed in. If you moved to require this explicitly you could drop the deps.

In the meantime I’m going to have to drop ethereum support from my default set so that I can avoid this issue.

**Comment by holgerd77** [comment]
Should be solved or at least substantially mitigated by #1917 (to be released along upcoming VM v6 Breaking Release round), will close.
