### ISSUE TITLE
Possible race condition on `get` operation

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/ethereumjs-monorepo#1060]
The `get` operation of the trie does not have a lock. It seems to me that if you run a `get` (which calls `findPath`) and meanwhile also do a `put` operation, this would change the path (`get` operation runs on an old trie). If you would change the same key using `put` to a new value, then `get` will probably yield the old value. Not sure if this is a big problem though.

**Comment by holgerd77** [comment]
I will close this for now since we do not really have known problems with the reliability of the Trie package right now. Feel free to reopen if an issue arrises suspected to be related respectively to be triggered by the way this is implemented.
