### ISSUE TITLE
Trie: supporting web browsers by using a Buffer polyfill

### ISSUE THREAD

**Issue by brickpop** [ethereumjs/ethereumjs-monorepo#1062]
The standard JS class to represent byte arrays is `Uint8Array`, which NodeJS extends with extra features on the `Buffer` class, used in this repo.

However, the Buffer class is not available on web browsers, so people trying to validate a Merke Proof will not be able to provide valid parameters. 

Our particular problem arises when using `BaseTrie.fromProof`, at [which point](https://github.com/ethereumjs/merkle-patricia-tree/blob/master/src/baseTrie.ts#L614-L621) `keccak(nodeValue)` throws an error because the `Uint8Array` value is not a NodeJS `Buffer`.

- Would it be possible to use another `keccak()` implementation that supported `Uint8Arrays`?
- Should `ethereumjs-util` > `keccak()` [be updated instead](https://github.com/ethereumjs/ethereumjs-util/blob/dd2882d790c1d3b50b75bee6f88031433cbd5bef/src/helpers.ts#L18-L23)?

There is a universal implementation available (https://www.npmjs.com/package/buffer) which provides a drop-in replacement that also inherits from `Uint8Array`.

Otherwise, the alternative is for the caller to manually overwrite the global `Buffer` class, which is anything but elegant. Also, depending on a global `Buffer` class that is not explicitly imported, could allow other dependencies to inject a malicious global `Buffer` replacement. 

Thank you!

**Comment by holgerd77** [comment]
No follow-up, will close.
