### ISSUE TITLE
Trie: Add support for EIP-1186 (eth_getProof)

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1078]
As discussed in our last call 21 we might want to add support for [EIP-1186](https://eips.ethereum.org/EIPS/eip-1186) to the trie library.

On first thought I think the most obvious thing to integrate might be proof compatibility for the [Trie.verifyProof()](https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/trie#merkle-proofs) method, so to allow for the method to "understand" the proofs delivered by `eth_getProof`.

This would need some closer look though how to best structurally integrate. There also might be other functionality useful to add in this context.

**Comment by jochem-brouwer** [comment]
Hi @holgerd77, would it make sense to add this to StateManager? This would then act as an endpoint where you would get proofs in the EIP1186 format. It will also get a `verifyProof`, which supports the JSON output of this EIP. I don't think we should change anything into `trie`: Trie itself does not really know what the structure of the trie means (it does not know about accounts, storages, etc.). 

`StateManager` would then call `verifyProof` and `createProof` of `trie`.
