### ISSUE TITLE
Client: Centralized Event Bus

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1079]
We likely want to add more events over time in the client, there was already an idea for a new 'badpeer' event here https://github.com/ethereumjs/ethereumjs-monorepo/pull/1075#discussion_r567690721 and likely others will follow.

For this not more and more bloating the code base by the need of chaining these events from class to class I described the idea of a centralized event bus (some calls ago I guess).

The idea is to add a parameter `events` to the `Config` class (which is already available everywhere), which inherits from the `Event` class and can therefore emit and receive events. In turn the `Event` inheritance on all other classes would be removed.

It then get's possible to receive all events in all classes without chaining.

To give some additional orientation I would also add some namespaces to the event names like:

- 'fetched' -> 'fetcher:fetched'
- 'added' -> 'peer:added'
- ...

Since I am not 100% sure if this idea might have side effects I am not anticipating properly (does this have other advantages I am not seeing right now if the class who deals with the logic is the EventHandler itself) I am dropping this here. Would be happy for some judgement - @cgewecke might be a particularly good candidate here, other opinions welcome as well of course - since I would want to start with this relatively soon (next week or so).

**Comment by cgewecke** [comment]
@holgerd77 Yes, will take a look at this...

**Comment by ryanio** [comment]
This sounds nice!

It could be a good time to also introduce some more type safety to our EventEmitter usage. I started looking around for ways to do this and this looks interesting: https://basarat.gitbook.io/typescript/main-1/typed-event although I'm not sure if it's worth the overhead of having a separate emitter per event type, I like the idea of having the type safety without using an external eventemitter package or adding any new deps. Perhaps we can modify the reference example to accept an enum of valid event values.

**Comment by holgerd77** [comment]
I would want to continue here a bit since this would simplify things on development tasks on the table. I would e.g. like to use this to route events from the RPC manager to the TxPool on a `eth_sendRawTransaction` retrieval (@cgewecke let me know what is your availability here on this task, alternatively I can eventually continue myself or Ryan can take over).

@ryanio I like the idea of having type safety on events but also not sure yet if it's worth the effort, have done some experiments. I have first tested some alternative approach here #1187 - you might want to have a look, not sure if I like to concept myself and if this leads to anything. I also have tried to integrate the code from above but I am realizing that either my TypeScript abilities are still too limited (likely) or the structure to be set up is just too complicated to realize.

This is an extract of my first try here:

```typescript
export enum EventTypes {
  VMEXECUTION_ERROR = 'vmexecution:error'
}

export interface EventVMExecutionError {
  error: Error
}

export interface EventVMExecutionError2 {
  error: Error
}

type EnumDictionary<T extends string | symbol | number, U> = {
  [K in T]: U;
}


const a: EnumDictionary<EventTypes, TypedEvent<EventVMExecutionError | EventVMExecutionError2>> = {
  [EventTypes.VMEXECUTION_ERROR]: new TypedEvent<EventVMExecutionError>,
};


export interface Listener<T> {
  (event: T): any
}

export interface Disposable {
  dispose(): any
}

/** passes through events as they happen. You will not get events from before you start listening */
export class TypedEvent<T> {
  private listeners: Listener<T>[] = []
  private listenersOncer: Listener<T>[] = []
  //...
}
```

Can you have a look ([this](https://stackoverflow.com/questions/54542318/using-an-enum-as-a-dictionary-key) is one inspiration article)? This is not working but I am also getting somewhat lost on the task putting these event types into a typed enum dictionary.

**Comment by cgewecke** [comment]
@holgerd77 I'm happy for anyone who's up for it to take over here...
