### ISSUE TITLE
VM: Analyze "Exit early on no code or value tranfer overflowed" behavior

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1082]
When testing our first consensus issue on the VM triggered by a client run described here #1076 I came across the above mentioned VM behavior when running the VM with a not-yet-correct example from https://github.com/ethereumjs/ethereumjs-monorepo/issues/1076#issuecomment-771820140 (so (since example might have been updated): this was by not setting the VM to `Frontier` by not passing in a properly set `Common` instance).

Here is an output using the debugging functionality from #1080 :

![image](https://user-images.githubusercontent.com/931137/106872357-7dd25100-66d3-11eb-84a2-6c53d86d83ee.png)

So the VM is exiting [here](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/vm/lib/evm/evm.ts#L185) early on described with "Exit early on no code or value tranfer overflowed" in the debug run.

This whole behavior is really questionable and unfortunate from a user perspective, before I did the debug run I actually was convinced that the VM actually was running some code since (at least in the triggered case, see also the comment from the code linked) there was not even an `ErrorMessage` along the result.

It should be investigated if this is the proper behavior, under what kind of conditions this early exit will be triggered and if we can better indicate here that something went wrong. It might also not be appropriate to handle these 2-3 cases from `if (!message.code || message.code.length === 0 || errorMessage)` together but rather decompose and handle separately.

**Comment by holgerd77** [comment]
I separated the debug messages here in https://github.com/ethereumjs/ethereumjs-monorepo/pull/1089/commits/67f4dfd6f3762a536c052e1b5260ce9c0eb36e5d, think this can be closed for now, an eventually needed analysis (not sure, maybe this is just always this no-code part of the condition) can be easily done subsequently if needed.

**Comment by jochem-brouwer** [comment]
Small comment here (should have mentioned this earlier), this actually seems like the right behavior. I think you were running the isolated transaction here in the wrong context, in particular on the wrong fork. In that case, in the message which tries to create a contract, it runs out of gas (so it exits early).

**Comment by holgerd77** [comment]
I don't think this is triggered due to a run out of gas, since the exit message says " "Exit early on no code or value tranfer overflowed" - these are also the two things checked in the code base? 🤔
