### ISSUE TITLE
RPC based execution

### ISSUE THREAD

**Issue by LogvinovLeon** [ethereumjs/ethereumjs-monorepo#1083]
Currently `VM` has only one StateManager implementation - `DefaultStateManager`.
It requires the `trie` as a constructor argument and the trie requires the `database` access.
So - if someone wishes to execute some block from a month ago - they need an access to full archive node (~7T atm).
At the same time - it is possible to get the historic state from someone else's archive node (Infura, Alchemy).
We can use `eth_getBalance`, `eth_getCode`, `eth_getTransactionCount`. I'm aware - that we don't have access to anything like `eth_getStorageRoot`, `eth_getCodeHash` or `eth_accountExistsPreByzantinium`, but I still think it will be very useful fo be able to execute some mainnet transactions/blocks without having a full archive node.

I've implemented that for my own use-cases and it works. Obvsly - it's hella slow on recent mainnet blocks, because each state read goes to infura, but there are other use-cases. If someone wants to re-execute transactions as they come in using ethereumjs-vm and has a full archive node - this approach allows him to do that without the need to stop the node and therefore to be up to date with the mainnet. (LevelDB is single process unfortunately).

There is currently only one blockers:
* Invalid block state root
  * Without having access to the database - we can't generate state roots and therefore can't go through this check. There should be an option to disable it. I can still check the execution correctness using `receiptRoot`. Not perfect but good enough in practice

I'm proposing `skipStateRootValidation?: boolean` flag on `RunBlockOpts` which will disable this check defaulting to `false`.
Let me know what you think and I can create a PR if OK.

**Comment by holgerd77** [comment]
Hi Leonid, thanks for the extensive write-up, I am ok with this new flag. Just to get this right, do you only want to add the flag or the whole alternative state manager? I am personally also ok with adding up to a handful of useful alternative state managers to the package, but I would want to wait for another opinion on that.

**Comment by LogvinovLeon** [comment]
As I'm the new contributor - I'd like to start small to get to know the tooling, conventions etc.
Therefore - I want to add only this flag for now. Adding an additional state manager will require a lot of coordination and design decisions. My State manager for example doesn't support all the methods as it doesn't have access to tries.

**Comment by holgerd77** [comment]
Ok, sounds good. Just to note that our own experience with different `StateManager` implementations and accompanying needs is also very limited, so it might also very well be the case that our interface definition is too strict e.g..

**Comment by LogvinovLeon** [comment]
I took a second glance at that and now I'm not so sure I need this option. There is already a `generate` option that allows me to not do all of the four checks and I can just do three of them outside of the VM code. Closing for now
