### ISSUE TITLE
VM Tracker for consensus bugs which are not tested in ethereum/tests

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/ethereumjs-monorepo#1092]
Tracking issue for consensus bugs which we find, which are not covered by ethereum/tests.

- #1081, #1076: Address of created contract not put on stack when codestore runs out of gas (Frontier).

**Comment by holgerd77** [comment]
Before we report any consensus bugs we should update our version of `ethereum/tests` to the latest release (currently named [v7.01](https://github.com/ethereum/tests/releases/tag/v7.0.1) though. My old (not to be merged likely) release notes PR https://github.com/ethereum/tests/pull/692 for an intended v8.0.0-beta.1 release might also help on the update process.

**Comment by holgerd77** [comment]
I guess it is not likely any more that we will find consensus-bug-after-consensus-bug and a report will likely tackled on a case by case basis and not on a tracking schedule.

Will close here.
