### ISSUE TITLE
How to verify tries in Solidity?

### ISSUE THREAD

**Issue by alvin854** [ethereumjs/ethereumjs-monorepo#1096]
I'm looking to generate a Merkle tree in JS and verify proofs on-chain in Solidity. There are Solidity libraries like [OpenZeppelin's MerkleProof.sol](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/cryptography/MerkleProof.sol) that let me do so, but I can't find a reliable Merkle library in JS. merkle-patricia-trees seems to be the most reliable, but I can't find any examples on how I would verify tries in Solidity. 

With a Merkle tree, each of my objects would look something like this:
```
{
    address: "0x123",
    token: "0x456",
    amount: "15000000000000000000"
}
```
...which I would ideally hash with something like `web3.utils.soliditySha3(address, token, amount)`, and pass an array of those leaves to the tree. 

Am I correct in thinking that in a trie, the key would be `Buffer.from(address)` and the value would be `Buffer.from('${token}${amount}')`? And then how would I verify that in Solidity? Would really appreciate a hand or any resources that I may have overlooked. Thanks.

**Comment by ryanio** [comment]
Hey there. After setting up your trie, you would use [Trie.createProof](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/trie/docs/classes/_basetrie_.trie.md#static-createproof), and then pass the proof along with the root (`Trie.root`) and leaf (`Buffer.from(address)`) to MerkleProof.sol's `verify` method.

For some examples on how this is done within merkle-patricia-tree, check out [test/proof.spec.ts](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/trie/test/proof.spec.ts)

**Comment by alvin854** [comment]
Thanks @ryanio. I need to reconstruct the leaf in Solidity to verify that the other arguments passed to the contract function (like `amount`) are correct before they can claim that `amount` in tokens. With a tree, I'd probably pass `address`, `token`, and `amount` to a contract function that reconstructs the leaf via `keccak256(abi.encodePacked(address, token, amount))`, and then pass that leaf to MerkleProof.sol's `verify`.

1. How would I reconstruct a leaf of those values in Solidity to align with the root and proof generated by merkle-patricia-tree? 

2. Also, how might you recommend `put`ting an object with multiple values? Would it make sense to have value  `Buffer.from(amount)` for key `Buffer.from('${address}${token}')`?

**Comment by ryanio** [comment]
I found the openzeppelin PR that introduces the `MerkleTree.sol` contract, that has tests, docs and helpers along with it: https://github.com/OpenZeppelin/openzeppelin-contracts/pull/260

Following this example with their [JS `MerkleTree` helper class](https://github.com/OpenZeppelin/openzeppelin-contracts/pull/260/files#diff-3cb122c8dad040664df2e9aa964d307b1f3bd95250a8a34f96c093aa7eb8fb25R3), you should be able to modify for your own uses:

```js
  describe("verifyProof", function() {
    it("should return true for a valid Merkle proof", async function() {
      const elements = ["a", "b", "c", "d"];
      const merkleTree = new MerkleTree(elements);

      const root = merkleTree.getHexRoot();

      const proof = merkleTree.getHexProof(elements[0]);

      const leaf = bufferToHex(sha3(elements[0]));

      const result = await merkleProof.verifyProof(proof, root, leaf);
      assert.isOk(result, "verifyProof did not return true for a valid proof");
    });
```
([link](https://github.com/OpenZeppelin/openzeppelin-contracts/pull/260/files#diff-d5d6e478d1f9941bc9b66630f6188d5b8b6d57984fed6a8c37565c40d08dc830R14))

So your `elements` array could be ```[`${address}${token}${amount}`, ...]```

**Comment by holgerd77** [comment]
@ryanio is this something where we could extract some useful example from for our [proof section](https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/trie#merkle-proofs) in the Trie library README? 🤔

**Comment by ryanio** [comment]
The OP was asking how to verify a merkle tree in solidity and I pointed to OpenZeppelin's `MerkleTree.sol` contract and their respective JS code.

From https://github.com/OpenZeppelin/openzeppelin-contracts/pull/260:

> `merkleTree.js` contains a helper Merkle tree class that is used to generate Merkle trees, roots and proofs in the JS tests. When generating the Merkle tree, leaves are sorted and pre-images are also pair-wise sorted before being concatenated/hashed to create the parent of a pair of pre-images.
> 
> `verifyProof` in `MerkleProof.sol` assumes that the Merkle root provided is from a Merkle tree with sorted leaves and pair-wise sorted pre-images.

I am not sure if we do this same sorting in `merkle-patricia-tree` so our lib might return a different proof? I haven't investigated further.

**Comment by holgerd77** [comment]
Long period of inactivity and very special topic, somewhat solved with some hints as well, will close.
