### ISSUE TITLE
VM: only expose API methods on docs

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1115]
We currently expose all kind of weird stuff in the VM [documentation](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/vm/docs/README.md), this was found along the work on #1112. We should relatively urgently give this an update here, otherwise people will start to use this more and more eventually which would not be too healthy.

If someone works on this please give a short reasoning on every removal.

**Comment by ryanio** [comment]
These can be added to the `exclude` array in the [typedoc.js](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/vm/typedoc.js#L8) config.

On first look I think we can add to exclude:

* `evm/opcodes/*`
* `evm/precompiles/*`
* `state/index`

**Comment by holgerd77** [comment]
Mini-breakthrough for me here: just learned that you can use `npx typedoc --options typedoc.js --plugin none --out html` to deactivate the markdown rendering + create HTML docs to a local directory and then use a package like [http-server](https://www.npmjs.com/package/http-server) to quickly serve the files locally.

This really helps a lot to get some orientation, I was previously always "bling-generating" and seeing for the first time post-merge on site. 😄
