### ISSUE TITLE
EIP2929 problems

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/ethereumjs-monorepo#1123]
There's a problem with the current [EIP2929](https://eips.ethereum.org/EIPS/eip-2929) implementation. We currently track which addresses/slots are tracked on a message level (so each CALL creates a new message), while we should track it on transaction level.

Since EEI and Interpreter are re-instantiated each time we execute a new message, we need to do it at a higher level (e.g. EVM). The best place to me seems to place this in `StateManager`, we can track these things the same way as almost the same way as we track `touched` accounts. The only problem I have with this one is that we might bloat the StateManager a lot with the EIP2929 stuff.

Thoughts?

This is rather important, since EIP2930 especially depends on how these storage slots / addresses are tracked, so creating EIP2930 on the current EIP2929 implementation would end up that we do this work twice. So let's first at least figure out how we should fix EIP2929 and then proceed to implement EIP2930.

**Comment by jochem-brouwer** [comment]
Extra context https://github.com/ethereumjs/ethereumjs-monorepo/pull/1048#issuecomment-782736703

**Comment by holgerd77** [comment]
Haven't deeply thought about that, but I would also think that this very well fits into the `StateManager`, seems to me that this is not bloating `StateManager` too much. I guess it should be able to integrate just the generic part of it - so managing the state access lists - and keep for e.g. the code from https://github.com/ethereumjs/ethereumjs-monorepo/pull/889/files#diff-e465f53957b9864d032863905f05d69c33d2699dc9bb75b436099de6ed4d8d84 to a large part at its place and the call into `StateManager` to request on the accounts (so to replace these `runState.accessedAddresses.has(addressStr)` and similar calls)?

**Comment by jochem-brouwer** [comment]
OK great - I had a similar idea, I'll start working on it 😄

**Comment by cgewecke** [comment]
@jochem-brouwer Sorry about this...was uncertain about the right location for this tbh.

The spec says...

> The sets are transaction-context-wide, implemented identically to other transaction-scoped constructs such as the self-destruct-list and global refund counter

Above you suggest:
> Since EEI and Interpreter are re-instantiated each time we execute a new message, we need to do it at a higher level (e.g. EVM). The best place to me seems to place this in StateManager, we can track these things the same way as almost the same way as we track touched accounts. 

May be misreading, but it looks like we maintain the refund counter and selfdestruct lists in `evm/eei`, for example here

https://github.com/ethereumjs/ethereumjs-monorepo/blob/a983867f8046c1071f0b97befc7e6f1049772d71/packages/vm/lib/evm/eei.ts#L375

**Comment by jochem-brouwer** [comment]
Hi, sorry for the confusion here. I initially thought EEI would be a logical place, but since we handle commit/checkpoint/revert at state manager, this seems to be a better place to put this logic.
