### ISSUE TITLE
Wrap `runCode` and `runCall` into `runTx`

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/ethereumjs-monorepo#1127]
As mentioned in #1124, `runCode` and `runCall` do not execute some parts of `runTx`. This can lead to some unexpected behavior. It would make sense to create a "fake transaction" for these methods, which then call into `runTx`. We are then ensured that `runCode`/`runCall` also setups the extra logic of `runTx` (such as cleaning touched accounts at the end of the transaction, or EIP2929-related logic).

**Comment by holgerd77** [comment]
Outdated and new thoughts/concepts along v6 EVM/VM refactor, will close.
