### ISSUE TITLE
Create a DEFAULT_COMMON in Common

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/ethereumjs-monorepo#1128]
In #1048 we discussed the possibility to export a `DEFAULT_COMMON` from Common. We use default commons across the packages, so for me it would make sense that we put this default on a centralized point (i.e. in Common).

**Comment by holgerd77** [comment]
My first-thought suggestion here would be to add an additional `DEFAULT_CHAIN` parameter (likely set to `mainnet`?) and then add a static constructor method `Common.getDefaultCommon()` using `DEFAULT_CHAIN` and `DEFAULT_HARDFORK` for instance creation.

**Comment by jochem-brouwer** [comment]
Yep, this makes sense!

**Comment by holgerd77** [comment]
I've made some search here for `new Common({ chain: 'mainnet' })` and see where this applies and also looked into some code parts directly, and there are actually really few places where such a pattern is used in its plain form (so with no additional parameters for whatever reason).

Also this issue hasn't been addressed for some months so there seems to be not such an urgent need.

I will therefore cautiously close, feel free to reopen everyone who sees the need for this functionality (also no very strong opinion here, we can just add and that's it, think this *would* make some send and would eventually have some benefits).
