### ISSUE TITLE
E2E - Tracking issue for upgrading HardhatEVM to V5

### ISSUE THREAD

**Issue by cgewecke** [ethereumjs/ethereumjs-monorepo#1154]
This is a companion to [hardhat PR 1337][1] for tracking what needs to be done to resolve any issues that come up during their upgrade.

**TODO**
- [x] Resolve #1153 
- [ ] Add Hardhat as E2E target here

[1]: https://github.com/nomiclabs/hardhat/pull/1337

**Comment by cgewecke** [comment]
HH merged, so we add them E2E.

**Comment by holgerd77** [comment]
Not needed as a tracking issue any more, will close here. A new issue can be opened for Hardhat E2E integration if still planned or alternatively directly tackled within a PR.
