### ISSUE TITLE
Custom chainId example not working

### ISSUE THREAD

**Issue by canguruhh** [ethereumjs/ethereumjs-monorepo#1164]
The example for a custom chain common from [https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/common](https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/common) is not working when using it for creating a VM instance

```
const customChainParams = { name: 'custom', chainId: 123, networkId: 678 }
const customChainCommon = Common.forCustomChain('mainnet', customChainParams, 'byzantium');
const vm = new VM({ common: customChainCommon  })
```

Its returning the following error message:

UnhandledPromiseRejectionWarning: Error: Chain with name 123 not supported

**Comment by holgerd77** [comment]
Thanks for reporting, yes, I can reproduce.

This is going back to the `Blockchain` library and the following code part in the `_init()` method:

```typescript
if (!genesisBlock) {
  const common = new Common({
    chain: this._common.chainIdBN(),
    hardfork: 'chainstart',
  })
  genesisBlock = Block.genesis({}, { common })
}
```

This kind of `Common` replication generally will not be working well on custom chains and we should have a broader look if we have similar constructs somewhere else in the monorepo.

Fix here I guess would be to use the `Common.copy()` functionality and then set the `hardfork` with the `setHardfork()` method.

Will apply this tomorrow and eventually directly have a bugfix release on `Blockchain` followed here (`Common.forCustoomChain()` is relatively important - Hardhat e.g. is using this as well. The functionality is generally undertested, maybe I can also add some more tests along. Would e.g. eventually make sense to test custom commons directly in other libraries).
