### ISSUE TITLE
Dynamic gas costs are not exposed by the VM, but rather consumed during execution

### ISSUE THREAD

**Issue by alcuadrado** [ethereumjs/ethereumjs-monorepo#1169]
(Moving a discussion here from discord)

While implementing `debug_traceTransaction` we realized that ethereumjs-vm handle gas in a very different way form Geth, so it's not really possible to implement this RPC method as Geth does it without reimplementing significant parts of gas-cost-related logic.

Each opcode in Geth has functions that return how much gas they cost, one for the constant part of the gas, and another one for the dynamic part. The dynamic one takes the entire state of the EVM, and returns the max amount of gas that the execution of that instruction can consume. With that, and extra function that returns the amount of memory that the instruction will use, you can use/consume the max gas that this step (execution + memory expansion) can use before executing.

A key thing to note is that only *CALL instructions don't use the max amount of gas, and that is handled in this way: the opcode handler is in charge of initializing a new child vm, with the max gas that it can spent, and run it. Once it returns, any leftover gas is returned to the parent vm.

Instead of doing this, ethereumjs-vm now consumes the gas while executing, so in order to know before execution how much an instruction can spend, we have to reimplementing its gas counting logic.

PS: We've already handled this by duplicating parts of the gas cost calculations that geth does, but ideally this should be provided by the vm.

**Comment by alcuadrado** [comment]
My original message on discord:

I think we hit a major blocker with the current design of the VM that would force us to reimplement a lot of gas-cost-related logic if want to be 100% compatible with geth's implementation of debug_traceTransaction. I think it will be interesting for everyone, so I'll describe it here.

debug_traceTransaction returns traces of the execution of past txs. It takes a txid and returns (among other things) an array with a struct for every opcode that was executed.

This struct has two fields related to the gas used by the instruction: gas and gasCost. gas is the amount of gas left, and gasCost is the max amount of gas that that operation can spend.

gas is already available in the step event, but gasCost is not, and it is really complex for some opcodes. In most cases we can compute it looking at the next step, but that doesn't work on edge cases (latest step) nor in CALL-related opcodes (they normally spend less than the gasCost).

They way geth solves this is very neat. For each opcode, they have two functions for computing gas. One that returns the constant part of it, and another one that returns the dynamic part. For example: https://github.com/ethereum/go-ethereum/blob/master/core/vm/jump_table.go#L130-L138

Using the combination of them you can create that gasCost field.

They way they use dynamicGas is by extracting the max amount of gas an opcode can consume before actually executing it, and don't have gas-substraction logic in the implementation. For call-related opcodes, which can spend less than that, their implementation is in charge of initializing the child-EVM with that amount of gas, and return any left over that this child-EVM has post-execution.

I know implementing this in ethereumjs-vm is a big change, and there are two significant HFs coming, but I think it's a really interesting problem and design.

**Comment by jochem-brouwer** [comment]
Related EIP [3155](https://eips.ethereum.org/EIPS/eip-3155). I'll implement this EIP but will first start a bit of research to see how we can implement it. It'll be a huge internal refactor. I think how Geth implemented it makes a lot of sense and I'll probably go for that one.

**Comment by jochem-brouwer** [comment]
Okay, did some research and got a general idea how to implement it. However I got some questions about the EIP itself and wonder about some edge cases how these should be handled, which I have just asked.

**Comment by alcuadrado** [comment]
We've been working on this pretty intensively for the last few weeks, so feel free to ask me whatever you need here or on discord.

Something we noticed is that edge cases aren't really well thought through, but rather return whatever happens to be the result of the partial execution of geth's implementation. For example, on some failures, the `gasCost` may not include the dynamic part of it at all.

**Comment by jochem-brouwer** [comment]
Do you have an example of this edge case where the dynamic part is not included on failure?

**Comment by alcuadrado** [comment]
For example, if an operation OOGs because there's less gas than the constant part. Take a look at this if: https://github.com/ethereum/go-ethereum/blob/bbfb1e4008a359a8b57ec654330c0e674623e52f/core/vm/interpreter.go#L247 -- Note the `defer` in that function too.

**Comment by jochem-brouwer** [comment]
Ah right. It would report the constant gas for that operation then? Or does it report the current gas left in the current context? (I think the latter makes more sense?)

**Comment by alcuadrado** [comment]
It would be the static part of the gas, not the entire gas left, which is what I would expect. Note that it may report more than the gas left. It's pretty weird.

**Comment by holgerd77** [comment]
Issue #382 is likely related, will close over there to consolidate on issues.

**Comment by ryanio** [comment]
> Okay, did some research and got a general idea how to implement it. However I got some questions about the EIP itself and wonder about some edge cases how these should be handled, which I have just asked.

@jochem-brouwer did you get clarification on your questions? I would be curious what they were (and the answers).

How should we prioritize this issue? It would be nice to implement EIP 3155 - would there have to be breaking changes if such an extensive internal refactor is required? @jochem-brouwer could you outline an overview of the internal changes needed?

**Comment by alcuadrado** [comment]
> would there have to be breaking changes if such an extensive internal refactor is required?

I think so. Not 100% sure, but as it's a big change, I suspect it'd be breaking.

**Comment by holgerd77** [comment]
Have added this to the v6 planning notes as a "Potential implementation candidate". 🙂

**Comment by jochem-brouwer** [comment]
#1553

**Comment by holgerd77** [comment]
Closed by #1364 respectively #1553 (backwards-compatible version)

Release on this soon (1-3 weeks)
