### ISSUE TITLE
On RPC method block parameters, allow block identifiers as "latest", "earliest" or "pending"

### ISSUE THREAD

**Issue by evertonfraga** [ethereumjs/ethereumjs-monorepo#1175]
https://github.com/ethereumjs/ethereumjs-monorepo/blob/53150c159b559b31b6b7c321d784dbb11b082fb9/packages/client/lib/rpc/modules/eth.ts#L259-L264

This helps on compatibility with other tooling. Getting the latest block is a common type of request.

**Comment by gabrocheleau** [comment]
Also ran into this issue when trying to establish a connection between an ETH 2.0 teku client and ethjs. 

I think the `latest` case could be implemented simply by setting `block = await this._chain.getLatestBlock()` in that case. Not sure how the other 2 cases should best be handled.

The validation would also need to be changed from `validations.hex` to `validations.blockOption`, which allows `latest`, `earliest` and `pending`.
