### ISSUE TITLE
Invalid root length. Roots are 32 bytes

### ISSUE THREAD

**Issue by harnen** [ethereumjs/ethereumjs-monorepo#1194]
I'm pretty new to JS, so I may be omitting something obvious. I was trying to connect to geth using code from [this README](https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/trie) - Read stream on Geth DB. 

However, every time I get the following error:
```
node:internal/process/esm_loader:74
    internalBinding('errors').triggerUncaughtException(
                              ^

AssertionError [ERR_ASSERTION]: Invalid root length. Roots are 32 bytes
    at SecureTrie.setRoot (ethereumjs-monorepo/packages/trie/dist/baseTrie.js:55:9)
    at new Trie (ethereumjs-monorepo/packages/trie/dist/baseTrie.js:33:18)
    at new CheckpointTrie (ethereumjs-monorepo/packages/trie/dist/checkpointTrie.js:11:9)
    at new SecureTrie (ethereumjs-monorepo/packages/trie/dist/secure.js:16:9)
    at file://ethereumjs-monorepo/packages/vm/app.mjs:8:14
    at ModuleJob.run (node:internal/modules/esm/module_job:154:23)
    at async Loader.import (node:internal/modules/esm/loader:177:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}

```

It seems that `basetTrie.setRoot()` expects 32byte input, while receiving 64byte (as indicated in the README). Should the state root be converted in before passing it to `new Trie()`?

**Comment by jochem-brouwer** [comment]
Where exactly did you find this 64 byte thing in the README? I cannot seem to find it.

Anyways, they are indeed 32 bytes. If you have a hex string from Geth as root, you need to convert it to a Buffer, make sure you strip the `0x` prefix if it is present;

`const root = Buffer.from("9765a9413563899a88027f229c2a5f67383f7fd04a1874e3718d4c56b4a6c45e",'hex')`

(root of [block 12206871](https://etherscan.io/block/12206871))

**Comment by jochem-brouwer** [comment]
Ah wait I see which part you mean. Yeah it seems likes this README is not correct, we should update it.

**Comment by harnen** [comment]
That worked. Thanks a lot! And yes, it'd be great to update the examples for the newbies like me.

**Comment by holgerd77** [comment]
@harnen that's already pretty advanced for a "newbie question"! 😄 

You would actually get more tool support if you use `TypeScript` for testing or in the form of `ts-node` as a console, than `TypeScript` would complain that the input is wrong, not sure if this is an option for your kind of setup.

We haven't tested connecting to a geth DB for quite a while, would be interesting in the results if you want to post them here (as well as stating your geth version).
