### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by chbfiv** [ethereumjs/ethereumjs-monorepo#1223]
I'm trying to do basic transactions and have struggled so far. I've tried a few different approaches from a few different sources (web3 docs and tests in this repo)

```javascript
import Web3 from 'web3';
import Tx from '@ethereumjs/tx';

const web3 = new Web3('wss://ropsten.infura.io/ws/v3/myinfruraproject');

// Test Address 1
const sourceAddr = '0xXXXXXXAddr';
const sourcePk = Buffer.from('XXXXXXPrivateKey', 'hex');
// Test Address 2
const destinationAddr = '0xYYYYYYAddr'

const txCount = await web3.eth.getTransactionCount(sourceAddr);
const networkType = await web3.eth.net.getNetworkType()

const customCommon = {
   baseChain: networkType,
   harfork: 'berlin'
};

const txRaw = {
   nonce:    web3.utils.toHex(txCount),
   to:       destinationAddr,
   value:    web3.utils.toHex(web3.utils.toWei('0.1', 'ether')),
   gasLimit: web3.utils.toHex(21000),
   gasPrice: web3.utils.toHex(web3.utils.toWei('10', 'gwei')),
   common: customCommon
};

const test = async () => {
   const txSigned = await web3.eth.accounts.signTransaction(txRaw, sourcePk);
   console.log(txSigned);


   // const txReceipt = await web3.eth.sendSignedTransaction(txSigned.rawTransaction);
   // console.log(txReceipt);
}

test();

```

results in this error. 

```bash
(node:96607) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
    at signed (node_modules/web3-eth-accounts/lib/index.js:149:62)
    at node_modules/web3-eth-accounts/lib/index.js:206:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async test (src/test.js:30:21)
(Use `node --trace-warnings ...` to show where the warning was created)
<node_internals>/internal/process/warning.js:43
(node:96607) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
<node_internals>/internal/process/warning.js:43
(node:96607) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by chbfiv** [comment]
FYI I'm using NodeJs w/ these dependencies

node --version
v14.16.0
npm --version
6.14.11

```  "dependencies": {
    "@openzeppelin/contracts": "3.4.1",
    "@truffle/contract": "4.3.13",
    "sha3": "2.1.4",
    "web3": "1.3.5",
    "@ethereumjs/tx": "3.1.3"
  }```

**Comment by cgewecke** [comment]
@chbfiv Web3 is using [an older version of [ethereumjs-tx][1] that isn't inter-operable with the latest release.

And they have an issue open tracking their upgrade to newer ethereumjs stack, [here][2].

[1]: https://github.com/ChainSafe/web3.js/blob/5d027191c5cb7ffbcd44083528bdab19b4e14744/packages/web3-eth-accounts/package.json#L20 
[2]: https://github.com/ChainSafe/web3.js/issues/3963

**Comment by chbfiv** [comment]
Thanks for the info. 

It seems like I'm blocked by this because I removed my `ethereumjs/tx` reference (Wasn't used) and it's still has the same issue. I also tried downgrading web3 and the issue still appears. Should I be trying to use web3? or maybe there is a better way? or should I just wait for web3 to fix

**Comment by cgewecke** [comment]
> maybe there is a better way?

@chbfiv I would take a look at [ethers][1].  

[1]: https://docs.ethers.io/v5/

**Comment by holgerd77** [comment]
@chbfiv Yes, ethers might also be something to look at.

Note that the `Common` object in your example is not correct. This is not a simple dict but an instance of `@ethereumjs/common` (from this monorepo in `packages`), this is super insufficiently documented on the [Web3 docs](https://web3js.readthedocs.io/en/v1.2.11/web3-eth-accounts.html#signtransaction) I just realized, this just *can't* be grasped without some context.

**Comment by holgerd77** [comment]
//cc @gregthegreek

**Comment by holgerd77** [comment]
Will cautiously close here, feel free to reopen if still necessary.
