### ISSUE TITLE
VM: test VM.runBlock() ommer reward functionality

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1226]
Currently in the VM the ommer (uncle) reward functionality within `assignBlockRewards()` and `calculateOmmerReward()` is completely [untested](https://codecov.io/gh/ethereumjs/ethereumjs-monorepo/src/master/packages/vm/lib/runBlock.ts). This should be changed by adding one or more tests in `tests/api/runBlock.spec.ts`.

Some inspiration on how a block with uncles can be generated might eventually be taken from the `Block` library [tests](https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/block/test). Also note that the accounts receiving the ommer rewards need to be added with a custom `StateManager` before running `VM.runBlock()` for this to work properly.

**Comment by jochem-brouwer** [comment]
Why do the ommer accounts need to get added to `StateManager `manually?

**Comment by holgerd77** [comment]
Because they are otherwise not present in the state and can't receive a reward? Or am I missing something here?

**Comment by jochem-brouwer** [comment]
If you `getAccount` on a non-existing account, `StateManager` reports an empty account, which you can then edit :) So this is not a problem.

**Comment by acolytec3** [comment]
I'm experimenting on this one.
