### ISSUE TITLE
Client: RPC Tests Coverage Improvements

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1227]
The coverage of the client RPC tests - especially for the `eth` and `web3` calls - are pretty low with `eth` < 70% and `web3` < 80%, see [Codecov report](https://codecov.io/gh/ethereumjs/ethereumjs-monorepo/tree/master/packages/client/lib/rpc/modules).

This should be significantly improved. 😋

**Comment by holgerd77** [comment]
@Ghorbanian hi there, thanks for watching out for open issues! 😄 

I had a closer look here, I guess this is not so much needed any more since it improved significantly by 1-2 PRs already been done on this and at least some remaining cases might be to hard to do and not worth the effort. Didn't have such a close look though and there will very likely still room for useful improvements, so if you stumble upon code coverage gaps which you think should be filled feel free to give it a go. I will nevertheless close this issue here for now.

Another test case which would be neat: we introduced a new `debug` option for the VM and the VM is doing a lot of console debug output if an environment variable `DEBUG` is set. I just realized that these switches are completely skipped by the tests, see e.g. [runBlock.ts](https://codecov.io/gh/ethereumjs/ethereumjs-monorepo/src/master/packages/vm/src/runBlock.ts) coverage. It would be neat to have at least one generic test here which calls the VM on a higher level (likely best: `VM.runBlock()` and tricking the VM to think `DEBUG` is set, so that all (or a lot of) the debug messages actually get triggered. This would substantially improve the test coverage, but would also be useful to be tested by itself, since there is always the chance that someone adds some code to a debug message generation which breaks the debug flow.

One bonus thing here would be to deactivate `console.log` just for this test, so that the test output doesn't get bloated with all these debug messages.

If you want you can give this one a try, also see [this docs section](https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/vm#understanding-the-vm) for some context on VM debug. Otherwise I can also just open a dedicated issue on this, then someone else can just pick this up.

**Comment by Ghorbanian** [comment]
> @Ghorbanian hi there, thanks for watching out for open issues! smile
> 
> I had a closer look here, I guess this is not so much needed any more since it improved significantly by 1-2 PRs already been done on this and at least some remaining cases might be to hard to do and not worth the effort. Didn't have such a close look though and there will very likely still be room for useful improvements, so if you stumble upon code coverage gaps which you think should be filled feel free to give it a go. I will nevertheless close this issue here for now.
> 
> Another test case which would be neat: we introduced a new `debug` option for the VM and the VM is doing a lot of console debug output if an environment variable `DEBUG` is set. I just realized that these switches are completely skipped by the tests, see e.g. [runBlock.ts](https://codecov.io/gh/ethereumjs/ethereumjs-monorepo/src/master/packages/vm/src/runBlock.ts) coverage. It would be neat to have at least one generic test here which calls the VM on a higher level (likely best: `VM.runBlock()` and tricking the VM to think `DEBUG` is set, so that all (or a lot of) the debug messages actually get triggered. This would substantially improve the test coverage, but would also be useful to be tested by itself, since there is always the chance that someone adds some code to a debug message generation which breaks the debug flow.
> 
> One bonus thing here would be to deactivate `console.log` just for this test, so that the test output doesn't get bloated with all these debug messages.
> 
> If you want you can give this one a try, also see [this docs section](https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/vm#understanding-the-vm) for some context on VM debug. Otherwise I can also just open a dedicated issue on this, then someone else can just pick this up.

Thanks for the update! I don't mind giving it a go.

**Comment by Ghorbanian** [comment]
@holgerd77 I am not sure what you mean by "tricking the VM to think `DEBUG` is set." I am assuming we want to be able to set the debug option before a test is run so as to trigger log output, which I am looking into using shell scripting using the `tester` that is already available. Does this sound like a dead end to you? Am I understanding what you mean by "tricking the VM to think `DEBUG` is set" correctly?

**Comment by Ghorbanian** [comment]
@holgerd77 I don't have a lot of time to contribute for the coming weeks. Feel free to turn this into its own issue and let others take a shot at it.
