### ISSUE TITLE
Is ethereumjs ready for EIP-1559?

### ISSUE THREAD

**Issue by jtomtan** [ethereumjs/ethereumjs-monorepo#1231]
Is ethereumjs ready for EIP-1559? If so, where can I find code snippet for sending tx with EIP-1559 (baseFee + Tip)?

Thanks.

**Comment by ryanio** [comment]
Hey, yes it is currently being worked on in #1148

**Comment by jtomtan** [comment]
> Hey, yes it is currently being worked on in #1148

Cool. Good work. I will follow this.

**Comment by holgerd77** [comment]
London/1559 ready versions of all affected libraries have now been released along #1263, will close.
