### ISSUE TITLE
Block: Improve Code Coverage

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1232]
When looking at the [coverage report](https://codecov.io/gh/ethereumjs/ethereumjs-monorepo/tree/master/packages/block/src) for the `Block` library especially the core `block.ts` and `header.ts` files show significant gaps in coverage with several lines being completely in the red.

This should be improved so that coverage goes into the realm of 82-85% in a first round, and this with an extra attention/eye on newly added code parts along the introduction of typed transactions (`EIP-2718`/ `EIP-2930`).

**Comment by acolytec3** [comment]
I'm going to take a stab at this, mainly focused on testing some of the error conditions that aren't currently addressed in `header.ts`

**Comment by holgerd77** [comment]
Just had another look here, coverage has gotten sufficient and is now up to the 82-85% level we have on the other libraries (not really sure on which PRs this has increased, but checked the latest `master`, so definitely in).

There are still some gaps here and there which would be worth to fill. Nothing out of realm though compared to the other libraries, will close this issue here.
