### ISSUE TITLE
Tx: Potential EIP-2930 getMessageToSign() Typing Bug

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1251]
Something is not correct with the overload typing of [getMessageToSign()](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/tx/src/eip2930Transaction.ts#L283) on EIP-2930 compatible txs.

When looking at the implementation this method should return a `Buffer` for all the `hashMessage=false` cases for EIP-2930 txs.

However TypeScript is assuming this to be `Buffer[]`, this can e.g. be tested by adding the following to the respective `eip2930.spec.ts` test case:

```typescript
//@ts-ignore
console.log(unsignedTx.getMessageToSign(false).toString('hex'))
```

So this needs a `@ts-ignore` to work (when run this then outputs the correct hex string) since TypeScript is assuming this to be a `Buffer[]`.

**Comment by ryanio** [comment]
Ah, so since the function returns a Buffer either way then I think we can just remove the overloads and simplify it to:

`getMessageToSign(hashMessage = true): Buffer {`

**Comment by ryanio** [comment]
Ohh this is confusing because typed txs return the serialized tx when hashMessage is false, so I defined the overloads correctly for legacy txs but not typed txs. I will open a PR to fix.
