### ISSUE TITLE
Tx: isSigned() bug for typed txs

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1252]
*sigh*

This is an important one: we still have got a bug on [isSigned()](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/tx/src/baseTransaction.ts#L173) for typed txs with a `v=0` value.

Current implementation looks like the following:

```typescript
public isSigned(): boolean {
    const { v, r, s } = this
    return !!v && !!r && !!s
  }
```

It can be easily tested that this goes to `false` with a`v=0`:

```shell
> const v = 0
'use strict'
> const r = 1
undefined
> const s = 2
undefined
> !!v && !!r && !!s
false
>
```

I will fix this along the EIP-1559 tx test additions (we'll release soon anyhow) and give this a very very explicit implementation.

Ugh. 🙁

**Comment by jochem-brouwer** [comment]
Ugh why does this stuff keep returning :cry: It's this thing where JS interprets the number `0` as falsy :sob:

**Comment by ryanio** [comment]
`v`, `r`, `s` are stored as `BN | undefined`, so `v` would be `new BN(0)` so the logic should still work correctly.

**Comment by holgerd77** [comment]
Ah, sorry, then this was my wrong analysis. Hadn't taken `BN` into the mix.

**Comment by ryanio** [comment]
no problem. should we revert this commit then? https://github.com/ethereumjs/ethereumjs-monorepo/pull/1148/commits/3f8f382e1c1cff74ca61077b7ad9e56fa148272a

**Comment by holgerd77** [comment]
@ryanio I have no strong opinion on reverting 3f8f382 - I am a bit lazy here TBH - if you want you can just do along another PR (or also separately, as you prefer).

**Comment by ryanio** [comment]
on second look, i think the commit is fine. i'll just close this then.
