### ISSUE TITLE
How to send signed transaction for Polygon(Matic) testnet

### ISSUE THREAD

**Issue by 0xMars** [ethereumjs/ethereumjs-monorepo#1260]
Here is my code.
```
export const callContractFunc = async (contractFunction, contractAddress) => {
	const functionABI = contractFunction.encodeABI();
	const account = process.env.PUBLIC_KEY;

	const gasAmount = await contractFunction.estimateGas({ from: account });
	console.log('Estimated GAS:', gasAmount);

	const _nonce = await web3.eth.getTransactionCount(account);
	const nonce = _nonce.toString(16);
	console.log('Nonce:', nonce);

	const txParams = {
		gasPrice: web3.utils.toHex(10e9),
		gasLimit: Web3.utils.toHex(gasAmount),
		from: account,
		to: contractAddress,
		data: functionABI,
		nonce: '0x' + nonce,
	};

	const tx = new Transaction(txParams, { chain: 'goerli' });
	tx.sign(Buffer.from(process.env.PRIVATE_KEY, 'hex'));
	const receipt = await web3.eth.sendSignedTransaction('0x' + tx.serialize().toString('hex'));
	console.log('Receipt:', receipt);
	return receipt;
};
```

This function works correctly on ethereum mainnet and testnets like ropsten, rinkeby and goerli.
Now our team is focusing on matic network and I have no idea what should I put to `chain` param when creating a new transaction.
Need your help.

**Comment by holgerd77** [comment]
Actually I guess we have no idea as well, I don't think anyone from the team has deeper experience with the Polygon network! 😀

So I guess we need to figure this out together.

Dropping a link here where we might find some further information:

- [Matic Docs - Network Information](https://docs.matic.network/docs/integrate/network-detail)

It might be possible to get this going with the [Common library custom chain functionality](https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/common#working-with-privatecustom-chains), so this is likely worth a try.

Eventually there needs to be some adoption on the libraries, not sure.

**Comment by holgerd77** [comment]
@0xMars not sure about your closing here, if it is for:

1. having your question unanswered for too long: sorry, but we don't have the resources to immediately jump on new requests on dedicated new tech aspects, even if it would be nice to be able to.

2. having this figured out yourself: can you share your findings here?

Ok, have a nice day! 😄

**Comment by BarneyChambers** [comment]
Also interested in this please

**Comment by jochem-brouwer** [comment]
https://github.com/maticnetwork/static/blob/da36673471412cb09862959e7352034c4ed36cb9/network/mainnet/v1/index.json#L79

Looks like Chain ID is 137?

**Comment by holgerd77** [comment]
@BarneyChambers @jochem-brouwer seems like the original author of this issue is not interested in following up on the discussion here. I have open a new dedicated issue where we can continue on an exchange.
