### ISSUE TITLE
Client: PoW Consensus Validation Default / Ethash Library

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1268]
Running the client with consensus validation activated on PoW is extremely slow since we are using the plain JS implementation library [@ethereumjs/ethash](https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/ethash) for PoW validation.

For some reference: I have just tested this with `mainnet` block synchronization, and this already jumps from 2-3 second wait time from the last execution (before block queue is empty) to the sync of the next import-chunk of blocks up to 20-30 seconds wait time between these two events, with sync starting around block 500.000. So there is some evidence that this is just not working at all atm with higher difficulty on later block numbers.

Two decisions to be made here:

1. What should we actually use as some default setting for now? There was some back-and-forth switching in the past with somewhat good arguments for both sides (development: "impractical" -> turn off, protocol: "cheating" -> turn on) 😋  One first suggestion/possibility: we could turn on and add a CLI flag to explicitly turn off if wished.

2. We have a [node-ethash](https://github.com/ethereumjs/node-ethash) library which offers some bindings to C++ and is likely orders of magnitude faster. This library is unmaintained though for quite some time. Would it eventually be worth the effort (also considering the fact that "The Merge" [tm] is only an estimated 4-8 months away and this will limit the use of PoW significantly) to revive and find a practical way to integrate?

3. Maybe there are also other solutions: e.g. the `@ethereumjs/ethash` library might be good candidate for a first `WASM` test with a very limited number of dependencies and a very reduced API surface which would need to be compatible

**Comment by holgerd77** [comment]
Side note: point 3. might be a good task for @acolytec3 to experiment with.

**Comment by acolytec3** [comment]
One thought on this might be to see if we can compile the go implementation [here](https://github.com/ethereum/ethash) to WASM.  I'll start thinking on it

**Comment by holgerd77** [comment]
@acolytec3 I am a bit cautious here since I had mixed experiences with creating this strong 3rd-party dependencies with these kind of things with no direct control of the original code, but might be a way. I was also thinking about making our own ethash implementation [AssemblyScript](https://www.assemblyscript.org/)-ready and then try a WASM build from that. This would generally be a cool experiment since eventually we can use this for other libraries (RLP e.g.) as well.

**Comment by acolytec3** [comment]
@holgerd77 Understood. I started looking over the AssemblyScript documentation last night and may start playing around with it this week.

**Comment by holgerd77** [comment]
(@acolytec3 I don't have all the arguments here on my side, just wanted to throw this in the ring since we had some not-so-good experiences with some Web3 infrastructure library (Websocket) forking, might be a case-by-case decision though)

**Comment by holgerd77** [comment]
Related: #845

**Comment by axic** [comment]
> One thought on this might be to see if we can compile the go implementation here to WASM. I'll start thinking on it

The `ethereum/ethash` project seems to be old and not much maintained. As a note, https://github.com/chfast/ethash is a modern implementation (used by Silkworm) and it compiles to wasm (individually as well as part of Silkworm). If you'd consider taking an upstream project, I would recommend this one.

**Comment by acolytec3** [comment]
@axic Thanks for the reference. I cloned the repo and will start experimenting with it. This seems like it might be a good way forward given the time limited nature of this issue (pending The Merge (tm))

**Comment by holgerd77** [comment]
The Merge is approaching fast and getting closer and closer, I think we likely don't want to spend additional ressources on further ethash optimization, will close here. Feel free to reopen if you feel otherwise.

**Comment by holgerd77** [comment]
Ah, actually I will reopen so that we at least can decide on 1. (default setting for PoW validation e.g. on 'mainnet'). I guess I would still pledge for "turn on" and allow to turn off by CL switch. //cc @jochem-brouwer, others

**Comment by acolytec3** [comment]
Can we go ahead and close this?  The merge is for real going to be happening soon :tm: and we've already got a snap sync implementation started so seems like we will never need a high powered ethash implementation.  Amirite?

**Comment by holgerd77** [comment]
> Can we go ahead and close this? The merge is for real going to be happening soon ™️ and we've already got a snap sync implementation started so seems like we will never need a high powered ethash implementation. Amirite?

Yes, that makes a lot of sense I guess (everyone feel free to disagree and/or reopen).

Will close here. 🙂
