### ISSUE TITLE
VM: Fix Undefined Opcode Bug

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1271]
Test runs along #1269 have discovered a bug on calling a contract with an undefined opcode as first byte of the code added as a test in `ethereum/tests` here https://github.com/ethereum/tests/pull/836.

Test run can be reproduced with:

```shell
ts-node ./tests/tester --state --fork=Berlin --test='undefinedOpcodeFirstByte'
```

As some debug trace shows exception is thrown within an `SSTORE` operation on a `const found = await getContractStorage(runState, runState.eei.getAddress(), keyBuf)` call (see code [here](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/vm/lib/evm/opcodes/functions.ts#L766)):

![image](https://user-images.githubusercontent.com/931137/119648282-8fc23600-be21-11eb-8dd9-aa18fccfa737.png)

This respectively the root cause of the bug should be examined and the test readded to the tests to be run on CI.

**Comment by ryanio** [comment]
This is the error stack trace:

```
vm:eei:gas SSTORE (base fee): used 0 gas (-> 69976319) +0ms

(node:22277) UnhandledPromiseRejectionWarning: Error: Invalid node
    at Object.decodeNode (/Users/ryanghods/dev/ethereumjs-monorepo/packages/trie/src/trieNode.ts:190:11)
    at SecureTrie.lookupNode (/Users/ryanghods/dev/ethereumjs-monorepo/packages/trie/src/baseTrie.ts:272:19)
    at /Users/ryanghods/dev/ethereumjs-monorepo/packages/trie/src/util/walkController.ts:49:20
```

I traced it to `walkController.startWalk` -> `trie.lookupNode` -> which was returning a value of `<Buffer 80>` which errored out in `decodeNode` as it wasn't valid rlp.

I found a fix by returning null from `lookupNode` if `decodeNode` fails, like so:

prior ([link](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/trie/src/baseTrie.ts#L270)):

```typescript
if (value) {
  foundNode = decodeNode(value)
}
```

this fixes the test:

```typescript
    if (value) {
      try {
        foundNode = decodeNode(value)
      } catch (e) {
        // If unable to decode the node a complete node
        // may not have been returned.
        return null
      }
    }
```

I'm still not sure why the db was returning data `<Buffer 80>` from the storageTrie at key 0x0 though.

**Comment by holgerd77** [comment]
Please don't try to solve this issue right now but rather the ones related to 1559 from the tests PR. This one is for ages in the VM, got never triggered before and we can very well postpone in doubt.

**Comment by holgerd77** [comment]
This is still an issue and should be tackled at some point. Might also be a good starter issue for the VM since relatively locally.

**Comment by acolytec3** [comment]
This is merged in our `develop` branch and will be addressed in the next breaking release.
