### ISSUE TITLE
Tx: EIP-155 not properly supported for legacy txs in raw() and serialize() methods

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1278]
Just had a long discussion in the chat (ethereumjs channel) about ledger signing (using [ledgerjs/hw-app-eth#signtransaction](https://github.com/LedgerHQ/ledgerjs/tree/master/packages/hw-app-eth#signtransaction)) being not properly supported by the `@ethereumjs/tx` package, respectively going wrong when doing a plain `tx.serialize()` and then sending the serialized tx to the ledger JS app.

We were able to locate the problem and hotfix this with:

```typescript
import { BN } from 'ethereumjs-util'
const tx = Transaction.fromTxData(txParams, { common, freeze: false }) // Allow the tx to be modified
tx.v = new BN(4) // Rinkeby chain ID
tx.serialize()
```

So the chain ID before was not included in the raw tx and therefore the serialized tx output was different than the one expected. I did some googling, there is even a whole [blog post](https://matthewdowney.github.io/signing-ethereum-transactions.html) on this problem (how to hotfix `ethereumjs-tx` to allow signing with a hardware wallet/ledger).

With re-reading up on  [EIP-155](https://eips.ethereum.org/EIPS/eip-155) I've generally the impression that we are not sufficiently supporting the EIP.

> If block.number >= FORK_BLKNUM and CHAIN_ID is available, then when computing the hash of a transaction for the purposes of signing, instead of hashing only six rlp encoded elements (nonce, gasprice, startgas, to, value, data), you SHOULD hash nine rlp encoded elements (nonce, gasprice, startgas, to, value, data, chainid, 0, 0).

So for now I think both the `raw()` and (follows somewhat automatically) the `serialize()` method for unsigned legacy txs should be modified to return the chain ID for `v` instead of an empty value. As I read `EIP-155` I would also imply that this would go through as a bug fix, also regarding that "preparing for tx signing" is very much the most prevalent use case for instantiating an unsigned tx (or am I missing something here?).

To keep the roundtrip working I would also suggest that we also allow for this kind of input in the `fromSerializedTx()` static constructor (why not?), and we might add an additional check on the passed in chainId comparing with the chainId from Common.

I am currently tempted to go as far to suggest that we actually should *internally* set the `v` value on unsigned legacy txs to the chainId. This seems the most coherent solution to me. This would need to be implemented with some significant care though, since it would also need (just internal) modifications on other methods, e.g. `isSigned()`.

WDYGT? 🤔

//cc @alcuadrado @ryanio @jochem-brouwer

**Comment by holgerd77** [comment]
There was some continued discussion here and @alcuadrado pointed out that EIP-155 would not be so far reaching, will cite here from the chat discussion:

> I don't think that would be a good idea
> there's no such a thing as serializing an unsigned tx in the protocol
> and the signature process is not defined anywhere as sign(hash(serialize()))
> that's a misconception many users have
> but it's not actually true, neither with eip155 nor the envelope txs

We've found out though that the `tx.getMessageToSign()` method - which is intended to be used for such a use case is not optimal from an API perspective by not returning the RLP encoded serialized tx format (when used with `hash=false`) which is confusing for the users.

A working example for using this method would be:

```typescript
import { rlp } from 'ethereumjs-util'
import Common from '@ethereumjs/common'
import { Transaction } from '@ethereumjs/tx'

const common = new Common({ chain: 'goerli', hardfork: 'berlin'})
const tx = Transaction.fromTxData({}, { common })

const message = tx.getMessageToSign(false)
const serializedMessage = rlp.encode(message) // use this for the ledger input
```

We will improve here by changing the API on the next breaking release. For now I will add a subsequent PR doing better documentation on various fronts.

Will close here.

**Comment by alcuadrado** [comment]
Can you provide more info about how you are using ethers?

**Comment by alcuadrado** [comment]
I see. I think you are doing one rlp encoding more than what ledger expects.
