### ISSUE TITLE
Tx/Common: Arbitrum One Support

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1290]
Part of #1288 

[Arbitrum One](https://arbitrum.io/) building on the Arbitrum Optimistic Rollup technology is a L2 solution by [Offchain Labs](https://offchainlabs.com/) which just recently launched in mainnet beta.

We should see if we get a connection going - eventually by adopting the Common library and a new network - and if it's possible to send a tx with our tx library.

There is a [public testnet](https://developer.offchainlabs.com/docs/public_testnet) which might be a good starting point for trying to send a test tx, token bridge (from Kovan, interestingly) can be found [here](https://bridge.arbitrum.io/) and explorer [here](https://explorer5.arbitrum.io/).

**Comment by holgerd77** [comment]
I've now tried to compose together an Arbitrum testnet tx with the following script:

```typescript
/**
 * Usage:
 * ts-node create-arbitrum-tx.ts PRIVATE_KEY
 */
import { Transaction } from '../ethereumjs-monorepo/packages/tx/src'
import Common from '../ethereumjs-monorepo/packages/common/dist'

const from = '0xaaec86394441f915bce3e6ab399977e9906f3b69'

const PRIV_KEY = process.argv[2]
const to = '0xe13ece23b514caa5b53395c01d0d53d1843258ad'

const common = Common.forCustomChain(
  'mainnet',
  {
    name: 'arbitrum-testnet-v5',
    networkId: 144545313136048,
    chainId: 144545313136048,
  },
  'berlin',
)

const txData = {
  from,
  nonce: 0,
  gasPrice: 1000000000,
  gasLimit: 100000,
  to,
  value: 100,
}

const tx = Transaction.fromTxData(txData, { common })
const signedTx = tx.sign(Buffer.from(PRIV_KEY, 'hex'))

console.log(signedTx.serialize().toString('hex'))
```

This results in the following serialized tx format: `f86b80843b9aca00830186a094e13ece23b514caa5b53395c01d0d53d1843258ad6480870106ed28163b84a038234a7282181eac9cb3e735357b60f92db0c250d868622308b7b4c7e9ec9ab0a00f6a9412b5061a439105fe46e6879f346eddb39cfb446a8a1ff299379c901ca5`

**Comment by holgerd77** [comment]
There is a public [RPC endpoint](https://kovan5.arbitrum.io/rpc) for the testnet.

I've now sent the tx with:

```shell
curl https://kovan5.arbitrum.io/rpc \
    -X POST \
    -H "Content-Type: application/json" \
    -d '{"jsonrpc":"2.0","method":"eth_sendRawTransaction","params":["0xf86b80843b9aca00830186a094e13ece23b514caa5b53395c01d0d53d1843258ad6480870106ed28163b84a038234a7282181eac9cb3e735357b60f92db0c250d868622308b7b4c7e9ec9ab0a00f6a9412b5061a439105fe46e6879f346eddb39cfb446a8a1ff299379c901ca5"],"id":1}'
```

Interestingly enough this gives `{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"execution reverted: error code InsufficientGasForBaseFee"}}` (1559 already implemented here?) 😄 .

**Comment by holgerd77** [comment]
Cautious half-success: there seems to be a new gas unit called `arbGas` on Arbitrum, see e.g. the info field on the tx parameters of [this transaction](https://explorer5.arbitrum.io/#/tx/0x93105540a20a4382e25dee4e5f045f7cf5c55303d218981e070a0610c8e627d2), citing here:

![image](https://user-images.githubusercontent.com/931137/121179297-d8d1ab80-c85f-11eb-846b-7ba5840279b2.png)

So I tried to send the same tx with a 100x (or actually: used 30x) `gasLimit` - so `3000000`. This tx seems to have gone through, reported tx hash is `{"jsonrpc":"2.0","id":1,"result":"0xe598c1b537f6b8f849deba0e7be50b27bf4f489fee28c7d3f2bf51b39560036d"}`.

Tx is just not showing up on the block explorer or can be searched, there are generally no updates there though so might be a problem on the testnet and/or explorer side.

Anyhow. Nice start. 🙂

**Comment by ryanio** [comment]
Added in https://github.com/ethereumjs/ethereumjs-monorepo/pull/1317
