### ISSUE TITLE
Common: Remove retired dev networks

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1294]
As some housekeeping I guess we can remove the retired dev networks again from `Common`, these are:

- Yolov3
- Aleut
- Baikal

References to remove are:

- The chain files (`aleut.json`)
- References in `chains/index.ts`
- Likely some test cases
- The listing in the respective README section

(or do we want to keep for some kind of historical reasons or something?)

**Comment by emersonmacro** [comment]
@holgerd77 I put up a PR (https://github.com/ethereumjs/ethereumjs-monorepo/pull/1296) - it was pretty straightforward cleanup. I didn't see any affected tests in the `common` package, but the automated checks on the PR caught that there is a test in the `tx` package that uses the `aleut` network: https://github.com/ethereumjs/ethereumjs-monorepo/pull/1296/checks?check_run_id=2808390978#step:7:23

Looks like it's a set of tests for EIP1559 transactions - https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/tx/test/eip1559.spec.ts#L9

I'm not fully up to speed on EIP1559... Can I update that test file to use a different chain? Should I add `aleut` back to the `common` package?

**Comment by emersonmacro** [comment]
I updated the PR, converted the `eip1559` test in `tx` to use `rinkeby` instead of `aleut`

**Comment by holgerd77** [comment]
Closed by #1296
