### ISSUE TITLE
Client: Calaveras (London Testnet) Syncing

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1306]
I just tested the [Calaveras](https://github.com/ethereum/eth1.0-specs/blob/master/network-upgrades/client-integration-testnets/calaveras.md) network run. The client sync being stuck (as in Baikal) has again to do with this spammy blocks - on this network in the early 2000-2500 or so block range.

I don't have a quick fix at hand, this is likely some devp2p timeout or size limitation issue with not all Block bodies coming through being too large.

This can be mitigated though with this fix we already had in Baikal by setting the `maxPerRequest` value (always not sure if `BlockFetcherBase` or `Fetcher` from `50` to `1`, so that blocks are just requested sequentially.

This then makes it possible again to sync the network and see if we can run all the blocks.

Opening up this issue for general observations around the Calaveras sync and block/tx compatibility.

**Comment by acolytec3** [comment]
Closing as London is now on testnets with target mainnet date.
