### ISSUE TITLE
Tx Error { Error: Returned error: only replay-protected (EIP-155) transactions allowed over RPC

### ISSUE THREAD

**Issue by amitOodles** [ethereumjs/ethereumjs-monorepo#1309]
I am using the following modules to transact on the ethereum rinkeby network

```
@ethereumjs/common: 2.3.0,
@ethereumjs/tx: 3.2.0,
web3: 1.3.4
```

Following is the code to generate the signed transaction which is then broadcasted through web3's sendSignedTransaction method

```
const EthereumTx = require("@ethereumjs/tx").Transaction;
const Common = require("@ethereumjs/common").default;

async function signTx(payload) {
    let { to, data, value, gas, gasPrice, privKey, nonce, chainId } = payload
    let txParams = {
      to,
      data,
      value: web3HttpInstance.utils.toHex(value),
      gasPrice: web3HttpInstance.utils.toHex(gasPrice),
      gas: web3HttpInstance.utils.toHex(gas),
      nonce: web3HttpInstance.utils.toHex(nonce),
      chainId : web3HttpInstance.utils.toHex(chainId)
    }
    var tx = new EthereumTx(txParams,{common : new Common({chain:"rinkeby"})})
    privKey = new Buffer(privKey, 'hex')
    tx.sign(privKey)
    return tx
}
```

But the transaction is failing with the given errors

```
2021-06-20T09:37:39.705Z: ETHTRANSACTIONUTIL.JS: ERROR: Tx Error { Error: Returned error: only replay-protected (EIP-155) transactions allowed over RPC
    at Object.ErrorResponse (/home/amit/Projects/WETHIO/Bridge/wethio-bridge/node_modules/web3-core-helpers/lib/errors.js:28:19)
    at /home/amit/Projects/WETHIO/Bridge/wethio-bridge/node_modules/web3-core-requestmanager/lib/index.js:303:36
    at XMLHttpRequest.request.onreadystatechange (/home/amit/Projects/WETHIO/Bridge/wethio-bridge/node_modules/web3-providers-http/lib/index.js:98:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/amit/Projects/WETHIO/Bridge/wethio-bridge/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/home/amit/Projects/WETHIO/Bridge/wethio-bridge/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/home/amit/Projects/WETHIO/Bridge/wethio-bridge/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/home/amit/Projects/WETHIO/Bridge/wethio-bridge/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) data: null }

```

This error gets thrown after sending the signed transaction with web3. What is the issue here ?

**Comment by ryanio** [comment]
Hey, the reason is that `.sign()` returns a new tx object so you should do `return tx.sign(privKey)` or `tx = tx.sign(privKey); return tx`

**Comment by amitOodles** [comment]
Hi ryanio, thanks i checked the source code and updated my code to use the new object returned, the issue was resolved then.

**Comment by anistark** [comment]
> Hey, the reason is that `.sign()` returns a new tx object so you should do `return tx.sign(privKey)` or `tx = tx.sign(privKey); return tx`

The sign() function returns undefined for me. Has this changed since this comment?

**Comment by jochem-brouwer** [comment]
Could you post a code snippet @anistark? On what version of ethereumjs/tx are you? The sign method should not return `undefined` per function signature.

**Comment by anistark** [comment]
@jochem-brouwer Thanks for quick response. Stuck on this since morning. 😓 

Versions:
```
"@ethereumjs/common": "^2.6.0",
"@ethereumjs/tx": "^3.4.0",
```

Here's the code snippet:

```
...

const ethereumjs_common = require ('ethereumjs-common').default;
const EthereumTx = require('ethereumjs-tx').Transaction;

const common = ethereumjs_common.forCustomChain(
  'goerli',
  {
    name: 'matic-mumbai',
    networkId: 80001,
    chainId: 80001
  },
  'muirGlacier'
)

var txData = {
  nonce: nonce,
  chainId: 80001,
  from: address1,
  to: address2,
  data: contract.methods.methodName(params).encodeABI()
}
              
let tx = new EthereumTx(txData, {common : common});
let signedTx = tx.sign(Buffer.from(privateKey, 'hex'));
console.log('signedTx:', signedTx);
...
```

Output as:
`signedTx: undefined`

**Comment by jochem-brouwer** [comment]
It seems like you are using `ethereumjs-tx` and `ethereumjs-common` in your snippet instead of `@ethereumjs/tx` and `@ethereumjs/common`?

**Comment by jochem-brouwer** [comment]
Looking at https://github.com/ethereumjs/ethereumjs-tx/blob/master/src/transaction.ts (deprecated `ethereumjs-tx`) it seems that `sign` does not return any value (it always returns `undefined`). Instead, it assigns the signature to the Object. So, this should work:

```
let tx = new EthereumTx(txData, {common : common});
tx.sign(Buffer.from(privateKey, 'hex'));
console.log('signedTx:', tx);
```

**Comment by anistark** [comment]
I see. But with this I'm still getting  `Error: Returned error: only replay-protected (EIP-155) transactions allowed over RPC`

**Comment by anistark** [comment]
> It seems like you are using `ethereumjs-tx` and `ethereumjs-common` in your snippet instead of `@ethereumjs/tx` and `@ethereumjs/common`?

When I go with 
```
const EthereumTx = require('@ethereumjs-tx').Transaction;
```

I get `Error: Cannot find module '@ethereumjs-tx'`

**Comment by jochem-brouwer** [comment]
You need a slash (/): `@ethereumjs/tx` not `@ethereumjs-tx`. 

What is the `v` value of your tx? If it is 36 or 37 then for some reason it is not using EIP 155. 

I strongly suggest updating to `@ethereumjs/tx` since `ethereumjs-tx` is very outdated.
