### ISSUE TITLE
Retrieving the prefix 0x02 or 0x03 of the public key from the uncompressed form

### ISSUE THREAD

**Issue by Jdodo45** [ethereumjs/ethereumjs-monorepo#1318]
I use this code to generate a public key but it provide the uncompressed form. So it doesn't provide the first part that is either 0x02 or 0x03.  I tried `addHexPrefix()` from  `ethereumjs-util` but it doesn't  work. 

So, my question is: how can I can retrieve this prefix?

```
    bip39 = require('bip39');
    ethUtil = require('ethereumjs-util');
    hdkey = require('hdkey');
    
    const mnemonic = bip39.generateMnemonic(256); 
    const seed = bip39.mnemonicToSeedSync(mnemonic);
    const root = hdkey.fromMasterSeed(seed);
    const masterPrivateKey = root.privateKey.toString('hex');
    
    var path = "m/44'/60'/0'/0/0"  // change path 
    var addrNode = root.derive(path); 
    var pubKey = ethUtil.privateToPublic(addrNode._privateKey);
    var addr =  '0x' +  ethUtil.publicToAddress(pubKey).toString('hex');
    var address = ethUtil.toChecksumAddress(addr);
    
    console.log( "\n", "\n", "\n","ACCOUNT ", path, "\n", "private key : 0x", addrNode._privateKey.toString('hex'), "\n", "public key : ",pubKey.toString('hex'), "\n", "address : ", address)
```

This is what I get :

```
     ACCOUNT  m/44'/60'/0'/0/0
     private key : 0x459b3b4aa03ed8284162a19ffc3176aa94ac9cec5081825fc44975d5da0ee43b
     public key :  fc97d3de3a50d6acefd56a6df5a1d986f029ae1d44f9af46184eec1e7b0a7f5bfd65899b50ce8a6cf3c2523667e47426e0d9d05440d93c0c8252ec855440a049
     address :  0x95F6896D9Ea299133CEd273F410F62D58aaDd62B
```

I know that I can get this prefix on the website https://iancoleman.io/bip39/ but only for development project. For security purposes, I can't use this website for actual wallet (unless there is a way, that I am not aware of, to make it work locally).

**Comment by ryanio** [comment]
Hey @Jdodo45, searching around this is what I found to help answer your question:

> It seems that iancoleman is compressing your public key: It was discovered that it was possible to "compress" a ecdsa public key (composed of a X,Y couples of values), but just using the X value, and knowing if Y if even or odd, and adding the 0x02 or 0x03 prefix X. There is documentation about that everywhere on the internet, like on this page https://bitcoin.stackexchange.com/questions/3059/what-is-a-compressed-bitcoin-key.

from: https://bitcointalk.org/index.php?topic=3168380.msg32773245#msg32773245

I'm not sure if `ethUtil.privateToPublic` works with the compressed form though, if you try please let us know how it goes.

**Comment by Jdodo45** [comment]
Thanks for your answer @ryanio. I went a bit down the rabbit hole but still, I can't find a way to calculate if Y is even or odd (by the way, some say > or < 0 instead of even/odd). Any idea?

**Comment by Jdodo45** [comment]
Sorry I posted to fast. The [secp256k1-node](https://github.com/cryptocoinjs/secp256k1-node#get-x-point-of-ecdh) is able to find it:

```
// compressed public key from X and Y
function hashfn (x, y) {
  const pubKey = new Uint8Array(33)
  pubKey[0] = (y[31] & 1) === 0 ? 0x02 : 0x03
  pubKey.set(x, 1)
  return pubKey
}

```

**Comment by ryanio** [comment]
nice!

**Comment by acolytec3** [comment]
@ryanio, @Jdodo45  is there anything further for us to address on this one? Do we need something similar in `ethereumsjs-util`?

**Comment by acolytec3** [comment]
Closing as seems to be addressed.
