### ISSUE TITLE
ERROR: throw new Error("Cannot convert string to buffer. toBuffer only supports 0x-prefixed hex strings and  this string was given: " + v);                 ^  Error: Cannot convert string to buffer. toBuffer only supports 0x-prefixed hex strings and this string was given: 1000000000000000000

### ISSUE THREAD

**Issue by sachinlokanna** [ethereumjs/ethereumjs-monorepo#1321]
const EthereumTx = require('ethereumjs-tx').Transaction
const Web3 = require("web3")
const url = "https://rinkeby.infura.io********"
var web3 = new Web3(url)

const account1 = ' '
const account2 = ' '

const privatekey1 = Buffer.from('private key','hex',)
//web3.eth.getBalance(account1,(err,bal)=>{console.log(web3.utils.fromWei(bal,"ether"))})
console.log(privatekey1)
web3.eth.getTransactionCount(account1,(err,txCount)=>{
    //Build the transaction
    const txObject = {
        nonce: web3.utils.toHex(txCount),
        to: account2,
        value: web3.utils.toWei('1','ether'),
        gasLimit: web3.utils.toHex(21000),
        gasPrice: web3.utils.toHex(web3.utils.toWei('10','gwei')),
    }

    //sign the transaction 
    const tx = new EthereumTx(txObject,{chain:'rinkeby'})
    tx.sign(privatekey1)

    const serializedTransaction = tx.serialize()
    const raw = '0x' + serializedTransaction.toString('hex')

    //Broadcast the transaction
    web3.eth.sendSignedTransaction(raw,(err,txHash)=>{
        console.log('txHash:',txHash)
    })
})

**Comment by holgerd77** [comment]
Can you please provide some more information? What `@ethereumjs/tx` and `web3.js` versions are you using?

Also: on what line of your script is this error thrown? Thanks!

**Comment by ryanio** [comment]
Your integer string is too large of a number, please use a 0x-prefixed hex string representing the number or a BN object instead.

Also signing the tx with `sign()` won't overwrite the tx, please use `const signedTx = tx.sign()` and then pass that signedTx to sendSignedTransaction (or with your code you can do `const serializedTransaction = tx.sign(privatekey1).serialize()`)

**Comment by holgerd77** [comment]
Will close here for now, should likely be solved.
