### ISSUE TITLE
Common: hardforkBlockBN() (hardforkIsActiveOnBlock()) Bug for HFs with null value

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1328]
`hardforkBlockBN()` is currently returning an empty `BN` instance for HFs with a null value, see e.g.:

![grafik](https://user-images.githubusercontent.com/931137/123943257-43c45d00-d99c-11eb-9c66-c1a3b2e73deb.png)

This is likely not what we want - this should rather return `null`. This also leads to at least one internal bug with `hardforkIsActiveOnBlock()` falsely returning `true` for a `null` HF check (also see screenshot above).

Issue is somewhat urgent since we should include in #1327, fix should be simple though.

**Comment by ryanio** [comment]
Working on this now
