### ISSUE TITLE
Client: Improve client synchronization behavior.

### ISSUE THREAD

**Issue by gabrocheleau** [ethereumjs/ethereumjs-monorepo#1335]
PR #1314 implemented a `synchronized` prop on the client and a `startingBlock` prop on the `synchronizer`. These implementations are a bit naïve, and would likely not behave as expected in the event of synchronization errors, synchronization lagging behind, or synchronization restarts.

For `synchronized`:

The `synchronized` boolean property is initialized as false when the client is instantiated and gets set to true when the synchronized event is emitted. There is room for improvement when other kind of events are emitted, for example when error events are emitted, when the chain falls behind, or perhaps when the synchronization is rebooted without the client rebooting (not sure if that would ever happen?).

For `startingBlock`:

Starting block is initialized as the "local latest block" when the synchronizer `opens`. However, the startingBlock should not be reset to the new "local latest block" if we stop/start the synchronization again, unless the synchronization has already reached the tip of the chain. So basically, unless we've successfuly completed a synchronization, we shouldn't reset `startingBlock`. This fits with the `eth_syncing` behavior described here: https://eth.wiki/json-rpc/API#eth_syncing

**Comment by acolytec3** [comment]
Do we still need this now that the PRs for tracking the tip of the chain are done?

**Comment by holgerd77** [comment]
Agree, I guess we have improved substantially enough here to regard this issue as outdated. Will close.
