### ISSUE TITLE
Monorepo: Separate Node and Browser Build commands

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1339]
One CI improvement which is relatively high on my personal wishlist would be to have separate build commands for Node and the browser, since in 90%+ of the cases I am only interested in the Node builds and always doing the browser builds takes an unnecessary amount of extra time (especially for the client, there it is rather insane).

My suggestion here would be to follow the pattern of the `package.json` `test` commands and separate into a `build:node` and `build:browser` + an encompassing `build` (calling into both the other commands) command. I would then also suggest that we retire (respectively: delete) the current [config/cli/ts-build.sh](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/config/cli/ts-build.sh) script. I have the impression that this is not adding a lot of value and we can just simply call into `tsc -p ./tsconfig.browser.json"` via the local `package.json` file commands. There is nothing lost which was centralized before and the config is then still inherited from within the local `tsconfig.browser.json` files from the central `config` directory.

**Comment by ryanio** [comment]
makes sense, could another option be to add a `--skip-browser` flag that the `ts-build.sh` script understands?

i do like having a unified build script with the included browser builds so they aren't forgotten, but I understand why in some cases why you would want to skip them.

**Comment by holgerd77** [comment]
I think I am somewhat stronger in favor of my suggestion, my fear is a bit that this would be yet another option which I would forget at some point and others will likely never discover, so I would find explicit node commands more transparent for such a basic operation, I would also find it more in line with the current `test`, `test:node`, `test:browser` command structure.

I am also not seeing this concern that browser builds could be forgotten. There still will be the unified `npm run build` command calling into `npm run build:node` and `npm run build:browser` and this will also be called before a release. And if someone is just typing in `npm run build:node` he/she should know what he/she is doing I guess?

That said: if you see some value in having this build script respectively feel that this might be expanded in the future (atm I am really not seeing the usefulness of this) we can also go with the `--skip-browser` option, for me this would already be an improvement. Though, another argument I am just live-thinking about 😋: there *are* also use cases where one just *wants* to build the *one* or the *other* thing (and not just the one-sided browser skip), e.g. if one is testing the browser tests and needs some constant rebuilding. This would just not be possible with `--skip-browser` (or would need another option `--skip-node`, lol).

Anyhow: seems I have a somewhat stronger opinion on this than I anticipated myself initially. 😜 Are there other voices on this? What do the others think?

**Comment by holgerd77** [comment]
(ah, and an additional thought: maybe we can also just combine both approaches and let the build script just pick up the CL parameter from the script invocation (so `test:node` e.g.) and then decide based on this value on what to do?)

**Comment by ryanio** [comment]
yeah sure i can go along with that, `npm run build` which calls `npm run build:node && npm run build:browser` seems very reasonable and doable.

**Comment by holgerd77** [comment]
Thanks 😊

**Comment by emersonmacro** [comment]
I can work on this

**Comment by holgerd77** [comment]
Ok, nice 😀
