### ISSUE TITLE
Latest release breaks signatures

### ISSUE THREAD

**Issue by JChanceHud** [ethereumjs/ethereumjs-monorepo#1340]
I'm encountering an error signing transactions after the latest release (3.3.0).

`Error: Expected message to be an Uint8Array`

This seems to be coming from [here](https://github.com/ethereumjs/ethereumjs-util/blob/master/src/signature.ts#L26). The secp256k1 library is wanting Uint8Arrays for both the message and key.

This error is bubbling through the web3.js function `web3.eth.accounts.signTransaction`.

**Comment by ryanio** [comment]
thanks for reporting, could you share the code you are using and the full error stack trace? that should help us further identify the issue.

**Comment by JChanceHud** [comment]
Hm, I've been trying to recreate but can't seem to. I may have been experiencing dependency hell in the project I'm working on.

Going to close this and reopen if I run into this issue again.

**Comment by holgerd77** [comment]
Ok, thanks for letting us know. 😄
