### ISSUE TITLE
Monorepo: Node 16 Tests failing

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1341]
The nightly Node tests are [failing](https://github.com/ethereumjs/ethereumjs-monorepo/runs/3024683130?check_suite_focus=true) for Node 16, this should be investigated and fixed.

**Comment by acolytec3** [comment]
The original issue was just network connectivity.  I re-ran the jobs and now it's that issue of not being able to resolve multihashes in the libp2p sub-dependencies again.

**Comment by holgerd77** [comment]
Ok, would be nice if we can fix this relatively soon.

**Comment by ryanio** [comment]
on it
