### ISSUE TITLE
Tx: Integrate Fake Transaction Support

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1343]
Along our latest tx releases, Hardhat broke twice and needed a hotfix, see https://github.com/nomiclabs/hardhat/pull/1641 and https://github.com/nomiclabs/hardhat/issues/1537. Both of these breakages were related to Hardhat's [FakeSenderTransaction](https://github.com/nomiclabs/hardhat/blob/6cc9411afbd5574a16d2354e3f15c79d9e67a115/packages/hardhat-core/src/internal/hardhat-network/provider/transactions/FakeSenderTransaction.ts) implementation, where a lot of the functionality of our tx implementation get's overwritten and things are high to break even on internal changes.

When looking at their implementation and reasoning in the comments it turns out that the provided functionality is highly generic, Hardhats definition of a Fake Transaction is:

```typescript
/**
 * This class represents a legacy transaction sent by a sender whose private
 * key we don't control.
 *
 * The transaction's signature is never validated, but assumed to be valid.
 *
 * The sender's private key is never recovered from the signature. Instead,
 * the sender's address is received as parameter.
 */
 ```

We should therefore consider to take this functionality into our main code base, I would very much assume this can be useful for various other use cases (also considering the fact that our own [suggestion](https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/tx#fake-transaction) in the documentation how to add such functionality seems very much not sufficient for the Hardhat use case (side note: at some point we also already had integrated such a simplified fake transaction in the code base which we decided to remove at some point, we didn't have the whole context back then though)).

From looking at the Hardhat code base I think we can also very much go along their implementation to a greater extend. The main structural difference will likely be that we very much not want to do this by inheritance since we would otherwise need to extend all tx type classes for having a consistent fake transaction support for all tx types. This is likely not what we want nor is it necessary.

The better option will likely be to expand our `TxOptions` dict with an appropriate parameter `fakeSender` or something, which then set's an internal state `isFake` (likely not the final name 😋 ) and then can act accordingly internally (so: doing similar things like Hardhat is doing in their implementation).

I have to admit that I also do not have the complete picture here (e.g. I am not yet completely getting the differentiation of this additional `sender` parameter and the `from` field in the tx itself). And this will generally need some additional thinking, it is not necessarily that all design decisions made in the HH implementation are the correct ones (I wonder e.g. if we can't just assume such a tx to be an already signed tx - in contrast to what HH is doing - and act accordingly?).

So this will likely be something which will rather evolve during 2-3 weeks (or more) and is not doable in some few hours. An implementation would also need somewhat sufficient code coverage.

And, some final note: I very much wonder about this whole "fake" terminology, I don't find this very much expressive (I actually learned today for the first time what this would actually mean after having dealt with the term for several years) and I would suggest that we give this some thought to find something which better describes the nature of such a tweaked tx object.

//cc @alcuadrado @fvictorio

**Comment by holgerd77** [comment]
(I think though that this is some kind of task where it - despite of the open design questions - might make sense to start implementing early on to get a better grasp of the problem, even if this will be followed by the need to partially rework things later on)

**Comment by holgerd77** [comment]
Would still value some feedback from @alcuadrado and/or @fvictorio here.

**Comment by alcuadrado** [comment]
I'm not sure the right approach would be to add native support for this. I'd rather have clean and stable`interface`s that we can implement, and have the vm and other packages take those instead of concrete implementations. 

The reason for this is that we can't be sure right now that we won't need other kinds of special transaction types. Now we have these:

(1) A tx with an arbitrary sender, whose signature is completely invalid and never validated nor used to retrieve the sender.
(2) A tx that's known to be valid, as we fetched it from a blockchain, but we don't have access to its common, because it can come from any EVM blockchain.

**Comment by holgerd77** [comment]
Some stronger scepticism on this suggestion, I will close for now. Feel free to reopen everyone if you stumble upon this and think there is/might be some generic need in the described direction.
