### ISSUE TITLE
Devp2p: BSC support

### ISSUE THREAD

**Issue by srgl** [ethereumjs/ethereumjs-monorepo#1349]
Assuming that istanbul is the latest known fork on bsc chain with hash 0xfc3ca6b7, eth65 protocol version unable to get peers because it sends Buffer(0x00) as the ForkNext field in status message. When sending empty buffer as the ForkNext field I am getting peers. Also it works when I use additional random data filled hardfork in common config (ForkNext is random number).

**Comment by ryanio** [comment]
Thanks for opening!

I remembered that @jochem-brouwer actually discovered this while testing our client with 1559 on Aleut and added this code [here](https://github.com/ethereumjs/ethereumjs-monorepo/pull/1148/files#diff-7fb2afed5136be13178c003c1ba9074350eb4cb4b950c338f1d381d56fb5bceeR220-R222) (on [master](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/devp2p/src/eth/index.ts#L221-L223)):

```typescript
const nextForkB = this._nextForkBlock.eqn(0)
        ? Buffer.from('', 'hex')
        : this._nextForkBlock.toArrayLike(Buffer)
```

Are you running an example or some code that isn't routing through there?

**Comment by srgl** [comment]
@ryanio  I am running slightly modified peer-communication.ts example.
The thing is this commit https://github.com/ethereumjs/ethereumjs-monorepo/commit/afd00a8bfee1b524352a0f6c79f3bcfe43debe4c
should fix the issue, but I don't see this code in devp2p npm package v4.0.0
Seems like https://www.npmjs.com/package/@ethereumjs/devp2p is outdated.

**Comment by ryanio** [comment]
@srgl ah so sorry about that, it has been some time since we did a devp2p release. I recently added les 3/4 and eth 66 support so I'll start a PR for the release and will be sure that fix is included on the changelog.

**Comment by srgl** [comment]
@ryanio It would be just amazing to see the fix and eth66 support soon, thanks!

**Comment by ryanio** [comment]
@srgl devp2p [v4.1.0](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Fdevp2p%404.1.0) is now released on npm 👍 thanks for your patience

**Comment by myuniswap2000** [comment]
Hello, two big brothers. May I ask you a question please?

1. On the BSC network, I can successfully use eth66 to communicate with peer and obtain TX

2. However, I can't communicate with peer (only eth65 is supported) using eth65.

3. Debug MSG is:
  'Add peer: 3.236.210.90:30311 Geth/v1.1.0-7dd68d07-20210803/linux-amd64/go1.16.3 (eth65) (total: 1)'
  DISCONNECT reason: USELESS_PEER 3.236.210.90:30311
  'Remove peer: 3.236.210.90:30311 - peer disconnect, reason: USELESS_PEER (3) (total: 0)'

4. My connection configuration common should be correct. Can successfully communicate with eth66 (BSC).
My common configuration is:
# config of @srgl 
My rlpx configuration is:
const rlpx = new devp2p.RLPx(PRIVATE_KEY, {
  dpt,
  maxPeers: 100,
  capabilities: [devp2p.ETH.eth66,devp2p.ETH.eth65,devp2p.ETH.eth64,devp2p.ETH.eth63],
  common,
  remoteClientIdFilter: REMOTE_CLIENTID_FILTER,
  listenPort: 30311,
  clientId: Buffer.from("Geth/v1.1.0-beta/linux-amd64/go1.16.5")
})

5, thank you very much! please help me. thank you .
