### ISSUE TITLE
Monorepo review: check for BN toArrayLike

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/ethereumjs-monorepo#1350]
BN's `toArrayLike(Buffer)` method usually works well and produces the expected and desired results. However, if the `BN` is `BN(0)`, then the output is `Buffer <0x00>` which is not desired. This has led, for instance, in a `devp2p` bug where, if we had a next fork block of `0` (no known future forks), devp2p would send the 0x00 Buffer over the wire, causing a peer disconnect.

We should scan the repo for `toArrayLike(Buffer)` and review if this could cause bugs in case that the BN is zero.

**Comment by holgerd77** [comment]
Am I correct that this is only relevant in an RLP context?

**Comment by ryanio** [comment]
@holgerd77 not really specific to RLP, this is more of a zero BN<>Buffer conversion issue.

in the OP case over the devp2p wire of zero (Buffer <00>) vs empty (Buffer <>)

**Comment by holgerd77** [comment]
Not relevant any more after transition to BigInt, will close.
