### ISSUE TITLE
Monorepo review: check for `if (0) { ... } else { ... }`  patterns.

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/ethereumjs-monorepo#1351]
Many times we have had bugs where, in the if statement, a `0` value is evaluated, and then the `else` clause is thus evaluated. In these bugs, we usually only check if some value exists (it is not `undefined`) and then evaluate the `if` block directly. However, in thus the cases that `0` is passed on (for instance a `yParity` value in EIP1559 txs), then the `else` clause would be evaluated, which is not what we want.

We should scan the monorepo for these patterns to see if this kind of bug could happen there. 

I'm not sure how to do this efficiently, since it is not efficient to check every if statement.

**Comment by holgerd77** [comment]
I guess looking at the already identified comparison patterns and then doing some selected substring searches like e.g. `.eqn(0)` should already do a good job and catch a lot of occurrences. The mentioned search e.g. got 14 results in the monorepo, there are likely 1-3 more approaches.

Maybe also to side-check if changes play well with the `BN` `isZero()` function (a search for `isZero()` on the code base gives 70 results). Not sure if this is a thing but just wanted to mention.

**Comment by ryanio** [comment]
relevant eslint rule we can consider adding to our global config: [strict-boolean-expressions](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/strict-boolean-expressions.md)

we would probably want to evaluate each option, like `allowNumber` is default `true` but in the OP example would be good to make it `false`:

```typescript
const defaultOptions: Options = {
  allowString: true,
  allowNumber: true,
  allowNullableObject: true,
  allowNullableBoolean: false,
  allowNullableString: false,
  allowNullableNumber: false,
  allowAny: false,
  allowRuleToRunWithoutStrictNullChecksIKnowWhatIAmDoing: false,
};
```

**Comment by holgerd77** [comment]
@ryanio this eslint rule is not yet in place, right?

**Comment by ryanio** [comment]
not yet, would be a great starting issue for someone since it's rather localized, although when the rule is added there might be some existing source lines to update. we also need to decide on the options for the rule above.

i have a small handful of new eslint rules i'd like to add to the monorepo so if I can get to it in a PR I will include this rule as part of it and link this issue, but until then it can be picked up by anyone else.
