### ISSUE TITLE
Release new version of `ethereumjs-util` under new namespace `@ethereumjs/util`

### ISSUE THREAD

**Issue by ryanio** [ethereumjs/ethereumjs-monorepo#1366]
This is a tracking issue to deprecate `ethereumjs-util` and release under the new namespace `@ethereumjs/util`.

As part of this, we should also rename all internal monorepo references to the new package name for consistency.

**Comment by holgerd77** [comment]
As much as I can understand this desire from a consistency perspective - this also hurts my eyes when seeing it 😋 - I honestly have to say: we shouldn't do this (yet).

As we have seen along this native-crypto-modules-removal work suggested and executed by @alcuadrado and others from Nomic Labs (see https://github.com/ethereum/js-team-organization/issues/18 as well as execution PRs like https://github.com/ethereumjs/ethereumjs-util/pull/261) the Util library has an extremely long update cycle with people sticking to old versions for years (some context here: Nomic Labs did the work and removed the native dependencies for the hashing (keccak) and signature (secp256k1) libraries for v4, v5 and v6 branches of the library. That was actually some heroic task dramatically improving the developer/installation experience for a vast amount of users).

With somewhat unnecessarily doing an update here we would loose another round of users which likely won't do the update for another 1-2 - maybe three years - just for the sake of a naming adjustment. And for eventual crypto (or other) related (emergency) bug fixes we have yet another major release cycle to care for. I would say that this price is very much too high for the win.

I would therefore suggest to close here. We can pick this up again (without the need for having an issue open until then) once we really have incentives to do breaking changes on the Util library.

**Comment by ryanio** [comment]
ok, that makes sense to me, thanks for the explanation!
