### ISSUE TITLE
Invalid sender 

### ISSUE THREAD

**Issue by ssirapidinnovation** [ethereumjs/ethereumjs-monorepo#1392]
Getting invalid sender when using FeeMarketEIP1559Transaction

**Comment by acolytec3** [comment]
Can you share your code that is causing this error so we can research further?

**Comment by ssirapidinnovation** [comment]
Yes sure

here is the sample code 
// eslint-disable-next-line @typescript-eslint/no-var-requires
const Web3 = require('web3')
const web3 = new Web3(new Web3.providers.HttpProvider('REPLACE WITH INFURA PROVIDER')
import { FeeMarketEIP1559Transaction } from '@ethereumjs/tx'
const privateKey = Buffer.from('REPLACE WITH PRIVATE KEY', 'hex')
import Common from '@ethereumjs/common'
const common = new Common({ chain: 'ropsten', hardfork: 'london' })

    const facetCutCall = new web3.eth.Contract(
        [
          {
            inputs: [
              {
                internalType: 'address',
                name: '',
                type: 'address',
              },
              {
                internalType: 'uint256',
                name: '',
                type: 'uint256',
              },
            ],
            name: 'approve',
            outputs: [
              {
                internalType: 'bool',
                name: '',
                type: 'bool',
              },
            ],
            stateMutability: 'nonpayable',
            type: 'function',
          },
        ],
        '0xfe724a829fdf12f7012365db98730eee33742ea2'
      )
      const functCall = await facetCutCall.methods.approve('0xfe724a829fdf12f7012365db98730eee33742ea2', 100000000).encodeABI()
      const count = await web3.eth.getTransactionCount('0xB6e3974F93B9e5790Ae0a3f4Aea00c83bdD26bfc')
      const txData = {
        nonce: web3.utils.toHex(count),
        gasLimit: web3.utils.toHex(3000000),
        to: '0xfe724a829fdf12f7012365db98730eee33742ea2',
        from: '0xB6e3974F93B9e5790Ae0a3f4Aea00c83bdD26bfc',
        input: functCall,
        maxFeePerGas: '0xb2d05e00',
        maxPriorityFeePerGas: '0xb2d05e00',
        value: 0,
        accessList: [],
        chainId: '0x3',
      }
      const transaction = FeeMarketEIP1559Transaction.fromTxData(txData, { common })
      transaction.sign(privateKey)
      const serialisedTransaction = transaction.serialize().toString('hex')

      const receipt = await web3.eth.sendSignedTransaction('0x' + serialisedTransaction)

**Comment by acolytec3** [comment]
I believe your issue is here
```
transaction.sign(privateKey)
const serialisedTransaction = transaction.serialize().toString('hex')
```
This should be
```
const signedTransaction = transaction.sign(privateKey)
const serialisedTransaction = signedTransaction.serialize().toString('hex')
```
since `transaction.sign()` returns a new transaction object representing the signed transaction.
