### ISSUE TITLE
devp2p ，Does it support BSC networks?

### ISSUE THREAD

**Issue by myuniswap2000** [ethereumjs/ethereumjs-monorepo#1394]
hello, amin, everyone!
1,devp2p ，Does it support BSC networks?
2, I run /packages/devp2p/examples/peer-communication.ts:
node -r ts-node/register ./examples/peer-communication.ts:
but, it is  error:
Peer error1 (18.176.58.248:30311): Genesis block mismatch: d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3 / 0d21840abff46b96c84b2ac9e10e4f5cdaeb5693cb665db62a2f3b02d2d57b5b
Remove peer: 18.176.58.248:30311 - peer disconnect, reason: SUBPROTOCOL_ERROR (16) (total: 1)
3,i add bsc conf is : import bsc.json
const common = new Common({ chain: bsc });

4, thank you !!

**Comment by myuniswap2000** [comment]
my version   is @ethereumjs/devp2p@4.1.0 , thank you .

**Comment by myuniswap2000** [comment]
other error is:
[

Peer error1 (135.125.219.7:30303): NetworkId mismatch: 38 / d74c
Remove peer: 135.125.219.7:30303 - peer disconnect, reason: SUBPROTOCOL_ERROR (16) (total: 1)

]


>

**Comment by myuniswap2000** [comment]
2, other error:
Peer error1 (35.73.137.11:30311): Genesis block mismatch: d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3 / 0d21840abff46b96c84b2ac9e10e4f5cdaeb5693cb665db62a2f3b02d2d57b5b

**Comment by myuniswap2000** [comment]
3, other info:
Remove peer: 35.73.137.11:30311 - peer disconnect, reason: SUBPROTOCOL_ERROR (16) (total: 0)
Total nodes in DPT: 1, open slots: 25, queue: 0 / 0
Add peer: 167.99.162.43:30305 Geth/v1.5.0-EthoProtocol--Atlas/linux-amd64/go1.14.15 (eth66) (total: 1)
Remove peer: 167.99.162.43:30305 - peer disconnect, reason: SUBPROTOCOL_ERROR (16) (total: 0)
Add peer: 52.231.165.108:30303 Geth/v1.10.4-unstable-017cf71f-20210525/linux-amd64/go1.16.4 (eth66) (total: 1)
DPT error: Error: Peer is banned
DPT error: Error: Peer is banned
DPT error: Error: Peer is banned
Peer error1 (52.231.165.108:30303): NetworkId mismatch: 38 / 01

**Comment by acolytec3** [comment]
I know @srgl was able to get it working (see comments in [this issue](https://github.com/ethereumjs/ethereumjs-monorepo/issues/1349).  We don't actively support BSC but it looks like it should work based on this previous issue.  @srgl, any chance you could share the `common` configuration you used to get BSC working?

**Comment by srgl** [comment]
I am using the following common object:
```
new Common({
    "chain": {
      "name": "mainnet",
      "chainId": 56,
      "networkId": 56,
      "defaultHardfork": "istanbul",
      "consensus": {
        "type": "pow",
        "algorithm": "ethash",
        "ethash": {}
      },
      "comment": "The Ethereum main chain",
      "url": "https://ethstats.net/",
      "genesis": {
        "hash": "0x0d21840abff46b96c84b2ac9e10e4f5cdaeb5693cb665db62a2f3b02d2d57b5b",
        "timestamp": null,
        "gasLimit": 40000000,
        "difficulty": 1,
        "nonce": "0x0000000000000000",
        "extraData": "0x11bbe8db4e347b4e8c937c1c8370e4b5ed33adb3db69cbdb7a38e1e50b1b82fa",
        "stateRoot": "0xd7f8974fb5ac78d9ac099b9ad5018bedc2ce0a72dad1827a1709da30580f0544"
      },
      "hardforks": [
        {
          "name": "chainstart",
          "block": 0,
          "forkHash": "0xfc64ec04"
        },
        {
          "name": "homestead",
          "block": 1150000,
          "forkHash": "0x97c2c34c"
        },
        {
          "name": "dao",
          "block": 1920000,
          "forkHash": "0x91d1f948"
        },
        {
          "name": "tangerineWhistle",
          "block": 2463000,
          "forkHash": "0x7a64da13"
        },
        {
          "name": "spuriousDragon",
          "block": 2675000,
          "forkHash": "0x3edd5b10"
        },
        {
          "name": "byzantium",
          "block": 4370000,
          "forkHash": "0xa00bc324"
        },
        {
          "name": "constantinople",
          "block": 7280000,
          "forkHash": "0x668db0af"
        },
        {
          "name": "petersburg",
          "block": 7280000,
          "forkHash": "0x668db0af"
        },
        {
          "name": "istanbul",
          "block": 9069000,
          "forkHash": "0xfc3ca6b7"
        }
      ],
      "bootstrapNodes": [
        {
          "ip": "52.71.43.172",
          "port": 30311,
          "id": "1cc4534b14cfe351ab740a1418ab944a234ca2f702915eadb7e558a02010cb7c5a8c295a3b56bcefa7701c07752acd5539cb13df2aab8ae2d98934d712611443",
          "location": "ap-southeast-1-001",
          "comment": "bootnode-aws-ap-southeast-1-001"
        },
        {
          "ip": "34.246.65.14",
          "port": 30311,
          "id": "28b1d16562dac280dacaaf45d54516b85bc6c994252a9825c5cc4e080d3e53446d05f63ba495ea7d44d6c316b54cd92b245c5c328c37da24605c4a93a0d099c4",
          "location": "us-east-1-001",
          "comment": "bootnode-aws-us-east-1-001"
        },
        {
          "ip": "35.73.137.11",
          "port": 30311,
          "id": "5a7b996048d1b0a07683a949662c87c09b55247ce774aeee10bb886892e586e3c604564393292e38ef43c023ee9981e1f8b335766ec4f0f256e57f8640b079d5",
          "location": "eu-west-1-001",
          "comment": "bootnode-aws-eu-west-1-001"
        }
      ],
      "dnsNetworks": [
        "enrtree://AKA3AM6LPBYEUDMVNU3BSVQJ5AD45Y7YPOHJLEF6W26QOE4VTUDPE@all.mainnet.ethdisco.net"
      ]
    }
  }
```
Also replace checkblock parameters in peer-communication.ts according to bsc chain.

**Comment by myuniswap2000** [comment]
thank you

**Comment by myuniswap2000** [comment]
> I know @srgl was able to get it working (see comments in [this issue](https://github.com/ethereumjs/ethereumjs-monorepo/issues/1349). We don't actively support BSC but it looks like it should work based on this previous issue. @srgl, any chance you could share the `common` configuration you used to get BSC working?


>> hi，@ thank you for hlep me!
(1)i conf is like @srgl .
(2)but, run peer-communication.ts:
i have many erro is : 
DPT error: Error: Peer is banned
DPT error: Error: Peer is banned
(3)and have not receive TX!
please help me!

**Comment by myuniswap2000** [comment]
hi，@srgl  thank you for hlep me!
(1)i conf is like above.
(2)but, run peer-communication.ts:
i have many erro is :
DPT error: Error: Peer is banned
DPT error: Error: Peer is banned
(3)and have not receive TX!
please help me!

**Comment by srgl** [comment]
You can ignore peer ban errors. What TX are you trying to receive?

**Comment by myuniswap2000** [comment]
in addition, 
Do I need to configure  "genesisStates" ?

**Comment by myuniswap2000** [comment]
I need to receive new block and tx

**Comment by myuniswap2000** [comment]
i have not  find checkblock param ...

**Comment by srgl** [comment]
You need to correct these lines according to the bsc:
https://github.com/ethereumjs/ethereumjs-monorepo/blob/3a989d0d9d59dca1113759c8babd1d1fb55c6f8e/packages/devp2p/examples/peer-communication.ts#L36-L44

**Comment by myuniswap2000** [comment]
> CHECK_BLOCK

Do you have a specific code? Please help me, thank you!

I don't know where to find the corresponding information.

**Comment by srgl** [comment]
Sorry, I do not have a code, but you can use any block number/hash from the chain.

**Comment by myuniswap2000** [comment]
> Sorry, I do not have a code, but you can use any block number/hash from the chain.
1,
ok, thank you very much! 
2,
Has the data message of BSC changed? Do you have relevant information about the code I want to modify? I'm not proficient in geth. thank you

**Comment by myuniswap2000** [comment]
I succeeded. I got TX. Thank you very much for your help. I wish you have a nice day!
💯  🥇 👍

**Comment by bpbogdanpop** [comment]
@srgl @myuniswap2000 I'm still not sure what should I use for CHECK_BLOCK_HEADER? I already took the number and hash of a block from BSC. But where do I get that CHECK_BLOCK_HEADER Buffer hex string from?

**Comment by ryanio** [comment]
> I'm still not sure what should I use for CHECK_BLOCK_HEADER? I already took the number and hash of a block from BSC. But where do I get that CHECK_BLOCK_HEADER Buffer hex string from?

@bpbogdanpop That is the block RLP for the Berlin hardfork block (as an example). If you want to replace it with another block, you can request it from the peer and console.log their payload output (with `toString('hex')` on the buffer to get a nice copy and paste value), and replace it.
