### ISSUE TITLE
Blockchain: getTotalDifficulty -> Merge Context / Functionality / Testing

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1413]
I was thinking about how [getTotalDifficulty()](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/blockchain/src/index.ts#L1050) should behave in the Merge respectively in a Proof-of-Stake context and wanted to test this in the newly added [PoS tests](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/blockchain/src/index.ts#L1050).

Along testing I realized that this method is very much under-developed and also substantially under-tested. 

I added the following line under the `putBlock()` call in the PoS tests (tried both the "hash only" and "hash + number" versions):

```javascript
await blockchain.putBlock(block)
await blockchain.getTotalDifficulty(block.hash(), block.header.number)
```

1. Both resulted in directly throwing on the first block. This should be investigated.
2. There is just *one* single generic test on this function in `index.spec.ts` and only running once on a genesis block, this should be substantially expanded (testing for a further-down-the-road block, testing with and without the number option)
3. I find the overall API of this function strage, so to always reqest by block hash, since I guess the very most (only?) use case for the function will likely be to get the total difficulty "for the chain" so related to the canoncical head (that's how we use this in the client in `chain.ts` for example also ourselves). So I guess we should at least make this first `hash` parameter optional and then return the TD for the chain? Everything else seems strange and counter-intuitive to me.

In the Merge context I was wondering what to do. I was first thinking about returning the total difficulty from the last PoW block but this might be a bit overengineered and is also not possible in a pure PoS environment. So my current thinking is to just throw when called on a PoS block.

**Comment by gabrocheleau** [comment]
Not sure about throwing when `getTotalDifficulty()` is called on a PoS block. In my view, `getTotalDifficulty` should return the "total difficulty accrued by the blockchain", which would be, for PoS blocks, equal to the `totalDifficulty` of the last `PoW block`. 

My feeling is that the totalDifficulty of a PoS block should be equal to its parent block. This has the following advantages: 

- Consistent with PoS block `difficulty === 0`.
- Compatible with the **Terminal PoW block** rule: `block.total_difficulty >= TERMINAL_TOTAL_DIFFICULTY` *and* `block.parent_block.total_difficulty < TERMINAL_TOTAL_DIFFICULTY`.  
- Enables checking that we're on PoS with `getTotalDifficulty` (not sure if that's useful though).
