### ISSUE TITLE
Wrong getSenderAddress() when getting v, r, s from Ledger HW 

### ISSUE THREAD

**Issue by goldlamp95** [ethereumjs/ethereumjs-monorepo#1417]
Hi. I need help understanding why `signedRawTx.getSenderAddress` returns a different address than what Ledger HW uses for signing.

My issue is very similar to the one posted here: #706 
I think there's an issue when I try to instantiate the transaction using one of the modules from 'ethereumjs/tx' 

```
import { getAppEth, getWeb3 } from '@/instances';
import Common from '@ethereumjs/common';
import { FeeMarketEIP1559Transaction } from '@ethereumjs/tx';
import * as ethers from 'ethers';

const common = new Common({ chain: 'ropsten', hardfork: 'london' });
const sendSignTx = async (scaledAmount: string, senderAddress: string, contractAddress: string, encodedActionAbi: any, gasPrice: number) => {
  const web3 = getWeb3();
  const txCount = await web3.eth.getTransactionCount(senderAddress);
  const txObject = {
    chainId: 3,
    nonce: web3.utils.toHex(txCount + 1),
    maxPriorityFeePerGas: web3.utils.toHex(3000000000),
    maxFeePerGas: web3.utils.toHex(3000000000),
    gasLimit: web3.utils.toHex(300000),
    to: contractAddress,
    value: scaledAmount,
    data: encodedActionAbi,
    accessList: [],
  };
  // appEth is an app instance of @ledgerhq/hw-app-eth
  const appEth = getAppEth();

  const path = `44'/60'/0'/0/0`;

  const rawTx = FeeMarketEIP1559Transaction.fromTxData(txObject, { common });
  const rawTxHex = rawTx.serialize().toString('hex');

  const VRS = await appEth.signTransaction(path, rawTxHex);

  txObject.r = Buffer.from(VRS.r, 'hex');
  txObject.s = Buffer.from(VRS.s, 'hex');
  txObject.v = Buffer.from(VRS.v, 'hex');

  const signedRawTx = FeeMarketEIP1559Transaction.fromTxData(txObject, { common });

  // here, 'senders' gives me a different address than the one I use in Ledger
  const senders = signedRawTx.getSenderAddress().toString('hex');

  const serializedSignedTx = signedRawTx.serialize().toString('hex');

  const serializedData = Buffer.from(serializedSignedTx, 'hex').slice(1, serializedSignedTx.length);

  return web3.eth.sendSignedTransaction(`0x${serializedSignedTx}`);
};

export default sendSignTx;

```
I'm out of ideas and I would be grateful for any input!! Thank you.

**Comment by ryanio** [comment]
From the issue you linked:

> The problem was that he wasn't setting the right v value, and was using EIP115.

Could you verify that `appEth.signTransaction(path, rawTxHex)` is signing using the correct chainId?

**Comment by goldlamp95** [comment]
> From the issue you linked:
> 
> 
> 
> > The problem was that he wasn't setting the right v value, and was using EIP115.
> 
> 
> 
> Could you verify that `appEth.signTransaction(path, rawTxHex)` is signing using the correct chainId?

Yeah. Im working on the ropsten network so the chainId should be set to 3?

**Comment by ryanio** [comment]
> Yeah. Im working on the ropsten network so the chainId should be set to 3?

yeah that would be correct

Can you try `const rawTxHex = rawTx.getMessageToSign(false).toString('hex')`

**Comment by goldlamp95** [comment]
> > Yeah. Im working on the ropsten network so the chainId should be set to 3?
> 
> yeah that would be correct
> 
> Can you try `const rawTxHex = rawTx.getMessageToSign(false).toString('hex')`

Hey thanks I think I managed to solve the wrong sender address issue by referencing issue #1278 .
Now, I have another problem where the transaction is not being broadcasted, even when I have the transaction hash. 
I'll open another issue for this problem. 
Thanks.
