### ISSUE TITLE
Client: Connection to sync peer gets lost quickly

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1421]
Just observed when trying to reproduce on #1416 that the sync connection to a peer is lost pretty quickly (within 1-2 minutes I would say). Sync is then rebooted and continued, soon after rebooting and reconnecting the connection is lost again and so on.

I tested syncing with `goerli`: `DEBUG=devp2p:* npm run client:start -- --loglevel=debug --network=goerli`

What I noticed: immediately before the disconnection we are sending another `PING` method to the already connected peer. I could capture this in the following screenshot:

![grafik](https://user-images.githubusercontent.com/931137/130621212-b71f1e3e-7ac9-4b09-8254-bee47c812a51.png)

So here we are already connected to this peer with the IP `145.239.255.212` and sync is processing. Then we are sending another `PING` and we disconnect afterwards with a `USELESS_PEER` disconnect reason.

Two possible explanations here (I can think of on first thought):

1. These `PING` re-sending is part of normal protocol behavior, might be requested to re-send a `PING` after some amount of time to reassure the connection is still active (for now I would assume this is rather not the case from my rough protocol knowledge, but might also be taken into consideration as a possibility). Might be that we then not analyze properly the message flow and inappropriately disconnect.
2. We re-stumble upon this peer because it is again send to us by peer discovery. We likely do not check here if we already have an ongoing connection with such peer, then try to reconnect which interferes with the already ongoing sync process with named peer.

I would assume 2. is rather the more likely possibility. Nevertheless wrote down both cause I am not 100% sure.

We should analyze this (with some priority), the current behavior is not really sustainable for a robust sync process.

**Comment by acolytec3** [comment]
As another example of this, I have seen this occur where I had a `geth` instance running on rinkeby and then had our client syncing from it as a bootnode and got the same sort of results:
```
devp2p:rlpx:peer Received header 127.0.0.1:30303 +8ms
  devp2p:rlpx:peer Received body 127.0.0.1:30303 169b011cf89933f896c2c0c0fe0300fe03004a0300 +0ms
  devp2p:rlpx:peer Received undefined (message code: 22 - 16 = 6) 127.0.0.1:30303 +0ms
  devp2p:eth Received BLOCK_BODIES message from 127.0.0.1:30303: f89933f896c2c0c0c2c0c0c2c0c0c2c0c0c2c0c0c2c0c0c2c0c0c2c0c0c2... +0ms
  devp2p:eth Send GET_BLOCK_HEADERS message to 127.0.0.1:30303: c834c6820ea7328080 +10ms
  devp2p:rlpx:peer Received header 127.0.0.1:30303 +43ms
  devp2p:rlpx:peer Received body 127.0.0.1:30303 14cdeb01f04ff975ca34f975c6f90258a0baa5e258ec62d0ee0131aba187... +0ms
  devp2p:rlpx:peer Received undefined (message code: 20 - 16 = 4) 127.0.0.1:30303 +0ms
  devp2p:eth Received BLOCK_HEADERS message from 127.0.0.1:30303: f975ca34f975c6f90258a0baa5e258ec62d0ee0131aba18798cdd706b8bd... +1ms
  devp2p:eth Send GET_BLOCK_BODIES message to 127.0.0.1:30303: f9067635f90672a09f20f75433ba02f4fdf11f66124253ea0c6c8f9a493f... +7ms
  devp2p:rlpx:peer Received header 127.0.0.1:30303 +4ms
  devp2p:rlpx:peer Received body 127.0.0.1:30303 169b011cf89935f896c2c0c0fe0300fe03004a0300 +1ms
  devp2p:rlpx:peer Received undefined (message code: 22 - 16 = 6) 127.0.0.1:30303 +0ms
  devp2p:eth Received BLOCK_BODIES message from 127.0.0.1:30303: f89935f896c2c0c0c2c0c0c2c0c0c2c0c0c2c0c0c2c0c0c2c0c0c2c0c0c2... +0ms
  devp2p:eth Send GET_BLOCK_HEADERS message to 127.0.0.1:30303: c836c6820ed9328080 +13ms
  devp2p:rlpx:peer Received header 127.0.0.1:30303 +11ms
  devp2p:rlpx:peer Received body 127.0.0.1:30303 14cdeb01f04ff975ca36f975c6f90258a05999a7566bb1b2ac6fbbe47afa... +0ms
  devp2p:rlpx:peer Received undefined (message code: 20 - 16 = 4) 127.0.0.1:30303 +0ms
  devp2p:eth Received BLOCK_HEADERS message from 127.0.0.1:30303: f975ca36f975c6f90258a05999a7566bb1b2ac6fbbe47afa3ee38c9b8e21... +1ms
  devp2p:eth Send GET_BLOCK_BODIES message to 127.0.0.1:30303: f9067637f90672a0b632b7b2f046ff6bb095234f91d78e866bb23cd199e8... +11ms
  devp2p:rlpx:peer Received header 127.0.0.1:30303 +9ms
  devp2p:rlpx:peer Received body 127.0.0.1:30303 010204c103 +1ms
  devp2p:rlpx:peer Received DISCONNECT (message code: 1 - 0 = 1) 127.0.0.1:30303 +0ms
  devp2p:rlpx:peer DISCONNECT reason: USELESS_PEER 127.0.0.1:30303 +0ms
  devp2p:rlpx 127.0.0.1:30303 disconnect, reason: USELESS_PEER +4ms
  devp2p:rlpx Restart connection refill .. with selector 0 peers: 0, queue size: 0, open slots: 25 +3s
```
In this instance, I was using rinkeby as custom parameters so our client didn't know about any other peers.  As such, I wonder if it's truly a peer discovery issue.  I see several responses with `undefined` messages after a body is received.

**Comment by ryanio** [comment]
@acolytec3 could you try running that again but with geth in verbose debug logging to see if it shares any hints prior to sending the disconnect? I searched for `DiscUselessPeer` in the geth codebase and there are a few places where it could be triggered, and some of the reasons have debug logging along with it that could hopefully give some insight.

**Comment by acolytec3** [comment]
@ryanio Here's two snippets from the geth logs that maybe help us?
```
TRACE[08-24|15:02:19.141|p2p/dial.go:246]                        Discarding dial candidate                id=42ff189b0396dc48 ip=192.168.0.194   reason="node does not provide TCP port"
```
Here, our client didn't provide a TCP port.  Not sure if this is is somehow due to it running locally or something else (maybe an ENR issue?)

And then these two.  The port number looks wrong (not sure why it's showing 55398 as my ethereumjs client was running on 30305 but the id `42ff189b0396dc48` corresponds to other logs that match the ethereumjs client.
```
WARN [08-24|15:02:28.738|eth/handler.go:321]                     Checkpoint challenge timed out, dropping id=42ff189b0396dc48 conn=inbound addr=192.168.0.194:55398   type=ethereumjs-devp2p/v4...
DEBUG[08-24|15:02:28.738|eth/protocols/eth/handler.go:162]       Message handling failed in `eth`         id=42ff189b0396dc48 conn=inbound err=EOF
```

**Comment by ryanio** [comment]
Ahh I was wondering if it could be that "checkpoint challenge timed out" when looking at the source since it throws useless peer, so it could be that, we can trace why the challenge isn't being returned timely.

Not sure if the tcp port could also be affecting it, but worth investigating.

**Comment by holgerd77** [comment]
Did some research on this ping interval here. So we have this in the code [here](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/devp2p/src/rlpx/peer.ts#L20), go-ethereum has the same thing [here](https://github.com/ethereum/go-ethereum/blob/836c647bdd65896c0e5bef97466d5d514db419e7/p2p/peer.go#L48), so this really seems protocol-intended that this is resend every 15 seconds.

(I first thought that the issue might be pretty much mitigated by delaying this interval if a new message has been received. But a) it really seems to be intended that this is sent independently (if I read the geth code directly, couldn't find any spec reference on this) and b) this actually *wouldn't* mitigate the issue, I tested setting this up to 60s and the disconnect also happened if there is only a `PING` from the other side.

That's - also as some side note - one realization I had: this PING - PING - PONG message exchange from the screenshot above is actually the result from *two* message flows, since both clients are sending their reassurance PING messages roughly at the same time.

Tried to further dig into the go-ethereum source code to see what actually triggers this DISCONNECT (I'm 95% sure that this happens on retrieval of our PONG message response to the PING from the peer), but wasn't successful on this yet.

**Comment by holgerd77** [comment]
(several edits, please read on site)

**Comment by holgerd77** [comment]
@acolytec3 will "answer" to this `undefined` question by directly doing a small separate improvement PR to improve the situation, this code part (in `rlpx/peer.ts`) is actually as close to black magic as one can get with people (including myself) having stumbled upon this several times.
