### ISSUE TITLE
Devp2p: DPT discovers nodes even if open slots = 0 and eats up memory

### ISSUE THREAD

**Issue by andkom** [ethereumjs/ethereumjs-monorepo#1429]
```
Total nodes in DPT: 139, open slots: 0, queue: 3758 / 3757
```

How to stop DPT from node discovering when there are no open slots?
`_peersQueue` is constantly growing and eating up all memory

**Comment by holgerd77** [comment]
Still relevant and might be a good issue if someone wants to dig a bit into the `devp2p` code. While touching core logic this is very local and not getting too deep into specific networking mechanisms.

**Comment by holgerd77** [comment]
Closed by #1816
