### ISSUE TITLE
Monorepo, VM: API browser tests failing on `master` (nightly CI run)

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1448]
VM API browser tests are currently failing on `master` along the [nightly CI run](https://github.com/ethereumjs/ethereumjs-monorepo/runs/3490843724?check_suite_focus=true). Here is an extract of the log:

```shell
Run npm run test:API:browser

> @ethereumjs/vm@5.5.2 test:API:browser
> karma start karma.conf.js

02 09 2021 01:09:00.706:INFO [compiler.karma-typescript]: Compiling project using Typescript 4.4.2
Error: 02 09 2021 01:09:06.462:ERROR [compiler.karma-typescript]: src/evm/evm.ts(261,11): error TS2322: Type 'unknown' is not assignable to type 'VmError | undefined'.
  Type 'unknown' is not assignable to type 'VmError'.

Error: 02 09 2021 01:09:06.464:ERROR [compiler.karma-typescript]: src/evm/evm.ts(361,11): error TS2322: Type 'unknown' is not assignable to type 'VmError | undefined'.
  Type 'unknown' is not assignable to type 'VmError'.

Error: 02 09 2021 01:09:06.465:ERROR [compiler.karma-typescript]: src/evm/interpreter.ts(116,30): error TS2571: Object is of type 'unknown'.

Error: 02 09 2021 01:09:06.466:ERROR [compiler.karma-typescript]: src/evm/interpreter.ts(116,35): error TS2571: Object is of type 'unknown'.

Error: 02 09 2021 01:09:06.467:ERROR [compiler.karma-typescript]: src/evm/interpreter.ts(120,13): error TS2571: Object is of type 'unknown'.
```

At the same time PR CI runs still pass, so it seems likely (?) that something is rather wrong with the CI setup in [vm-nightly-test.yml](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/.github/workflows/vm-nightly-test.yml), this would need some investigation and further analysis though.

Overall this should be fixed relatively soon so that nightly tests will pass again and we are not risking that other bugs remain hidden.

**Comment by ryanio** [comment]
I'll look into this today. I also noticed it says:

> Compiling project using Typescript 4.4.2

So I'll add some config to ensure that it's using the same typescript version that our monorepo packages are using, that's my first hunch 👍
