### ISSUE TITLE
devp2p: Add superclass to ETH and LES protocol implementations

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1450]
There is actually a lot of redundancy between the ETH and LES protocol implementation. This should be combined into a superclass sitting between e.g. `ETH` and `EventEmitter` at some point. This will likely lead to a substantially cleaner implementation of the subclasses, increase readability as well as ease adding new features and avoid introducing consistency gaps along the way.

(this new superclass should likely be not exposed in any way to the users, on a first run it would likely also be good to keep the API unchanged and eventually rather wrap calls if a method signature is rather realized in a more optimal way in the superclass)

Also totally possible to start with a subset of superclass integrations and then expand along the way "on occasion".

This is a good first issue for getting a bit more familiar with the `devp2p` library.

**Comment by Ghorbanian** [comment]
@emersonmacro Are you actively working on this ticket?

**Comment by holgerd77** [comment]
Hi @Ghorbanian, nice! 🙂 I am not sure if I can follow your interpretation of things (why should there be multiple ETH integrations?), so I will be just rephrasing what I meant:

So, first: APIs shouldn't change along this refactor at all. This is solely to reduce code redundancy.

The new superclass shouldn't be exposed in any way. With `Also totally possible to start with a subset of superclass integrations and then expand along the way "on occasion".` I mean the following. There are various possible changes for the superclass, e.g.:

1. Moving the `_version` property to the superclass
2. Moving the `_peer` property to the superclass
3. ...

The comment simply means that it is also possible to e.g. only do 1. and leave 2. for now.

If you start on this: I guess it's really important here to very much do this step-by-step and only do *one* refactor step per commit to not introduce bugs along the way. So for the above this would be two commits "devp2p -> ETH/LES refactor: move _version to superclass, unify constructor instantiation", "devp2p -> ETH/LES refactor: move _peer to superclass, unify constructor instantiation". Or actually for these two things, also ok to do on one step. But generally don't do too much at once but split things up. Also really important to let the tests run quite regularly.

**Comment by Ghorbanian** [comment]
@holgerd77 @ryanio Please refer to the following for the first iteration of the refactor and provide feedback. I am planning on keeping all debug related code inside the child classes, for now. 
![ethereumjs_devp2p_eth_les_refactor](https://user-images.githubusercontent.com/24584383/145053046-79e9b7c0-8da9-44d7-a0e3-ec501a8a6461.jpg)

**Comment by holgerd77** [comment]
Oh, that's nice. 🙂 👍

**Comment by ryanio** [comment]
@Ghorbanian really nice, love that you started with a diagram!

i would think you could normalize some of the debugging logic to the base class and prefix it with e.g. an overridden `_name` (`ETH` or `LES`), but maybe it will be more clear if it is possible after seeing some code and I can help.
