### ISSUE TITLE
Client spams peers with `GET_BLOCK_HEADER` requests

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ethereumjs-monorepo#1454]
Often times when I'm syncing the client to one or more peers with `DEBUG=devp2p:*` enabled, I see scenarios like this.

![image](https://user-images.githubusercontent.com/17355484/132042966-f85e72ea-6e20-42cb-b00f-cdecedb19e2a.png)

I haven't seen a consistent pattern but we should determine whether or not the client is actually sending tons of requests to peers, and if so, what causes it.

**Comment by holgerd77** [comment]
I would assume this has been fixed and will therefore close for now. Feel free to re-open if the issue still persists.
