### ISSUE TITLE
Invalid sender when using FeeMarketEIP1559Transaction

### ISSUE THREAD

**Issue by rkyshz** [ethereumjs/ethereumjs-monorepo#1459]
Getting **Returned error: invalid sender** when using the new **FeeMarketEIP1559Transaction**
Same thing works if I use web3 js directly to send the transaction

```
 "@ethereumjs/common": "^2.4.0",
 "@ethereumjs/tx": "^3.3.0",
  "web3": "^1.5.2"
```

```
const {FeeMarketEIP1559Transaction: EthereumTx} = require("@ethereumjs/tx");
const Common = require("@ethereumjs/common").default;
const Chain=require('@ethereumjs/common').Chain;
const Hardfork=require('@ethereumjs/common').Hardfork;
let details = {
            "to": toAddress,
            "value": web3.utils.toHex(amount.toString()),
            "gas": web3.utils.toHex(21000),
            "nonce": nonce,
            "maxPriorityFeePerGas": web3.utils.toHex(gasPrice),
            "maxFeePerGas": web3.utils.toHex(gasPrice)
          };
const chainData = new Common({chain: Chain.Ropsten,hardfork: Hardfork.London})
const transaction = EthereumTx.fromTxData(details, {common:chainData});
let privateKey = data.privateKey.split('0x');
let privKey = Buffer.from(privateKey[1], 'hex');
transaction.sign(privKey);
const serializedTransaction = transaction.serialize();
web3.eth.sendSignedTransaction('0x' + serializedTransaction.toString('hex'), (err, id) =>{
//handle error/response
});

```

Working web3 without ethereumjs
```
       let details = {
            "to": toAddress,
            "value": web3.utils.toHex(amount.toString()),
            "gas": web3.utils.toHex(21000),
            "nonce": nonce,
            "maxPriorityFeePerGas": web3.utils.toHex(gasPrice),
            "maxFeePerGas": web3.utils.toHex(gasPrice),
            "type": "0x02",
            "chainId": 3,
            "chain":`ropsten`,
            "hardfork": `london`
        };
const transaction = await web3.eth.accounts.signTransaction(details,data.privateKey);
web3.eth.sendSignedTransaction(transaction.rawTransaction, (err, id) =>{
//handle error/response
});
```

**Comment by acolytec3** [comment]
I believe the issue is here.
>`transaction.sign(privKey)`

`sign` returns a new transaction object so you need to store like
`const signedTransaction = transaction.sign(privKey)`
and then use `signedTransaction` in the following steps.

**Comment by rkyshz** [comment]
Tried that. It still doesn't work.
PS: I have similar code which works for non EIP-1559 so that's not the error.

**Comment by rkyshz** [comment]
> Tried that. It still doesn't work.
> PS: I have similar code which works for non EIP-1559 so that's not the error.

Update: It worked. Had to change 2 things.
1) Store the signed txn and use the returned obj to serialize as mentioned by @acolytec3 
2) change ```gas``` to ```gasLimit```

Some clarifications required.
Was the ```transaction.sign(privKey)``` mutating the original transaction in the older versions? Cos it seems to still work for me in the  2.1.2 version.

**Comment by holgerd77** [comment]
> Was the transaction.sign(privKey) mutating the original transaction in the older versions?

Yes, the new behavior was introduced in the v3 tx library update for security reasons.
