### ISSUE TITLE
Unable to NPM install after cloning this repo.

### ISSUE THREAD

**Issue by nots29vv** [ethereumjs/ethereumjs-monorepo#1460]
Please help, my aim is to use this repo to learn how the blockchain actually works . 
Steps I have taken:
I cloned this repository but I am unable to npm install, I get this error:
> root@1.0.0 preinstall C:\Users\LENOVO\Desktop\Library\BLOCKCHAIN.READ\Blockchain development\Ethereum\ethereumjs-monorepo
> npm run checkNpmVersion

> root@1.0.0 checkNpmVersion C:\Users\LENOVO\Desktop\Library\BLOCKCHAIN.READ\Blockchain development\Ethereum\ethereumjs-monorepo
> ./scripts/check-npm-version.sh

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! root@1.0.0 checkNpmVersion: `./scripts/check-npm-version.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the root@1.0.0 checkNpmVersion script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\LENOVO\AppData\Roaming\npm-cache\_logs\2021-09-08T08_26_02_055Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! root@1.0.0 preinstall: `npm run checkNpmVersion`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the root@1.0.0 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\LENOVO\AppData\Roaming\npm-cache\_logs\2021-09-08T08_26_02_309Z-debug.log

In my log 

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install'
1 verbose cli ]
2 info using npm@6.14.15
3 info using node@v14.17.6
4 verbose npm-session e6e612447215c787
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall root@1.0.0
7 info lifecycle root@1.0.0~preinstall: root@1.0.0
8 verbose lifecycle root@1.0.0~preinstall: unsafe-perm in lifecycle true
9 verbose lifecycle root@1.0.0~preinstall: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\LENOVO\Desktop\Library\BLOCKCHAIN.READ\Blockchain development\Ethereum\ethereumjs-monorepo\node_modules\.bin;C:\Python39\Scripts\;C:\Python39\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Users\LENOVO\AppData\Local\Microsoft\WindowsApps;C:\Users\LENOVO\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\LENOVO\AppData\Roaming\npm;C:\Users\LENOVO\AppData\Local\GitHubDesktop\bin
10 verbose lifecycle root@1.0.0~preinstall: CWD: C:\Users\LENOVO\Desktop\Library\BLOCKCHAIN.READ\Blockchain development\Ethereum\ethereumjs-monorepo
11 silly lifecycle root@1.0.0~preinstall: Args: [ '/d /s /c', 'npm run checkNpmVersion' ]
12 silly lifecycle root@1.0.0~preinstall: Returned: code: 1  signal: null
13 info lifecycle root@1.0.0~preinstall: Failed to exec preinstall script
14 timing stage:rollbackFailedOptional Completed in 2ms
15 timing stage:runTopLevelLifecycles Completed in 1923ms
16 verbose stack Error: root@1.0.0 preinstall: `npm run checkNpmVersion`
16 verbose stack Exit status 1
16 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
16 verbose stack     at EventEmitter.emit (events.js:400:28)
16 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
16 verbose stack     at ChildProcess.emit (events.js:400:28)
16 verbose stack     at maybeClose (internal/child_process.js:1055:16)
16 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
17 verbose pkgid root@1.0.0
18 verbose cwd C:\Users\LENOVO\Desktop\Library\BLOCKCHAIN.READ\Blockchain development\Ethereum\ethereumjs-monorepo
19 verbose Windows_NT 10.0.18363
20 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
21 verbose node v14.17.6
22 verbose npm  v6.14.15
23 error code ELIFECYCLE
24 error errno 1
25 error root@1.0.0 preinstall: `npm run checkNpmVersion`
25 error Exit status 1
26 error Failed at the root@1.0.0 preinstall script.
26 error This is probably not a problem with npm. There is likely additional logging output above.
27 verbose exit [ 1, true ]

**Comment by holgerd77** [comment]
Not totally sure, but it seems that you are running on Windows and you might need to install the WSL ()Windows Subsystem for Linux) for some custom bash scripts to work.

@ryanio I think it would be more user friendly if we have at least these kind of mandatory scripts as Node.js scripts?

**Comment by ryanio** [comment]
> @ryanio I think it would be more user friendly if we have at least these kind of mandatory scripts as Node.js scripts?

Seems reasonable, although I'm not sure if we can check npm version inside of node. I found [check-node-version](https://www.npmjs.com/package/check-node-version) we could switch to instead, I should have checked for something like that before writing a custom script :)

**Comment by nots29vv** [comment]
It has been a min, spent the whole day trying to get bash on my laptop because of some registry file issues. But bash didn't solve this, thank you @holgerd77 I read through the article, i know this maybe bad practise but i modified my package.json, since i meet the npm requirement in the .sh scripts. That worked. Then I had Issues with npm run build --workspaces which i also took out. @ryanio Thanks also, hope your day is going fine. what issues might / would i face because of this?

**Comment by ryanio** [comment]
@nots29vv what's your goal with the library? you'll need the build command to do development. but if you are just looking to use the exported APIs, then you can install the packages you need in your own package.json and import them at the top of your file.

**Comment by nots29vv** [comment]
@ryanio I would like to use this library to learn how things work under the hood.

**Comment by gabrocheleau** [comment]
Hey @nebojsa94, I'm also on a Windows PC and have run into the same issue. The problem is that Windows doesn't allow running scripts that start with `./` or `../`. Until these scripts are made compatible with Windows, you can force windows to use git bash to run scripts (you'l need to instal git bash for this) with the following command:

`npm config set script-shell "C:\\Program Files (x86)\\git\\bin\\bash.exe" `

You can then reset it with this command:

`npm config delete script-shell`

**Comment by holgerd77** [comment]
@gabrocheleau Oh, that's some great insight, can we directly add this as a note to our [monorepo](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/config/MONOREPO.md) setup documentation?

**Comment by nots29vv** [comment]
thanks @gabrocheleau, this helped but I am met with a new error:
 npm ERR! code 1
npm ERR! path C:\Users\LENOVO\Desktop\Blockchain\Ethereumjs\TRY\ethereumjs-monorepo\packages\client
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c npm run binWorkaround
npm ERR! > @ethereumjs/client@0.0.6 binWorkaround
npm ERR! > test -f dist/bin/cli.js || echo 'install fails if bin script does not exist (https://github.com/npm/cli/issues/2632), creating placeholder file at "dist/bin/cli.js"' && mkdir -p 'dist/bin' && touch dist/bin/cli.js
npm ERR!
npm ERR! 'install fails if bin script does not exist (https://github.com/npm/cli/issues/2632), creating placeholder file at "dist/bin/cli.js"'
npm ERR! 'test' is not recognized as an internal or external command,
npm ERR! operable program or batch file.
npm ERR! The syntax of the command is incorrect.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\LENOVO\AppData\Local\npm-cache\_logs\2021-09-10T12_19_32_216Z-debug.log

is this familiar? can you please help?

**Comment by gabrocheleau** [comment]
Hmm, I haven't seen that error actually. Perhaps this issue might help?: [npm/cli#2632](https://github.com/npm/cli/issues/2632)

Also, could you confirm the steps you've taken to install the repo? Are you running `npm install` from the root dir only?

**Comment by nots29vv** [comment]
Thank you @gabrocheleau. The new issue I have has to do with me using windows, I am also met with a new error "test -f" command not found. Thank you @holgerd77 @ryanio, this was also a problem from me npm was @version 6, by upgrading it and using wsl2, i have no issues. Thanks again.
