### ISSUE TITLE
Legacy transaction common details are defaulted even after passing a common object for another chain

### ISSUE THREAD

**Issue by JaskSkull** [ethereumjs/ethereumjs-monorepo#1461]
The problem I am facing is that when I initialize a legacy transaction and create a transaction with @ethereumjs/tx with a Common object, it defaults to the defaults values of the chain (mainnet and istanbul hardfork). This doesn't happens with the FeeMarketEIP1559Transaction option of the @ethereumjs/tx.

```
const { Transaction } = require( '@ethereumjs/tx' );
const Common = require( '@ethereumjs/common' ).default;

const chain = new Common( { chain : 'rinkeby', hardfork : 'berlin' } );
const rawTx = {
    to          :   web3.utils.toHex( receivingAddress ),
    gasPrice    :   web3.utils.toHex( web3.utils.toWei( '1.5' , 'gwei' ) ),
    gasLimit    :   web3.utils.toHex( 210000 ),
    value       :   web3.utils.toHex( web3.utils.toWei( '0.5' , 'ether' ) ),
    data        :   web3.utils.toHex( 'TEST' ),
    nonce       :   web3.utils.toHex( await web3.eth.getTransactionCount( sendingAddress , 'pending' ) ),
};

const tx = Transaction.fromTxData( rawTx , { chain } );
console.log(tx);
```

The output of the console.log(tx) is the following (the common Details more exactly:

```
common: Common {
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  _supportedHardforks: [],
  _eips: [],
  _customChains: [],
  _chainParams: {
      name: 'mainnet',
      chainId: 1,
      networkId: 1,
      defaultHardfork: 'istanbul',
      consensus: [Object],
      comment: 'The Ethereum main chain',
      url: 'https://ethstats.net/',
      genesis: [Object],
      hardforks: [Array],
      bootstrapNodes: [Array],
      dnsNetworks: [Array]
  }
}
```
To be able to execute the transaction I had to hardcode into the transaction object the details for the rinkeby testnet network with the following code:
```
var tx = Transaction.fromTxData( rawTx , { chain } );

tx.common._chainParams.name = 'rinkeby';
tx.common._chainParams.chainId = 4;
tx.common._chainParams.networkId = 4;
tx.common._chainParams.defaultHardfork = 'berlin';
tx.common._chainParams.comment = 'PoA test network';
tx.common._chainParams.url = 'https://www.rinkeby.io';
```
Which gave me the following output for a console.log( tx ):
```
_chainParams: {
      name: 'rinkeby',
      chainId: 4,
      networkId: 4,
      defaultHardfork: 'berlin',
      consensus: [Object],
      comment: 'PoA test network',
      url: 'https://www.rinkeby.io',
      genesis: [Object],
      hardforks: [Array],
      bootstrapNodes: [Array],
      dnsNetworks: [Array]
}
```
This allowed me to execute the transaction without any problems. I am wondering if this is a bug or I am doing something wrong?, I am asking because, as I mentioned before, when I use the common object for the FeeMarketEIP1559Transaction it works like a charm.

This is the transaction hash to corroborate in [rinkeby etherscan](https://rinkeby.etherscan.io/) that it is working with the hardcode of the transaction object.
Tx Hash: 0x2a80647a1b6ceebc5224af5d1727426fd3c3c7c434123565fc8f702aa4ac5401

**Comment by ryanio** [comment]
> `const tx = Transaction.fromTxData( rawTx , { chain } );`

the option param is `common` not `chain`

**Comment by JaskSkull** [comment]
`const chain = new Common( { chain : 'rinkeby', hardfork : 'berlin' } );`

chain is the name I assigned to the Common object.

**Comment by ryanio** [comment]
@JaskSkull sure, then you should do:

`const tx = Transaction.fromTxData( rawTx , { common: chain } );`

**Comment by JaskSkull** [comment]
Thanks @ryanio it worked!
