### ISSUE TITLE
Client throws `outdated fork status` error when syncing to client on different hardfork

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ethereumjs-monorepo#1466]
When running multiple instances of the client, if a new instance of the client is started and tries to connect to the first client and the first client is on a later hardfork, the first client throws the below error when it receives the STATUS message from the second client and won't connect:
```js
devp2p:eth Send STATUS message to 127.0.0.1:37270 (eth66): [V:66, NID:15470, TD:3699, BestH:130a6fd, GenH:2eed290, ForkHash: 0x14f6d8f0, ForkNext: NaN] +881ms
  devp2p:eth Received STATUS message from 127.0.0.1:37270: [V:66, NID:15470, TD:1, BestH:2eed290, GenH:2eed290, ForkHash: 0x5616a08c, ForkNext: 20] +5ms
  devp2p:eth Outdated fork status, remote needs software update +0ms
ERROR [09-09|15:36:16] AssertionError [ERR_ASSERTION]: Outdated fork status, remote needs software update
```

If the second client connects to a geth peer on the same network, geth will connect and start exchanging messages with the second client:
```
 devp2p:eth Send STATUS message to 127.0.0.1:37792 (eth66): [V:66, NID:15470, TD:1, BestH:2eed290, GenH:2eed290, ForkHash: 0x5616a08c, ForkNext: 20] +1m
  devp2p:eth Received STATUS message from 127.0.0.1:37792: [V:66, NID:15470, TD:3707, BestH:5d6a712, GenH:2eed290, ForkHash: 0x14f6d8f0, ForkNext: NaN] +1ms
  devp2p:eth Send GET_BLOCK_HEADERS message to 127.0.0.1:37792: e601e4a05d6a712507a2c24c9f0251e6498e25499ac93e9c6bc319508a53... +4s
```

To recreate, set up a private network using the attached geth genesis file.
[poa.json.txt](https://github.com/ethereumjs/ethereumjs-monorepo/files/7139348/poa.json.txt)

1) `cat poa.json.txt > poa.json`
2) Create a new account for mining and update the `extradata` field in `poa.json` with this new account.
3) `geth --datadir data --networkid 15470 --log.debug --mine --unlock 0xMyMinerAccount -nodiscover` and unlock your account for mining 
4) Run `DEBUG=devp2p:eth npm run client:start -- --gethGenesis=path/to/poa.json --port=30305` in a new terminal window
5) Run  `geth attach data/geth.ipc` in another terminal window
6) `admin.addPeer("client enode address")`
7) Go back to the terminal window with the client instance running and wait until it passes the first hardfork block (block 20)
8) Open a new terminal window and run `DEBUG=devp2p:eth npm run client:start -- --datadir=data2 --gethGenesis=../../../../poa.json --port=30307 --bootnodes=enode://mysyncedEthJSClientEnodeAddress@0.0.0.0:30305 --transports=rlpx`
9) Go back to the terminal window with the first client and you should see an error message similar to the top of this post when the two clients exchange `STATUS` messages

**Comment by holgerd77** [comment]
Oh, that's interesting. That's already a great benefit coming out of this new possibility of setting up own small inter-EthereumJS-client dev networks with a custom chain setup, that this exposes a lot more clearly these kind of inconsistencies respectively misbehaviours.

@acolytec3 Thanks for this thorough write-up on how to recreate! 😄 👍
