### ISSUE TITLE
Monorepo: Distribute modules with esm as well

### ISSUE THREAD

**Issue by kumavis** [ethereumjs/ethereumjs-monorepo#1468]
since the packages are authored as typescript esm it should be easy to distribute as esm in addition to cjs

**Comment by kumavis** [comment]
eg `@ethereumjs/tx` only provides a "main" https://npmfs.com/package/@ethereumjs/tx/3.3.0/package.json#L16

**Comment by holgerd77** [comment]
Some context on this, [here](https://nodejs.org/api/esm.html#esm_modules_ecmascript_modules) is the Node.js ESM documentation.

Some articles on possible approaches:

- [How to Create a Hybrid NPM Module for ESM and CommonJS](https://www.sensedeep.com/blog/posts/2021/how-to-create-single-source-npm-module.html), Feb 12 2021 (I like that one on a very first read)
- [Hybrid npm packages (ESM and CommonJS)](https://2ality.com/2019/10/hybrid-npm-packages.html), 2019-10-22 (a bit older)

Related issue: #978

What do you guys think, might be a good time to prioritize a bit on this? (@kumavis thanks for the suggestion)

**Comment by paulmillr** [comment]
This should be delayed until node.js drops support for v14, which is 2023+. The constraint list:

It is not possible to use dynamic requires same code to be used in node.js and browser (NPM etc). I'm talking about this pattern:

```ts
export const crypto: { node?: any; web?: any } = (() => {
  const webCrypto = typeof self === 'object' && 'crypto' in self ? self.crypto : undefined;
  const nodeRequire = typeof module !== 'undefined' && typeof require === 'function';
  return {
    node: nodeRequire && !webCrypto ? require('crypto') : undefined,
    web: webCrypto,
  };
})();
```
