### ISSUE TITLE
"invalid sender" when using "@ethereumjs/tx"

### ISSUE THREAD

**Issue by hammerstrike** [ethereumjs/ethereumjs-monorepo#1471]
Dependencies used
- [x] @ethereumjs/tx (^3.3.0)
- [x] web3 (^1.5.2)
- [x] web3js-quorum (^21.7.0-rc1)

using `ethereumjs-tx`
```
const tx = new EthereumTx(rawTransaction, {
        chain: 'mainnet',
        hardfork: 'homestead'
    });
```

using `@truffle/hdwallet-provider`
```
const tx = EthereumTx.fromTxData(rawTransaction, {
        chain: 'mainnet',
        hardfork: 'homestead'
    });
```

Private signed Tx works fine with `require('ethereumjs-tx').Transaction;` 
While not works with `require('@ethereumjs/tx').Transaction;` and return error `{ code: -32000, message: 'invalid sender' }`

**Comment by ARJUN-R34** [comment]
I am also facing a similar issue when trying to send a signed eip-1559 transaction.
`Error: Returned error: invalid sender`

**Comment by ryanio** [comment]
@hammerstrike There are several important breaking changes from tx v2 to v3, please read them [here](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/tx/CHANGELOG.md#major-refactoring---breaking-changes).

For your code, there would be two things: instantiate and pass in a `common` option for the chain and hardfork, and also the signed tx returns a new object (does not modify the existing tx) so you will need to capture that.

i.e.:

```typescript
const common = new Common({ chain: 'mainnet', hardfork: 'homestead' })
const tx = EthereumTx.fromTxData(rawTransaction, { common })
const signedTx = tx.sign(privKey)
const serializedTx = '0x' + signedTx.serialize().toString('hex')
console.log('use this: ', serializedTx)
```

---

@ARJUN-R34 could you provide a more complete code example? You might want to send the signedTx as a hex string, so:

```typescript
const serializedTx = '0x' + signedTx.serialize().toString('hex')
web3.eth.sendSignedTransaction(serializedTx).on('receipt', console.log)
```

**Comment by ARJUN-R34** [comment]
> @hammerstrike There are several important breaking changes from tx v2 to v3, please read them [here](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/tx/CHANGELOG.md#major-refactoring---breaking-changes).
> 
> For your code, there would be two things: instantiate and pass in a `common` option for the chain and hardfork, and also the signed tx returns a new object (does not modify the existing tx) so you will need to capture that.
> 
> i.e.:
> 
> ```ts
> const common = new Common({ chain: 'mainnet', hardfork: 'homestead' })
> const tx = EthereumTx.fromTxData(rawTransaction, { common })
> const signedTx = tx.sign(privKey)
> const serializedTx = '0x' + signedTx.serialize().toString('hex')
> console.log('use this: ', serializedTx)
> ```
> 
> @ARJUN-R34 could you provide a more complete code example? You might want to send the signedTx as a hex string, so:
> 
> ```ts
> const serializedTx = '0x' + signedTx.serialize().toString('hex')
> web3.eth.sendSignedTransaction(serializedTx).on('receipt', console.log)
> ```

`const { FeeMarketEIP1559Transaction } = require('@ethereumjs/tx');
const Common = require('@ethereumjs/common');
const { Chain, Hardfork } = require('@ethereumjs/common');
const Web3 = require('web3');
const web3 = new Web3(new Web3.providers.HttpProvider(<infura_url>));

async function signAndSendTx(to, from, value, gasLimit, nonce) {
    const privateKey = 'private_key'

    const rawTx = { to, from, value, gasLimit, data: '0x00', nonce }

    const pkey = Buffer.from(privateKey, 'hex'); 

    const common =  new Common({ chain: Chain.Ropsten, hardfork: Hardfork.London });

    const tx = FeeMarketEIP1559Transaction.fromTxData(rawTx, { common })

    tx.sign(pkey);

    const signedTx = `0x${tx.serialize().toString('hex')}`;

    const response = await web3.eth.sendSignedTransaction(signedTx);

    return response.transactionHash;
}`

**Comment by holgerd77** [comment]
@ARJUN-R34 since a tx object is immutable (for security reasons) the `tx.sign()` method is not changing the tx itself but returns a new signed tx (see also the code cods of the method). So it has to be used like this:

```javascript
const signedTx = tx.sign(pkey)
```

Will close, feel free to reopen if there are remaining issues (nevertheless guys: please also spent some significant time on reading the [README](https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/tx), there are very clear examples on all the things you have posted as questions here).

**Comment by ARJUN-R34** [comment]
> @ARJUN-R34 since a tx object is immutable (for security reasons) the `tx.sign()` method is not changing the tx itself but returns a new signed tx (see also the code cods of the method). So it has to be used like this:
> 
> ```js
> const signedTx = tx.sign(pkey)
> ```
> 
> Will close, feel free to reopen if there are remaining issues (nevertheless guys: please also spent some significant time on reading the [README](https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/tx), there are very clear examples on all the things you have posted as questions here).

@holgerd77 I have followed the steps mentioned in the README for EIP-1559 transaction. The transaction is not going forward. Waiting for a solid solution on this.
Check out my code [here](https://github.com/ARJUN-R34/eip1559-tx-signing).

**Comment by NabiKAZ** [comment]
> @holgerd77 I have followed the steps mentioned in the README for EIP-1559 transaction. The transaction is not going forward. Waiting for a solid solution on this. Check out my code [here](https://github.com/ARJUN-R34/eip1559-tx-signing).

In your `rawTx`, you need to specific the chain id.
You using `Chain.Ropsten` so add Ropsten's chain id, `3` into `rawTx`.

```
const rawTx = {
   :
   chainId: web3.utils.toHex(3)
};
```
