### ISSUE TITLE
Util: toType() behaviour for `undefined` and `null` values

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1472]
Just stumbled upon this along some `Common` library Merge work and want not to side-introduce, so I'll work around that in my own PR and post here instead so that this can be tackled independently.

So `toType()` is currently returning `<BN: 0>` values for `undefined` and `null`, see:

```shell
> toType(3, TypeOutput.BN)
<BN: 3>
> toType(undefined, TypeOutput.BN)
<BN: 0>
> toType(null, TypeOutput.BN)
<BN: 0>
```

(this should also be checked for conversion to other types if existant)

I would assume that this is error prone and shouldn't be the case (as we have seen along some `null`, 0, undefined problems within the tx library along setting the v, r, s values e.g.).

So this should very likely return:

- `undefined` -> `undefined`
- `null` -> `null`

Anything else?

**Comment by ryanio** [comment]
ah thanks, I will look into this and open a PR to fix, and add some of these test cases for `undefined` and `null`.

I will have to change the return type to `| undefined | null` though so it might affect some of our usage where we'll have to assert as non-null before using.
