### ISSUE TITLE
Replace ethjs-util dependency with something else

### ISSUE THREAD

**Issue by kingjerod** [ethereumjs/ethereumjs-monorepo#1474]
The ethjs-util package is on version 0.1.6. The API for that package could change and would end up breaking this package. 

Additionally, ethjs-util is including two 1 liner packages (also made by the same author):

https://github.com/SilentCicero/strip-hex-prefix/blob/master/src/index.js
`return isHexPrefixed(str) ? str.slice(2) : str;`

https://github.com/SilentCicero/is-hex-prefixed/blob/master/src/index.js
`return str.slice(0, 2) === '0x';`

This just creates extra lines in our lock files and extra requests on install. Personally I think we should discourage these 1 line packages in the NodeJS community.

**Comment by talentlessguy** [comment]
are there any alternative packages?

**Comment by kingjerod** [comment]
It seems like most of the functions used in this library are very simple. Some of them are a couple lines, others are like 10 or so lines. You can either create a new package with the util functions in them or just create a new module in this library. 

In the bytes util, these are used:
`stripHexPrefix, padToEven, isHexString, isHexPrefixed`

In object util, `stripHexPrefix` is used.

In types util, `isHexString` is used.

There are exported from index for end users to use:
`isHexPrefixed, stripHexPrefix, padToEven, getBinarySize, arrayContainsArray, toUtf8, toAscii, fromUtf8, fromAscii, getKeys, isHexString`

I can try to help with this, depending on which direction you want to go (new library or just add it to this one).

**Comment by talentlessguy** [comment]
@kingjerod I think it's worth making a new npm package

**Comment by kingjerod** [comment]
Do you want me to make a new package under my account or do you want to create a new one under the ethereumjs namespace and I can push to it? You already have the ethereumjs-util package, it could also be added to that.

**Comment by acolytec3** [comment]
We've been discussing this recently and are still working through the various options. We'll checkout back in the next couple of weeks once we have a decision.

**Comment by kingjerod** [comment]
Sounds good, happy to help.

**Comment by holgerd77** [comment]
We'll likely be directly rewriting the methods in the `ethereumjs-util` package.

**Comment by talentlessguy** [comment]
@holgerd77 yeah sounds better to have it all in one package

the less dependencies there is, the lesser there's maintenance burden
