### ISSUE TITLE
Block: add calcBaseFeeFromHeader option

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1478]
Similar to the existing [calcDifficultyFromHeader](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/block/src/types.ts#L51) option on the Block library we should add a calcBaseFeeFromHeader option for convenience (if I am not missing something, just writing this up pretty quickly on the side line).

**Comment by ryanio** [comment]
We already have [`calcNextBaseFee()`](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/block/src/header.ts#L671) so it just needs to be passed in:

`Block.fromBlockData({ header: { baseFeePerGas: parentHeader.calcNextBaseFee() } })`

The BlockBuilder also does this automatically if `baseFeePerGas` is not provided.
