### ISSUE TITLE
VM: Blake2 precompiled contract gives incorrect result on some inputs

### ISSUE THREAD

**Issue by convexman** [ethereumjs/ethereumjs-monorepo#1482]
Version: release v4.1.3 (commit feef85f7d51c4e09da3105ebe473e86dcff45eb1)
Node: v10.24.1
Steps to reproduce:
1. go to `tests/api/istanbul/eip-152.js` and add following testcase to `const testCases = [...`
```
  {
    input: '0000000c48c9bdf267e6096a3ba7ca8485ae67bb2bf894fe72f36e3cf1361d5f3af54fa5d182e6ad7f520e511f6c3e2b8c68059b6bbd41fbabd9831f79217e1319cde05b61626364650000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000500000000000000000000000000000001',
    expected: 'f3e89a60ec4b0b1854744984e421d22b82f181bd4601fb9b1726b2662da61c29dff09e75814acb2639fd79e56616e55fc135f8476f0302b3dc8d44e082eb83a8',
    name: 'vector 9'
  }
```
2. run `npm run test:API`

One can verify that expected value is correct by querying mainnet node
```
curl https://mainnet.infura.io/v3/<infura token> \
    -X POST \
    -d '{
    "jsonrpc": "2.0",
    "method": "eth_call",
    "params": [
        {
            "from": "0x0000000000000000000000000000000000000000",
            "to": "0x0000000000000000000000000000000000000009",
            "data": "0x0000000c48c9bdf267e6096a3ba7ca8485ae67bb2bf894fe72f36e3cf1361d5f3af54fa5d182e6ad7f520e511f6c3e2b8c68059b6bbd41fbabd9831f79217e1319cde05b61626364650000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000500000000000000000000000000000001"
        },
        "latest"
    ],
    "id": 0
}' \
    -H "Content-Type: application/json"
{"jsonrpc":"2.0","id":0,"result":"0xf3e89a60ec4b0b1854744984e421d22b82f181bd4601fb9b1726b2662da61c29dff09e75814acb2639fd79e56616e55fc135f8476f0302b3dc8d44e082eb83a8"}
```

Hashing string `abcde` using some online hash calculator confirms this result (https://www.toolkitbay.com/tkb/tool/BLAKE2b_512)

One can also write similar test in go-ethereum repo (which I initially did), but this requires building go-ethereum.

**It seems that all strings of length less or equal 4 are hashed correctly** (thus all mentioned test vectors work), problem occurs whenever length of string is *at least 5* (and it so happened all current test vectors are hashing string `abc`)

I was not able to figure out what's causing this issue, js implementation seems quite different from golang in go-ethereum

**Comment by holgerd77** [comment]
@convexman hi there, thanks a lot for reporting and for this detailed write-up. We'll try to investigate soonish. 🙂

**Comment by holgerd77** [comment]
Some context for reference: the associated precompile implementation in the VM can be found [here](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/vm/src/evm/precompiles/09-blake2f.ts), precompile has been implemented along PR #584 .

**Comment by holgerd77** [comment]
Test vectors added to `ethereum/tests`: https://github.com/ethereum/tests/pull/619

**Comment by jochem-brouwer** [comment]
This [line](https://github.com/ethereumjs/ethereumjs-monorepo/blob/fcc895596435a694dcf0029b90757cf7861db6e1/packages/vm/src/evm/precompiles/09-blake2f.ts#L8) is wrong, the copied code is actually [here](https://raw.githubusercontent.com/dcposch/blakejs/410c640d0f08d3b26904c6d1ab3d81df3619d282/blake2b.js) . [EIP](https://eips.ethereum.org/EIPS/eip-152) states we should implement blake2b, not blake2s.

I checked the original source code which indeed reports the values @convexman has supplied here.
