### ISSUE TITLE
devp2p: deduplicate per-Message/DISCONNECT/DISCONNECT reason/IP-based debug logger messages

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1485]
Adding the new debugging capabilities (see title) within the `devp2p` packages along #1449 had the side effect of producing redundant messages on certain `DEBUG` logger combinations, mostly visible if the plain `devp2p:*` logger is used, see e.g.:

![grafik](https://user-images.githubusercontent.com/931137/134163543-69ccefd0-3e1d-4c33-8924-485aaf4814db.png)

This is distracting and reduces oversight and should therefore be fixed.

Not sure yet how to approach, since there is no (obvious) way to detect along the `debug()` calls if a debug message has been logged to the console.

One first step might be to update the `debug` package version (this is generally pretty outdated and therfore somewhat strongly recommended) (this should then be done in all currently applying libraries - so `VM`, `Blockchain` and `devp2p` - for consistency reasons) and see if there have been more fine grained capabilities introduced along this question ("has the debug msg been send?". Changing the return type for `debug()` would actually be pretty helpful in this regard, just as some more theoretical (?) thought).

**Comment by Gonad78** [comment]
#1613

**Comment by holgerd77** [comment]
Still highly relevant and a good first issue if someone wants to play around with the client + the devp2p code without going to much into the weeds.

Fix is not strongly connected to some devp2p code logic but there just needs to be some clever solution how to not always activate all these loggers at once.

**Comment by ScottyPoi** [comment]
I'll work on this one

**Comment by ScottyPoi** [comment]
![devp2p_debug_fix](https://user-images.githubusercontent.com/66335769/149844766-db2f4aab-028a-4ba9-965d-8276f4dfcdab.png)
