### ISSUE TITLE
Passing decimal values to FeeMarketEIP1559Transaction generates invalid output silently

### ISSUE THREAD

**Issue by Matko95** [ethereumjs/ethereumjs-monorepo#1497]
In the snippet attached below, if you pass decimal numbers to the FeeMarketEIP1559Transaction constructor it doesn't throw any errors, but alters the values silently, this can be very dangerous as the final payload when ran in a browser environment converts `33974229950.550003` -> `35624562130324685` which is a much larger number than what was originally passed, increasing the gas price.

```
const ethereumJsTx = require('@ethereumjs/tx') //  "@ethereumjs/tx": "^3.3.0",

const decimal_gas_fee = 33974229950.550003
const base_fee = 5 * 10 ** 9

const rawTx = {
  maxPriorityFeePerGas: decimal_gas_fee,
  maxFeePerGas: decimal_gas_fee + base_fee,
  chainId: 1,
  nonce: 0,
  gasPrice: null,
  gasLimit: 144000,
  to: '0x0000000000000000000000000000000000000000',
  value: 0,
  data: []
}

const tx = ethereumJsTx.FeeMarketEIP1559Transaction.fromTxData(rawTx)

// Browser environment
// maxFeePerGas: 45061746130324685, maxPriorityFeePerGas: 35624562130324685

// Node.js environment
// maxFeePerGas: 2123389402, maxPriorityFeePerGas: 2123389402

console.log(tx.maxFeePerGas.toString(), tx.maxPriorityFeePerGas.toString())
```

**Comment by holgerd77** [comment]
We are on it, we will discuss in a call later today and provide a hotfix release on the library as soon as possible.

**Comment by kongnet** [comment]
https://github.com/indutny/bn.js/issues/211

**Comment by jochem-brouwer** [comment]
Hi @Matko95, thanks for opening this issue. One thing I keep wondering about, which you might have more insight in: why does the browser report different values than the values reported by node?

**Comment by holgerd77** [comment]
We have just released new versions of the Util and Tx libraries in #1501 which address the issue and provides a safer instantiation on the integer values.

**Comment by Matko95** [comment]
Thanks for solving this so quickly, you're awesome! 

@jochem-brouwer I found it very confusing that different values were reported as I was testing, can't be sure what's the reason yet.
