### ISSUE TITLE
Client: Add Engine API object types and validation functions for affected methods

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1506]
Merge relevant, see [Engine API](https://github.com/ethereum/execution-apis/blob/v1.0.0-alpha.1/src/engine/interop/specification.md), also take note of the priority and urgency label on the sideline (may change over time).

Feedback from Ryan required before starting on an implementation: recommended

---

Various methods from the Engine API take in parameters as objects, comparable on taking in a [transaction object](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/client/lib/rpc/modules/eth.ts#L128) on various ETH RPC calls. These object parameters currently have no validation method (unless Ryan has implemented in the meantime) like the [transaction()](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/client/lib/rpc/validation.ts#L186) method in `rpc/validation.ts`, which can then be added for validating RPC call input parameters similar to [here](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/client/lib/rpc/modules/eth.ts#L57).

Following RPC calls affected:

- `preparePayload` (as of current `master`, input for `Engine.preparePayload()` is also not taken in as an object yet (not encloses with `{}` as in `forkchoiceUpdated` e.g., this would eventually also need an update first)
- `executePayload` (type `ExecutionPayload` exists in `engine.ts`, should be handles as the other newly added types, eventually also moved to `types.ts` like the `RpcTx` interface(not sure, generally: types or interfaces here?))
- `consensusValidated`
- `forkchoiceUpdated`

While not strictly necessary for the Merge to work, this is highly recommended to have ready early, since it will likely strongly help on detecting errors regarding interoperability when we have proper validation here, so this would be a very thankful task to be picked up since it is both not that difficult to implement but would take some time to do properly and therefore would save some significant amount of time.

**Comment by ryanio** [comment]
I have added an `object` validator that accepts keys and validators for the values, e.g.:

```typescript
    this.preparePayload = middleware(this.preparePayload.bind(this), 1, [
      [
        validators.object({
          parentHash: validators.blockHash,
          timestamp: validators.hex,
          random: validators.hex,
          feeRecipient: validators.address,
        }),
      ],
    ])
```


added in PR #1512 commit https://github.com/ethereumjs/ethereumjs-monorepo/pull/1512/commits/b88232baedfb49017227017210761b5322ea87b5

also added `validators.array` for the `transactions` key and `validators.values` for consensusValidated's `status` param (to ensure one of "VALID" or "INVALID")
