### ISSUE TITLE
Negative BNs causing weird situations as txs with negative value

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/ethereumjs-monorepo#1513]
Our VM is OK with running message calls and transactions where the call value is a negative BN. This should throw on both Tx and on VM. This creates ETH out of thin air. I wonder if there is any case in our stack where we would actually need negative BNs - if that's nowhere, then we should probably block negative BNs at the BN module level.

What's also weird is that we can `serialize` txs with negative call value, and then recover the transaction (where now the BN is the positive variant of the number). This should throw on RLP level, since I don't think RLP supports negative numbers either?

**Comment by gabrocheleau** [comment]
My understanding is also that RLP doesn't support negative numbers. From the yellow paper (top of page 20 - Berlin version):

> If RLP is used to encode a scalar, defined only as a non-negative integer (in N, or in Nx for any x), it must be encoded
> as the shortest byte array whose big-endian interpretation is the scalar

**Comment by gabrocheleau** [comment]
One thing I just noticed is that the `toBuffer()` method that we use, for example, in the Transaction constructor, converts negative big numbers to positive ones. See for example:

```
    const negativeBN = new BN('-10')
    const negativeBuffer = new BN(toBuffer(negativeBN))

    console.log('negativeBN: ', negativeBN)                  // negativeBN:  <BN: -a>
    console.log('isNegative: ', negativeBN.isNeg())       // isNegative:  true
    console.log('negativeBuffer: ', negativeBuffer)        // negativeBuffer:  <BN: a>
    console.log('isNegative: ', negativeBuffer.isNeg())  // isNegative:  false
```

This seems to me like something that could lead to weird and potentially dangerous bugs
