### ISSUE TITLE
Client: Implement eth_getLogs RPC endpoint

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1520]
During the Merge interop event it turned out that Eth2 clients need the [eth_getLogs](https://eth.wiki/json-rpc/API#eth_getlogs) JSON RPC endpoint, so we should implement (as some hack when doing work on #1512 we just mocked the call and gave a static response).

For these kind of historical data we would need some database to store along client sync, latest state after some discussion with Ryan was that we likely wouldn't want to store in the configuration database (due to being misplaced) but also do not want to add a new database for every new type of data stored, so we settled a bit on doing one additional database for all now and future historical data additions (e.g. receipts as well if needed) and use some prefixing here for access (`log_*` or similar). If there are drawbacks which we might have overlooked let us know.

Update: from looking at the API from the RPC description linked above with the different possible filter parameters (block numbers, address, topic), I wonder if we would rather need a small relational database here? 🤔

Logs are produced along VM execution runs in [runTx.ts](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/vm/src/runTx.ts) respectively [runBlock.ts](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/vm/src/runBlock.ts).

**Comment by gabrocheleau** [comment]
Would there be any issue for The Merge compatibility if we follow the same rules as Alchemy as outlined in the post shared above (or perhaps make them more/less loose depending on our needs)? Namely:

> Here are the safety nets Alchemy has in place for large eth_getLogs requests:
> 1. You can make eth_getLogs requests with up to a 2K block range and no limit on the response size.
> 2. You can also request any block range with a cap of 10K logs in the response.

**Comment by acolytec3** [comment]
I think we can safely call this one closed via #1566
