### ISSUE TITLE
Monorepo: Fix npm audit security vulnerabilities (nyc / verdaccio / tap-spec / npm-auth-to-token)

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1537]
Doing an `npm i` from the root directory on `master` currently gives the following result:

![grafik](https://user-images.githubusercontent.com/931137/138247091-9b497c29-6ea1-41fb-a41f-1a402ad8e66a.png)

Many of these vulnerabilities are linked to outdated versions of `nyc` (see also #832) and `verdaccio`, so we should give updates of these two libraries some priority in some first round.

While both of the libraries are dev dependencies, generally having a large number of vulnerabilities shown on `npm audit` also comes with some greater risk of overlooking some more severe vulnerabilities.

Mid-term we should optimally come to a situation where we just regularly update and get to a somewhat 0-vulnerabilities situation on all levels.

**Comment by holgerd77** [comment]
Ok, looking into the remaining vulnerabilities here. One other high severe vulnerability is coming from [tap-spec](https://github.com/scottcorgan/tap-spec), which is a dev dependency in the VM [package.json](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/vm/package.json) and is used for the [formatter](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/vm/DEVELOPER.md#running-tests-with-a-reporterformatter) dev command for VM testing which routes to the [formatTest.js](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/vm/scripts/formatTest.js) script in the `vm/scripts` folder, where `tap-spec` is used as the default formatter.

My first thought was that we might want to remove this formatter script all together since I guess this is rarely (not at all?) used. But on another thought it should already be enough to remove `tap-spec` as a default and make this script more generic. If one then wants to use this with `tap-spec` it is always possible to install globally e.g..

(so, some other context on `tap-spec`: package seems no to be maintained any more, last release is from over 3 years ago, so not possible to update (already on latest version) and therefore would be generally desirable to get rid of this package).

**Comment by holgerd77** [comment]
Second high severe vulnerability is coming from [npm-auth-to-token](https://www.npmjs.com/package/npm-auth-to-token), an extremely obscure dev dependency which we should definitely remove. This has been published four years ago and there is neither a README nor a matching code/GitHub site available.

Dependency is used in the [E2E publish script](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/scripts/e2e-publish.sh#L32) (for doing the Hardhat tests) for logging in to npm, I guess this should be possible to be relatively easily achieved in a more standard way? 🤔

**Comment by emersonmacro** [comment]
@holgerd77 I have a PR up for the first vulnerability. I found a more up-to-date fork of `tap-spec`. A fresh `npm i` after that change shows just 2 high vulnerabilities, which I think is down to the `npm-auth-to-token` vulnerability. I'll try to tackle that next.

**Comment by emersonmacro** [comment]
Update: I found a workaround for `npm login` functionality in the `e2e-publish` script that does not require an external library, so the PR removes `npm-auth-to-token` as well. After those two changes, a fresh `npm i` shows zero high severity vulnerabilities! 🎉

**Comment by holgerd77** [comment]
> Update: I found a workaround for `npm login` functionality in the `e2e-publish` script that does not require an external library, so the PR removes `npm-auth-to-token` as well. After those two changes, a fresh `npm i` shows zero high severity vulnerabilities! 🎉

That's super cool, thanks! 🙂 👍

**Comment by holgerd77** [comment]
Most of this has been addressed, will close.

Nevertheless: fixes on vulnerabilities from `npm audit` are always welcome!
