### ISSUE TITLE
Add Sepolia PoW chain support

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/ethereumjs-monorepo#1558]
One of the questions at the ArrowGlacier PR was (see #1527): why is there no difficulty bomb delay planned for Ropsten? Well, this is because the testnet will be deprecated and replaced by Sepolia. See https://github.com/ethereum/go-ethereum/pull/23730

It seems that this will replace Ropsten after the merge, so it has no high priority, but it is anyways nice to implement this at some point and should not be a lot of work.

CC @holgerd77

**Comment by holgerd77** [comment]
Ah, oh, that's nice, have a new on-the-beginning lightweight PoW testnet at hand soon. 🙂

**Comment by holgerd77** [comment]
Ah, just remember that this was also discussed along the Merge even, lol (oh oh, the memories). 😜

**Comment by emersonmacro** [comment]
@holgerd77 @jochem-brouwer I took a stab at this here #1581. I haven't set up a new chain before so there might be something obvious that I missed - any feedback welcome. Specifically in `chains/sepolia.json`, I couldn't find anything for `url` or `dnsNetworks`, and not sure if I got the hardforks right.
