### ISSUE TITLE
Client reports inflated transaction counts in block executed logs

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ethereumjs-monorepo#1559]
The client is reporting highly inflated transaction counts in blocks when executing them in the course of syncing the chain.  Below is one example:

`INFO [11-08|11:47:22] Executed blocks count=2 first=653251 hash=27b23634... td=3895421746169041320 hardfork=chainstart last=653253 hash=cb3429e5... with txs=86`
According to Etherscan, [Block 653251](https://etherscan.io/block/652251) has 2 transactions in it and [653252](https://etherscan.io/block/652252) has 5 while our client is reporting 86 transactions executed in these two blocks.  

The transaction count is computed [here](https://github.com/ethereumjs/ethereumjs-monorepo/blob/f15f28b580923d040c6bdf9de68ff38cf1f5fab4/packages/client/lib/sync/execution/vmexecution.ts#L119).

**Comment by acolytec3** [comment]
I used the new `--executeBlocks` client parameter and ran the first block in question - 653251- and got the below result
```
> @ethereumjs/client@0.1.0 client:start
> ts-node bin/cli.ts "--executeBlocks=653251"

INFO [11-08|11:56:55] Initializing Ethereumjs client version=v0.1.0 network=mainnet 
INFO [11-08|11:56:55] Data directory: /home/jim/Library/Ethereum/ethereumjs
INFO [11-08|11:56:55] Full sync mode
INFO [11-08|11:56:55] Initializing VM execution hardfork=chainstart 
INFO [11-08|11:56:55] Latest local block: number=654550 td=3905270219621352758 hash=5ea38aa9... hardfork=chainstart 
INFO [11-08|11:56:55] Preparing for block execution (debug mode, no services started)...
INFO [11-08|11:56:55] Executed block num=653251 hash=0x27b23634515807f550f40a7047df9e877b9e4512a9d2b05cc5acc01a0512e8e9 txs=2 gasUsed=42000 
```

which matches what Etherscan reports for this.  So, it doesn't appear to be an issue with the VM.

**Comment by acolytec3** [comment]
The issue is that `txCounter` is not reset between sets of blocks being executed in [this iterator method](https://github.com/ethereumjs/ethereumjs-monorepo/blob/f15f28b580923d040c6bdf9de68ff38cf1f5fab4/packages/client/lib/sync/execution/vmexecution.ts#L92).

**Comment by ryanio** [comment]
have fixed in https://github.com/ethereumjs/ethereumjs-monorepo/pull/1556/commits/1f3ef440d1d87d62c99cee79582c8fb09928abd6 (#1556)

**Comment by holgerd77** [comment]
Ok, cool, thanks for figuring out so quicky, will take this fix over to the release PR. This is so severe that we should really fix ASAP.

**Comment by jochem-brouwer** [comment]
This is a logging issue, right, so it should not be that severe? We should release it nevertheless.

**Comment by acolytec3** [comment]
Correct, as far as I can tell in the code, the only place that was used was
in the logs. So, unless somebody has critical code tracking our client
logs, we should be okay.

**Comment by holgerd77** [comment]
> This is a logging issue, right, so it should not be that severe? We should release it nevertheless.

From a UI perspective I find these kind of things extremely severe. This is one of the core stats seen in the logs and substantially diminishes trust in the overall proper functionality if these kind of things are off the charts.

Have added to the release PR though directly. 😄

**Comment by acolytec3** [comment]
This one appears to be resolved (based on running the latest iteration of the client) though I don't remember which PR we took the fix into.

**Comment by holgerd77** [comment]
For the record: took over the commit from @ryanio into the Arrow Glacier releases in #1555.
