### ISSUE TITLE
Monorepo: Custom ESLint Rule to forbid BN.toBuffer() usage

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1569]
We had a bug in our blockchain library reported in #1552 which somewhat broke the library for browser usage due to the usage of the `bn.toBuffer()` function, fix has been done in #1566.

These are these kind of bugs which are just not possible to not be reintroduced by future devs (or even by ourself [TM]). So we should address these kind of things structurally to avoid. As @ryanio pointed out it might be possible to create a custom ESLint rule - see e.g. [this](https://www.kenneth-truyers.net/2016/05/27/writing-custom-eslint-rules/) article - have only skimmed over though and didn't really dive in to see how complex this is.

There might also be other ways to achieve this. Note that it is not enough to just detect `toBuffer` by name, since we also have an own implementation of a function named like this in the Util library.

**Comment by holgerd77** [comment]
Ah, and again the question (sorry, might have overlooked something in the chat): why has this not been caught by the browser tests? 🤔

**Comment by ryanio** [comment]
> Ah, and again the question (sorry, might have overlooked something in the chat): why has this not been caught by the browser tests? 🤔

I was wondering about this as well. It seems to be an issue specifically with browserify and bn.js in this case

The author of bn.js [said](https://github.com/indutny/bn.js/issues/147#issuecomment-221153462):
> This is intentional to reduce the size of javascript library. I think you may try to use `num.toArrayLike(Buffer, endian, length);` in your code to mitigate this.

I think karma-typescript automatically includes `Buffer` so it works, as opposed to browserify will only include it if specifically referenced as an import, and bn.js avoids that (to reduce the size as mentioned above)

We could add a GH Action workflow or step that runs this repo and fails if it doesn't output as expected: https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/vm/examples/run-code-browser
in general it might be a good idea to run all our examples in ci so they don't break without us noticing (this occasionally tends to happen as we continue to develop and forget to update or improve the examples)

**Comment by holgerd77** [comment]
> in general it might be a good idea to run all our examples in ci so they don't break without us noticing (this occasionally tends to happen as we continue to develop and forget to update or improve the examples

Yes, that's what I also already thought a couple of times, will directly open an issue, thanks for suggesting. 😄

**Comment by holgerd77** [comment]
This would still be useful to address, no specific monorepo knowledge needed.
