### ISSUE TITLE
VM, Tx: Run Code Examples in CI

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1574]
We have code examples included in various packages. These are somewhat neglected respectively forgotten right now and there is a somewhat higher chance that these break over time with nobody noticing.

This should be changed by adding these examples to CI being run with GitHub actions, optimally in a (somewhat) standardized/unified way (but also: likely no need to introduce overblown centralized structures like a script to route everything through or something), but also without too much custom code on the examples itself (we'll see how it goes).

Following packages contain relevant examples (client + devp2p examples should likely be omitted, too complex, too diverse):

- VM: [examples](https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/vm/examples) folder
- Tx: [examples](https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/tx/examples) folder

Just to mention here: these examples could generally need some love ❤️ and it would make sense to modernize and also think about new relevant (and also: a bit more exciting!) use cases, e.g. creating a L2 tx with the Transaction library, I am sure there will be others. Other libraries like `Block` or `Blockchain` would likely also benefit from a - small - examples collection.

**Comment by cbrzn** [comment]
I was thinking of tackling this the following way:

With `npm workspaces` we can create a script (which can be `examples` for example) and in the root package.json the script: `"examples": "npm run examples --workspaces --if-present"` will allow us to add the `examples` script in the packages and simply run it if it exists in the package.

The way we would add the examples in packages would be the following:
- Create a folder called `examples` (As is currently done)
- In the package.json, add the script `examples: ts-node examples/*/.ts`
- Create a file for specific examples (i.e: In `transactions`, create one that executes different transaction types and hard forks, or in `block`, a file where a block for PoW and PoS are created) - PD: Just thinking out of loud here, lmk if this doesn't make sense :P
-  Create a README.md in every example folder, to explain every example that lives in this folder

Then adding the command `npm run examples` in the CI will make sure every example works as expected 

At the same time, we can create a new package where we can have reusable functions (probably we can use the `common` library? Not sure, I was thinking of utils package which won't be ever published, to npm, it's just for the sake of the playground), making it easier to create more complex examples and allowing new developers to dive in a more comfortable way into the code by learning from these 

The main points I see with this proposal:
- Reusing code will help to keep consistency between the different packages examples, hence, making it easier to maintain
- By having just one readme per example folder, it's easier to see all the examples in a single source of truth
- (Minor) Devs won't need to do `npm i` in needed examples to download required dependencies, these dependencies can live in the package where reusable function lives, making a better developer experience

Also, I want to point out that - _(If I understand this correctly)_ - the main difference with tests is that the automated tests focus on testing the packages in a modular way, and with these examples, we can do any e2e and complex logic we want to add, by playing with the legos blocks (aka reusable functions that combine all the packages) - I think of it as a playground

**Comment by holgerd77** [comment]
Closed by #1658
