### ISSUE TITLE
VM: Optimize (Replace) Jump Analysis Algorithm

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1575]
The EVM uses the `JUMPDEST` and `BEGINSUB` opcodes to mark jump or subroutine destinations. Control flow is then directed to these potential destinations with the `JUMP`, `JUMPI` and `JUMPSUB` opcodes which are respectively setting the program counter, see the respective [opcode implementations in functions.ts](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/vm/src/evm/opcodes/functions.ts).

Our VM determines which jump destinations are valid in the [Interpreter._getValidJumpDests()](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/vm/src/evm/interpreter.ts#L240) function. Martin from the geth team pointed out that our implementation is generally suboptimal from a performance perspective and would become really slow with a lot of jump destinations, since we put all jump dests into a large array.

Go-Ethereum has its own - more sophisticated - algorithm for a jump analysis which Martin described. Will repost here:

---

Look at https://github.com/ethereum/go-ethereum/blob/master/core/vm/analysis.go#L81. It has several tricks

- The output is a bitmap, each bit telling if the op is part of `data` or part of `code`. 

Thus, when checking if a jump is valid, there are two parts: is it code and is the code actuall `JUMPDEST`. So the opcode check is deferred until the jump is made. 

By doing the bitmap this way, we improve the speed. Let's consider your algo. There are two things which make it slow. 
1. The speed of the read 
2. The speed of the write

For speed of read -- there is a worst-case on "everything except PUSH". For any non-push, it will only progress one byte at a time. 
For speed of write -- there is a worst-case on JUMPDEST and BEGINSUB. For those two, it will push something on every byte. 

So the data-filled-with-jumpdest neatly hits both worst-cases. Now, if you consider my algo instead

- The speed of read is also worst on non-push. 
- The speed of write is worst on push -- because then we need to write 1 into the bitmaps. However, e.g. on PUSH32, we can write 32 bits at the same time. 

So with my algo, there is no singular worst-case which combines the two. Most likely PUSH1 is worst, since it "only" progresses 2 byte at a time, and fills every second bit with `1`. 

Also, your algo is slow because  you alloc -- every jumpdest forces a vector to be extended. In my algo, we pre-allocate a bitmap of 1/8th the size of the code, and then just flips the bits.

> Should this initial code analysis just be skipped and the rather be determined if a jump is valid on the fly when JUMP, JUMPI or JUMPSUB is called?

That is a good optimization in the general case, however, it won't help with this case. My attack does a jump across the entire code, landing close to the end of it.
`i += code[i] - 0x5f` == `i += code[i] +1 - PUSH1` == `i += 1 if PUSH1, 2 if PUSH2, 3 if PUSH3` ...`
`this.lookupOpInfo(code[i]).name` -- totally useless overhead. Just check the opcode directly.

```
if (curOpCode === 'PUSH') {
```

replace with

```javascript
if (code[i] >= 0x60 && code[i] <= 0x7f){
```

That might even be two mem lookups (not sure how clever javascript is), so might be better to 

```
    for (let i = 0; i < code.length; i++) {
      const curOpCode = code[i]

      // no destinations into the middle of PUSH
      if (curOpCode >= 0x60 && curOpCode <= 0x7f){
        i += curOpCode - 0x5f
      }
```

---

We should consider an implementation of the algorithm referenced to optimize on this front.

**Comment by holgerd77** [comment]
Note: trivial part of this (direct hex opcode comparison) has been implemented in https://github.com/ethereumjs/ethereumjs-monorepo/pull/1570/commits/e2e15eaf2599c4d132ff2fa4d51f817b7faf295a.

**Comment by jochem-brouwer** [comment]
Could we write this as a Buffer? We could use certain byte values which characterizes the nature of the opcode (JUMPDEST/PUSH/BEGINSUB). In case of a PUSH we could use the Buffer.fill method to fill the Buffer. We already know beforehand how large the buffer is going to be (code size) so we only need to allocate this once and not keep pushing to these arrays each time.

**Comment by holgerd77** [comment]
@jochem-brouwer in doubt give it a try if you want. I do not understand the code from Go-Ethereum good enough yet to give some assessment here.
