### ISSUE TITLE
Error in usage demo on main page

### ISSUE THREAD

**Issue by samlaf** [ethereumjs/ethereumjs-monorepo#1583]
The [usage demo script](https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/util#usage) on the main page has a problem:

`assert.equal(unpadBuffer(Buffer.from('000000006600', 'hex')), Buffer.from('6600', 'hex'))`
raises a weird error

> internal/process/esm_loader.js:74
>   internalBinding('errors').triggerUncaughtException(
>                               ^
> 
> AssertionError [ERR_ASSERTION]: Buffer(2) [Uint8Array] [
>   102,
>   0
> ] == Buffer(2) [Uint8Array] [
>   102,
>   0
> ]
>     at file:///home/samlaf/dev/ethereum/ecdsa/tx_demo.mjs:7:8
>     at ModuleJob.run (internal/modules/esm/module_job.js:170:25)
>     at async Loader.import (internal/modules/esm/loader.js:178:24)
>     at async Object.loadESM (internal/process/esm_loader.js:68:5) {
>   generatedMessage: true,
>   code: 'ERR_ASSERTION',
>   actual: Buffer(2) [Uint8Array] [ 102, 0 ],
>   expected: Buffer(2) [Uint8Array] [ 102, 0 ],
>   operator: '=='
> }

this is because equality doesn't work for buffers (for some reason that I don't understand):
```
>>> Buffer.from('11', 'hex') == Buffer.from('11', 'hex')
    false
>>> Buffer.from('11', 'hex').equals(Buffer.from('11', 'hex'))
    true
```

So instead the usage demo should be changed to
`assert.ok(unpadBuffer(Buffer.from('000000006600', 'hex')).equals(Buffer.from('6600', 'hex')))`

**Comment by acolytec3** [comment]
Thanks for this.  I've checked and verified this issue and have a PR to resolve it.

**Comment by samlaf** [comment]
Also just realized none of the [module links](https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/util#modules) below work.

**Comment by ryanio** [comment]
> Also just realized none of the [module links](https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/util#modules) below work.

Thanks, we should remove those links, typedoc likes to play funny games and change permalinks often so it's fruitless to keep trying to match it. It might help if we also move the link to /docs to the top of the section.

**Comment by holgerd77** [comment]
> > Also just realized none of the [module links](https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/util#modules) below work.
> 
> Thanks, we should remove those links, typedoc likes to play funny games and change permalinks often so it's fruitless to keep trying to match it. It might help if we also move the link to /docs to the top of the section.

@ryanio have you kept a reference somewhere on this task so that we do not forget? If not, can you do so or alternatively directly execute on this? 🙂

**Comment by ryanio** [comment]
> > > Also just realized none of the [module links](https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/util#modules) below work.
> 
> > 
> 
> > Thanks, we should remove those links, typedoc likes to play funny games and change permalinks often so it's fruitless to keep trying to match it. It might help if we also move the link to /docs to the top of the section.
> 
> 
> 
> @ryanio have you kept a reference somewhere on this task so that we do not forget? If not, can you do so or alternatively directly execute on this? 🙂 

Will open a PR for it today :)
