### ISSUE TITLE
CREATE2 fails because of nonce

### ISSUE THREAD

**Issue by LogvinovLeon** [ethereumjs/ethereumjs-monorepo#1592]
I'm trying to re-execute a transaction using ethereumjs-vm and I get a wrong result.
[Here](https://etherscan.io/tx/0x4ee97f695dbb85314c8bfe90b0e212c73bb739c077d0fffcd5b8ac0deb7058df) is the transaction I'm trying to execute. [EthTx](https://ethtx.info/mainnet/0x4ee97f695dbb85314c8bfe90b0e212c73bb739c077d0fffcd5b8ac0deb7058df/)

After some digging in I've discovered the issue. This transaction creates a new contract using `CREATE2`. The problem seems to be that this contract was already created and selfdestructed before. Specifically in the transaction comming right before it. [Etherscan](0x43aff36ae06a08073151e175d1d0ca6917de8f08bace30281779ccb4e5d7d858). [EthTx](https://ethtx.info/mainnet/0x43aff36ae06a08073151e175d1d0ca6917de8f08bace30281779ccb4e5d7d858/). Notice the transaction positions within a block. 47 and 48. It seems like the issue is in this [`if`](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/vm/src/evm/evm.ts#L304). When I remove the nonce check - it works.

Question being - is this fix general enough? I'm not familiar with all the EIPs and old hard fork specifications. Maybe this check should still be there just not for create2.

You can see here that this contract is constantly being created and destroyed within the same block.
https://oko.palkeo.com/0xf2d47e78dEA8E0F96902C85902323d2a2012b0c0/code/

**Comment by jochem-brouwer** [comment]
Could you share your testing code? If you would execute the selfdestruct transaction and then execute the transaction which recreates the contract, it should work. Selfdestruct wipes the entire contract account, which also sets nonce to zero and clears the code. This *should* work, so I have the feeling that there might be something going on in your testing code.

**Comment by LogvinovLeon** [comment]
Yes, you're right. I wasn't resetting the nonce on the account deletion. Thanks
