### ISSUE TITLE
Create standalone StateManager package

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/ethereumjs-monorepo#1599]
In #1590 we implement stuff which is not directly related to the VM. It therefore makes sense to create a standalone package for StateManager - in some cases, we don't need VM support but only use StateManager as an interface to the DB.

**Comment by jochem-brouwer** [comment]
@g11tech 

I think this should be done in the following steps (these steps are different PRs)

- Create the interface for StateManager. What should be in it and what not? Anything VM-related (warm addresses, touched accounts) should be removed from StateManager and should go into VM. (`evm.ts` or `eei.ts`)
- Second PR should actually remove the StateManager into a seperate package. 

We should also figure out exactly what the semantics of StateManager should be. This is essentially a bridge between VM and Trie. The specific VM-related tasks such as warm addresses should be kept in the VM, StateManager should not have to deal with these (this also makes implementing custom state managers much easier as you do not have to "copy" this code).

**Comment by g11tech** [comment]
closing because of successful merge of https://github.com/ethereumjs/ethereumjs-monorepo/pull/1817 :slightly_smiling_face:
