### ISSUE TITLE
Maybe an error with not reverting gas refunds when the contract code storage failed

### ISSUE THREAD

**Issue by LogvinovLeon** [ethereumjs/ethereumjs-monorepo#1601]
Hi. I'm using ethereumjs-vm to re-execute the transactions from ethereum mainnet. Specifically this one: https://ethtx.info/mainnet/0xfd544642ce821bda8a5b90aa0d8583e52853ad7082c84d650ac0009e7773131b/
After that I check that the gas consumed is correct (consistent with the mainnet). And I'm getting an error.
Ethereumjs-vm applies the refund from a failed code.
```
  vm:evm Received message results gasUsed=128892 execResult: [ gasUsed=128892 exceptionError=[object Object] returnValue= gasRefund=undefined ] +2ms
  vm:evm message checkpoint reverted +1ms
  vm:tx ---------------------------------------------------------------------------------------------------- +0ms
  vm:tx Received tx results gasUsed=128892 execResult: [ gasUsed=128892 exceptionError=out of gas returnValue= gasRefund=15000 ] +0ms
  vm:tx Generated tx bloom with logs=0 +0ms
  vm:tx:gas tx add baseFee 271108 to gasUsed (-> 400000) +0ms
  vm:tx Subtract tx gasRefund (15000) from gasUsed (-> 385000) +0m
```

I see that there is a mechanism on `runInterpreter` to avoid that: https://github.com/ethereumjs/ethereumjs-monorepo/blob/501be8da11b07d138bb4497f8a18bdf0fa2d11d7/packages/vm/src/evm/evm.ts#L498
I think that there needs to be a similar one on `executeMessage`. I've added it locally here: https://github.com/ethereumjs/ethereumjs-monorepo/blob/501be8da11b07d138bb4497f8a18bdf0fa2d11d7/packages/vm/src/evm/evm.ts#L199 but I'm not sure if this is the best place. There is also a TODO above that seems related: https://github.com/ethereumjs/ethereumjs-monorepo/blob/501be8da11b07d138bb4497f8a18bdf0fa2d11d7/packages/vm/src/evm/evm.ts#L191

**Comment by jochem-brouwer** [comment]
Could you show me how you are re-executing this transaction? It would help debugging this issue.

I think the problem here is that even though the transaction goes OOG, we still get a refund applied?

**Comment by LogvinovLeon** [comment]
Hi. Unfortunately I can't share the code as it's close sourced, but I have a custom StateManager that I connect to an archive node.

Yes. That's the problem. We revert the state, but gas refund is stored on the EVM object and not on the _state object so it doesn't get reverted.

**Comment by LogvinovLeon** [comment]
Also - a quick question. Has anyone tried to sync mainnet with the TS client on top of ethererumjs-vm? Cause then this issue will come up. The first block that has this error is: 2772981 within tx: 0xe3b0fb0a45bc905d1f98baabaadd194901267d02de74cdad187b7feb8920d7b3

**Comment by jochem-brouwer** [comment]
@acolytec3 did you run into this issue when syncing?

Thanks for reporting this, this indeed looks like a problem which we should fix asap.

**Comment by LogvinovLeon** [comment]
Good news is - that I did re-execute all ethereum mainnet blocks using etereumjs-vm and geth/errigon archive db and this is the only issue I've found after Homestead HF

**Comment by jochem-brouwer** [comment]
You re-executed **all** mainnet blocks using our VM? How long did that take?

**Comment by LogvinovLeon** [comment]
Well - a couple of month of real compute time. But three things. First - I've replaced the state management code to not copy all the state on checkpoint, but use a layered solution. I know - it's now also done like that, but it did not used to be so. And it was a drastical perf improvement on current blocks. Second - I've used a couple of machines for that. Third - I've used erigon DB as the backend and not geth one. It's faster. Also - the only leveldb node client available can't reasonably handle 7-8TB DB as it does unnecessary compactions on reads

**Comment by jochem-brouwer** [comment]
It is very great to hear that you have actually executed all mainnet blocks and that we are in most cases correct. I can indeed reproduce this issue (I took this tx 0xe3b0fb0a45bc905d1f98baabaadd194901267d02de74cdad187b7feb8920d7b3)

**Comment by jochem-brouwer** [comment]
It seems that this has to do with contracts being created which then go out of gas. Is this the only case where this issue happens, or does this also happen with transactions which do not create a contract, but instead interact with one (and then go out of gas)?

**Comment by LogvinovLeon** [comment]
Based on empirical evidence - only COOG (contract creation code storage out of gas)

**Comment by acolytec3** [comment]
I was never able to get the client to sync that far. Got bogged down in the 2.4MM range.

**Comment by LogvinovLeon** [comment]
Yes, there is smth in 2.4M-2.5M range that I'm also investigating. I have a list of all the errors
```
block,gasUsed,gasUsedCanonical,diff,txIndex,txHash
2485031,71982,46982,-25000,1,0x2270de0c2a799e80eb41014f4a34827bb01027ac66b5f24fc124bffeb8c19b4d
2485069,50000,33256,-16744,5,0xca423ec1e6972f72cca52332b255a066b95647e3a0928a4b2ac55671daf308c6
2485074,71982,46982,-25000,0,0x30c423cc7e7957ecfa71481fcdd850abc5fa6529c8343a6d053d02486c4d4c38
2485078,71982,46982,-25000,2,0x98b0e03e555676c571da923bdfeb4fb1d1452e1dee8f5e845080fb0d1869e01f
2485094,71982,46982,-25000,3,0x08b0fa0b7c3283bef7d16129000fa1a2f66552c04d79a1262cdcb0e6218545a2
2516717,74702,24702,-50000,0,0x78976cc35ee1f615cdc35b32809b0ff0460d393141aaa4cd87f680140640610e
2516719,74504,49504,-25000,1,0xcc3026bcd7493a3d41a907d952a01a3e664fb9e227b984829e81cf0fc7946052
2516727,74504,49504,-25000,2,0x449f5205ebd9ab8e16359c8f32b4e1dda29302bb0731658e7f01a756787faa5a
2516767,131755,99396,-32359,9,0x68dc874f832fff022bdca181480f8c39aa02f171b8c3383e366d8a53a8b25970
2516793,92699,67699,-25000,1,0x9d5d691e5ab63cb3110a3c7d70eae28f747d30894fa532109b08ba7f845cec54
2516857,1400000,1306305,-93695,9,0x57a80b0bfba4e931418c95c931b16252d7813e69a1a42756b7b46d6bbfcc1ecb
2527784,59270,34270,-25000,8,0x1a135c0b7c8731e2be812d1af0315283716e1d16e1b90c580e3914fdecb333fd
2527994,100000,82699,-17301,0,0x73a76bdd85bf13da618487c27e77cc9b71e0d128c36459d7e65e6f5331b8166c
2528061,76666,51666,-25000,2,0x9e259167a93cef947575cefb6e8def38303a5c0a9953358f84322bd550958cbe
2772981,429999,489999,60000,3,0xe3b0fb0a45bc905d1f98baabaadd194901267d02de74cdad187b7feb8920d7b3 out of gas
2986212,1472203,1502203,30000,1,0x1b27e88dd481a17f63fd4d0f0051fbcb2048077e8ed00165fa88e4ef0e4ad45c out of gas
4272268,870000,900000,30000,45,0xbc6989fde0fdd6415bb117ec93faf0701cd422e97706b09fc9bcff813dcc020a out of gas
4328973,1985000,2000000,15000,66,0xd42701838efe3b9085671c57fda802671fece50cb22cb6e1cf7f31b8c1a4052b out of gas
4329009,1985000,2000000,15000,82,0xbb2c9fe39cbc1cb91b45253ed59d0522a1f3abdc9d7e80b1016e9abf735a9efe out of gas
4337370,908320,923320,15000,113,0xad8f7d475b965691f3e107f76fadd88c2e4d74e534035370df7aec795167bfe0 out of gas
4583387,4985000,5000000,15000,35,0x2769164681b0e6d85d1e4ccf3211b11a61358cab5d4fc582971a2d13e7e11b41 out of gas
4618818,4685000,4700000,15000,25,0x7ad00d0e78b60eeb3970c0ec7f2056c837564acde12adafc478f0a137f3dd812 out of gas
4618855,4685000,4700000,15000,25,0x072e69508b42bd297895ccf0f09446d3280be8479467132004ab69da89000fc0 out of gas
4618863,4685000,4700000,15000,25,0x73cb4731d78a9d900fad6a81c3a50edbfc64525798b8023d6b5d5f9046fff086 out of gas
4739698,4535000,4550000,15000,34,0x67ae1700ac80c26d445de9d18918223957d0d8c4324b9c1cf2564c25da457f3e out of gas
4756397,1272755,1317755,45000,123,0x8ce1e3a27915fe2fc0e5a3eb91fcdea73d30ea5f2ff9085d2edde803159f869f out of gas
4777735,1753295,1798295,45000,34,0xa06cbd1f91fc12a9f70d48164f302c6dd58475986c5bca5a5ad2061f66102b6b out of gas
4779053,3735000,3750000,15000,37,0xe05e0fea29c0f475658d550f3446b694c33a9ea3b94216dbd5f372981c35f34d out of gas
4911060,669885,714885,45000,176,0xf3a6cda4ca2bc1c44e567b3a86c93893cc46a2afc9ee8fb93ce19cbc12f16fae out of gas
4912225,489865,534865,45000,197,0xce54e63873a2ea7a289a3128eeaaf289c504ab3e1a2bd3e51cc5d11f4a88fac8 out of gas
4914461,462522,507522,45000,202,0x1508f556ead0ac3d8a1292b0fcbb250818980df1e9b904d6cd2f3c7d9784ee2d out of gas
4915781,489865,534865,45000,110,0x1a819bd1145bb50b1a6a856f52b41f704f7df6f07d18cb4562773cb11ac796e9 out of gas
4993075,385000,400000,15000,26,0xfd544642ce821bda8a5b90aa0d8583e52853ad7082c84d650ac0009e7773131b out of gas
6169988,3975000,3990000,15000,11,0x8575252c4e6e6b6274e7d443034e8435ce85d0eeeb2a11eceb43039d76a4edab out of gas
6202148,4655000,4700000,45000,40,0x06583dcb1f3b742e34c9060f40317fbb2179afee1b8f60b56a7472dbcc2716f1 out of gas
6299452,570000,600000,30000,14,0x07cc038225132fbc55e2179cd625b921d4ce22ee1bd4e2a50a6cc27be6829bda out of gas
6526891,1741396,1756396,15000,60,0xbf2eeecdedcb97ac1aa96371ee843abdb00fc36c94ecdcc12495541f41fad0e0 out of gas
6618046,4655000,4700000,45000,22,0xa45f6727c3a230268f76400d0af5ec5d035169332a5e1c0a887542b750728a6d out of gas
8850939,1709101,1724101,15000,45,0x3e1523eb51c5ce1edd37289eb76008845dbd5530f45829bdd66dffdea1fc95ec out of gas
8857885,1853542,1868542,15000,57,0x9a83ad3001e35980dc6047d789d1d00db5d9ed6fbdc292aa9c61a8912ea3c97f out of gas
8863263,1973672,1988672,15000,118,0x238e9fa3ce448940798ee007ff20e401e3a3b6f0f9ba272b26b07a78852e2971 out of gas
9684567,2730985,2750185,19200,23,0x8695af1a7af16db3ebbbcf724bb0c93ed0573a6760b49cd23b56f34fcdf08f79 out of gas
10015952,980800,1000000,19200,143,0x084c24f3eb2a499048c0f7580c3f0e0cdc947a2b07cd4218fed11c577276f68f out of gas
10360590,3756606,3803406,46800,39,0x578fc4135e3858eb0b568a1354d8a8edced22523b6af6c599d54c0e1e5d81f7f out of gas
10388589,480800,500000,19200,59,0xe2cd32b60a9c8e0fd82bce4714aebacb9b38597f6305e65e99831916e2711915 out of gas
10388610,480800,500000,19200,40,0xa0e06da806ad06534a56fb87f7b09b3b821d518319169b8d2f820adb4ab82179 out of gas
10388616,680800,700000,19200,23,0xbf37baa36bc1c50b5d167b28bab3dd2c65e398a19731d2f34659f3175b87c2e3 out of gas
10440865,880800,900000,19200,110,0x580e987ae5f54a938ffe0abc3092d623a2fe5bef180fabc804b6ed0bfb3baba4 out of gas
10441494,2092467,2111667,19200,82,0xf6beb110e2a238755fe9cf8e45c49cba6dd49c925125e18adca80df6e37df25c out of gas
10696486,1290565,1356565,66000,14,0xea802c883380e531723dc9ddec9b38ca7e3d285f925e2f2c769fe3de890dbbc4 out of gas
11017526,4902602,5002802,100200,28,0x1e1082b1c9deba68e177d948ae4e320dc5e7d9bd2ca1fb17255f7da8ff3a3f00 out of gas
11020958,4441919,5449919,1008000,52,0xda075a4819d08077cd18cf32dcd3d00371fb785a950dec1fc361c8cbb4e016cf out of gas
11063111,3480276,3525276,45000,6,0x14f6a34c90e9e4519b29fa49ee984ca56bcdae7ad26e508ba2914516671c6d22 out of gas
11312569,607960,612160,4200,118,0x796c79b899ee66171864a8698917a94022f667de4051aa52c6f7ccb349177c67 out of gas
11681085,879250,898450,19200,49,0xb83914810d69d5618408a3720b6c2763ce69d82fb141b6701b078314ca0dd829 out of gas
11686425,879250,898450,19200,82,0x387dc33823531278cb3e8b353252b5ad6802d80f5a48fa25b0d35f597330f124 out of gas
11728759,1580800,1600000,19200,24,0x5a1b91e2db75f265a827738704dada637505508b11e43e25d391baa256e620ec out of gas
12620714,505587,550987,45400,0,0xe6f224de4d3c30621695f9fd9925d083e44a77d4f8dced54a6626c227ca905d8 out of gas
12621042,745743,748543,2800,26,0x59c11d5480474ec494d870461b7eb4ffe914f3631f8bcd7d28461a7eb468a486 out of gas
13601647,2594092,2596892,2800,98,0xbb8aace9ab121a167353effff9e3cb84cd3175dc61a8c273bb0a84dca0394063 out of gas
13707381,2454600,2500000,45400,94,0x2ab38144a2dc72bb7220094aa04f6e0e49241cb7e5a6391cd306b4e937fb7290 out of gas
13752784,2983878,3003778,19900,72,0x03ba1bd2b3b776728823de40a873dafa3e33068a5c1042fb75c1c8d7f5dd1bb1 out of gas
```

After this one is fixed - there are only 14 blocks left and all of them before Homestead. I'll let you know when I figure those blocks out.

**Comment by jochem-brouwer** [comment]
There seems to be a global GitHub CI issue, so I don't know if all consensus tests now pass, but I'm fairly certain that #1603 fixes the problem.

**Comment by LogvinovLeon** [comment]
I've just figured out those last 14 blocks. Those were errors on my side. So yeah. Now I can say that if this bug is fixed and the stateManager implementation is correct - this majestic library can sync mainnet!
@acolytec3 If you ever continue syncing and get stuck at the same blocks - my code had two issues.
1. `accountExists` on precompiles should return `true`
2. `accountExists` should not only check for `nonce` & `balance` but also for `codeHash`. This is not required on later hard forks because of nonce increments.

**Comment by acolytec3** [comment]
> I've just figured out those last 14 blocks. Those were errors on my side. So yeah. Now I can say that if this bug is fixed and the stateManager implementation is correct - this majestic library can sync mainnet! 

Albeit, very, very, very slowly :grimacing:.  I was trying to sync it on my laptop and it made Ubuntu on my 8th gen i7 cry when we got into the Shanghai DDOS attack section of the chain.


>@acolytec3 If you ever continue syncing and get stuck at the same blocks - my code had two issues.
>
>accountExists on precompiles should return true
>accountExists should not only check for nonce & balance but also for codeHash. This is not required on later hard forks because of nonce increments.

Good to know.  We'll add these to our fix list

**Comment by jochem-brouwer** [comment]
@LogvinovLeon could you provide, if possible, the txs where you ran into the first issue? The second one should not be a problem in our library, if an account has code it is implicitly in the trie and therefore our account exists method will always return true. The first one however could lead to some problems. However I think that you might have ran into an edge case which caused a fork on mainnet years back. Was the tx in question on Spurious dragon fork and was it calling to 0x3, the ripemd precompile?

**Comment by holgerd77** [comment]
@LogvinovLeon that's all great stuff here! 😄 Is your `StateManager` implementation something you could open-source, and might it be worth to add as an additional state manager to our base implementation?

**Comment by holgerd77** [comment]
> @LogvinovLeon that's all great stuff here! 😄 Is your `StateManager` implementation something you could open-source, and might it be worth to add as an additional state manager to our base implementation?

@LogvinovLeon short reiteration on the question from above: feel very free to decline for whatever reason - this is your code 😋 - just want to make sure this just doesn't get overlooked. *In case* it's possible to contribute this might be a valuable addition.

**Comment by LogvinovLeon** [comment]
@holgerd77 I'll ask the team about the scope of the stuff we can contribute. Will get back to you soon

**Comment by holgerd77** [comment]
@LogvinovLeon great, that's nice! 🙂
