### ISSUE TITLE
Possible fixes needing review

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ethereumjs-monorepo#1605]
From [this issue](https://github.com/ethereumjs/ethereumjs-monorepo/issues/1601#issuecomment-991165834) , the original poster identified a couple of potential issues in our `stateManager`  that should be reviewed as we contiune down the list of fixes for the VM.

- accountExists on precompiles should return true
- accountExists should not only check for nonce & balance but also for codeHash. This is not required on later hard forks because of nonce increments.

**Comment by LogvinovLeon** [comment]
Just a clarification. I was not using your state manager. I was using a custom one that was inspired by your but has erigonDB or RPC as a backend. Your uses gethDB. So it might as well be that your state manager doesn't have those issues

**Comment by ryanio** [comment]
> accountExists on precompiles should return true

have we looked more into this one yet?

**Comment by acolytec3** [comment]
I haven't done any further research but the person who posted the original comment about that said it was his state manager implementation that was causing that issue so I'm going to optimistically trust we don't need to check further.

**Comment by ryanio** [comment]
ok thanks, I will close this for now then. @LogvinovLeon if you have any further helpful information please feel free to comment or open a new issue.
