### ISSUE TITLE
common.forCustomChain not being a function

### ISSUE THREAD

**Issue by rsmith2002** [ethereumjs/ethereumjs-monorepo#1609]
States it is depreciated and hinted to use Common.custom but that also states it is not a function either. If this issue has been addressed or you need more information then let me know... or I am being completely dumb. Importing with import Common from '@ethereumjs/common' and installing with npm install @ethereumjs/common

**Comment by jochem-brouwer** [comment]
Could you post a minimal code snippet which throws this error for you?

**Comment by rsmith2002** [comment]
> Could you post a minimal code snippet which throws this error for you?

import Common from '@ethereumjs/common'

...some code

var BSC_FORK = Common.forCustomChain(
              'mainnet',
              {
                  name: 'Binance Smart Chain Mainnet',
                  networkId: 56,
                  chainId: 56,
                  url: 'https://bsc-dataseed.binance.org/'
              },
              'istanbul',
          );

...some other code

var transaction = new Tx(rawTransaction, { 'common': BSC_FORK });

throws error:
(node:7040) UnhandledPromiseRejectionWarning: TypeError: Common.custom is not a function

**Comment by jochem-brouwer** [comment]
What version of node/ts-node are you using? I cannot reproduce this on ts-node v9.1.1.

**Comment by rsmith2002** [comment]
> What version of node/ts-node are you using? I cannot reproduce this on ts-node v9.1.1.

C:\Users\Reece Smith>node -v
v14.18.1

**Comment by jochem-brouwer** [comment]
This is related to #978.

Try using this for your imports;

```javascript
import _Common from '@ethereumjs/common'
let Common = _Common.default```

It is ugly, but it should work.

**Comment by rsmith2002** [comment]
> This is related to #978.
> 
> Try using this for your imports;
> 
> ```js
> import _Common from '@ethereumjs/common'
> const Common = _Common.default
> ```
> 
> It is ugly, but it should work.

I think this worked, no longer getting errors due to it seeming to be depreciated. Since I am getting errors elsewhere not associated with this I can't test out the part using common further down in the code but I presume that should work too.

**Comment by jochem-brouwer** [comment]
Great! I will close here, if there are still issues then please re-open 😄
