### ISSUE TITLE
Unnecessary enforcing `esModuleInterop` for users of the package 

### ISSUE THREAD

**Issue by nazarhussain** [ethereumjs/ethereumjs-monorepo#1615]
Currently the `BN` package imported as default import causing the users of the ethereumjs to always enable `esModuleInterop` in their projects. 

https://github.com/ethereumjs/ethereumjs-monorepo/blob/0c7bdfcdf5866fc31df2b87508156f3294bbae45/packages/util/src/externals.ts#L7

This is not necessary if we fix the import syntax as. 

```
import * as BN from 'bn.js'
```

The error log: 

```
./../node_modules/ethereumjs-util/dist/constants.d.ts:2:8 - error TS1259: Module '"/web3.js/node_modules/@types/bn.js/index"' can only be default-imported using the 'esModuleInterop' flag

2 import BN from 'bn.js';
         ~~

  ../../node_modules/@types/bn.js/index.d.ts:594:1
    594 export = BN;
```

**Comment by nazarhussain** [comment]
For reference: https://github.com/ChainSafe/web3.js/pull/4607/files#r768699324

**Comment by ryanio** [comment]
I'm open to changing this if there aren't any other objections or anticipated downsides.

Thanks @nazarhussain. Would you like to open a PR, or I can?

This is the way bn.js sets its exports ([link](https://github.com/indutny/bn.js/blob/4187ca213e91b41acf72be046072f2dc1f06d0de/lib/bn.js#L42)):

```js
  if (typeof module === 'object') {
    module.exports = BN;
  } else {
    exports.BN = BN;
  }
```

**Comment by nazarhussain** [comment]
Seems like the right change. @ryanio Go ahead and open the PR if you have time.

**Comment by ryanio** [comment]
@nazarhussain I started to work on this PR but when I change the import to your suggestion I get this error:
> Type originates at this import. A namespace-style import cannot be called or constructed, and will cause a failure at runtime. Consider using a default import or import require here instead.

To take its suggestion, an alternative could be to use `import BN = require('bn.js')`?

**Comment by ryanio** [comment]
i will be opening an ESM PR for develop today that will disable esModuleInterop by default to solve this issue for downstream users
