### ISSUE TITLE
READMEs of vm/examples/* are out of date

### ISSUE THREAD

**Issue by Ainevsia** [ethereumjs/ethereumjs-monorepo#1622]
Do i need to update them in order to run the examples for those without any prior knowledge?

**Comment by ryanio** [comment]
@Ainevsia they should be up-to-date, is there something in particular that you noticed is wrong or missing? Make sure to run "npm install" in the example folder you are interesting in running.

**Comment by Ainevsia** [comment]
I noticed that `packages/vm/examples/decode-opcodes/README.md` states that I should `run npm run build:dist in the root of this project`, but I can't find any command named `build:dist` in any folder.

**Comment by Ainevsia** [comment]
By the way, I cannot compile the `index.ts` file in the `decode-opcodes` folder because my `tsc` complains about some missing type annotations. I have to manually add some extra type annotations before I can finally run this example demo.

**Comment by ryanio** [comment]
ah you are right, sorry about that, will open a PR to fix now, you can try the new branch and let me know if it works for you

**Comment by holgerd77** [comment]
Guess we really should tackle https://github.com/ethereumjs/ethereumjs-monorepo/issues/1574, this would prevent breakages like this one.
