### ISSUE TITLE
rlp: v3.0.0 release

### ISSUE THREAD

**Issue by ryanio** [ethereumjs/ethereumjs-monorepo#1628]
The current plan is to merge this repository into [ethereumjs-monorepo](https://github.com/ethereumjs/ethereumjs-monorepo), test integration of the new version within the monorepo, and if all goes well, release v3.0.0.

The alternative would be to do a rc or beta release in this repository for some testing before a proper release, however since we plan to bring rlp into the monorepo and test the integration there, I think we can be confident 3.0.0 will be ready after that is accomplished.

I will start the process to bring this repository into the monorepo today.

**Comment by paulmillr** [comment]
Seems like we are ready for the release?

**Comment by ryanio** [comment]
@paulmillr I would like to test the new version in the monorepo first to see if there are any issues, I don't anticipate there to be, but can be much more confident to release v3 after an internal integration with all existing tests/ci passing.

I've started a WIP PR at https://github.com/ethereumjs/ethereumjs-monorepo/pull/1630, have to finish for the night, but will pick up tomorrow. Let me know if there are any suggestions you may have there to simplify or improve. Thanks!

**Comment by paulmillr** [comment]
I think this can be closed now
