### ISSUE TITLE
Common: Execute on all Deprecation Notes for Breaking Release

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1633]
Part of #1024

Target branch: `develop`
Please assign if interested.

There are various deprecation notes in the [Common](https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/common) library, search for the "deprecated" tag in the `src` folder.

These should be executed upon.

This would encompass:

1. Completely remove deprecated `forCustomChain()` constructor method, eventual tests + all references in docs
2. Rename all *BN methods to their non-BN names (so e.g. `hardforkBlockBN` -> `hardforkBlock`), these the BN returning methods should become the default now. The associated code should be taken from the BN methods and the original non-BN returning in-calling methods should be removed (we switched over from `number` to `BN` on certain occurrences due to the JavaScript number limit to 53bits). This will need several adoptions in the upstream monorepo libraries (VM, client, other)
3. Remove `chains/index.ts` file and internalize the function `_getInitializedChains()` into the main `index.ts` file (I am only 90% sure on this execution). The `chainsType` export should be removed completely along.
4. Also not 100% sure, but I guess `genesisStates/index.ts` can also be removed completely

**Comment by ScottyPoi** [comment]
I think i've fixed this but I know I messed up in the way i committed changes.  So they may already be committed to depoly branch (sorry!).

else they are in this branch: https://github.com/ethereumjs/ethereumjs-monorepo/tree/Fix-for-PR-%231633

**Comment by holgerd77** [comment]
Closed by #1698 and #1709
