### ISSUE TITLE
Monorepo: Next Minor Release Round

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1635]
The next minor release round is at the doorstep, various libraries are up for releases with substantial feature additions, release roughly planned for within the next 1-3 weeks (base date: Saturday, January 15 2022). Depends a bit if there are last things to discuss or take in.

This is somewhat of a tracking issue for myself and also for making the process transparent and let people chime in if they have a request.

Currently I would plan for the following releases (just citing the most significant changes here for some overview, will properly link to the PRs in an upcoming release PR):

- RLP
  - Not sure: should there be a `v2.2.7` -> `v2.2.8` release? (mainly with https://github.com/ethereumjs/rlp/pull/109 I guess) 

- Trie `v4.2.2` -> `v4.2.3`
  - Deduped RLP dependency

- Util `v7.1.3` -> `v7.1.4`
  - RLP dedupe
  - validateNoLeadingZeroes()
  - new constants
  - negative BN checks

- Common `v2.6.0` -> `v2.6.1`
  - Sepolia
  - EIP-3855 (Push0)

- Tx `v3.4.0` -> `v3.5.0`
  - 2^64-1 value checks
  - EIP-2681
  - Sepolia
  - Tx integer leading zero checks
  - Throw on negative BN

- Block, Blockchain
  - Cautiously I would say no releases needed

- devp2p `v4.2.0` -> `v4.2.1`
  - Dedupe RLP dependency

- VM `v5.6.0` -> `v5.7.0`
  - Dynamic Gas Cost Refactoring
  - StateManager refactoring (BaseStateManager)
  - Proof State Manager (discuss `ProofStateManager` interface exposure!!)
  - EIP-2681 (Limit account nonce to 2^64-1)
  - EIP-3607 (Reject transactions from senders with deployed code)
  - EIP-3855 (Push0)
  - Sepolia
  - Tx out-of-gas consensus issue
  - Jump Dest Analysis Refactoring
  - Throw on negative BN
  
- Client `v0.2.0` -> `v0.3.0`
  - Client releases now always necessary (at least on minor), otherwise: side effects!
    - -> But: also makes sense in general! 🙂 
  - This (a client release) would need a general consistency check (maybe we should standardize a bit)!
  - ReceiptsManager, save receipts and logs (to re-confirm: this doesn't need a DB delete + fresh sync, right?)
  - Sepolia
  - Allow past block numbers in RPC queries
  - Fixed mainnet consensus bug (see VM)
  - Libp2p fixes
  - Error logging fixes/improvements
  
  Ok, so far for a high-level overview.
  
  Phew, this impresses me each and every time again how extensive this gets when writing this together. 😀
  
  Let me know if you agree with the extend of releases, the version numbers chosen (eventually some of this can rather be discussed in chat to not bloat here too much), also if you think I missed some major features to mention here (I didn't list all the smaller things yet) since then there might be a chance that I've really overlooked some older PR which took some time to finish.

**Comment by ryanio** [comment]
> ReceiptsManager, save receipts and logs (to re-confirm: this doesn't need a DB delete + fresh sync, right?)

Correct, there were no changes to the other dbs (chainDB, stateDB), only new one added called metaDB, so there should be no problems there.

**Comment by holgerd77** [comment]
@ryanio do we need to do an RLP release? 🤔

**Comment by holgerd77** [comment]
@ryanio ah, and also second question: how realistic is this, that we might get an ESM build into this release round? 🤔  From what you wrote in #1632 there seems to be a lot of unchartered territory still so I would assume it rather won't go in? Would you agree or are you more optimistic on that (so we can very well delay for up to a week I would say for that, but also not much more)?

**Comment by ryanio** [comment]
@holgerd77 it is still a bit uncharted, but I can give a new PR a start today or tomorrow and try to quickly fix/update everything it complains about, and if it's doable, then we can consider it, and if there are still obscure errors to fix, maybe we hold off, but it would be really neat to ship our releases with esm support.
