### ISSUE TITLE
kintsugi: docker-compos up error

### ISSUE THREAD

**Issue by jakrypto** [ethereumjs/ethereumjs-monorepo#1644]
Hi,

whenever I try to _docker-compose --file docker-compose.ethereumjs.yml up_ in /packages/client/kintsugi/ I receive the following error.

> Recreating ethereumjs_client ... done
> Attaching to ethereumjs_client
> ethereumjs_client          | Error: ENOENT: no such file or directory, open '/usr/app/ethereumjs-monorepo/packages/client/kintsugi/genesis.json'
> ethereumjs_client          |     at Object.openSync (node:fs:585:3)
> ethereumjs_client          |     at readFileSync (node:fs:453:35)
> ethereumjs_client          |     at run (/usr/app/ethereumjs-monorepo/packages/client/dist/bin/cli.js:572:68)
> ethereumjs_client          |     at Object.<anonymous> (/usr/app/ethereumjs-monorepo/packages/client/dist/bin/cli.js:629:1)
> ethereumjs_client          |     at Module._compile (node:internal/modules/cjs/loader:1101:14)
> ethereumjs_client          |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
> ethereumjs_client          |     at Module.load (node:internal/modules/cjs/loader:981:32)
> ethereumjs_client          |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
> ethereumjs_client          |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
> ethereumjs_client          |     at node:internal/main/run_main_module:17:47 {
> ethereumjs_client          |   errno: -2,
> ethereumjs_client          |   syscall: 'open',
> ethereumjs_client          |   code: 'ENOENT',
> ethereumjs_client          |   path: '/usr/app/ethereumjs-monorepo/packages/client/kintsugi/genesis.json'
> ethereumjs_client          | }
> ethereumjs_client exited with code 0

**Comment by ryanio** [comment]
Ah, genesis.json is in the config folder in kintsugi now, I will update in my PR, thanks for reporting.
