### ISSUE TITLE
Upgrade ethereum-cryptography to 1.0

### ISSUE THREAD

**Issue by paulmillr** [ethereumjs/ethereumjs-monorepo#1668]
Hey folks, we've finally released ethereum-cryptography 1.0: https://github.com/ethereum/js-ethereum-cryptography

I think this could be a tracking issue for the monorepo upgrade process?

Note that we've made it extremely easy to upgrade. It contains exactly three incompatibilities:

1. We return `Uint8Array` from all methods that worked with `Buffer` before
2. We target runtimes with `bigint` support, which is Chrome 67+, Edge 79+, Firefox 68+, Safari 14+, node.js 10+
3. Users of `ethereum-cryptography/secp256k1` should rename import to `ethereum-cryptography/secp256k1-compat`. There is no immediate urge in switching to `noble-secp256k1` abstractions, we provide a compatibility layer for old code and do integration testing

**Comment by paulmillr** [comment]
@ryanio @holgerd77 this seems to be a simple change. Are there any caveats? E.g. should this be done to develop branch?

**Comment by holgerd77** [comment]
Yes, to manage expectations here, we can only do this in within the range of our next round of breaking releases, and these are still some months away. So this would be work to be done towards the `develop` branch, yes.
