### ISSUE TITLE
VM: Analyze rustbn.js native implementation possibility

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1672]
The ﻿﻿[rustbn.js](https://github.com/ethereumjs/rustbn.js) is rather somewhat of a submodule of the VM and is used for the [ECADD](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/vm/src/evm/precompiles/06-ecadd.ts), `ECMUL` and `ECPAIRING` precompiles.

This is realized as a WASM precompile from Rust and there is atm no one to really maintain this library.

Since this decision to go this way (and the subsequent implementation) has been made 4 years ago along the [Byzantium](https://eips.ethereum.org/EIPS/eip-609) hardfork implementation we might want to re-analyze the current native JS library situation and if more direct/native integration in the VM is possible.

Otherwise it might also be useful to integrate the package into the monorepo (it's rather not much code + no tests to be run I guess).

**Comment by jochem-brouwer** [comment]
So the question is either we move the WASM into our repo, or we write this ourselves in JS?

**Comment by axic** [comment]
> This is realized as a WASM precompile from Rust and there is atm no one to really maintain this library.

Well, the thing is it required no changes, hence no updates to it.

**Comment by axic** [comment]
Could consider using iden3's webassembly implementation (https://github.com/iden3/wasmsnark), if this is still driven by the licensing question. It is not a drop-in replacement though.

**Comment by holgerd77** [comment]
@axic thanks, that helps a lot! We'll be more cautious here on an eventual decision.

**Comment by holgerd77** [comment]
Will close this after the feedback from @axic
