### ISSUE TITLE
Address that EIP-3607 is always activated

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/ethereumjs-monorepo#1686]
https://github.com/ethereumjs/ethereumjs-monorepo/blob/543422fec2127f65ee734ea51e8df20dc9287ae4/packages/vm/src/runTx.ts#L303-L307

EIP-3607 is always activated, there is no way to disable this. 

Possible fixes:

1. Add option to VM to disable the EIP
2. Disable the EIP by default, read if the option is enabled from Common

CC @alcuadrado

**Comment by holgerd77** [comment]
I guess we more or less already settled on opion 2. in the call?

If someone could pick this up quickly (optimally: today) and submit a PR that would be great, then we can publish a quick bugfix release.

For some context: task is mainly to add a new EIP (so: EIP-3607) to `Common` as an EIP file (with no association to any hardfork whatsoever) and then guard mainly/solely the functionality implemented in this commit https://github.com/ethereumjs/ethereumjs-monorepo/pull/1568/commits/2e92010224a172d50afa044bc19b624a29047b44 (part of #1568) with a respective EIP check.

Additionally there should be at least one test in the VM (not sure, might be already there and might then needs some modification) to see if both an activation and a deactivation of the EIP would work as expected.

**Comment by ryanio** [comment]
I can do this shortly, this morning 👍
