### ISSUE TITLE
Split all hardforks into EIPs

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/ethereumjs-monorepo#1687]
Older hardforks currently have all EIPs "baked in": at VM level we do checks if common is currently at that hardfork or at a later hardfork (`gteHardfork`) and then execute logic. 

It is cleaner to instead re-write all this logic as EIP-based logic. Then we check if the EIP is activated and execute the logic. At common, this means that older hardforks like Byzantium / SpuriousDragon etc. now have an EIP list of activated ones.

**Comment by holgerd77** [comment]
I would tend to not do this since ressources in the team are constrained and benefit/cost relation seems not strong enough to justify the effort.

**Comment by holgerd77** [comment]
I will close this for the feeling that this is too much work for not enough benefit, since disabling old EIPs which are already well-established has little use cases and for the newer EIPs we now have this in place for some time now.

Feel free to re-open if the need rearises.
