### ISSUE TITLE
Large bundle size due to genesisStates/mainnet.json

### ISSUE THREAD

**Issue by sterlu** [ethereumjs/ethereumjs-monorepo#1695]
While analyzing our bundle, I realized there's a single file in the @ethereumjs/common at `genesisStates/mainnet.json` taking up over 600KB. Unfortunately, the @ethereumjs/common package seems to be required by @ethereumjs/tx so it's impossible to remove. Are there any recommendations regarding this? Perhaps decoupling the large files might be a good idea since it's a package that a lot of other packages depend on?

Possibly related: #1673

**Comment by holgerd77** [comment]
Hi there, thanks for reporting! This will close-to-for-sure be a breaking change and not sure yet if we can/will do, but have written up a proposal on this here #1696.

**Comment by sterlu** [comment]
Thanks for the quick reply! I'll be following #1696

**Comment by holgerd77** [comment]
Will close the issue here, guess #1696 is enough.

**Comment by sterlu** [comment]
By the way, in case someone has a similar issue, I worked around this by making webpack ignore imports of the genesisState files using Webpack's IgnorePlugin. 
```js
new webpack.IgnorePlugin({
  resourceRegExp: /genesisStates\/[a-z]*\.json$/,
  contextRegExp: /@ethereumjs\/common/,
});
```

**Comment by JunlinZhu-Tommy** [comment]
Any updates?

**Comment by acolytec3** [comment]
> Any updates?

The genesis states were moved to `blockchain` as part of our breaking releases back in September.
