### ISSUE TITLE
Tx: add Ethereum/tests TransactionTests

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/ethereumjs-monorepo#1701]
Ethereum/tests has a TransactionTests directory: https://github.com/ethereum/tests/tree/develop/TransactionTests

It would be nice to add these tests - it is especially interesting to see if we invalidate all invalid transactions.

**Comment by ryanio** [comment]
We are running them in the tx package :) see https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/tx/test/transactionRunner.ts#L32

**Comment by jochem-brouwer** [comment]
Oh great, fake news :joy: 

I was not aware that we were running those! Will close.

**Comment by holgerd77** [comment]
Hehe. 😋
