### ISSUE TITLE
VM: Implement EVM Object Format (EOF) (EIP-3540)

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1704]
[EIP-3540](https://eips.ethereum.org/EIPS/eip-3540) is long in the making and moved to CFI (Considered-for-Inclusion) for the `Shanghai` HF with strong developer backing in [ACD 131](https://github.com/ethereum/pm/issues/459) (February 4, 2022), so this should be safe to implement on our side as well.

The EIP introduces a container format for EVM bytecode which allows for validation of this code at the time of deployment (pros and cons of deployment vs. runtime validation in the EIP). This will allow to more easily add new features to the EVM and deprecate existing feature and/or bytecodes.

For the VM we need to implement the switches from the [Code Validation](https://eips.ethereum.org/EIPS/eip-3540#code-validation) section from the EIP for contract creation txs and `CREATE` or `CREATE2` instructions, likely to happen somewhere in/around the [evm._executeCreate()](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/vm/src/evm/evm.ts#L296) method.

For EOF(1) identified bytcode the [validation rules](https://eips.ethereum.org/EIPS/eip-3540#validation-rules) need to be applied. There are also some changes to the VM [execution semantics](https://eips.ethereum.org/EIPS/eip-3540#changes-to-execution-semantics) which needs to be considered, e.g. things need to run on `code` (e.g. "JUMPDEST analysis is only run on the code.") and not the whole container thing.

Test for this EIP are in the works here: https://github.com/ethereum/tests/pull/847

Two additional implementation notes:

1. Work should very likely be done towards `master`, do not expect anything breaking here
2. Please do not introduce a new HF `shanghai` here yet (or assign this functionality) - too early in the process - but limit to an EIP which can be activated or not

**Comment by cbrzn** [comment]
I would love to eventually do this :-) (If there's no rush :P)

**Comment by holgerd77** [comment]
> I would love to eventually do this :-) (If there's no rush :P)

Sorry, I've already assigned Andrew. 🙂

**Comment by acolytec3** [comment]
I'm going to also implement [EIP3670](https://eips.ethereum.org/EIPS/eip-3670) as a companion to this since it is intended to go in at the same time as 3540 and build a PR on top of #1719.
