### ISSUE TITLE
unable to sign transaction with new update.

### ISSUE THREAD

**Issue by nileshpanhale** [ethereumjs/ethereumjs-monorepo#1710]
Hello all,

I am sending token transfer transactions to rinkeby with the below code snippet. It was working before. But now its not working. Request you all to please help me to resolve this error.

`const Web3 = require('web3');
const ETx = require('@ethereumjs/tx').Transaction;
const web3 = new Web3(new Web3.providers.HttpProvider('https://rinkeby.infura.io/v3/0eefca2527d44b9589a...'));

const contractAddr = '0x269cfae3a28eb1...';
const contractABI = [...];

const contract = new web3.eth.Contract(contractABI, contractAddr);

const owner = "0xDB514fa071F5EE05...";
const privateKey = "3cde59ab831a8845aeb2e6...";

async function Transfer(receiver, amt) {

    let nonce = await web3.eth.getTransactionCount(owner);
    const amount = web3.utils.toHex(amt);
    const transferFunction = contract.methods.transfer(receiver, amount).encodeABI();
    const NetworkId = await web3.eth.net.getId();

    const rawTx = {
        "from": owner,
        "to": contractAddr,
        "data": transferFunction,
        "nonce": nonce,
        "value": "0x00000000000000",
        "gasLimit": web3.utils.toHex(210000),
        "gasPrice": web3.utils.toHex(90000000000),
        "chainId": NetworkId
    };
    
    let transaction = new ETx(rawTx, { chain: "rinkeby", hardfork: "petersburg" });

    const pvt = Buffer.from(privateKey, 'hex');
    transaction.sign(pvt);

    web3.eth.sendSignedTransaction("0x" + transaction.serialize().toString("hex"), async (err, hash) => {
        if (err) {
            console.log(err);
        }
        else {
            console.log(`${amt} tokens sent successfully from ${sender} to ${receiver}`);
            console.log("hash ", hash);
            return hash;
        }
    });
};`

while calling this function, received the below error.
Error: Returned error: transaction could not be decoded: unsigned transactions not supported

Smart contract is working fine. 
Npm module versions : 
"@ethereumjs/tx": "^3.4.0",
"web3": "^1.7.0"

**Comment by acolytec3** [comment]
>transaction.sign(pvt);

`sign` returns a new signed transaction object and does not modify the original `transaction`. You need to store the result from `transaction.sign` and pass that new signed `transaction` object to `web3`

**Comment by ryanio** [comment]
will close this for now, thanks @acolytec3 for answering so quickly :) @nileshpanhale let us know if you have any other issues

**Comment by nileshpanhale** [comment]
> > transaction.sign(pvt);
> 
> `sign` returns a new signed transaction object and does not modify the original `transaction`. You need to store the result from `transaction.sign` and pass that new signed `transaction` object to `web3`

Tried this. not working.

**Comment by jochem-brouwer** [comment]
What is your updated code, and what is the error?

**Comment by acolytec3** [comment]
Can you provide any details on what exactly you did differently and if it's a different error message this time? Your code above showed you passing an unsigned transaction to web3 which generated the error message I would expect.
