### ISSUE TITLE
VM: Is there a way to have `runTx({...})` skip transaction signature checking?

### ISSUE THREAD

**Issue by cd1m0** [ethereumjs/ethereumjs-monorepo#1711]
I have a use case where I need to invoke `runTx()` with txs from certain accounts for which I don't have keys. Is there a way to have `runTx()` either skip checking the signature, or accept unsigned transactions? Or even accept an invalid signature? Something similar to how `ganache --unlock 0xABCD...` works?

Thanks!
Dimo

**Comment by ryanio** [comment]
Hey there, yes all you should need to do is override the `tx.getSenderAddress()`, check out the example [here](https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/tx#fake-transaction)

**Comment by ryanio** [comment]
I will close this for now, but let me know if you run into any issues or have any more questions.
