### ISSUE TITLE
Monorepo: Limit ES2020 Support to BigInt

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1729]
For our v6 releases #1717 we are planning a wider BigInt support for our libraries and are therefore lifiting up the TypeScript [compilation target](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/config/tsconfig.json) to [ES2020](https://en.wikipedia.org/wiki/ECMAScript#11th_Edition_%E2%80%93_ECMAScript_2020) which is a huge step especially for our browser target coming from [ES5](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/config/tsconfig.browser.json).

If I get this right users are *not* able to further compile this down to lower ECMAScript versions. So we need to self-restrict on minimally other ES2020 and likely also lower-version-features and not use in our libraries respectively remove, since we likely do not want to limit our user base for some side-syntactic-sugar features, which didn't make it into all browsers yet. Also to note here is that BigInt has been adopted by browsers relatively easy.

So I guess we need to go down feature-by-feature to at least ES2018/2019 and see what we would need to remove from our code base (I guess in doubt: everything else).

We also need to see how we enforce this not to be re-introduced, e.g. for the nullish coalescent operator (this is a bit of a pity, no drama though as well) there is an ESLint rule [es/no-nullish-coalescing-operators](https://eslint-plugin-es.mysticatea.dev/rules/no-nullish-coalescing-operators.html).

There might be alternative ways to go here, for TypeScript I haven't found a way for a more selective compilation/transpilation (might have overlooked something though), we might also want to think if we want to add a more complex build pipeline (not sure, would this be able to solve the problem? 🤔)

**Comment by ryanio** [comment]
I guess I'm confused, if we minimally support bigint for our next major releases then es2020 support is required so what is the benefit of removing use of the other es2020 features?

**Comment by holgerd77** [comment]
Browsers do not switch over and support "ES2020" by one switch-over but they start adding these features one-by-one. So BigInt was implemented relatively early on and is supported in Chrome 67 onwards (see [caniuse](https://caniuse.com/?search=bigint) page) (which would likely be a good target browser to settle on given that we have the ok for Metamask).

For other ES2020 features (and eventually also older ECMAScript features) the situation is very different, for e.g. nullish coalescent operator is only [supported in Chrome 80](https://caniuse.com/?search=bigint) (!) an upwards.

So if we would have a code base with this combination *and* people are not able to further transpile down this would mean that the code base is only used in the highest minimal supported browser version. So we need to go through features one by one and either remove e.g. nullish coalescing operator usage from our code base entirely - or find another solution.

Richard is doing the same respectively he said that he would only (solely) support BigInt and none of the other ES2020 features.

Sorry, I guess this would have been clear, think I've raised this on times but might be a bit on the side line (or correct me if I am misinterpreting something here).

**Comment by ryanio** [comment]
Oh I see, thanks for explaining, I thought they were all added at a time, but piecemeal is more challenging!

According to [this answer](https://stackoverflow.com/a/59787575) we should be able to specify a lower target while including `es2020.bigint` in `lib` so it is included. Hopefully in that case we don't have to remove the extra features from our actual TS code and instead just have it down leveled like in our current ES5 setup.

Node 12 is reaching EOL in April and Node 14 has full es2020 support so I guess this decision is more important for browser compatibility then.

**Comment by holgerd77** [comment]
Closed by #1734
