### ISSUE TITLE
Block: Rework fromHeaderData() and main BlockHeader constructor

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1738]
Part of #1717 

The static constructors for the Block and Tx libraries (like `Block.fromBlockData()`, Block.fromValuesArray(),...) have been introduced along the last breaking release round in November 2020 (e.g. [Block v3.0](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Fblock%403.0.0).

While we aligned the main constructor and the `from*Data()` constructor method in the tx library in an additional iteration (see e.g. for the [legacy tx](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/tx/src/legacyTransaction.ts#L35)) (so basically: we got this right) by having the constructor take in the same data dictionary as the `from*Data()` constructor (which is then simply an alias), we missed this opportunity in the `Block` library for the `BlockHeader`.

So a `BlockHeader` object should take in the same `headerData` dictionary for the main constructor as being taken in `fromHeaderData()` and the latter should be made just an alias for the main constructor. Along the default value setting should be moved over to the main constructor (this needs to be aligned with the `fromValuesArray()` instantiation.

**Comment by gabrocheleau** [comment]
Should we close this since https://github.com/ethereumjs/ethereumjs-monorepo/pull/1787 was merged in?
