### ISSUE TITLE
Util: Deprecation Tasks

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1745]
Part of #1717 

Following deprecations on Util are uncritical and it can be executed upon:

- Remove the whole `object.ts` module (so the complete file)
- Remove deprecated `bnToRlp()` method

Other deprecations are around signature functionality or BN/BigInt and should rather be done along the respective dedicated task executions.

**Comment by acolytec3** [comment]
Addressed by #1809
