### ISSUE TITLE
Add option to tx to decode txs from unknown chains.

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/ethereumjs-monorepo#1759]
Situation: you get a tx RLP, but you do not know which chain this comes from. It is currently impossible to decode this tx, because in the constructor of each tx `getCommon` https://github.com/ethereumjs/ethereumjs-monorepo/blob/c842a973bc8058df71cda140fe0720292e1aafe1/packages/tx/src/baseTransaction.ts#L346 is called, and if the provided common does not match the chain Id then it will throw. You will have no way knowing what the chain Id was (it is also not in the error message).

We should probably add a flag to the constructor where we ignore this chain id check. We should then also add a method `getChainId` (this is for legacy txs as for EIP2930/EIP1559 you can directly read the `chainId` field) to return the chain Id. This leads to (1) it is now possible to decode txs from unknown origins and (2) it is possible to figure out what the origin was (the chain id). 

Steps:

- [ ] Change error message https://github.com/ethereumjs/ethereumjs-monorepo/blob/c842a973bc8058df71cda140fe0720292e1aafe1/packages/tx/src/baseTransaction.ts#L346  to also include the reported chain id and the chain id on Common
- [ ] Add a flag `skipChainIdCheck` (defaults to false) to ignore the chain id check.
- [ ] Add a `getChainId` abstract method to `baseTransaction` and add these methods to legacy and EIP2930/EIP1559 transactions (the last 2 are trivial, just reads to `chainId`).

**Comment by holgerd77** [comment]
Maybe I am overlooking something (I know you had some longer discussion on this already in the chat). But this error message is only activated if a `Common` is actually **provided** on instantiation. `Common` in tx is [optional](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/tx/src/types.ts#L51) and if no `Common` is provided the `_getCommon` method actually tries to [initialize a Common with the chain ID provided](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/tx/src/baseTransaction.ts#L353).

So this should be what is asked for here or am I missing something? 🤔

For legacy txs - where no chain ID can be read from the tx itself - I am not 100% sure, there [this](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/tx/src/baseTransaction.ts#L371) code part should get activated and I would assume that a tx is created in this context without error message as well, but eventually having a not correct chain ID in Common (which can't be avoided I guess).

**Comment by jochem-brouwer** [comment]
Hi @holgerd77 thanks for digging into this, I completely missed this.

I just checked what happens for legacy txs, it also works there as well:

```typescript
import {
  TransactionFactory,
  Transaction,
} from '../src'

const pkey = Buffer.from(('04').repeat(32), 'hex')

const txData = {
    value: 10
}

// Tx from Rinkeby
let eip1559TxRLP = '02f86b04778260918301a4d182f38594000000000000000000000000000000000000aaaa8403e6c7f380c001a05e40977f4064a2bc08785e422ed8a47b56aa219abe93251d2b3b4d0cf937b8c0a071e600cd15589c3607bd9627314b99e9b5976bd427b774aa685bd0d036b1771e'
const tx = TransactionFactory.fromSerializedData(Buffer.from(eip1559TxRLP, 'hex'))
console.log(tx.common.chainId()) // 4

const common = tx.common

const leg = Transaction.fromTxData(txData, { common })
const legSig = leg.sign(pkey)
const txFrom = TransactionFactory.fromSerializedData(legSig.serialize())

console.log(txFrom.common.chainId()) // 4
```

I think we can close here, sorry for missing this.
