### ISSUE TITLE
Common: Update EIP status fields, VM: move EIP-2315 to EXPERIMENTAL state

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1773]
The `status` field in the [EIP files](https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/common/src/eips) in `Common` has gotten a bit forgotten. We should go through each EIP file and update to the latest status from the different EIP specs, eventually (likely) with some additional other clean-up (switch to finalized EIP URLs (so: this format https://eips.ethereum.org/EIPS/eip-3675)), update descriptions and the like.

For the VM we have concluded that we should move [EIP-2315](https://eips.ethereum.org/EIPS/eip-2315) support back to `EXPERIMENTAL` (so: I guess basically adopt EIP comment block in VM `index.ts`), being still in `DRAFT` status and an eventual HF inclusion still somewhat far away.

**Comment by ryanio** [comment]
The hardfork files similarly have a "status" field

**Comment by jochem-brouwer** [comment]
The common part is updated, but 2315 is not moved to experimental in VM per #1777

**Comment by holgerd77** [comment]
Ah, I've just done this as part of #1774, will close again here.
