### ISSUE TITLE
rlp decode example does not work

### ISSUE THREAD

**Issue by shafu0x** [ethereumjs/ethereumjs-monorepo#1832]
Running `rlp decode 0xc88363617483646f67` returns `["636174","646f67"]` for me not `["cat","dog"]`.

What is this format and how do I return the actual string?

**Comment by SharifElfouly** [comment]
Ok, so this seems to be a simple hex encoding. But shouldn't the function return the actual string as described in the example?

**Comment by ryanio** [comment]
hey @SharifElfouly thanks for reporting, you are indeed right we are just returning the hex strings in the cli interface.

to return the string representation, I replaced this line:

https://github.com/ethereumjs/ethereumjs-monorepo/blob/7a3549aed58836adfaf03bcb64bac4384096afc0/packages/rlp/bin/rlp#L50

with

```javascript
return new TextDecoder().decode(ba)
```

Which works:

```bash
❯ bin/rlp decode 0xc88363617483646f67
["cat","dog"]
```

However then we can't decode simple numbers, like [this](https://github.com/ethereum/tests/blob/0e8d25bb613cab7f9e99430f970e1e6cbffdbf1a/RLPTests/rlptest.json#L54-L57):

```json
"mediumint1": {
    "in": 128,
    "out": "0x8180"
  },
```

```bash
❯ bin/rlp encode 128
0x8180
❯ bin/rlp decode 0x8180
"�"
```




so I'm not sure what's the best approach here.
@paulmillr do you have any thoughts?
