### ISSUE TITLE
Verifying transactionsRoot in a block header

### ISSUE THREAD

**Issue by Shandin17** [ethereumjs/ethereumjs-monorepo#1847]
Hello! Your library is really awesome!
However, is it possible to use your package to check transactionsRoot in the block header?
What I'm trying to do: 
1. grep the block by using web3.getBlock (sorry for web3 :D)
2. grep hashes of transactions list from it 
3. push this list as bottom level of a new tree
4. obtain the root of it 
5. transacionRoot === Obtained Root?

So the problem can probably be specified as:
- How to create a new tree with already hashed nodes at the bottom?
- Maybe there are other more optimal ways to obtain transactionRoot?)))

**Comment by Shandin17** [comment]
> 
Thank you very much!!! So I could repeat this process and the only thing left for me to do is figure out how to grep the raw transaction hexes from the node or calculate it by myself and then build a trie from it.

**Comment by ryanio** [comment]
@Shandin17 yes, but the block rpc response should give you the transactionsRoot already, recalculating it would only be necessary if you are adding or removing to it, which would also change other fields for the block (hash, stateRoot, receiptsRoot, etc)

**Comment by Shandin17** [comment]
@ryanio yes, it's kind of obvious)
 The problem is that I'm solving a problem where the data provider is abstract, it might not be the node's rpc response. 
 So for proofing of data integrity (Im creating database of transactions) I need to compare the **transactionsRoot** from the block header with the root which i create from the transactions.
Unfortunately, the only fields I am guaranteed to know are the hash of the transaction, transactionsRoot and indexes of transactions in the block. I don't have fields like max_fee_per_gas, trans. type and so on. So I guess I need to start building a trie from already hashed transactions.

**Comment by jochem-brouwer** [comment]
Given that information you can indeed calculate the transaction trie root!

**Comment by Shandin17** [comment]
@jochem-brouwer Yeah..why is there always so much work to do when you wanna do something quickly. Trying to rebuild a reference mechanism so it would just use pre-hashed values and not keccak(value) addresses. 
Maybe you have any thoughts... wishes?

**Comment by holgerd77** [comment]
Will close this issue here, feel free anyone to still give additional advice.
