### ISSUE TITLE
Snap sync issue tracker

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/ethereumjs-monorepo#1848]
This issue is to track implementing Geth's snap sync into the client. This issue will most likely get updated a lot.

High level plan:

1. Implement snap protocol into client
2. Implement a way to get state root from snapshot
3. Setup Geth with a small test network (Sepolia), and freeze this chain (do not support dynamic snapshots first, which moves along with the chain as it updates), i.e. `geth --sepolia` and when it is synced (it has the snapshot) `geth --sepolia --nodiscover`
4. Use snap protocol + db to download the snapshot and when this is done, retrieve the state root and verify
5. TODO: extra steps to upgrade to dynamic snapshots (i.e. we can follow a live chain)

Semi-related is to switch to using snap for beam sync.

Handy URLs:

- [Ask about Geth: Snapshot acceleration](https://blog.ethereum.org/2020/07/17/ask-about-geth-snapshot-acceleration/)
- [Geth snap sync release, v1.10.0](https://blog.ethereum.org/2021/03/03/geth-v1-10-0/)
- [devp2p snap protocol](https://github.com/ethereum/devp2p/blob/master/caps/snap.md)
- [Geth state snapshot code](https://github.com/ethereum/go-ethereum/tree/master/core/state/snapshot)
- [Geth snap/1 protocol](https://github.com/ethereum/go-ethereum/blob/d8ff53dfb8a516f47db37dbc7fd7ad18a1e8a125/eth/protocols/snap)

**Comment by jochem-brouwer** [comment]
#1876

**Comment by scorbajio** [comment]
#1893

**Comment by scorbajio** [comment]
Closing this and continuing on #2874.
