### ISSUE TITLE
client: TxPool tx validation

### ISSUE THREAD

**Issue by ryanio** [ethereumjs/ethereumjs-monorepo#1850]
Currently our TxPool implementation is rather simple and doesn't include tx validation checks that other tx pools have to ensure validity with consensus.

These should be added so our users can receive the error first (e.g. when using RPC via `eth_sendRawTransaction`) rather than accepting and other nodes rejecting upon broadcast.

Validation checks to add:

- [x] tx nonce is greater than sender's current nonce
- [x] tx doesn't exceed the current block gas limit
- [x] sender has enough funds to cover the costs (cost == V + GP * GL)
- [x] tx supplies enough intrinsic gas
- [x] replacement tx's gas must be 10% higher to replace (if not, error as underpriced replacement)
- [x] reject txs with data over a defined max size (to prevent DOS attacks, not a consensus validation)
- [x] make sure tx is properly signed
- [x] error if tx is already known in the pool
- [x] error if the tx pool is full and can't accept another remote tx
  - (local txs should be prioritized and accepted even when remote pool is full)

I can work on this, I just wanted to open an issue to start tracking.

For reference, geth: [tx_pool.go](https://github.com/ethereum/go-ethereum/blob/master/core/tx_pool.go), [tx_list.go](https://github.com/ethereum/go-ethereum/blob/master/core/tx_list.go)

**Comment by jochem-brouwer** [comment]
I'm gonna assign this one to me, it has been too long since I had a rather deep look into `client`, and I am also not very aware about our TxPool so that's a great exercise :smile:

**Comment by ryanio** [comment]
ok, cool! i know you have a lot going on, so no rush, i am also happy to work on this :)
