### ISSUE TITLE
Client Signer Setup

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1871]
On a similar realm like #1870 taking into account that the client usage is getting more serious we should give our signer setup some strategic thinking. Should this remain in the client or rather extracted for security reasons? What are successful (secure) setups other clients have? Are there somewhat best practices to secure users PKs?

**Comment by ryanio** [comment]
In the best case scenario we should be able to support communicating with external signers like [`clef`](http://adam.schmideg.net/go-ethereum/clef/Overview), however I'm not sure how many people would use this option today so I'm not sure if it's worth spending the time to implement. This would be great for separating concerns and not needing to handle production PKs in the client.

We currently support PK through command line prompt and external file. These are useful for developer scenarios, e.g. the external file PK option was added for hive (CI) support.

**Comment by ryanio** [comment]
another popular signer I have seen is [Web3Signer](https://docs.web3signer.consensys.net/en/latest/)

**Comment by holgerd77** [comment]
Outdated, will close.
