### ISSUE TITLE
Block: Low-Level Validation Method Refactor

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1879]
This is a (relatively) modest proposal to refactor the Block validation methods and logic as one of the last bigger tasks on the way to the breaking releases. Major outcome would be that we would free ourself from the problematic (and in some sense circular) `Blockchain` dependency and that subclassing of `Block` or `Header` for consensus specific customizations would get easier.

Lots of little tasks which will sum up to - hopefully - a consistent set of improvements:

### BlockHeader

- [ ] `_validateHeaderFields()` called in the constructor should be renamed to `_genericFormatValidation()`
- [ ] `Header.validate()`:
  - [ ] The first upper consensus-specific checks are misplaced here since these are just static format checks as well. These should be moved to a separate `_consensusFormatValidation()` method called from the constructor after `_genericFormatValidation()`. This also allows for easier consensus-specific replacement on subclassing
  - [ ] The rest of the `validate()` functionality (Including the following consensus-specific checks) should be moved to a new method in the `Blockchain` class `validateBlockHeader(header: BlockHeader, height)`
- [ ] The `validateDifficulty()` and `validateCliqueDifficulty()` methods should be unified to `validateDifficulty()` with appropriate consensus checks
  - [ ] Subtask: same for the `Block` class

### Block

- [ ] `validateUncles()`: method should be moved to `Blockchain` as `validateBlockUncles(block: Block)`
  - [ ] Same with private `_validateUncleHeaders()` method called from within the above method
- [ ] `validate()`: method can be removed without replacement
- [ ] Bonus task: The `onlyHeader` param on the `validateData()` method is a bit quirky, wonder if this can be removed along the refactoring (or in general)?
- [ ] TBD - also on th `validateData()` method: this method is a bit the corresponding method to `_genericFormatValidation()` in `BlockHeader` if I am not mistaken. I wonder if we should align here and a) remove this method (respectively rename to private `_genericFormatValidation()`) and then call from the constructor? 🤔

### Generic

- [ ] Remove `@ethereumjs/blockchain` dependency (good check if nothing gots forgotten)

I think @emersonmacro would be a good candidate for this task, since he already dealt with the `Blockchain` refactoring and this is going somewhat along the same line. 🙂 Haven't got a confirmation from him though yet if he is available and think this fits.

**Comment by holgerd77** [comment]
Additional context and transparency note here: this is *somewhat* related to #1044 - e.g. regarding aspects of the consensus encapsulation.

The #1044 was references by the following section in the v6 Breaking Release Planning note doc at #1717:

"Better separation on general format validations ("invalid block number, not subsequent"), invalid consensus format validations (timestamp for Clique) and consensus validation itself, likely rename functions (-> validateConsensus() or the like). Related issue: https://github.com/ethereumjs/ethereumjs-monorepo/issues/1044"

I've now removed the above section from the TODO list since I think this is sufficiently covered (for now or in general, not sure yet) by this new issue here and also regarding that we want to close in on the releases and simplify and decide on where we want to make practical cuts.

If someone disagrees here let me know respectively drop a note here.

**Comment by emersonmacro** [comment]
@holgerd77 I ran into a small issue with the Block `validateData()` -> `_genericFormatValidation()` refactor: you mentioned renaming it to `_genericFormatValidation()` and moving the call to the constructor, but validating the transactions trie requires an `await`. Any thoughts/suggestions on how to handle?

I think I have every other subtask taken care of (except removing the `@ethereumjs/blockchain` dependency), so this `validateData()` refactor is essentially the last thing to figure out.

**Comment by holgerd77** [comment]
> @holgerd77 I ran into a small issue with the Block `validateData()` -> `_genericFormatValidation()` refactor: you mentioned renaming it to `_genericFormatValidation()` and moving the call to the constructor, but validating the transactions trie requires an `await`. Any thoughts/suggestions on how to handle?
> 
> I think I have every other subtask taken care of (except removing the `@ethereumjs/blockchain` dependency), so this `validateData()` refactor is essentially the last thing to figure out.

Ah, I guess we then just leave the method "as is", also the name (which also fits here well since the block format is more given in the header, this is really rather the block data).

Seems not worth to me to think about a larger restructuring with making the static constructors async and stuff - as we have in other libraries. This would also re-draw in all these problems if people then using the main constructor and things are not awaiting, this gets quickly pretty nasty.

**Comment by holgerd77** [comment]
(especially so late in our overall (release) process)
