### ISSUE TITLE
Tx: Throw when hash() is called on unsigned legacy txs

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1890]
Part of #1717 

Very small remaining breaking-release task:

Throw when `hash()` is called on unsigned legacy txs (so: align with behavior from typed txs), see also comment added along with #1445.

So if one is looking at e.g. the EIP-1559 Tx `hash()` function, the function throws if tx not signed, for the legacy tx this is not the case.

Will assign @ScottyPoi since he asked for a small EthereumJS task. 🙂

**Comment by ScottyPoi** [comment]
Can this be closed?
