### ISSUE TITLE
Parameter CHECK_BLOCK_HEADER for BSC

### ISSUE THREAD

**Issue by bpbogdanpop** [ethereumjs/ethereumjs-monorepo#1907]
In the peer communication example there are a few parameters to update for BSC.

I have done some bits already (custom chain).

However, I'm having trouble with the following:

`const CHECK_BLOCK_TITLE = '17093771' // Only for debugging/console output
const CHECK_BLOCK_NR = 17093771
const CHECK_BLOCK = 'f9bc3a1327e8107759fdf12053cc641ccac9aee98c3ccfb2b5e48bd014868c87'
const CHECK_BLOCK_HEADER = rlp.decode(
  bf
)`

I've already completed block number and block hash. But it also asks for block header, and that's where I'm not sure what to put.

**Comment by holgerd77** [comment]
This is not an issue but a support question (for a chain we do not support), I would close here, please continue and eventually expand on the discussion over on the issue where you already posted https://github.com/ethereumjs/ethereumjs-monorepo/issues/1394#issuecomment-1136559350, you can also use our Discord to ask if there is someone willing to help.
