### ISSUE TITLE
eip 1559 rawtx recover sender / pubkey problem in browser

### ISSUE THREAD

**Issue by kropple** [ethereumjs/ethereumjs-monorepo#1908]
i was using old version of ethereumjs-tx like this:

[test.html.txt](https://github.com/ethereumjs/ethereumjs-monorepo/files/8768342/test.html.txt)

with an old rawTX it nicely gives me address and pubkey.

with a EIP 1559 transaction it fails with some big error message.

can somebody please direct me how to do this with the new version of ethereumjs ? i couldnt find any examples or hints :(

it was so nice simply including that one little file and have this function so quickly.

thanks a lot

**Comment by ryanio** [comment]
The old version of `ethereumjs-tx` was before London so it can't support 1559 txs. Please use the latest `@ethereumjs/tx`, and if you need it for the browser you need to run browserify on the files first to make the bundled output that you can import in the browser.

**Comment by kropple** [comment]
> 

thats where i struggle. could you hint me to how to do this exactly?

**Comment by holgerd77** [comment]
Will close here for now, feel free to reopen if necessary.
