### ISSUE TITLE
Error: Returned error: only replay-protected (EIP-155) transactions allowed over RPC on polygon mumbai

### ISSUE THREAD

**Issue by MeganathanTraxx** [ethereumjs/ethereumjs-monorepo#1922]
when I try with rinkeby and kovan it's working fine, but when I try with polygon mumbai its throws this error **Error: Returned error: only replay-protected (EIP-155) transactions allowed over RPC** I have configured custom chain properly even though it says same error

Im using infura RPC

```
    const txParams: TxData = {
        nonce: await web3.eth.getTransactionCount(ethAddr),
        gasPrice: '0x0918400000',
        gasLimit: 160000,
        to: '0x0000000000000000000000000000000000000000',
        value: '0x00',
        data: '0x00',
        r: sig.r.toBuffer(),
        s: sig.s.toBuffer(),
        v: recoveredPubAddr.v,
    }

    const tx = Transaction.fromTxData(txParams, {
      common: Common.custom(CustomChain.PolygonMumbai, { hardfork: Hardfork.London })
    });
```

**Comment by ryanio** [comment]
You need to sign the tx and not use an existing signature since the v value has the chain id encoded for EIP-155

**Comment by MeganathanTraxx** [comment]
Im using KMS for signing the transaction, it's working fine with rinkeby ad kovan
issue happening only with polygon

**Comment by MeganathanTraxx** [comment]
@ryanio I have signed the transaction using KMS, and Im using  for **getMessageToSign(true)** this same code working fine with rinkeby and kovan even the transaction also succeed, but when I try with polygon it saying this error  **Error: Returned error: only replay-protected (EIP-155) transactions allowed over RPC**

Please let me your inputs regarding this

**Comment by holgerd77** [comment]
@MeganathanTraxx I guess you are not producing a EIP-155 tx via this KMS service (do not personally know), so you need to find out how to produce a signature conforming to EIP-155, so this would be a `v` value >= 37, depending on the chain ID.

**Comment by MeganathanTraxx** [comment]
Im not getting clearly, you mean the **v** value should differ based on chainId

Im checking the **v** value should be 27 or 28 below is my code
`import { KMS } from "aws-sdk";
import { keccak256 } from "js-sha3";
import * as ethutil from "ethereumjs-util";
import { Transaction, TxData } from "@ethereumjs/tx";
import Common, { CustomChain, Hardfork } from "@ethereumjs/common";
import { BN } from "ethereumjs-util";
import { ethers } from "ethers";

const asn1 = require("asn1.js");

const kms = new KMS({
  accessKeyId: "<access-key>", // credentials for your IAM user with KMS access
  secretAccessKey: "<secret-key>", // credentials for your IAM user with KMS access
  region: "us-east-1",
  apiVersion: "2014-11-01",
});

const keyId = "<key-id>";

const EcdsaSigAsnParse = asn1.define("EcdsaSig", function (this: any) {
  // parsing this according to https://tools.ietf.org/html/rfc3279#section-2.2.3
  this.seq().obj(this.key("r").int(), this.key("s").int());
});

const EcdsaPubKey = asn1.define("EcdsaPubKey", function (this: any) {
  // parsing this according to https://tools.ietf.org/html/rfc5480#section-2
  this.seq().obj(
    this.key("algo").seq().obj(this.key("a").objid(), this.key("b").objid()),
    this.key("pubKey").bitstr()
  );
});

async function sign(msgHash: any, keyId: any) {
  const params: KMS.SignRequest = {
    // key id or 'Alias/<alias>'
    KeyId: keyId,
    Message: msgHash,
    // 'ECDSA_SHA_256' is the one compatible with ECC_SECG_P256K1.
    SigningAlgorithm: "ECDSA_SHA_256",
    MessageType: "DIGEST",
  };
  const res = await kms.sign(params).promise();
  return res;
}

async function getPublicKey(keyPairId: string) {
  return kms
    .getPublicKey({
      KeyId: keyPairId,
    })
    .promise();
}

function getEthereumAddress(publicKey: Buffer): string {
  console.log("Encoded Pub Key: " + publicKey.toString("hex"));

  // The public key is ASN1 encoded in a format according to
  // https://tools.ietf.org/html/rfc5480#section-2
  // I used https://lapo.it/asn1js to figure out how to parse this
  // and defined the schema in the EcdsaPubKey object
  let res = EcdsaPubKey.decode(publicKey, "der");
  let pubKeyBuffer: Buffer = res.pubKey.data;

  // The public key starts with a 0x04 prefix that needs to be removed
  // more info: https://www.oreilly.com/library/view/mastering-ethereum/9781491971932/ch04.html
  pubKeyBuffer = pubKeyBuffer.slice(1, pubKeyBuffer.length);

  const address = keccak256(pubKeyBuffer); // keccak256 hash of publicKey
  const buf2 = Buffer.from(address, "hex");
  const EthAddr = "0x" + buf2.slice(-20).toString("hex"); // take last 20 bytes as ethereum adress
  console.log("Generated Ethreum address: " + EthAddr);
  return EthAddr;
}

async function findEthereumSig(plaintext: any) {
  let signature = await sign(plaintext, keyId);
  if (signature.Signature == undefined) {
    throw new Error("Signature is undefined.");
  }
  console.log("encoded sig: " + signature.Signature.toString("hex"));

  let decoded = EcdsaSigAsnParse.decode(signature.Signature, "der");
  let r: BN = decoded.r;
  let s: BN = decoded.s;
  console.log("r: " + r.toString(10));
  console.log("s: " + s.toString(10));

  let tempsig = r.toString(16) + s.toString(16);

  let secp256k1N = new BN(
    "fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141",
    16
  ); // max value on the curve
  let secp256k1halfN = secp256k1N.div(new BN(2)); // half of the curve
  // Because of EIP-2 not all elliptic curve signatures are accepted
  // the value of s needs to be SMALLER than half of the curve
  // i.e. we need to flip s if it's greater than half of the curve
  if (s.gt(secp256k1halfN)) {
    console.log(
      "s is on the wrong side of the curve... flipping - tempsig: " +
        tempsig +
        " length: " +
        tempsig.length
    );
    // According to EIP2 https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2.md
    // if s < half the curve we need to invert it
    // s = curve.n - s
    s = secp256k1N.sub(s);
    console.log("new s: " + s.toString(10));
    return { r, s };
  }
  // if s is less than half of the curve, we're on the "good" side of the curve, we can just return
  return { r, s };
}

function recoverPubKeyFromSig(msg: Buffer, r: BN, s: BN, v: number) {
  console.log(
    "Recovering public key with msg " +
      msg.toString("hex") +
      " r: " +
      r.toString(16) +
      " s: " +
      s.toString(16)
  );
  let rBuffer = r.toBuffer();
  let sBuffer = s.toBuffer();
  let pubKey = ethutil.ecrecover(msg, v, rBuffer, sBuffer);
  let addrBuf = ethutil.pubToAddress(pubKey);
  var RecoveredEthAddr = ethutil.bufferToHex(addrBuf);
  console.log("Recovered ethereum address: " + RecoveredEthAddr);
  return RecoveredEthAddr;
}

function findRightKey(msg: Buffer, r: BN, s: BN, expectedEthAddr: string) {
  // This is the wrapper function to find the right v value
  // There are two matching signatues on the elliptic curve
  // we need to find the one that matches to our public key
  // it can be v = 27 or v = 28
  let v = 27;
  let pubKey = recoverPubKeyFromSig(msg, r, s, v);
  if (pubKey != expectedEthAddr) {
    // if the pub key for v = 27 does not match
    // it has to be v = 28
    v = 28;
    pubKey = recoverPubKeyFromSig(msg, r, s, v);
  }
  console.log("Found the right ETH Address: " + pubKey + " v: " + v);
  return { pubKey, v };
}

txTest();
async function txTest() {
  const eth = new ethers.providers.JsonRpcProvider(
    "https://polygon-mumbai.infura.io/v3/<api-key>"
  );

  let pubKey = await getPublicKey(keyId);
  let ethAddr = getEthereumAddress(pubKey.PublicKey as Buffer);
  let ethAddrHash = ethutil.keccak(Buffer.from(ethAddr));
  let sig = await findEthereumSig(ethAddrHash);
  let recoveredPubAddr = findRightKey(ethAddrHash, sig.r, sig.s, ethAddr);

  const txParams: TxData = {
    nonce: await eth.getTransactionCount(ethAddr),
    gasPrice: "0x0918400000",
    gasLimit: 160000,
    to: "0x0000000000000000000000000000000000000000",
    value: "0x00",
    data: "0x00",
    r: sig.r.toBuffer(),
    s: sig.s.toBuffer(),
    v: recoveredPubAddr.v,
  };

  const tx = Transaction.fromTxData(txParams, {
    common: Common.custom(CustomChain.PolygonMumbai, {
      hardfork: Hardfork.London,
    }),
  });

  let txHash = tx.hash();
  sig = await findEthereumSig(txHash);
  recoveredPubAddr = findRightKey(txHash, sig.r, sig.s, ethAddr);

  const copyTxParams: TxData = {
    nonce: await eth.getTransactionCount(ethAddr),
    gasPrice: "0x0918400000",
    gasLimit: 160000,
    to: "0x0000000000000000000000000000000000000000",
    value: "0x00",
    data: "0x00",
    r: sig.r.toBuffer(),
    s: sig.s.toBuffer(),
    v: new BN(recoveredPubAddr.v).toBuffer(),
  };

  const tx1 = Transaction.fromTxData(copyTxParams, {
    common: Common.custom(CustomChain.PolygonMumbai, {
      hardfork: Hardfork.London,
    }),
  });

  console.log(tx1.getSenderAddress().toString());

  // Send signed tx to ethereum network
  const serializedTx = tx1.serialize().toString("hex");

  const data = await (await eth.sendTransaction("0x" + serializedTx)).wait();
  console.log(data);
}
`

**Comment by MeganathanTraxx** [comment]
this is the error when I execute this code

![image](https://user-images.githubusercontent.com/100118001/171153991-ccf6942f-6acb-4ff4-bd2c-7ec5423451ff.png)
![image](https://user-images.githubusercontent.com/100118001/171154048-924cac4e-5712-475a-9fe2-cb5dda4867b7.png)

**Comment by holgerd77** [comment]
Have a look at [EIP-155](https://eips.ethereum.org/EIPS/eip-155) to know what I mean.

**Comment by MeganathanTraxx** [comment]
I have looked into the EIP-155 and I followed the same pattern but it doesn't work, even I try with custom - xDaiChain it's working but not working with polygon-mumbai

**Comment by ryanio** [comment]
@MeganathanTraxx thanks for sharing your code. you see in `findRightKey` where you are getting your `v` value, it only returns 27 or 28.

Now look at EIP-155:

> If you do, then the v of the signature MUST be set to {0,1} + CHAIN_ID * 2 + 35 where {0,1} is the parity of the y value of the curve point for which r is the x-value in the secp256k1 signing process. If you choose to only hash 6 values, then v continues to be set to {0,1} + 27 as previously.

So try setting v to `(findRightKey().v - 27) + CHAIN_ID * 2 + 35`. For Mumbai chain id is `80001`

Possibly the other chains you are testing with accept pre-eip-155 transactions. I would find that weird that only Mumbai is enforcing it, but I'm not sure without digging deeper.

**Comment by MeganathanTraxx** [comment]
@ryanio oh man you are awesome, yup for other chains are accepting pre-eip-155
for polygon mumbai, I followed the same way of calculating the **v** value that you suggest and it's working fine

thank you so much for your help

**Comment by holgerd77** [comment]
@MeganathanTraxx Ok, great that this could be solved! You can transfer the EthereumJS support fee of $200 in ETH to the following Ethereum address: 1234567ETHerEuMJS89101112ISAWSOME131415. 😂 😂 😂

Thanks for taking in our services! 😜
