### ISSUE TITLE
devp2p: deduplicate `secp256k1` and `keccak` dependencies

### ISSUE THREAD

**Issue by ryanio** [ethereumjs/ethereumjs-monorepo#1934]
The devp2p package uses its own dependencies for `secp256k1` and `keccak`.

These should ideally be deduplicated and use `ethereum-cryptogrpahy/keccak` and `ethereum-cryptography/secp256k1` like the rest of the monorepo on the `develop` branch.

**Comment by ScottyPoi** [comment]
I have this mostly worked out.
There's one method from `ethereum-cryptography` for which I can't produce the same results as we get from `secp256k1`

This is in `rlpx/ecies.ts`

```
function ecdhX(publicKey: Buffer, privateKey: Buffer) {
  function hashfn(x: Uint8Array, y: Uint8Array) {
    const pubKey = new Uint8Array(33)
    pubKey[0] = (y[31] & 1) === 0 ? 0x02 : 0x03
    pubKey.set(x, 1)
    return pubKey
  }
  // @ts-ignore
  return Buffer.from(ecdh(publicKey, privateKey, { hashfn }, Buffer.alloc(33)).slice(1))
}
```

Replacing this:
```
import {ecdh } from 'secp256k1'
```
With this:
```
import {  ecdh } from 'ethereum-cryptography/secp256k1-compat'
```
Gives a similar method, which works with some tweaking, but causes a few tests to fail like this:
```
    operator: throws
    expected: |-
      undefined
    actual: |-
      [Error: should have valid tag: 42670be82545bddbd98525ba99f3ee36cf343e213844aa901c646f0488ac5840 / e2d5b5340c9e488eefea198576344afbdf66db5f51204a6961a63ce072c8926c]
    at: <anonymous> (/ethereumjs-monorepo/packages/devp2p/test/rlpx-ecies.ts:132:7)
```

The error is coming from that `ecdhX` method

**Comment by paulmillr** [comment]
@ScottyPoi could you please write an exact input that produces different outputs between these two `ecdh` functions, without the need to run tests?

**Comment by ScottyPoi** [comment]
Thanks @paulmillr -- but I managed to work out what was happening with that.  Just had to tweak the way the hash function was working.
```
function ecdhX(publicKey: Buffer, privateKey: Buffer) {
  function hashfn(x: Uint8Array, y: Uint8Array) {
    const pubKey = new Uint8Array(33)
    pubKey[0] = (y[31] & 1) === 0 ? 0x02 : 0x03
    pubKey.set(x, 1)
    return pubKey
  }
  return Buffer.from(ecdh(publicKey, privateKey, { hashfn }, Buffer.alloc(33)).slice(1))
}
```
changed to 
```
function ecdhX(publicKey: Buffer, privateKey: Buffer) {
  function hashfn(x: Uint8Array, y: Uint8Array) {
    const pubKey = new Uint8Array(33)
    pubKey[0] = (y[31] & 1) === 0 ? 0x02 : 0x03
    pubKey.set(x, 1)
    return pubKey.slice(1)
  }
  return Buffer.from(ecdh(publicKey, privateKey, { hashfn }, Buffer.alloc(32)))
}
```
Fixed that function.

**Comment by ScottyPoi** [comment]
The last use of the `keccak` package left is in `rlpx/mac.ts`.

The method `createKeccakHash` from `keccak` returns a Transform object with methods like `digest()` and `update()`
While `ethereum-cryptography/keccak` just the hash function:  `keccak256(msg: Uint8Array) => Uint8Array`

The code in `rlpx/mac.ts` hooks into the Transform API, using the  digest() and update() and clone() methods.  If we do want to remove the `keccak` dependency, we may have to rewrite some of `rlpx/mac.ts`

**Comment by paulmillr** [comment]
BTW, in the underlying package, it's done with `keccak256.create().update().digest()`. We've decided to not expose this API in eth-crypto. What would be the best way to expose this one particular method?

**Comment by ScottyPoi** [comment]
> BTW, in the underlying package, it's done with `keccak256.create().update().digest()`. We've decided to not expose this API in eth-crypto. What would be the best way to expose this one particular method, naming-wise?

I'm not sure what you mean.
We use both `digest()`  and `update()` methods from the `Keccak` class

```
  updateHeader(data: Buffer | string) {
    const aes = createCipheriv('aes-256-ecb', this._secret, '')
    const encrypted = aes.update(this.digest())
    this._hash.update(xor(encrypted, data))
  }
```
and 
```
  digest() {
    return this._hash._clone().digest().slice(0, 16)
  }
```









> BTW, in the underlying package, it's done with `keccak256.create().update().digest()`. We've decided to not expose this API in eth-crypto. What would be the best way to expose this one particular method, naming-wise?

**Comment by paulmillr** [comment]
I'm saying that keccak from ethereum-cryptography uses noble-hashes, which have very similar API: keccak256.create().update(data).digest(). It also has clone ability. 

It is not exposed in ethereum-cryptography, but it is there, you can view noble-hashes source for sha3.

So the question is how should the api in ethereum-crypto look like. Should we just expose .create(), but if we do that, it will expose it for all hashes.

**Comment by ScottyPoi** [comment]
Is there a reason not to expose these methods in the first place?   Like do we lose anything by exposing create() ?

**Comment by paulmillr** [comment]
The goal was to make function APIs same. @alcuadrado thoughts?

**Comment by alcuadrado** [comment]
Sorry I missed this. I think it makes sense to add that API if you need it.

We may want to make it more different from node's `.create().update().digest()`, as it has to be subtly different otherwise (i.e. we don't use `Buffer`). I believe making it notably different will be less confusing.

**Comment by ScottyPoi** [comment]
When #1947 is merged I believe this issue can close
