### ISSUE TITLE
Additional lint rules to consider

### ISSUE THREAD

**Issue by ryanio** [ethereumjs/ethereumjs-monorepo#1935]
After working in the monorepo extensively, I compiled some ESLint rules that should help improve dev ex, code quality and style.

These are nothing urgent or breaking and can be picked up over time. (These rules should be added to the top-level `config/eslint.js` to automatically be included in all packages.)

* [x] [strict-boolean-expressions](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/strict-boolean-expressions.md) https://github.com/ethereumjs/ethereumjs-monorepo/pull/2030
* [ ] [require-await](https://eslint.org/docs/rules/require-await) Extracted to https://github.com/ethereumjs/ethereumjs-monorepo/issues/2156 due to its size
* [x] [import-sort-order](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md) https://github.com/ethereumjs/ethereumjs-monorepo/pull/2086
* [x] [object-shorthand](https://eslint.org/docs/rules/object-shorthand) https://github.com/ethereumjs/ethereumjs-monorepo/pull/2131
* [x] [array-foreach](https://github.com/github/eslint-plugin-github/blob/main/docs/rules/array-foreach.md) https://github.com/ethereumjs/ethereumjs-monorepo/pull/2130
* [x] [no-sparse-arrays](https://eslint.org/docs/rules/no-sparse-arrays) included via `eslint:recommended`

**Comment by ryanio** [comment]
nothing breaking, also nothing super urgent, just some suggestions to improve code quality/style, can be done over time 👍

**Comment by gabrocheleau** [comment]
+1 [strict-boolean-expressions](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/strict-boolean-expressions.md), would have caught an issue that I just spent quite a bit of time troubleshooting :)

**Comment by ryanio** [comment]
Here's some of my preferred config, hardhat's [eslintrc rules](https://github.com/NomicFoundation/hardhat/blob/master/config/eslint/eslintrc.js) are a great resource.

```js
    "@typescript-eslint/consistent-type-imports": "error",
    "import/order": [
      "error",
      {
        alphabetize: {
          order: "asc",
        },
        groups: [
          "object",
          ["builtin", "external"],
          "parent",
          "sibling",
          "index",
          "type",
        ],
        "newlines-between": "always",
      },
    ],
    "sort-imports": ["error", { ignoreDeclarationSort: true }],
    '@typescript-eslint/strict-boolean-expressions': [
      'error',
      {
        allowString: false,
        allowNumber: false,
        allowNullableObject: false,
        allowAny: false,
      },
    ],
```

**Comment by ryanio** [comment]
another good one: [`@typescript-eslint/prefer-nullish-coalescing`](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/prefer-nullish-coalescing.md)

**Comment by holgerd77** [comment]
> Enabling the `@typescript-eslint/strict-boolean-expressions` rule with a strict config is quite a headache in the current state of the repository because of the `isTruthy` and `isFalsy` functions and the mixed use of `null` and `undefined` rather than sticking with `undefined` since `null` is generally regarded as a mistake.

So guess then we would want to get rid again of the `isTruthy` and `isFalsy` functions again in a first step (which we would want to do anyhow)?

For `undefined`/`null` can you clarify in what circumstances should this be regarded as a mistake? Likely not for all cases where we use `null`? Maybe/optimally you can give two examples, one with a "false" use case and one with a fitting one?

**Comment by holgerd77** [comment]
> @holgerd77 [no-sparse-arrays](https://eslint.org/docs/rules/no-sparse-arrays) doesn't result in any changes yet and I remember you said we should only add rules that result in an actual change. Does that still stand?

If we don't inflate I guess there is nothing to be said to add selected and reasoned additional ones, so I would be ok with that.

**Comment by acolytec3** [comment]
Is there any value to keep this open at this point? We've addressed basically all of the open rules.

**Comment by jochem-brouwer** [comment]
I think we should close this one, but nevertheless review (new) ESLint rules anyways. (We can discuss on the call)

**Comment by holgerd77** [comment]
Ok, would agree to both of you, will close.
