### ISSUE TITLE
Monorepo: Remove dist.browser Builds

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1966]
The `dist.browser` builds should be removed for the breaking releases (optimally before Beta 1 release, latest before Beta 2 release) since there is now no difference in the builds any more with going up to `ES2020`, see related meta issue #1946 

It should be carefully checked that all appearances of this are removed in the monorepo (e.g. by using fulltext search), e.g. in `.gitignore` files and the like.

Also, the client browser will likely need some different treatment (keep the folder, remove the separate build options? Just a first shot though.).

**Comment by holgerd77** [comment]
This would still be urgent and optimally done before Beta 1.

**Comment by g11tech** [comment]
addressed via https://github.com/ethereumjs/ethereumjs-monorepo/pull/1985
