### ISSUE TITLE
Let validator allow eth_call to test creation code

### ISSUE THREAD

**Issue by qwerty472123** [ethereumjs/ethereumjs-monorepo#1987]
The validator check field by 

https://github.com/ethereumjs/ethereumjs-monorepo/blob/74d5937b115d419a7d3fd697bc9c321355204a33/packages/client/lib/rpc/validation.ts#L199

and eth_call require `to` field

https://github.com/ethereumjs/ethereumjs-monorepo/blob/74d5937b115d419a7d3fd697bc9c321355204a33/packages/client/lib/rpc/modules/eth.ts#L318

The only way to let `to` be undefined(not a address) is

https://github.com/ethereumjs/ethereumjs-monorepo/blob/74d5937b115d419a7d3fd697bc9c321355204a33/packages/client/lib/rpc/modules/eth.ts#L452

The only way to test _executeCreate is let `!!to` be false.

https://github.com/ethereumjs/ethereumjs-monorepo/blob/74d5937b115d419a7d3fd697bc9c321355204a33/packages/evm/src/evm/evm.ts#L815

That is to say only `!!to` is allowed by validator, but it should allow one value that `!to` to test creation code.

**Comment by holgerd77** [comment]
@g11tech can you judge if this is an issue here?

**Comment by g11tech** [comment]
> @g11tech can you judge if this is an issue here?

ok will do!

**Comment by qwerty472123** [comment]
> > @g11tech can you judge if this is an issue here?
> 
> ok will do!
> 
> @qwerty472123 if i re-phrase this issue: you want to do `eth_call` without providing `to` and this validation is throwing error and hence not allowing you to do so?

Yes, I want to use `eth_call` to simulate the execution of a transaction that creates a contract.

Based on my experience in using go-ethereum and my rough reading of ethereumjs, I think it is necessary to provide a `null` `to` value (or without providing `to`) to achieve this, and the validator of ethereumjs does not allow me to do so.

**Comment by g11tech** [comment]
hey @qwerty472123 can you check it this works for you branch: `g11tech/eth-call-create` PR: https://github.com/ethereumjs/ethereumjs-monorepo/pull/2084

**Comment by qwerty472123** [comment]
> hey @qwerty472123 can you check it this works for you branch: `g11tech/eth-call-create` PR: #2084

i think this pr has achieved the function I expected. thx
