### ISSUE TITLE
Blockchain: Add consensus Option

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1993]
We have forgotten to allow the `consensus` class being passed in as an option to the Blockchain class, just realizing this while writing the Blockchain release notes where I already wanted to write this as a sentence because I thought: "sure, that's possible now". 🤪 😅

We should add, maybe a small test for now is enough where one of the existing consensus classes is passed in from the outside.

Would eventually be nice to do before Beta 1 but no total drama if done afterwards.

**Comment by holgerd77** [comment]
Update: maybe let's *really* do before Beta 1, I will already write this in the release notes, this is actually a very small update.

**Comment by ScottyPoi** [comment]
Was this meant only for `master` branch?

**Comment by holgerd77** [comment]
Yes.
