### ISSUE TITLE
Error in runCall due to negative nonce

### ISSUE THREAD

**Issue by frangio** [ethereumjs/ethereumjs-monorepo#2009]
I'm using the beta release. I may be using this wrong.

Here's a silly example that I think should work but it doesn't:

```javascript
const vm = await VM.create();
vm.evm.runCall({ to: undefined });
```

It raises the error:

```
Error: Cannot convert string to buffer. toBuffer only supports 0x-prefixed hex strings and this string was given: 0x-1
    at toBuffer (/node_modules/@ethereumjs/util/dist/bytes.js:147:19)
    at bigIntToBuffer (/node_modules/@ethereumjs/util/dist/bytes.js:197:33)
    at EVM._generateAddress (/node_modules/@ethereumjs/evm/dist/evm.js:634:94)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async EVM.runCall (/node_modules/@ethereumjs/evm/dist/evm.js:503:40)
```

It's happening here in `evm.ts`:

```
const acc = await this.eei.getAccount(message.caller)
const newNonce = acc.nonce - BigInt(1)
addr = generateAddress(message.caller.buf, bigIntToBuffer(newNonce))
```

`acc.nonce` is `0n` which seems correct given that the caller (the zero address) is an unused account. I'm not sure why it tries to do `acc.nonce - 1`, but in this case it results in a negative integer that can't be converted to a buffer.

Given that this works through `runTx`, I'm guessing that the nonce is meant to be incremented before execution. Is this the issue?

**Comment by acolytec3** [comment]
Thank you for reporting!

>Given that this works through runTx, I'm guessing that the nonce is meant to be incremented before execution. Is this the issue?

This indeed appears to be the issue (since we're assuming the nonce has already been incremented for the calling account external to the EVM) so subtracting one from it when generating the address via `create` would seem to be the naively correct way of generating the new address.  Will research further and make sure we have a fix in place before Beta 2.
