### ISSUE TITLE
Monorepo: Make Merge Default Hardfork

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#2015]
Since we are now getting so close to the Merge HF date with our breaking releases (or might be even do *after* the Merge, we'll see) I would be a big fan of directly making the Merge HF the default HF on the libraries.

There would be a very very tiny window of where we are "ahead" (and even this wouldn't be bad), and otherwise we would be aligned with the current HF during very much most of the time of the release lifecycle. 🙂 

Inspiration and guidance for update locations can be taken from the London HF work #1749 done by @emersonmacro. I would be very much expecting though that this upgrade work is not as extensive any more (but still some work to do), since Emmett hardened e.g. various code parts like test initializations along the way (by explicitly providing a certain HF e.g.).

This doesn't need to be finished before Beta 2 but can e.g. be done if someone gets bored while I am and other are on holidays e.g.. 😅

**Comment by g11tech** [comment]
@holgerd77 can put in my bucket! :slightly_smiling_face:

**Comment by holgerd77** [comment]
> @holgerd77 can put in my bucket! 🙂

Oh, my issues really sell like hot cakes today, also #2013 gone in less than 2 hours. 😅

@g11tech Sure, cool! 👍
