### ISSUE TITLE
Client: Fix Client Hive Merge Tests

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#2036]
We are now running with the Client within the Hive Merge test suite, yay!!! 🎉

Test results are still improvable and we should slowly work down, at least the ones which make sense for us, here is an extract of the latest results:

![grafik](https://user-images.githubusercontent.com/931137/178692065-38ce66e9-2e2a-425e-8caf-9ebf54c33694.png)

I'll give this a "days, weeks, months" label, this is actually a primer, but I think everything fits here. 😋

**Comment by holgerd77** [comment]
And some of the failing tests (from the `engine` suite):

![grafik](https://user-images.githubusercontent.com/931137/178692892-d35a70ae-c058-4ae8-9e11-2d69a814265c.png)

**Comment by jochem-brouwer** [comment]
Do you know where you have found this page?

**Comment by holgerd77** [comment]
Yes, here https://hivetests.ethdevops.io/ and here https://hivetests2.ethdevops.io/, and then click on "Load".

EthereumJS tests didn't seem to have run for some time though, I only could find some entries on page 2 of the first URL.

**Comment by jochem-brouwer** [comment]
Ah right sorry should have updated the question. The tests for hivetests2 do not run, the reason is Cesar once made us run the `execution` sim, but this one has been split up / renamed to `execution-api` and some other sims (asked this on R&D). I will look into this ASAP

**Comment by acolytec3** [comment]
Do we still need this? We fixed a lot of the merge tests but a number of them address really obscure edge cases that @g11tech and I spent a while trying to fix and made only limited progress.

**Comment by jochem-brouwer** [comment]
I am rather sure that this https://github.com/ethereumjs/ethereumjs-monorepo/issues/2498 is a duplicate so will close here.
