### ISSUE TITLE
Client: Fix Client Hive Execution Tests

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#2037]
We are now running with the Client within the Hive [Execution test suite](https://hivetests.ethdevops.io/), yay!!! 🎉

Test results are still improvable and we should slowly work down, at least the ones which make currently sense for us (if this is related to some unimplemented feature: we should independently decide on that and not do the feature "for the tests" 😋). Here is an extract of the latest results:

![grafik](https://user-images.githubusercontent.com/931137/178694464-43a99ab9-f6af-4481-8fe6-af2d9eaf494a.png)

**Comment by holgerd77** [comment]
Actually, this is all super-interesting, here are some `sync` suite test results:

![grafik](https://user-images.githubusercontent.com/931137/178694872-66b30391-04c1-4315-a57b-953f06f64431.png)

(wasn't aware that this is so much cross-client for various of the test suites)

**Comment by ScottyPoi** [comment]
https://github.com/ethereum/tests#clients-using-the-library

is pointing towards https://github.com/ethereumjs/ethereumjs-vm instead of the monorepo.  

Is it possible that the `hivetests` are not testing the most up-to-date version of our client?

**Comment by fjl** [comment]
The [EthereumJS client definition](https://github.com/ethereum/hive/blob/master/clients/ethereumjs/ethereumjs.sh) in hive is missing some features, which makes a lot of tests fail.

Most failures I have seen are 'genesis hash mismatch' errors. These are a result of missing functionality in the genesis.json parser. You can run `./hive --sim smoke/genesis --client ethereumjs --docker.pull` to see some of these errors in isolation.

EthereumJS is also missing a feature to import blocks on startup. In hive tests, the client can be initialized with a `chain.rlp` file containing blocks to be imported. The test can also request the client to import blocks from a directory of rlp files. See this document for more information: https://github.com/ethereum/hive/blob/master/docs/clients.md#files.

**Comment by jochem-brouwer** [comment]
Thanks @fjl , will also link an issue and a PR;

https://github.com/ethereumjs/ethereumjs-monorepo/issues/2498

https://github.com/ethereumjs/ethereumjs-monorepo/pull/2507

**Comment by acolytec3** [comment]
We've made sufficient progress working on hive tests that it feels like this can safely be closed.
