### ISSUE TITLE
VM: Update ethereum/tests to "Tests update 11: Merge PoS"

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#2038]
A new `ethereum/tests` version has just been [released](https://github.com/ethereum/tests/releases/tag/v11) focusing on the Merge.

We should update here during the next 1-2 weeks or so.

There are actually three types of tests included, being 1. the pure State/blockchain tests for Merge HF rules (VM), 2. transition tests for ArrowGlacier -> Merge (VM as well) and 3. ArrowGlacier difficulty tests (Block).

First part 1. is likely a classical test runner update on the VM, for 2. I am not sure if this is already fully supported or if this need #1901 needs to be merged for this (maybe @jochem-brouwer can clarify), for 3. the import of the GrayGlacier testdata in `difficulty.spec.ts` in Block can now be updated to directly take in this data and the temporary local test files can be deleted again.

**Comment by ScottyPoi** [comment]
Part 3: 
```
the import of the GrayGlacier testdata in difficulty.spec.ts in Block can now be updated to directly take in this data and the temporary local test files can be deleted again.
```
Is addressed by #2052

**Comment by jochem-brouwer** [comment]
We indeed need #1901, especially since this addresses a test runner bug which makes it impossible to run transition tests. (But #1901 is now ready for review! :))

**Comment by jochem-brouwer** [comment]
I'm on part 1 and 2!

**Comment by jochem-brouwer** [comment]
Forks in tests;

```
  'Berlin',
  'Istanbul',
  'London',
  'Merge',
  'Byzantium',
  'Constantinople',
  'ConstantinopleFix',
  'EIP150',
  'EIP158',
  'Homestead',
  'Frontier',
  'ArrowGlacierToMergeAtDiffC0000',
  'BerlinToLondonAt5',
  'ByzantiumToConstantinopleFixAt5',
  'EIP158ToByzantiumAt5',
  'FrontierToHomesteadAt5',
  'HomesteadToDaoAt5',
  'HomesteadToEIP150At5'
```

**Comment by jochem-brouwer** [comment]
Part 1 and 2 are not yet done, can close if #2064 is merged.
