### ISSUE TITLE
RLP package not scoped

### ISSUE THREAD

**Issue by faustbrian** [ethereumjs/ethereumjs-monorepo#2058]
Is it intentional that https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/rlp/package.json#L2 isn't scoped to the `@ethereumjs` organisation like all other packages are now? Might be confusing to end-users if everything here is now scoped to that org but one package isn't.

**Comment by acolytec3** [comment]
We've discussed this internally a few times and the main reason to leave it unscoped was because it's a truly standalone package that's been in use as just `rlp` for a very long period of time and our user population knows it as such.  I'm not averse to changing it but would defer to @holgerd77 on this one.

**Comment by holgerd77** [comment]
I guess I would also be pro changing, given that we have already done so for MPT from `merkle-patricia-tree` (which is also somewhat a very much standalone tech implementation) *and* this is the last library non-scoped.

So I would feel it would very much make sense to align here. 🙂 Maybe some more voices on this from the team and optimally also others reading here would be nice.

**Comment by gabrocheleau** [comment]
I'm also in favor of renaming for consistency

**Comment by holgerd77** [comment]
Ok, I guess we have enough pro-changing voices here for an update, @faustbrian so happy to take in a PR on this if you want to take on this. 🙂 

You can take Gajinder's @g11tech PR https://github.com/ethereumjs/ethereumjs-monorepo/pull/1953 on `merkle-patricia-tree` -> `@ethereumjs/trie` renaming as some inspiration as well as an overview on what to change/update.
