### ISSUE TITLE
Trie values returning null after reboot?

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ethereumjs-monorepo#2061]
Following on the below discussion, we should add a new option to the base `trie` constructor to store the root hash under a `root` key in the db so it can be retrieved if a persistent DB is provided in the constructor.

### Discussed in https://github.com/ethereumjs/ethereumjs-monorepo/discussions/2056

<div type='discussions-op-text'>

<sup>Originally posted by **faustbrian** July 19, 2022</sup>
Indeed me being dense the root has to be manually restored. Maybe this could be improved by introducing a decorator like `new PersistedTrie(new SecureTrie())` which then takes care of writing the root to and reading the root from disk? Might be a nicer DX than everyone coming up with their own way of persisting the root and manually restoring it. Is there any mention in docs that it has to be restored manually?

---

So I'm attempting to use the trie package to store some persistent data that I need to access as soon as my application launches but something seems to be amiss here, probably me being dense. I'm creating a `ClassicLevel` instance that I pass to `SecureTrie`, then log that the value is `null`, then store `key` with a value of `one` and finally log that the value is `one`. That's all fine but then when I run the exact same script again `key` is again `null` instead of `one` as I would expect because in the first run we finished the script with `key` being `one` and we are using a LevelDB implementation with persistence.

```js
const { SecureTrie, LevelDB } = require('@ethereumjs/trie')
const { ClassicLevel } = require('classic-level')

const level = new ClassicLevel('./db')
const root = new SecureTrie({ db: new LevelDB(level) })

async function test() {
  // the first time we run this script this should be 'null'
  // the second time we run this script it should be 'one' (because of the 'put' call) but it isn't
  console.log(await root.get(Buffer.from('key'))) // null

  await root.put(Buffer.from('key'), Buffer.from('one'))

  console.log((await root.get(Buffer.from('key'))).toString()) // one
}

test()
```

The value can be accessed directly via Level so it is in the database. I assume it's because the root is not set after relaunching so it falls back to the `KECCAK256_RLP` value but how would the root be initialised so that all data from previous runs is accessible? Should this happen automatically or do I need to manually restore the root?

```js
try {
    console.log(await level.get(Buffer.from('401fb497d3e347e3d480e3137b1372491314d54a46f764e0bf00336649feb6c6', 'hex')));
} catch(e) {
    console.log(e)
}
```

I'm probably just being dense and not seeing what's wrong or is it right that `key` should be `null` when I run the script a second time even though the first run finished with persisting `key` with a value of `one`? Do I always have to manually restore the root?</div>

**Comment by jochem-brouwer** [comment]
Yeah, this makes a lot of sense, we should definitely add this!

**Comment by acolytec3** [comment]
I think this looks 

> Something in that direction [faustbrian@22e569e](https://github.com/faustbrian/ethereumjs-monorepo/commit/22e569eb0a7cbd4a77fc1759fc7f38b3eb966839) or did you already have an idea how to solve this?

This general direction looks good though I don't think we would want a whole new interface. @jochem-brouwer @g11tech weigh in here but my thought is just a new boolean flag in `TrieOpts` called `persistRoot` that gets stored in as a property of the `trie` like you have it.  Then, if someone wants to persist the root, they set that to `true` in the constructor and then in your `persistRoot` method, we store the root hash under the key `rootHash` or `root`.  Feels like unnecessary complexity to allow the user to provide their own key since we generally shy away from letting the library consumers have direct access to the DB without good reason.

**Comment by jochem-brouwer** [comment]
There is an edge case here which I just realized when I checked https://github.com/faustbrian/ethereumjs-monorepo/commit/22e569eb0a7cbd4a77fc1759fc7f38b3eb966839. If you would use any type of Trie (also the normal trie where we do not hash the keys before storing them) then you could thus use a key which you actually want to use in the Trie DB. So, if you would create a normal trie and would put a value at `root`, then if you would use the persistent key `root` also as the DB hash, then you would thus overwrite the value at that key. I'm not sure how we should handle this though..?

I agree with @acolytec3, it should be a boolean if you want to persist the root hash and not provide extra options like set the key (because this also adds edge cases like the case described above). I think we should default this setting to `true`? We should then also deprecate the constructor and add a static method to construct the trie. (This is breaking but we can do this at this point!)

**Comment by jochem-brouwer** [comment]
I think we should use a rather exotic key to avoid throws if user tries to put it at this value, so lets use `__persistedRootHash__` as key to avoid the edge case. Change it to a boolean should be fine I am only not confident if we should default this to `true` or not - @acolytec3 what do you think?

**Comment by acolytec3** [comment]
It should default to true if a DB is passed into the constructor and be hardcoded to false if not.  We shouldn't be doing persist operations on `memory-level` but allow the user to decide if they don't want to do it when writing to disc but have it turned on by default
