### ISSUE TITLE
Merge tracking issue

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/ethereumjs-monorepo#2066]
Tracking issue for things which need to change which I noticed in #2064 

- [ ] Rename `td` to `ttd` where appropriate. TD: total difficulty. TTD: total terminal difficulty. In `merge` hardfork this should be `ttd`, it is currently `td` (which is confusing). Inputs to most (if not all) methods in common should remain `td` #2075 
- [ ] `td` is currently of type `number` in Common, I think we should change to either string or bigint #2075 

Mainnet TD is currently larger than max safe number, so we should definitely change the type of `number` of `ttd` to either `string` or `bigint` (probably string for JSON)

**Comment by holgerd77** [comment]
> td is currently of type number in Common, I think we should change to either string or bigint

Guess bigint is a relative no-brainer here? 🤔

**Comment by g11tech** [comment]
> > td is currently of type number in Common, I think we should change to either string or bigint
> 
> Guess bigint is a relative no-brainer here? thinking

yes it needs to be bigint, and in the network jsons of the type string

**Comment by jochem-brouwer** [comment]
Ah right it is indeed a no-brainer, I suggested `string` because we import JSON files but of course we can then internally use it as `bigint`.
