### ISSUE TITLE
`hardforkByTD` in VM

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/ethereumjs-monorepo#2080]
The `hardforkByTD` option in VM should most likely be removed. This option tries setting `common` to a hardfork + blocknumber each time, but the option itself is constant and is never changed. Instead, what should be done, is that upon calling `runBlock` the `hardforkByTD` (or something similar) should be set, which then tries to transition the common in case we hit a Terminal Total Difficulty (TTD) block.

**Comment by holgerd77** [comment]
TBH I do not understand the problem set here yet. Could you give an additional short description what problem can/does arise with the current way the option is implemented respectively a scenario where this occurred? Especially since the option seemed to work well for quite some time? 🤔

**Comment by jochem-brouwer** [comment]
I don't remember anymore what the original issue was but I think this was related with the failing merge tests. Since the option is now removed this issue is not relevant anymore so will close.

**Comment by holgerd77** [comment]
For the record: this option has [not been removed](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/vm/src/types.ts#L131) from the VM.
