### ISSUE TITLE
stripHexPrefix returns undefined

### ISSUE THREAD

**Issue by adibhanna** [ethereumjs/ethereumjs-monorepo#2089]
When I pull the package to my Node app, them compiled JS code for the following functions looks like this: 

```js
exports.toChecksumAddress = function (address, eip1191ChainId) {
    address = ethjsUtil.stripHexPrefix(address).toLowerCase();
    var prefix = eip1191ChainId !== undefined ? eip1191ChainId.toString() + '0x' : '';
    var hash = hash_1.keccak(prefix + address).toString('hex');
    var ret = '0x';
    for (var i = 0; i < address.length; i++) {
        if (parseInt(hash[i], 16) >= 8) {
            ret += address[i].toUpperCase();
        }
        else {
            ret += address[i];
        }
    }
    return ret;
};
```
 
The `stripHexPrefix` is compiled to the following code
```js
module.exports = function stripHexPrefix(str) {
  if (typeof str !== 'string') {
    return str; // <----- this shouldn't return a string. 
  }

  return isHexPrefixed(str) ? str.slice(2) : str;
}
```
This is causing an issue where we end up calling `toLowerCase()` on a potentially undefined value: `address = ethjsUtil.stripHexPrefix(address).toLowerCase();`

A fix for this could just be a quick check for `undefined` values, or even throwing an Error. 
```js
 if (typeof address === 'undefined') return '';
```
Happy to create a PR for this, but wanted double check that this is an actual issue that needs addressing, and not me missing something. 

Cheers

**Comment by acolytec3** [comment]
Which version `ethereum--util` are you using?  The snippet you copied doesn't match what's in our [current master](https://github.com/ethereumjs/ethereumjs-monorepo/blob/6967774f40777d0438e8308caa5b9e3e7393f277/packages/util/src/internal.ts#L44) which is in beta or the [current published version](https://github.com/ethereumjs/ethereumjs-monorepo/blob/7b70265df025e6c2c1c689c3402de6042a28b301/packages/util/src/internal.ts#L44) which is 7.1.5.  Our current (and most recently published code) does throw an error if `str` isn't of type `string`.

I checked the `dist` directory locally as well to verify Typescript hadn't compiled it down to something funny and it's as below:
```
const stripHexPrefix = (str) => {
    if (typeof str !== 'string')
        throw new Error(`[stripHexPrefix] input must be type 'string', received ${typeof str}`);
    return isHexPrefixed(str) ? str.slice(2) : str;
};
exports.stripHexPrefix = stripHexPrefix;
```

**Comment by adibhanna** [comment]
Thank you for the quick response! 
I'm still using version `^6.1.0`, I'll upgrade to 7.1.5. Good to know that this is fixed!
