### ISSUE TITLE
Node version tests failing

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#2101]
Currently our nightly node version tests from [here](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/.github/workflows/node-versions.yml) are failing for Node 14, 16 and 18, see e.g. [this](https://github.com/ethereumjs/ethereumjs-monorepo/runs/7664048458?check_suite_focus=true) run.

Error message for all failing runs is:

```
Cannot find module '../../ethereum-tests/DifficultyTests/dfFrontier/difficultyFrontier.json'
```

So very likely something wrong along the `ethereum/tests` update or - the otherway around- with caching on the test runs, referring to some old files.

This should be fixed.

**Comment by acolytec3** [comment]
Can we at the same time also remove Node 12 from this?  I'll pick this up today.

**Comment by holgerd77** [comment]
> Can we at the same time also remove Node 12 from this?

Yes, definitely.

**Comment by holgerd77** [comment]
This is still not working, can someone please take on this issue during the week?
