### ISSUE TITLE
Tests with <Network>+EIPNumber not working

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/ethereumjs-monorepo#2106]
Test runner does not work on networks like `London+1153`, this was probably introduced in adding Merge tests PR and should be fixed.

**Comment by holgerd77** [comment]
Can we add some kind of a guard for this so (a bit like the test number count comparison for state/blockchain tests, I am not sure atm though if these are working atm TBH), so that this not gets structually lost again? 🤔

**Comment by jochem-brouwer** [comment]
The counts work!

I am not sure what you mean by a guard here, I have added tests, so this should not happen again in the future? (See the PR)

**Comment by holgerd77** [comment]
I was just reading "tests didn't work any more and no one noticed" from your initial comment/introduction here and therefore concluded that there is likely no kind of guard in place.

**Comment by jochem-brouwer** [comment]
Ah right; since we do not run these type of tests on the CI we did not notice it was failing. But the tests should guard against this problem :+1:

**Comment by holgerd77** [comment]
Ok, cool! 🙂 

What's the state of the assicated PR? Can this be updated and would be still open for review? VM API tests are currently failing?

**Comment by jochem-brouwer** [comment]
Oh whoops, I did not notice that the CI was failing, will update!

**Comment by jochem-brouwer** [comment]
OK, it failed due to newly introduced linting rules, it should pass now.

**Comment by holgerd77** [comment]
> OK, it failed due to newly introduced linting rules, it should pass now.

Ah, that makes sense, cool, will give it a go then! 👍
