### ISSUE TITLE
Consistently use `undefined` instead of mixed `null` and `undefined`

### ISSUE THREAD

**Issue by faustbrian** [ethereumjs/ethereumjs-monorepo#2158]
- https://github.com/ethereumjs/ethereumjs-monorepo/issues/1935#issuecomment-1215036381
- https://github.com/sindresorhus/meta/discussions/7
- https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines#null-and-undefined
- https://github.com/eslint/eslint/issues/6701
- https://www.youtube.com/watch?v=PSGEjv3Tqo0&t=561s

> What I mean by mistake is that generally `null` and `undefined` mean the same thing and people mostly argue semantics that `undefined` means _uninitialised_ and `null` means _currently_ unavailable but both of those are the same thing in terms of code, an empty state. It's basically the whole null-pointer billion-dollar mistake reasoning but also consistency because you don't want to introduce multiple values that have the same meaning.
> 
> This [sindresorhus/meta#7](https://github.com/sindresorhus/meta/discussions/7) is a good read and lists quite a few reasons why you should ditch `null` in your code. TypeScript itself also doesn't use `null` and denotes everything undefined with `undefined` and the Microsoft style-guide also tells developers to use `undefined`. Also a fun snippet to show how `null` can trip you up :trollface:
> 
> ```shell
> ❯ node
> Welcome to Node.js v16.16.0.
> Type ".help" for more information.
> > typeof null
> 'object'
> > typeof undefined
> 'undefined'
> ```

**Comment by gabrocheleau** [comment]
Not necessarily against this, but two things come to mind:

- To my knowledge, JSON only supports `null` and not `undefined`. Our repo is heavily reliant on .json files for configuration, testing, etc. What do you think would be the best way to handle this?
- In my view, `null` stands for "defined" empty, while `undefined` is "undefined" empty (at least that's how I try to use it). Would be good to investigate how much (if any) information loss would occur if we discard null completely in favor of undefined.
