### ISSUE TITLE
Remove unused dependencies

### ISSUE THREAD

**Issue by paulmillr** [ethereumjs/ethereumjs-monorepo#2193]
Based on @faustbrian analysis from #2190

- `buffer-xor` - (1 sub-dep) can be easily replaced with 5-line function
- `core-js-pure` - used for shimming `Set`, our targets should support `Set` as-is
- `fs-extra` - used for `ensureDirSync` in `client`, also `readFileSync` but that's available in `fs`. I would argue to replace it, since it has 3 deps, graceful-fs etc.
- `inherits`, `it-pipe`, `it-pushable`  - used as devDependency, while it's specified as prod dependency
- `miller-rabin` - (3 sub-deps) not used anywhere

**Comment by paulmillr** [comment]
unused devDeps:

- `@babel/plugin-transform-spread`, `node-fetch`, `pino-pretty`, `pull-pair`
- `node-dir` in `evm`, `tx`
- `web3` in `trie` is only used in `examples`, but not in tests or src. Can we create examples package.json so that it's not fetched by default when tests are executed?

Not sure if used, from webpack.config.js:

```
constants: require.resolve('constants-browserify'),
crypto: require.resolve('crypto-browserify'), // used by: rlpxpeer, bin/cli.ts
os: require.resolve('os-browserify/browser'), // used by: bin/cli.ts, web3_clientVersion rpc
stream: require.resolve('stream-browserify'), // used by: fetcher
```

**Comment by paulmillr** [comment]
- `master` npm install: `added 1925 packages, and audited 1939 packages in 40s`
- After removing all those packages: `removed 217 packages, and audited 1722 packages`
- After replacing `fs-extra` (a bit more complex): `removed 4 packages, and audited 1718 packages`

**Comment by holgerd77** [comment]
Totally love it that this gets some serious attention! ❤️
