### ISSUE TITLE
Update libp2p

### ISSUE THREAD

**Issue by paulmillr** [ethereumjs/ethereumjs-monorepo#2198]
Client uses `"libp2p": "^0.30.7"`, which is quite old, and has some security warnings related to outdated deps. Current version is 0.38, I think we should update it and all its peer/sub deps to the following versions:

```
    "libp2p": "^0.38.0",
    "@libp2p/bootstrap": "^2.0.0",
    "@libp2p/interfaces": "^3.0.3",
    "@libp2p/kad-dht": "^3.0.4",
    "@libp2p/mplex": "^5.0.0",
    "@libp2p/tcp": "^3.0.3",
    "@libp2p/websockets": "^3.0.2",
    "@libp2p/peer-id": "^1.1.8",
    "@chainsafe/libp2p-noise": "^8.0.1",
```

Note that old plugins were `libp2p-x` / `peer-id`, new ones are `@libp2p/x`

**Comment by holgerd77** [comment]
Yes, that would generally make a lot of sense! Just for some context: we had a lot of discussions lately if it would be worth to keep the libp2p support integrated or not with various arguments in both directions. Outcome of this discussion would obviously influence the update need! 🙂

**Comment by acolytec3** [comment]
Yup, this is part of #1967.

**Comment by holgerd77** [comment]
Ah, ok, then let#s keep #1967 as a meta-issue, will close here.
