### ISSUE TITLE
Implement eth/67

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/ethereumjs-monorepo#2262]
This just removes two methods from `devp2p` so that should not be a super big problem.

**Comment by rashidmya** [comment]
I can give it a go. which two methods to remove?

**Comment by jochem-brouwer** [comment]
Hi @rashidmya, see https://github.com/ethereum/devp2p/blob/master/caps/eth.md#eth67-eip-4938-march-2022 :)

**Comment by ernestosperanza** [comment]
Is this issue open to work?

**Comment by jochem-brouwer** [comment]
Hi @ernestosperanza, we have an open PR from @rashidmya by this, so I would say this is not open at this point.
