### ISSUE TITLE
Upgrade guide recommends errant import

### ISSUE THREAD

**Issue by MicaiahReid** [ethereumjs/ethereumjs-monorepo#2273]
Hi! I'm working on upgrading Ganache to the latest release. The `@ethereumjs/trie` package's [first line of code in the upgrade guide](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/trie/UPGRADING.md#implementation) to implement a `LevelDB` class has the following:
```TypeScript
import { isTruthy } from '@ethereumjs/util'
```

This line doesn't work because `@ethereumjs/util` doesn't have an `isTruthy` export. In fact, a search of the codebase indicates that an example is the only reference to `isTruthy`. Looking at previous versions, I'm not finding any definition there either.

**Comment by acolytec3** [comment]
Thanks for the catch.  We'll update the readme to reflect the current state of things.
