### ISSUE TITLE
Client: Node 18 Nightly CI Runs Failing

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#2275]
Currently the nightly CI tests on Node 18 are failing, see e.g. [this CI run](https://github.com/ethereumjs/ethereumjs-monorepo/runs/8240751506?check_suite_focus=true).

Concretely the following client tests are failing, all very concrete and deterministic tests where there is a clear behavior-not-working-correctly error message:

- not ok 45 gas limit should be double previous block
- not ok 46 baseFee should be initial value
- ok 47 should be strictly equal (on calcNextBaseFee())

This should be investigated and fixed.

**Comment by acolytec3** [comment]
Can we close this for now and re-address if it starts failing again?  It looks like some sort of fluke and the tests are all passing the past 2 weeks.

![image](https://user-images.githubusercontent.com/17355484/191772457-c2f62c8f-bc9c-4559-ae90-1e8a01388bfa.png)

**Comment by holgerd77** [comment]
Sure, please always do directly.
