### ISSUE TITLE
Invalid PoS block error on `createGenesisBlock` with custom `Common` instance

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ethereumjs-monorepo#2279]
In testing #2088, I think we've uncovered a small edge case bug in [`createGenesisBlock`](https://github.com/ethereumjs/ethereumjs-monorepo/blob/295deaa07ee8a45d7813e9f07971073652fafcb0/packages/blockchain/src/blockchain.ts#L1234) when using a custom `common` instance where the hardfork is set `merge`.  If your genesis block parameters (given by `common.genesis()`) has a `difficulty` parameter with a value greater than zero (like mainnet genesis), the blockheader constructor will throw an error because of [this check](https://github.com/ethereumjs/ethereumjs-monorepo/blob/295deaa07ee8a45d7813e9f07971073652fafcb0/packages/block/src/header.ts#L377) since `createGenesisBlock` doesn't pass `skipConsensusFormatValidation` set to true.  I'm not 100% sure the best way to solve this (or if we even should solve this) since the only reason we ran across this is because retesteth uses mainnet genesis parameters to instantiate all its transition tests.

The below snippet will recreate the issue.
```
  const common = Common.custom({
    chainId: 1n,
    genesis: {
      difficulty: 1,
      gasLimit: 5000,
      baseFeePerGas: '0x7',
      nonce: '0x123456789abcdef',
      extraData: '0x',
    },
    defaultHardfork: Hardfork.Merge,
    hardforks: [
      { name: Hardfork.London, block: 0 },
      { name: Hardfork.Merge, block: 0 },
    ],
  })

  const blockchain = await Blockchain.create({ common })
```

**Comment by holgerd77** [comment]
Have also read the latest discussion and comments in the chat on this, so just to pick this up and conclude: so it seems correct to me that this throws. With this setup block 0 is already a Merge block and by spec a merge block just can't contain/add any additional difficulty.

So I would cautiously assume we can close this again, also reading from the thread in the chat? Or is this still an issue worth discussing and/or thinking about?

**Comment by acolytec3** [comment]
Honestly, it feels like a non issue now that I put that hack in the retesteth PR to resolve it.  That feels like a design quirk in retesteth more than any real logic issue.  I'm going to close here.
