### ISSUE TITLE
Block: Clean up block RPC test data

### ISSUE THREAD

**Issue by gabrocheleau** [ethereumjs/ethereumjs-monorepo#2280]
Some test data from the block package does not seem to conform with the standard RPC interface, for e.g. `"sealFields"`. which from a quick research seems to be a now unused parity-specific field ([src](https://pkg.go.dev/github.com/INFURA/go-ethlibs/eth)).

Since we don't make use of them, we could easily clean those up and remove the need for typecasting in some of the tests:
e.g. `blockDataDifficultyAsInteger as unknown as JsonRpcBlock`

**Comment by holgerd77** [comment]
Ah, yes, would be a fan. 🙂 👍
