### ISSUE TITLE
EVM won't wait for 'step' event handler to finish before continuing execution

### ISSUE THREAD

**Issue by thevaizman** [ethereumjs/ethereumjs-monorepo#2290]
Hey, was trying to bump our version of ethereumjs in our [evm.codes](https://www.evm.codes/) project.

I am using the latest (6.0.0) @ethereumjs/vm and the latest (1.0.0) @ethereumjs/evm packages.
When my handler to the `step` event is called with a function as the 2nd arg, the EVM won't wait until the function is called and will just keep executing till the end.

My event handler declaration:

```typescript
    const contFunc = () => {};

    vm.evm.events!.on('step', (e: InterpreterStep) => {
      _stepInto(e, contFunc)
    })
```

My handler function:

```typescript
  const _stepInto = (
    { depth, pc, gasLeft, opcode, stack, memory }: InterpreterStep,
    continueFunc: () => void,
  ) => {

    // skip internal calls
    if (depth !== 0) {
      continueFunc()
      return
    }
  }
```

From the [docs](https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/vm#tracing-events), I understand that EVM execution should wait until I call `continueFunc()` in my handler, but this is not the case. The execution just continues. I do know for sure that my `_stepInto()` handler is called as I can see `console.log`s from there.

I know that the event emitting properties of EVM/VM changed in the last few versions, could it be a bug? Or am I doing something wrong?

Would appreciate your help, as you were always extremely helpful for us! :) @jochem-brouwer @holgerd77

**Comment by jochem-brouwer** [comment]
You need to add a second argument to the event listener.

`vm.events.on('step', async (e: InterpreterStep, contFun: Function) => {await someFun(); contFun()})`

**Comment by thevaizman** [comment]
Thanks a lot for the quick answer @jochem-brouwer! For future reference of people who may be getting into the same problem and bump into this ticket, when using `Function`, it ended up asking me for a different type for the 2nd argument of the event handler, but it's now working after I used:

```typescript
    vm.evm.events!.on('step', (e: InterpreterStep, contFunc: ((result?: any) => void) | undefined) => {
      _stepInto(e, contFunc)
    })
```

**Comment by holgerd77** [comment]
Is this sufficiently described in the code docs? Otherwise it would be good to add.

Will add as an eventual TODO to #2105
