### ISSUE TITLE
Build errors with newest ethereumjs/evm

### ISSUE THREAD

**Issue by thevaizman** [ethereumjs/ethereumjs-monorepo#2295]
Hey @jochem-brouwer @holgerd77,

I encountered 2 build errors using the newest package of `@ethereumjs/evm` (1.0.0) that prevent me from deploying my `evm.codes` app to Vercel. While I am able to easily solve these errors locally (by changing the sources of the `evm` package, this is obviously not ideal and I would like to know what is the correct way to handle these errors so that I can deploy to Vercel using the original package.

The first error:

```
./node_modules/@ethereumjs/evm/src/evm.ts:12:1
Type error: Import assignment cannot be used when targeting ECMAScript modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.

  10 |   zeros,
  11 | } from '@ethereumjs/util'
> 12 | import AsyncEventEmitter = require('async-eventemitter')
     | ^
  13 | import { debug as createDebugLogger } from 'debug'
  14 | import { promisify } from 'util'
  15 | 
error Command failed with exit code 1.
```
I am able to solve this easily by changing the erroneous line to `import AsyncEventEmitter from 'async-eventemitter'`

The second error:

```
./node_modules/@ethereumjs/evm/src/precompiles/index.ts:204:3
Type error: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.

  202 | 
  203 | export {
> 204 |   AddPrecompile,
      |   ^
  205 |   CustomPrecompile,
  206 |   DeletePrecompile,
  207 |   getActivePrecompiles,
error Command failed with exit code 1.
```

I am able to solve this one by changing the erroneous block of code to:

```typescript
export {
  getActivePrecompiles, precompiles,
  ripemdPrecompileAddress
}
export type {
  AddPrecompile,
  CustomPrecompile,
  DeletePrecompile, PrecompileFunc,
  PrecompileInput
}
```

Also, I cannot disable `--isolatedModules` since I am using SWC, which requires it to be enabled, in my project.

Below you can see my `tsconfig`:

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "target": "ESNext",
    "lib": [
      "dom",
      "dom.iterable",
      "ESNext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "ESNext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true
  },
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

Any thoughts on these errors? would appreciate your help! :)

**Comment by acolytec3** [comment]
In looking at these, the first two look to be easily addressable.  Looks like the only difference would be that we would do
`import * as AsyncEventEmitter from 'async-eventemitter'` since we have `esModuleInterop:false` in our tsconfig.  I think that would solve your issues, right?

**Comment by acolytec3** [comment]
@thevaizman Could you try building your app and point your EVM dependency to the head of #2303 and see if that resolves your issue?  Updating these import/exports doesn't seem to cause any issues for our internal builds but I don't have an ESM test setup to validate it will work for ESM based projects.

**Comment by thevaizman** [comment]
> @thevaizman Could you try building your app and point your EVM dependency to the head of #2303 and see if that resolves your issue? Updating these import/exports doesn't seem to cause any issues for our internal builds but I don't have an ESM test setup to validate it will work for ESM based projects.

Hey @acolytec3, thanks for responding to my issue! :)
Unfortunately, after installing from the branch you suggested, I am now getting another error when trying to build:

```typescript
./node_modules/@ethereumjs/evm/src/evm.ts:153:19
Type error: Property 'events' in type 'EVM' is not assignable to the same property in base type 'EVMInterface'.
  Type 'AsyncEventEmitter<import("/Users/talvaizman/Desktop/Tools/evm.codes/node_modules/@ethereumjs/evm/src/types").EVMEvents>' is not assignable to type 'import("/Users/talvaizman/Desktop/Tools/evm.codes/node_modules/@types/async-eventemitter/index")<import("/Users/talvaizman/Desktop/Tools/evm.codes/node_modules/@ethereumjs/evm/src/types").EVMEvents>'.
    The types returned by 'first(...)' are incompatible between these types.
      Type 'this' is not assignable to type 'AsyncEventEmitter<EVMEvents>'.
        Type 'AsyncEventEmitter<T>' is not assignable to type 'AsyncEventEmitter<EVMEvents>'.
          Types of property 'emit' are incompatible.
            Type '<E extends keyof T>(event: E & string, ...args: Parameters<T[E]>) => boolean' is not assignable to type '<E extends keyof EVMEvents>(event: E & string, ...args: Parameters<EVMEvents[E]>) => boolean'.
              Types of parameters 'args' and 'args' are incompatible.
                Type 'Parameters<EVMEvents[E]>' is not assignable to type 'Parameters<T[E]>'.
                  Type 'EVMEvents[E]' is not assignable to type 'T[E]'.
                    Type 'EVMEvents' is not assignable to type 'T'.
                      'EVMEvents' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint 'EventMap'.

  151 |   public readonly _transientStorage: TransientStorage
  152 | 
> 153 |   public readonly events: AsyncEventEmitter<EVMEvents>
      |                   ^
  154 | 
  155 |   /**
  156 |    * This opcode data is always set since `getActiveOpcodes()` is called in the constructor
error Command failed with exit code 1.
```

**Comment by thevaizman** [comment]
> Apologies, I think I've resolved that build issue now with my latest commit. Can you update to the latest HEAD commit and try it once more?

Now getting a new error:

```typescript
./node_modules/@ethereumjs/evm/src/evm.ts:226:23
Type error: This expression is not constructable.
  Type 'typeof AsyncEventEmitter' has no construct signatures.

  224 | 
  225 |   constructor(opts: EVMOpts) {
> 226 |     this.events = new AsyncEventEmitter<EVMEvents>()
      |                       ^
  227 | 
  228 |     this._optsCached = opts
  229 | 
error Command failed with exit code 1.
```

**Comment by acolytec3** [comment]
Hmm, interesting.  Can you link me to a repo where I can reproduce this?

**Comment by thevaizman** [comment]
> Hmm, interesting. Can you link me to a repo where I can reproduce this?

@acolytec3 sure thing. You can have a look [here](https://github.com/comitylabs/evm.codes/tree/replace-difficulty-with-prevrandao). This is the branch of my app. You simply need to replace the `@ethereumjs/evm` dependency to the one linked me and you will be able to reproduce my error by building with `yarn build`

**Comment by thevaizman** [comment]
@acolytec3 btw, I managed to get more context on the problem by running `yarn typecheck`:

```typescript
node_modules/@ethereumjs/evm/src/evm.ts:226:23 - error TS2351: This expression is not constructable.
  Type 'typeof AsyncEventEmitter' has no construct signatures.

226     this.events = new AsyncEventEmitter<EVMEvents>()
                          ~~~~~~~~~~~~~~~~~

  node_modules/@ethereumjs/evm/src/evm.ts:12:1
    12 import * as AsyncEventEmitter from 'async-eventemitter'
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Type originates at this import. A namespace-style import cannot be called or constructed, and will cause a failure at runtime. Consider using a default import or import require here instead.
```

It looks like it still wants the import to be `import AsyncEventEmitter from 'async-eventemitter'` instead of a namespace import.

**Comment by acolytec3** [comment]
I'm honestly not sure how to proceed here.  If I do a import the default of `AsyncEventEmitter` in our code, it is undefined (since the `AsyncEventEmitter` typing uses the `export=` syntax instead of `export default`.  From reading [this](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Modules.md#export--and-import--require) it seems like the only real option for us is the `import = require()...` or else importing as a namespace. but somehow neither of those is an option when targeting ESM I guess.

**Comment by thevaizman** [comment]
> ```ts
> A namespace-style import cannot be called or constructed
> ```

@acolytec3  Yeah it seems like the only way to resolve this is actually doing `import AsyncEventEmitter from 'async-eventemitter'` butt this would require you to enable `esModuleInterop`.
Is this out of the question for your project? (genuinely asking as I'm new to all these CommonJS/ES6 shenanigans...)

**Comment by acolytec3** [comment]
Unfortunately yes. We just went through the effort of removing that because of concerns we were impacting consumers of our code who might not want to use that setting. That said, we seem to have had the reverse impact on you. 😬 I can explore implementing some alternate typing for this module that resolves the issue, maybe switching it to have a named export. Will do some further research

**Comment by thevaizman** [comment]
> Unfortunately yes. We just went through the effort of removing that because of concerns we were impacting consumers of our code who might not want to use that setting. That said, we seem to have had the reverse impact on you. 😬 I can explore implementing some alternate typing for this module that resolves the issue, maybe switching it to have a named export. Will do some further research

That’s completely understandable :)
Thanks for taking the time to help with this issue. Hoping to hear good news 🤞

**Comment by thevaizman** [comment]
@acolytec3 Just an update, I managed to actually get the thing to build by changing the `index.d.ts` file so that it contains a named export: `export { AsyncEventEmitter }` at the end of the file instead of the `export = AsyncEventEmitter;` they have now.
That way, I can import it from your module by changing `types.ts` and `evm.ts` imports to:
`import { AsyncEventEmitter } from 'async-eventemitter'`

Not sure if this is something you would do normally, but since `async-eventemitter` is not maintained anymore (since 2017), maybe you would consider that? Just a thought.

**Comment by acolytec3** [comment]
I've actually been trying to do that locally but was continuing to get weird errors.  So, will try and put some more thought into on Monday!

**Comment by thevaizman** [comment]
@acolytec3 Sure thing! lmk if I can help somehow and have a great weekend :)

**Comment by acolytec3** [comment]
I went back and reread your last comment and I was actually trying something slightly different so I tried your approach this morning but unfortunately I'm having the same sort of errors.  The code will all build but our tests fail with a ` async_eventemitter_1.AsyncEventEmitter is not a constructor` error so something is obviously going awry.  In your successful build with named exports, does the app actually work or do you get runtime errors trying to instantiate our EVM/VM?

**Comment by thevaizman** [comment]
@acolytec3 that's weird. I am able to both build as well as use all features of the app when applying my changes.

Just to be more clear, these are my changes:

- `node_modules/@types/async-eventemitter/index.d.ts`
  - Removed `line 20` and append to end of file the following - `export {AsyncEventEmitter}`
- `node_modules/@ethereumjs/evm/src/types.ts`
  - Replace your `import type ...` with - `import {AsyncEventEmitter} from 'async-eventemitter'`
- `node_modules/@ethereumjs/evm/src/evm.ts`
  - Replace your `import * as ...` with - `import {AsyncEventEmitter} from 'async-eventemitter'`

**Comment by acolytec3** [comment]
Okay, went back to a clean slate and tried exactly the changes you noted above and I'm still getting the `not a constructor` error.  I'm stumped.  :thinking:

**Comment by acolytec3** [comment]
And I confirmed it's working fine when I look at your repo.  I cloned it and built locally, using `npm link` to link it to my local branch with these changes.  Seems like `ts-node` is doing something really screwy when I run our tests.

**Comment by thevaizman** [comment]
Hmm interesting, haven't tried running any of your tests on it, but I wouldn't be surprised if simply trying out different flags when running `ts-node` is going to solve it. I'll try to take a look at your project's configurations and see if I spot something that might break it.

**Comment by thevaizman** [comment]
@acolytec3 
Ok after some investigation, I managed to track the problematic sequence that causes `ts-node` to freak out.
The reason for the `this.events = new async_eventemitter_1.AsyncEventEmitter();` error we see is because for some reason, when you compile the project, you get the following lines in the `/ethereumjs-monorepo/packages/evm/dist/evm.js:45` file:

```javascript
const async_eventemitter_1 = require("async-eventemitter");

//...

this.events = new async_eventemitter_1.AsyncEventEmitter();
```

Whereas after using `yarn build` on my project and looking at the same file in `node_modules/@ethereumjs/evm/dist/evm.js` I get these lines:

```javascript
const AsyncEventEmitter = require("async-eventemitter");

// ...

this.events = new AsyncEventEmitter();
```

I managed to run all the tests just fine after changing these 2 lines of code manually in your project.
I have no idea what causes this anomaly between the two projects (maybe some compilation flags?) but these 2 lines of code are definitely the change that breaks the tests in your repo so it's not `ts-node`'s fault I guess.

**Comment by acolytec3** [comment]
Interesting... That may be a tricky one. What's especially remarkable is that you're using the same compiled output that I am. We just have some weird double declaration or something somewhere to cause this.

**Comment by thevaizman** [comment]
@acolytec3 Yeah, at first I thought it has to do something with the fact that there are 2 components name `AsyncEventEmitter` declared in the `node_modules/@types/async-eventemitter/index.d.ts` file, one is the namespace and the other is the class.

My intuition here says that for some reason, my project seems to "understand" that and it only imports the class from the module, hence the construct-able expression in my `evm.js` file, whereas your project tries to "find" the class in the namespace and construct it.
I thought it might be due to some `import * as AsyncEventEmitter` expression that is still present somewhere but I couldn't find one...

**Comment by acolytec3** [comment]
I definitely see the actual issue now, and I can see typescript intellisense seeing both the namespace and the named export but it's still not clear to me where typescript gets the idea to compile it to `async_emitter_1.AsyncEmitter`. I remember seeing something like this before somewhere in our repo so will keep digging. This is an odd bug to be sure.

**Comment by thevaizman** [comment]
@holgerd77 @acolytec3 Mine is `typescript 4.4.4`. I can see that your project has `4.7.4`.
It doesn't seem to make much difference as I upgraded mine to `4.7.4` using `yarn ad typescript@4.7.4` and I got the same compiled `node_modules/@ethereumjs/evm/dist/evm.js` file as before.

**Comment by holgerd77** [comment]
> @holgerd77 @acolytec3 Mine is `typescript 4.4.4`. I can see that your project has `4.7.4`. It doesn't seem to make much difference as I upgraded mine to `4.7.4` using `yarn add typescript@4.7.4` and I got the same compiled `node_modules/@ethereumjs/evm/dist/evm.js` file as before.

👍 Ah, thanks for investigating!

**Comment by thevaizman** [comment]
@holgerd77 @acolytec3 @jochem-brouwer Hey folks, would love to hear if y'all see any valid solution for this problem on your end.
The way I see it, our only option for using the newest version of your library is forking it (with the changes that break the tests) which we would really like to avoid for obvious reasons :/

**Comment by holgerd77** [comment]
The [AsyncEventEmitter](https://github.com/ahultgren/async-eventemitter) library is MIT licenced, I guess we can just internalize and modify the code base on our side?

WDYGT? 🤔

(also has some side-security-benefits)

**Comment by holgerd77** [comment]
(eventually we even add to the Util package, so that we can reuse in both VM and EVM)

**Comment by thevaizman** [comment]
> The [AsyncEventEmitter](https://github.com/ahultgren/async-eventemitter) library is MIT licenced, I guess we can just internalize and modify the code base on our side?
> 
> WDYGT? 🤔
> 
> (also has some side-security-benefits)

Yeah, this is pretty much what @acolytec3 and I did ([these](https://github.com/ethereumjs/ethereumjs-monorepo/issues/2295#issuecomment-1258257724) are my suggested changes), but the problem is that after you do that it somehow breaks the current tests that you have (as you can see [here](https://github.com/ethereumjs/ethereumjs-monorepo/issues/2295#issuecomment-1258789380)).
I am able to build and use the library perfectly fine on my project while for some reason, on your project the building process produces a slightly different output that breaks testing.

**Comment by acolytec3** [comment]
I'm going to pick this up again today at some point. There just be something obvious that I'm just missing.

**Comment by acolytec3** [comment]
Ugh, sorry the days have gotten away from me.  This is still on my to-do list so hoping to get to it tomorrow.

**Comment by thevaizman** [comment]
Thanks for keeping me updated! Appreciate it :)

**Comment by acolytec3** [comment]
@thevaizman Will you try building your app with the latest commit on this PR?  I pulled the `async-eventemitter` into the source directory and removed the dependency on the DefinitelyTyped version and your app seems to build locally for me in doing so.

**Comment by acolytec3** [comment]
I've spent another few hours puzzling over this and have made zero progress.  When I take the types for `async-eventemitter` internal and do named exports, I still have this same bizarre issue where it compiles to `async_eventemitter_1.AsyncEventEmitter()` which doesn't exist.  So...will take one more stab at it tomorrow.

**Comment by thevaizman** [comment]
@acolytec3 Yeah I tried messing around with the typing too, and tried a few variations for the types in the `index.d.ts` file but no matter what I tried, when building with your project it yielded the same result  :/

Thanks so much for the effort! Hope to hear good news tomorrow :)

**Comment by acolytec3** [comment]
I confess myself stumped at this point.  According to [this](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html#namespaces-in-module-code) the sort of thing we've done should just work but for the life of me I can't get it to not add that fake constructor to the declaration.  I've googled around as far as I can and I really just have no idea how to solve this one without completely rewriting the async event emitter (something I'm not eager to do).

**Comment by acolytec3** [comment]
@holgerd77 any thoughts here?  There is a more modern async event emitter we could look at though I'm not sure how different it's API is from the standard one - https://github.com/sindresorhus/emittery.  No deps to speak of so could maybe be an option?

**Comment by thevaizman** [comment]
@acolytec3 `emittery` seems to be a well maintained repo. Regardless of this issue, it seems like a healthy choice to switch from this "dead" library to something more modern and maintained, although I understand the cost of migrating to a new library.

Also, not sure if you already saw it, but there's [this](https://github.com/humanwhocodes/async-event-emitter) library which is by far less popular than `emittery` but seems to have an API that at first glance looked somewhat closer to what you use now and it seems to have native support for ESM imports too.

**Comment by acolytec3** [comment]
> Also, not sure if you already saw it, but there's [this](https://github.com/humanwhocodes/async-event-emitter) library which is by far less popular than emittery but seems to have an API that at first glance looked somewhat closer to what you use now and it seems to have native support for ESM imports too.

I think the issue with this one is it has no types (and doesn't look like any in DefinitelyTyped either) so not really any better of a solution than our existing one since we'd have to maintain the typing ourselves.  We will have to take this one back and think on it a bit.  Sorry I don't have a better answer for you at this point but I doubt we're going to have it all solved in the next day or two since there's a fair bit of code would need to be touched to switch out a dep like this that's so deeply embedded in our code.

Could be worth considering just adding a simple "hotfix" script in your build step for now to do that renaming since it works for your use case.  Probably not quite as simple as `    "tapeHotFix": "sed -i -e 's/js/ts/g' node_modules/tape/bin/import-or-require.js"` (which is an example of something we did in another repo).  Brittle and not ideal for the long term but it works for now

**Comment by thevaizman** [comment]
Yep, makes sense to not maintain the typing yourselves, I agree.
Thanks for the suggestion. I mean, we could also fork your repo and use our own fork for now, which is something we wanted to avoid, but if you're planning on implementing that change soon enough (not asking for a concrete ETA, just wondering if it's in the ballpark of ~1 week) it might be best to just wait for your implementation.

Again wanted to just say how much I appreciate the time you spent on this issue. @acolytec3 @holgerd77  You're both awesome :)

**Comment by acolytec3** [comment]
I'll take a look at the needed code changes. If it's a breaking change because the events API changes, it might be a bit trickier. Will keep you posted

**Comment by acolytec3** [comment]
Just for giggles, I tried swapping out `async-eventemitter` for `emittery` since a cursory review of our code showed minimal use of the API (just `emit` and `on`) and I immediately found that `emittery` is an ESM module with no CJS build.  So...that puts us in an interesting bind since we only build CommonJS and can't use top level await (or import ESM modules without using a dynamic import which in turn leads to other complications since we instantiate the event emitter inside our EVM and VM constructors which aren't async so therefore can't use dynamic imports).  

I then tried the other one you linked and it turns out that it doesn't have the `once` method on the `EventEmitter` API, so it's a non-starter too.

So...I'm kinda at a loss.  I don't know that we have a way out of this one unless somebody can divine the right way to tell Typescript to not compile the constructor call on the current `async-eventemitter` class to `async-eventemitter.AsyncEventEmitter()`.

**Comment by thevaizman** [comment]
Got it. That _does_  seem to put us in quite a pickle... We will maybe try get some people we work with working on a proper solution for that.
If so, we will update of course :)

Thanks for checking the libraries!

**Comment by acolytec3** [comment]
I wish I had a better answer on this but full conversion to ESM isn't on our immediate roadmap so that's not an immediate opportunity either.  

I think the best I can recommend at this point would be that simple hotfix approach where you just override the particular bits of the `async-eventemitter` type that are breaking in `node_modules`.  It's a tad brittle but as we've both noted, the `async-eventemitter` hasn't changed in 5 years and I wouldn't expect sudden changes any time soon.

**Comment by holgerd77** [comment]
Just further exploring the options here, @acolytec3 would it be an option to for now switch to an older version of the `emittery` package, so that would be [v0.13.1](https://github.com/sindresorhus/emittery/releases/tag/v0.13.1) I guess? 🤔

The `v1.0` version is pretty new anyhow - just released one month ago - so we would be switching to a version which can still be considered a "recent" version.

And when we move to ESM ourself we can still upgrade (likely relatively easily).

But on first round: is this technically an option/an improvement?

**Comment by acolytec3** [comment]
I'll take a look at the older version. Thankfully there are only a very few places where I have to touch things to switch since the API is the same as the standard event emitter

**Comment by acolytec3** [comment]
Unfortunately, the older version of Emittery commits the same sin as the `async-eventemitter` types in that it uses `export = Emittery` which is an older Typescript specific export style that seems to be incompatible with ESM modules (unless you have `esModuleInterop` turned on, which we don't).

Unless someone has another idea, I think the only solution we're going to have is to completely internalize the `async-eventemitter` module (not just the types) and update the exports to make it play nicely with our code.  Since it's a standalone module, it might not be that big a deal to do.  I will try that tack next.

**Comment by acolytec3** [comment]
@thevaizman Can you try building against the latest commit on the linked branch here?  I found another library called [`eventemitter2`](https://www.npmjs.com/package/eventemitter2) that adds async capabilities and doesn't seem to use the naught `export = asynceventemitter` syntax and it appears to allow all of our tests to pass (and has nice typing to boot).

**Comment by thevaizman** [comment]
@acolytec3 interesting, now the type checking passes without any problems, but I get the following error:

```typescript
yarn run v1.22.19
$ next build
info  - Checking validity of types  
info  - Creating an optimized production build  
Failed to compile.

../ethereumjs-monorepo/packages/evm/src/precompiles/index.ts
Module parse failed: Unexpected token (23:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import { precompile12 } from './12-bls12-map-fp2-to-g2'
| 
> import type { PrecompileFunc, PrecompileInput } from './types'
| import type { Common } from '@ethereumjs/common'
| 

Import trace for requested module:
./context/ethereumContext.tsx
./pages/precompiled.tsx
```

Any ideas? 🤔 
I built it using `yarn link` to link all `@ethereumjs` packages to the latest build of the `evm-import-fix` branch.

**Comment by thevaizman** [comment]
Oh my bad, it appears a if `yarn link` doesn't work well with loaders such as `babel` so I had to `yarn pkg` all of your packages and reference them locally in my `package.json`.
But the bottom line is - it worked! :) 

App builds successfully and I also ran a short test run to see that everything works fine.
That's really awesome! Thanks for your determination @acolytec3!

**Comment by acolytec3** [comment]
Cool. I'll take this back to the team for a final round of review and hopefully we can include this in an upcoming bug fix release in the next week or two.
