### ISSUE TITLE
The chain ID does not match the chain ID of Common

### ISSUE THREAD

**Issue by lalLAL95828** [ethereumjs/ethereumjs-monorepo#2297]
```js
import Web3 from 'web3';
import Common, { Chain, Hardfork } from '@ethereumjs/common'
import { FeeMarketEIP1559Transaction } from '@ethereumjs/tx'
const rpcUrl = "https://ropsten.infura.io/v3/47d4b716075541e49f38f9a03390b9b8"
const web3 = new Web3(rpcUrl)

const addressFrom = "0x0E99b21833Bc441ee56C405b2Ee6f974D84b88C3"
const addressTo = "0x25f0f9E87A13489e7C1b7bb146e21FDb4866C8A6"

const common = new Common({ chain: Chain.Ropsten, hardfork: Hardfork.London })
const tsTxObj = {
    from:     addressFrom,
    gasLimit: web3.utils.toHex(210000),
    maxPriorityFeePerGas: web3.utils.toHex('50000000000'),
    maxFeePerGas: web3.utils.toHex('2000000000'),
    nonce: web3.utils.toHex(13),
    to:    addressTo,
    value: web3.utils.toHex(web3.utils.toWei('0.1', 'ether')),
    accessList: [],
    chainId: web3.utils.toHex(3),
    type: '0x02',
}
const tx = FeeMarketEIP1559Transaction.fromTxData(tsTxObj, { common })
console.log(tx)
```
Uncaught Error: The chain ID does not match the chain ID of Common (tx type=2 hash=not available (unsigned) nonce=13 value=100000000000000000 signed=false hf=error maxFeePerGas=undefined maxPriorityFeePerGas=undefined)
![image](https://user-images.githubusercontent.com/16337280/191247470-81dfe413-1260-4531-addb-47487854cdf2.png)
![image](https://user-images.githubusercontent.com/16337280/191247656-eca1c226-f97a-4f8f-9b79-3c63882ea967.png)

**Comment by jochem-brouwer** [comment]
What are your package versions?

Your tx is invalid; maxFeePerGas is less than maxPriorityFeePerGas. If I change this on our latest versions, the tx builds fine.

**Comment by jochem-brouwer** [comment]
I can reproduce when using our latest version

**Comment by lalLAL95828** [comment]
This is a project built with create-react-app，@ethereumjs/tx is latest versions；

**Comment by lalLAL95828** [comment]
I can't understand why I got a 3 !== 3n

**Comment by lalLAL95828** [comment]
today， It's strange that I deleted node_module and package-lock.json, after npm i, everything is fine

**Comment by jochem-brouwer** [comment]
All right, great, thanks for the update and closing!
