### ISSUE TITLE
Stack underflow error while making a new commit using a copy object of state manager

### ISSUE THREAD

**Issue by AhmadKajjan-QU** [ethereumjs/ethereumjs-monorepo#2301]
Hello everyone,

I got a stack underflow error when I was trying to make a commit on a copy of the state manager

I have this code which creates a copy of state in array with 3 state objects max
```
public saveCopyOfState(): void {
    if (this.prevStates.length >= NUMBER_OF_STATE_COPIES) {
      this.prevStates.shift();
    }
    const stateCopy = this.stateManager.copy();
    this.prevStates.push(stateCopy);
  }
```

I have this code to revert back the state using a copied one 

```
public async revetStateManager() {
    const lastStateManager = this.prevStates.pop();
    if (lastStateManager) {
      this.stateManager = lastStateManager;
    } else {
      throw new Error("no prev states are saved.");
    }
  }
```

This code to run a new block 
```
export async function runBlock(
  this: VM,
  block: Block
): Promise<RunBlockResult> {
  const beneficiaryAddress: Address = block.blockHeader.coinbase;

  let beneficiaryAccount: Account;

  await this.saveCopyOfState();
  await this.stateManager.checkpoint();

  try {
    beneficiaryAccount = await this.stateManager.getAccount(beneficiaryAddress);
  } catch (error: any) {
    const accountData: Account = new Account(new BN(0), new BN(0));
    await this.stateManager.putAccount(beneficiaryAddress, accountData);
  }

  beneficiaryAccount = await this.stateManager.getAccount(beneficiaryAddress);
  beneficiaryAccount.balance.iadd(new BN(MINING_REWARD));
  await this.stateManager.putAccount(beneficiaryAddress, beneficiaryAccount);

  for await (let transaction of block.transactions) {
    try {
      await this.runTx(transaction);
    } catch (error: any) {
      await this.stateManager.revert();
    }
  }
  await this.stateManager.commit();

  return {
    receipts: [], // TxReceipt[]
    results: [], // RunTxResult[]
    stateRoot: block.blockHeader.stateRoot,
    gasUsed: BigInt(0),
    logsBloom: Buffer.from("0"),
    receiptRoot: Buffer.from("0"),
  };
}
```

here I got an error if somewhere I used the revetStateManager function before using runBlock function

"dependencies": {
    "@ethereumjs/trie": "^5.0.0",
}

**Comment by acolytec3** [comment]
Apologies for not responding to this sooner.  Can you provide a stack trace showing where this error occurs?  There's not enough detail here for us to answer confidently.  That said, the `stack underflow` error occurs [when you try to update a node](https://github.com/ethereumjs/ethereumjs-monorepo/blob/e6c2f6c1e96c431b3fa0f29ba899f05ef9f2a728/packages/trie/src/trie/trie.ts#L377) that doesn't exist in the trie so I'm guessing it happens when you try to `putAccount` and that's attempting to update the state trie.  If your state copies are missing one of the nodes along the path in the trie where that account is being put, that may be the issue.

**Comment by AhmadKajjan-QU** [comment]
Thanks for responding  I think what happened as you said there were some nodes missing.
I solve it by creating a new copy of the state making the changes to it and then replacing it with the global state.
I think there was more than on place updating the state that's why this issue happened.
