### ISSUE TITLE
Not able to compile the app after install and import

### ISSUE THREAD

**Issue by AndonMitev** [ethereumjs/ethereumjs-monorepo#2307]
When i try to run my app i'm hitting this error:

<img width="698" alt="image" src="https://user-images.githubusercontent.com/32274987/192115532-7110beb7-b1fe-4b9d-9b8b-3c75cf9f67af.png">

Any idea how to solve it?

**Comment by acolytec3** [comment]
The issue is most likely the `??` operator. You can try setting the targeted browsers in your package.json to something like [this](https://github.com/facebook/create-react-app/issues/9468#issuecomment-980702069) and this will likely solve it. Let me know if not and we can explore some other options.

**Comment by holgerd77** [comment]
@AndonMitev Any success? Can this be closed?

**Comment by jere344** [comment]
I have the same issue when running `serve -s build` on linux, the same code run fine on windows.
I tried setting the targeted browsers but it did not fix it.
I also tried replacing the 5 `??` and some optional chaining with classic ternary operator and got this error :
```
file:///usr/local/lib/node_modules/serve/build/main.js:427
  await printUpdateNotification(args["--debug"]);
  ^^^^^

SyntaxError: Unexpected reserved word
```

**Comment by acolytec3** [comment]
> I have the same issue when running `serve -s build` on linux, the same code run fine on windows.
> I tried setting the targeted browsers but it did not fix it.
> I also tried replacing the 5 `??` and some optional chaining with classic ternary operator and got this error :
> ```
> file:///usr/local/lib/node_modules/serve/build/main.js:427
>   await printUpdateNotification(args["--debug"]);
>   ^^^^^
> 
> SyntaxError: Unexpected reserved word
> ```
> 

Can you drive some more details about your particular setup? Are you using a bundler like webpack?

**Comment by jere344** [comment]
Oh my bad sorry it is absolutely not the good github project for this. I have the same error but it has nothing to do with ethereumjs. I came from https://github.com/facebook/create-react-app/issues/9468#issuecomment-980702069 that you linked and did not check which git we were on.

**Comment by acolytec3** [comment]
Going to close this for now due to inactivity.  If it continues to be an issue, please feel free to reopen and update with more details.
