### ISSUE TITLE
Getting wrong getSenderAddress() when signing a transaction

### ISSUE THREAD

**Issue by cryptobsc** [ethereumjs/ethereumjs-monorepo#2327]
Hi guys,

I am trying to sign a transaction using _ethereumjs-tx_ library but I am getting a wrong sender address.

I cannot have access to the private key of the user in my dapp, it's why I used the R, S, V values of the signature.

Please check out my code as below.

`

const signRawTx = async () => {

    const dest = "0xc977790E98E944e40cC78DEC45C43F9442Ce4402";
    const nonce = await web3.eth.getTransactionCount(currentAccount, 'latest');

    const chainBSC = new EthereumCommon.default.forCustomChain(
      'mainnet',{
        name: 'bsc',
        networkId: 56,
        chainId: 56
      },
      'petersburg'
    )

    const raw = {
      nonce: web3.utils.toHex(nonce),
      gasPrice: web3.utils.toHex(5000000000),
      gasLimit: web3.utils.toHex(550000),
      to: dest,
      value: web3.utils.toHex(web3.utils.toWei('0.01', 'ether')),
      data: '0x'
    }

    const tx = new EthereumTx(raw, { common: chainBSC })

    const txHash = '0x' + tx.serialize().toString('hex')
    const msg = web3.utils.sha3(txHash);

    const signature = await ethereum.request({
      method: 'eth_sign',
      params: [currentAccount, msg], 
    });
    

    const eCDSASignature = EthereumUtil.fromRpcSig(signature);

    const v = eCDSASignature.v;
    const r = EthereumUtil.toBuffer('0x' + eCDSASignature.r.toString('hex'));
    const s = EthereumUtil.toBuffer('0x' + eCDSASignature.s.toString('hex'));

    const pubKey = EthereumUtil.ecrecover(EthereumUtil.toBuffer(msg), v, r, s)
    const publicAddress = '0x' + EthereumUtil.pubToAddress(pubKey).toString('hex')

    const signedTx = new EthereumTx([...txParams, v, EthereumUtil.toBuffer(r), EthereumUtil.toBuffer(s)], { common: chainBSC })
    const signedTxHash = '0x' + signedTx.serialize().toString('hex');

    console.log("SenderAddress ", signedTx.getSenderAddress().toString('hex')); // Wrong sender address
  
  }
`

Thank you for your time!

**Comment by holgerd77** [comment]
Hi, this is not possible, the r, s, v values are the signature for a signed transaction. To sign a transaction the private key is needed (for a reason).

**Comment by cryptobsc** [comment]
> Hi, this is not possible, the r, s, v values are the signature for a signed transaction. To sign a transaction the private key is needed (for a reason).
Sure, the sign is happening via Metamask with the user's private key but the signature doesn't seem to be valid actually.

**Comment by acolytec3** [comment]
I'll take a look at this.  I think you might be approaching this the wrong way.  Will circle back a little later once I research.

**Comment by acolytec3** [comment]
What exactly are you trying to accomplish here.  The approach I was thinking that might work (`web3.eth.signTransaction`) doesn't work with metamask since they don't support that RPC method.  Are you wanting to broadcast the message to your own RPC endpoint?  Otherwise, i would just leverage `web3.eth.sendTransaction` and let metamask sign and submit the transaction.  Then, you can get the tx hash and pull the transaction from the provider to get the signature (if you still need it at that point for some reason).

**Comment by cryptobsc** [comment]
> What exactly are you trying to accomplish here. The approach I was thinking that might work (`web3.eth.signTransaction`) doesn't work with metamask since they don't support that RPC method. Are you wanting to broadcast the message to your own RPC endpoint? Otherwise, i would just leverage `web3.eth.sendTransaction` and let metamask sign and submit the transaction. Then, you can get the tx hash and pull the transaction from the provider to get the signature (if you still need it at that point for some reason).

Thank you, it works with `web3.eth.sendTransaction` actually!
