### ISSUE TITLE
Documentation: Bellatrix and Paris Hardforks

### ISSUE THREAD

**Issue by Hugo-Vincent** [ethereumjs/ethereumjs-monorepo#2346]
In packages/common/src/hardforks, all the names up until Gray Glacier are the official names. However I can't find the Bellatrix and Paris upgrades. I'm gonna guess Bellatrix is "MergeForkIdTransition" and Paris is "Merge", but I would just like to confirm this assumption is true.
I wasn't able to find this in the Documentation, so if other people ever have the same question they can confirm it in this issue :)

**Comment by jochem-brouwer** [comment]
Bellatrix is a consensus layer fork, which changes nothing at the execution layer (i.e. this monorepo). However, you are right that " Merge"  is Paris. 

Not sure what to do here, should we create an alias for the Merge called Paris? Thoughts?

**Comment by Hugo-Vincent** [comment]
Hmm if this were my repo I would probably just place a comment "// Also known as Paris" at the Hardforks Enum: https://github.com/ethereumjs/ethereumjs-monorepo/blob/f5821adda073be023c336a41954fe41e864732b2/packages/common/src/enums.ts#L25

Then if people search for Paris and can't find it, and check the Hardforks enum, they'll know.

**Comment by holgerd77** [comment]
> Hmm if this were my repo I would probably just place a comment "// Also known as Paris" at the Hardforks Enum:
> 
> https://github.com/ethereumjs/ethereumjs-monorepo/blob/f5821adda073be023c336a41954fe41e864732b2/packages/common/src/enums.ts#L25
> 
> Then if people search for Paris and can't find it, and check the Hardforks enum, they'll know.

Yes, I would agree, I guess a simple comment should do it in this case, everything else seems overblown respectively something like an alias makes things unnecessarily non-deterministic and will bite us in the future.

**Comment by acolytec3** [comment]
Should be resolved in v7
