### ISSUE TITLE
Implement `eth_feeHistory` RPC method

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ethereumjs-monorepo#2359]
We should implement the `eth_feeHistory` RPC method so that our client will be fully compatible with the testnet faucets which use `feeHistory` to construct their transactions.  The [Alchemy documentation is up to date](https://docs.alchemy.com/reference/eth-feehistory) so don't rely on the Ethereum.org RPC spec as it doesn't include the `GasUsedRatio` property in the response.

A stub implementation was included in #2316 to allow the Shandong testnet to proceed.

**Comment by scorbajio** [comment]
Does `eth_feeHistory` still need to be implemented? This ticket hasn't been updated in a while, is there any new context around this issue?

**Comment by acolytec3** [comment]
I'd say it's still open. We don't have an inventory need for it but always good to fill out missing rpc endpoints.

May 30, 2023 7:48:15 PM Scorbajio ***@***.***>:

**Comment by holgerd77** [comment]
Closed by #3295
