### ISSUE TITLE
Expose getActiveOpcodes to the VM object

### ISSUE THREAD

**Issue by thevaizman** [ethereumjs/ethereumjs-monorepo#2363]
Before v6, which separated the `vm` and `evm` packages, one could instantiate a `vm` object and use: `vm.getActiveOpcodes` ot get the list of available opcodes.
Now that these 2 packages had been separated, the `getActiveOpcodes` function is no longer available in the context of a `vm` object, but only if you instantiate a separate `evm` object and access it via that object.

This creates an awkward situation for us, where we would instantiate both `vm` and `evm` objects, but the `evm` object will only be used for accessing the `getActiveOpcodes`.

See [this](https://github.com/comitylabs/evm.codes/pull/180#discussion_r996768877) comment for reference.

**Comment by thevaizman** [comment]
Thanks for bringing this to my attention I didn't know the casting trick would work.
Having said that, I do feel that adding this function to the interface would be the more natural way to go with.

**Comment by holgerd77** [comment]
We've added directly in the release PR here https://github.com/ethereumjs/ethereumjs-monorepo/commit/ac16d71783dcc0a582245384c05433a40c3f654c, will close.

Tested manually by building the EVM and then running:

```typescript
import { VM } from '@ethereumjs/vm'
let vm = await VM.create({})
vm.evm.getActiveOpcodes!()
```

Works as expected.
