### ISSUE TITLE
EventEmitter2 changes how async events work

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/ethereumjs-monorepo#2366]
In old `async-eventemitter`:

`.on('step', (e) => {})` -> immediately resolves
`.on('step', (e, fn) => {setInterval(fn,1000)}` -> hangs interpreter for 1 s
`.on('step', async (e, fn) => {setInterval(fn,1000)}` -> hangs interpreter for 1 s
`.on('step', (e, fn) => {}` -> quits js (?) (I guess this is because node detects that there are only hanging promises left, and nothing is ran, so it deadlocks and therefore just quits)

In `EventEmitter2`:

```
.on('step') (e: InterpreterStep) => {
return new Promise((resolve) => {setTimeout(resolve, 1000)})
}
```

Also, the `EventEmitter2` events are now not typed, i.e. `.on('step', (e) => {})`, now `e` is cast as `any`

This is breaking and should be resolved.

TODO

- [ ] Ensure async events work as before
- [ ] Ensure events are typed
- [ ] Add a test which ensures async events work as in the past

**Comment by acolytec3** [comment]
For an asynchronous event like this:
```js
  evm.events.on('step', async function (eventObj: any) {
    console.log(eventObj.pc)
    const sleep = () =>
      new Promise((resolve) =>
        setTimeout(() => {
          console.log('timeout is over')
          resolve(undefined)
        }, 5000)
      )
    await sleep()
  })
```

This works, (outputing the PC and then hanging the interpreter for 5 seconds).  Is there anything wrong with this as the way the async events should be used?

For a synchronous event - 
```js
  evm.events.on('step', function (eventObj: any) {
    console.log(eventObj.pc)
  })
``` 

This works just fine.  I see each PC printed to the screen and then the result of the EVM call.
