### ISSUE TITLE
Modify Synchronizer class to support multi-fetcher syncs

### ISSUE THREAD

**Issue by scorbajio** [ethereumjs/ethereumjs-monorepo#2389]
Currently, in order to run a fetcher, the `fetcher` field of a `Synchronizer` object has to be set to a `Fetcher` object that has been initialized. This creates a one-to-one relationship between the `Synchronizer` and `Fetcher` classes. For snap sync, it is necessary to create and run many fetchers - specifically, four (storage, account, bytecode, and trie node). Modify the `Synchronizer` class to accept an array of fetchers. It can call the `fetch` method of each, and resolve only when all fetchers are done fetching.

Also see #2345

**Comment by holgerd77** [comment]
Yes, that seems to make sense to me. 👍
