### ISSUE TITLE
Support receipts when mining/sealing blocks

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ethereumjs-monorepo#2390]
The client currently does not honor the `saveReceipts` CLI parameter when mining/sealing blocks with either PoW or PoA consensus.  Ideally, the receipts should be caught [here](https://github.com/ethereumjs/ethereumjs-monorepo/blob/1e903db3f29f7b4f93db3b2c61248a3c1babad27/packages/client/lib/miner/miner.ts#L286) and stored around [this point](https://github.com/ethereumjs/ethereumjs-monorepo/blob/1e903db3f29f7b4f93db3b2c61248a3c1babad27/packages/client/lib/miner/miner.ts#L308) when the miner is done building the block and has put it in the chain.

**Comment by gabrocheleau** [comment]
Closing this since this has been marked as fixed by #2544
