### ISSUE TITLE
VM updates nonce after running a transaction, but should do right before executing it

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/ethereumjs-monorepo#2399]
There are three phases of a transaction:

1. The initialization phase. In this phase, the tx is unpacked and it is being read, and the execution environment is being set up. (I.e. we create the right parameters to pass on to `EVM` when running a transaction in `runTx`)
2. The execution phase. In this phase, the transaction is executed: if a contract is called, we run the code.
3. The final phase. In this phase, coinbase is credited and any gas which was not used is refunded to the caller.

Right between phase 1 and 2, the nonce of the account should be bumped. If a EOA account which does not have transactions (nonce is 0) tries to create a contract, then the parameters passed on to generate the contract address will use nonce 0 (not 1). However, when we now enter the execution frame, the nonce should be 1, not zero.

Right now this is a problem: we update the nonce after the account. This led to a consensus bug where, if the nonce is zero and the account sends all funds to a contract, the EVM now thinks that the account is empty (it has no code, no storage, no balance, and nonce is zero). This leads to problems in (1) `EXTCODEHASH` thinks the account is empty and thus pushes 0 on the stack, not the hash of the empty string, (2) `CALL`ing the account will lead to `callNewAccount` gas being charged if nonzero value is sent and (3) the same for `SELFDESTRUCT` which charges `callNewAccount` when the contract has nonzero balance.

These bugs are fixed in https://github.com/ethereumjs/ethereumjs-monorepo/pull/2397, but the method to fix those bugs could be said to be a bit on the hacky-ish side.

We have had a lengthy discussion about this nonce problem in the past when we separated VM and EVM. It is thus not trivial to fix. But, we should ensure that the nonce is updated right before we enter the EVM execution: otherwise, this will haunt us in the future.

**Comment by holgerd77** [comment]
@jochem-brouwer thanks for the detailed write-up on this! 🙂

**Comment by jochem-brouwer** [comment]
Agh, right, I just realized why we did this in the first place, and why we had such lengthy discussions about it.

If we change back that we update the nonce in the VM before running the execution frame, and rollback #2397, then blockchain + state tests should all pass and we are fine. However, we are /not/ fine when we try to run this into the EVM. The problem is that, if we try to create a contract in EVM, then we did not update the nonce. So, the creating account has nonce zero. If we now decrease the nonce, we now have a negative nonce (this is impossible) and EVM crashes. What if we introduce a rule, that when we run into account nonce 0, we do not decrease it, but if it is nonzero, we do decrease it?

Then, this happens:

Account has nonce zero, we create a contract, this is created at address A.

If we now update the nonce manually to 1, and then try to create a contract, we check; is nonce zero? (It is not). So, decrease the nonce. However, now we thus decrease the nonce and the EVM thinks we have to create a contract at address A again.

This is where VM and EVM diverges;

VM nonce 0 -> create contract at A

EVM nonce 0 -> create contract at A

VM nonce 1 -> create contract at B

EVM nonce 0 -> create contract at A

I think what might solve this is to increment the nonce inside the EVM, not in VM, but I think I recall having tested this in the past and then also running into new problems. (I will test again, though)

**Comment by jochem-brouwer** [comment]
I do recall refraining from wanting to increase the nonce in the EVM, but am not sure anymore and also not what the reason was. @acolytec3 @gabrocheleau does this point ring any bells to you?

**Comment by gabrocheleau** [comment]
> I do recall refraining from wanting to increase the nonce in the EVM, but am not sure anymore and also not what the reason was. @acolytec3 @gabrocheleau does this point ring any bells to you?

I vaguely remember that discussion and think I was in the "increase the nonce" camp. I'll try to find to discussion
