### ISSUE TITLE
Eth/66 request ID `0` RLP encoded improperly

### ISSUE THREAD

**Issue by shemnon** [ethereumjs/ethereumjs-monorepo#2402]
For an Eth/66 response where the sender sends a request ID of `0` the response Id is being encoded in an invalid scalar.

```
0xf901fe00f901faf901f7a021d614c165442d4bd5097f825ac857f31f2df54a8cc1e0b3d8d4d609f0cc3ae8a01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d4934794f97e180c050e5ab072211ad2c213eb5aee4df134a095f5929c80fd2a875796d2a10af2a6f4ba9913a791efa98d113bcf7121f3ff30a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421b90100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008082d21a83400000808463645fa080a0a7144184e31164c7f806a1eec4160c54ca4d541955dbf4657ae01a955cef279788000000000000000007
```

Is an in-the-wild response.  The fourth byte is `00` which per RLP is an invalid leading character for a scalar value, which the request ID of Eth/66 is defined to be.  The [correct encoding of an RLP zero](https://github.com/ethereum/tests/blob/develop/RLPTests/rlptest.json#L34) is the empty byte string: `80`.

The above should read:

```
0xf901fe80f901faf901f7a021d614c165442d4bd5097f825ac857f31f2df54a8cc1e0b3d8d4d609f0cc3ae8a01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d4934794f97e180c050e5ab072211ad2c213eb5aee4df134a095f5929c80fd2a875796d2a10af2a6f4ba9913a791efa98d113bcf7121f3ff30a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421b90100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008082d21a83400000808463645fa080a0a7144184e31164c7f806a1eec4160c54ca4d541955dbf4657ae01a955cef279788000000000000000007
```

**Comment by holgerd77** [comment]
Thanks for reporting. This is an important bug and we'll try to fix soon.

I've seen that you have started integrating with Shandong ﻿here https://github.com/hyperledger/besu/pull/4599, great, exciting to see! 🙂 

Is this bug a total blocker for you? Or can you move around respectively is this rather something annoying?

Anyhow: we'll also try to address short-term, not sure if we'll get this done before the weekend though.

**Comment by g11tech** [comment]
> Thanks for reporting. This is an important bug and we'll try to fix soon.
> 
> I've seen that you have started integrating with Shandong ﻿here [hyperledger/besu#4599](https://github.com/hyperledger/besu/pull/4599), great, exciting to see! slightly_smiling_face
> 
> Is this bug a total blocker for you? Or can you move around respectively is this rather something annoying?
> 
> Anyhow: we'll also try to address short-term, not sure if we'll get this done before the weekend though.

for reqId this is fixed, but needs to be evaulated for various other fields in this PR
- https://github.com/ethereumjs/ethereumjs-monorepo/pull/2409

**Comment by g11tech** [comment]
> 

may i know which encoded message is this? will add this as testcase

**Comment by shemnon** [comment]
Any message.  Besu would send a request with "0" as the request ID and any response would have "00" instead of "80" as a response.

Besu kicked the can down the road by starting at requestId 1.

**Comment by shemnon** [comment]
That's the crux of the bug.  Besu would send a reqId of 0, encoded in RLP as `0x80` (zero length byte array, as all leading zeros were trimmed).  EthJS would reply with a reqId of `0x00`, which should have been `0x80`.  A scalar of `0x00` is invalid, because it has one leading zero (the value itself).  So the correct number is no digits, hence the `0x80` zero-length byte array encoding.

**Comment by holgerd77** [comment]
This should be fixed with the Shandong restart from three days ago. @g11tech can you confirm?

**Comment by g11tech** [comment]
> This should be fixed with the Shandong restart from three days ago. @g11tech can you confirm?

Yes in shandong the fix is in. Do try syncing it and let know if everything works fine (or not :) )
