### ISSUE TITLE
Where to find ForkHash for BSC network?

### ISSUE THREAD

**Issue by skyzaq24** [ethereumjs/ethereumjs-monorepo#2403]
I'm trying to connect `ethereumjs` to BSC network
I've got Genesis hash and some other data from an issue in this repo, but when I try to run `peer-communication` it connects to some peers and then it gives me `"Unknown forkhash"` error and disconnects.
Where can I find the info of the most recent hardfork? (including ForkHash).
Also, there is a block header field in `peer-communication` which I don't know where to find either.
this is the code I'm using to create common:
```

new Common({
    "chain": {
      "name": "mainnet",
      "chainId": 56,
      "networkId": 56,
      "defaultHardfork": "istanbul",
      "consensus": {
        "type": "pow",
        "algorithm": "ethash",
        "ethash": {}
      },
      "comment": "The Ethereum main chain",
      "url": "https://ethstats.net/",
      "genesis": {
        "hash": "0x0d21840abff46b96c84b2ac9e10e4f5cdaeb5693cb665db62a2f3b02d2d57b5b",
        "timestamp": null,
        "gasLimit": 40000000,
        "difficulty": 1,
        "nonce": "0x0000000000000000",
        "extraData": "0x11bbe8db4e347b4e8c937c1c8370e4b5ed33adb3db69cbdb7a38e1e50b1b82fa",
        "stateRoot": "0xd7f8974fb5ac78d9ac099b9ad5018bedc2ce0a72dad1827a1709da30580f0544"
      },
      "hardforks": [
        {
          "name": "chainstart",
          "block": 0,
          "forkHash": "0xfc64ec04"
        },
        {
          "name": "homestead",
          "block": 1150000,
          "forkHash": "0x97c2c34c"
        },
        {
          "name": "dao",
          "block": 1920000,
          "forkHash": "0x91d1f948"
        },
        {
          "name": "tangerineWhistle",
          "block": 2463000,
          "forkHash": "0x7a64da13"
        },
        {
          "name": "spuriousDragon",
          "block": 2675000,
          "forkHash": "0x3edd5b10"
        },
        {
          "name": "byzantium",
          "block": 4370000,
          "forkHash": "0xa00bc324"
        },
        {
          "name": "constantinople",
          "block": 7280000,
          "forkHash": "0x668db0af"
        },
        {
          "name": "petersburg",
          "block": 7280000,
          "forkHash": "0x668db0af"
        },
        {
          "name": "istanbul",
          "block": 9069000,
          "forkHash": "0xfc3ca6b7"
        }
      ],
      "bootstrapNodes": [
        {
          "ip": "34.246.65.14",
          "port": 30311,
          "id": "28b1d16562dac280dacaaf45d54516b85bc6c994252a9825c5cc4e080d3e53446d05f63ba495ea7d44d6c316b54cd92b245c5c328c37da24605c4a93a0d099c4",
          "location": "ap-southeast-1-001",
          "comment": "bootnode-aws-ap-southeast-1-001"
        }
      ],
      "dnsNetworks": [
        "enrtree://AKA3AM6LPBYEUDMVNU3BSVQJ5AD45Y7YPOHJLEF6W26QOE4VTUDPE@all.mainnet.ethdisco.net"
      ]
    }
  })

```

Thanks for your help

**Comment by holgerd77** [comment]
Hi there, BSC is not officially supported by this repo, so this will likely require some substantial amount of manual work to get things working.

If you want to create a matching Common instance you first need to get a list with the correct hardforks which occurred on BSC together with the matching blocks. You should then be able to actually *drop* the fork hashes from the list (these will be invalid anyhow with changed block numbers) and Common should calculate correc new fork hashes internally and add.

It seems that BSC also has their custom hardforks (`Moran`?), which also needs to be taken into account.

If you get things working would be nice if you can report here, would be interesting to know.

Happy coding! 😎 🙂

**Comment by skyzaq24** [comment]
Thanks @holgerd77      
I did as you suggested and the fork hash issue is now resolved.    
However, I have trouble calculating the block header in RLP format.    
In peer-communication.ts there is a line that provides a block header Like this:    
https://github.com/ethereumjs/ethereumjs-monorepo/blob/4d8bbd10847659f885ccf489246b74b92f1c0066/packages/devp2p/examples/peer-communication.ts#L40-L45

I've already tried workarounds on the web, but the result is different.
How can I calculate the block header like this?

**Comment by holgerd77** [comment]
Hi there,
this is just an arbitrary check to see if syncing works correctly in the example, it is functionally not necessary though.

The hex code you linked above is an RLP-serialized block header. You can try to integrate one of the BSC blocks, e.g. by getting some block data via an RPC service (Infura or similar) and then serialize it in some way.

In the EthereumJS world you would first instantiate a block with the RPC data with a data-matching static `Block` (or `Header`) constructor method (depending on the data you have, there is some method `fromRPC()` or similar e.g.). Then you can call something like `Block.header.serialize()` or similar.

Note that these are not 1:1 instructions, you need to play around yourself a bit! 🙂

**Comment by haiwood** [comment]
> Thanks @holgerd77 I did as you suggested and the fork hash issue is now resolved. However, I have trouble calculating the block header in RLP format. In peer-communication.ts there is a line that provides a block header Like this:
> 
> https://github.com/ethereumjs/ethereumjs-monorepo/blob/4d8bbd10847659f885ccf489246b74b92f1c0066/packages/devp2p/examples/peer-communication.ts#L40-L45
> 
> I've already tried workarounds on the web, but the result is different. How can I calculate the block header like this?

can you share your common settings? been struggling to find the correct hardforks list

**Comment by skyzaq24** [comment]
Below are the hard forks for binance smart chain
```
hardforks: [
      {
        name: 'homestead',
        block: 0,
      },
      {
        name: 'byzantium',
        block: 0,
      },
      {
        name: 'constantinople',
        block: 0,
      },
      {
        name: 'petersburg',
        block: 0,
      },
      {
        name: 'istanbul',
        block: 0,
      },
      {
        name: 'muirGlacier',
        block: 0,
      },
      {
        name: 'ramanujan',
        block: 0,
      },
      {
        name: 'niels',
        block: 0,
      },
      {
        name: 'mirrorsync',
        block: 5184000,
      },
      {
        name: 'bruno',
        block: 13082000,
      },
      {
        name: 'euler',
        block: 18907621,
      },
      {
        name: 'nano',
        block: 21962149,
      },
      {
        name: 'moran',
        block: 22107423,
      },
    ]
```

**Comment by 18211308** [comment]
@ezopensea
