### ISSUE TITLE
pre eip158: 0 reward coinbase touch

### ISSUE THREAD

**Issue by winsvega** [ethereumjs/ethereumjs-monorepo#2421]
We found a bug in our tests. 

In StateTests when generating test on pre EIP158 network, a coinbase get touched by 0 reward. 
Thus the empty account must be present in the state pre EIP158. 

the t8ntool ethereumjs test runner shows that it does not put empty coinbase account in the state.

**Comment by holgerd77** [comment]
I would very much assume that this has been fixed in some way or the other, didn't follow closely but I remember a lengthy discussion around this. 🙂 

Will close.
