### ISSUE TITLE
never receive NEW_BLOCK_HASHES or NEW_BLOCK message

### ISSUE THREAD

**Issue by andkom** [ethereumjs/ethereumjs-monorepo#2430]
I never receive `NEW_BLOCK_HASHES` or `NEW_BLOCK` message from other nodes while communicating with Ethereum network.

Steps to reproduce:

```bash
DEBUG=devp2p:eth:* node -r ts-node/register ./examples/peer-communication.ts
```

**Comment by acolytec3** [comment]
These messages are disabled post merge so you shouldn't see them from mainnet any more.

**Comment by monstermax** [comment]
Understood.

But, how new blocks are propagated ?

Should we periodically poll all peers to get the block ${lastNumber+1} ?

Indeed we need new blocks to complete our local blockchain and to cleanup the mempool.

**Comment by monstermax** [comment]
see this code https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/client/lib/service/fullethereumservice.ts#L259

`      case 'NewBlockHashes': {
        if (this.config.chainCommon.gteHardfork(Hardfork.Merge) === true) {
          this.config.logger.debug(
            `Dropping peer ${peer.id} for sending NewBlockHashes after merge (EIP-3675)`
          )
          this.pool.ban(peer, 9000000)
        }`

**Comment by acolytec3** [comment]
For getting chain updates post merge, you need to run our client with a CL client to get block updates. Lodestar is a good choice that works well with our client

**Comment by acolytec3** [comment]
Is this issue resolved?
