### ISSUE TITLE
args.customGenesisState cause process exit.

### ISSUE THREAD

**Issue by weihaopeng** [ethereumjs/ethereumjs-monorepo#2435]
When use `args.customChain`, whether set `args.customGenesisState` a string of `path to json file` or undefined, the process will exit.

related file: `packages/client/bin/cli.ts`, line 581 to line 592.

BTW, didn't see the arg `customChainParams` in args, but used in line 582. Is it `customChain`?

![image](https://user-images.githubusercontent.com/33681454/204469657-682a0e17-7884-435e-b550-b128bc4f02d2.png)

**Comment by acolytec3** [comment]
Will close for now due to lack of activity.  Feel free to re-open if you have further questions.
