### ISSUE TITLE
@ethereumjs/client lint:diff error

### ISSUE THREAD

**Issue by JowieXiang** [ethereumjs/ethereumjs-monorepo#2450]
This error is preventing me from pushing commits to remote. Please offer some help.

![Screenshot_1](https://user-images.githubusercontent.com/31316150/207394955-63caaa07-1d35-4269-86f7-873037d3f287.png)

Merged master on the commit #2444 
![Screenshot_2](https://user-images.githubusercontent.com/31316150/207395588-12f9f92f-d859-4dc2-9fcf-812696a8bbb4.png)

**Comment by acolytec3** [comment]
Do `git push --no-verify`.  That's just the linter being confused by a new file.

**Comment by JowieXiang** [comment]
Got it. Thanks!
