### ISSUE TITLE
EIP 6122 - Update forkhash calculation for hardforks determined by timestamp

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ethereumjs-monorepo#2455]
There's a new proposed [EIP](https://github.com/ethereum/EIPs/pull/6122/files) that updates the forkhash calculation to account for hardforks by time.  We should keep an eye on this one and probably go ahead and implement in Q1 2023 if it moves forward.

**Comment by gabrocheleau** [comment]
Looks like EIP 6122 has moved forward: https://eips.ethereum.org/EIPS/eip-6122

**Comment by g11tech** [comment]
we already have it now, https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/common/src/common.ts#L835, closing the issue for now (pls reopen if anything is not working)
