### ISSUE TITLE
Support for eth_signTypedData \ eip-712

### ISSUE THREAD

**Issue by CodeOfLight** [ethereumjs/ethereumjs-monorepo#2456]
Please add support for eth_signTypedData \ eip-712

If it is already supported somehow can you please point out which function provides this functionality?

**Comment by acolytec3** [comment]
What is the context of this request? Are you asking us to support this in our client rpc? If so, it's not on our immediate roadmap but we could add it to the list of target rpc endpoints.

**Comment by CodeOfLight** [comment]
We're currently using @ethereumjs/tx@3.5.1 in our backend and calling .sign()

sign(privateKey: Buffer): TransactionObject;

Recently we have received a client request to sign transactions for OpenSea. The client provided me with sample code that works on the clients side using metamask \ web3. 

That code looks as follows:

    const signature = await signer._signTypedData(
      domainData,
      EIP_712_ORDER_TYPE,
      orderComponents
    );

So what I'm trying to do is replicate this on the server side using @ethereumjs/tx

**Comment by acolytec3** [comment]
Hmm, signTypedData is an RPC method for signing data, not transactions, so I don't think the `tx` library even applies. @holgerd77 any thoughts here?

**Comment by CodeOfLight** [comment]
I guess I don't understand the structure of the project all that well. My understanding is you construct a transaction and then call sign(). So I was thinking you would construct a EIP-712 transaction and call sign() on that.

**Comment by jochem-brouwer** [comment]
This is an RPC endpoint on the client. Normally you would sign arbitrary data (i.e. you sign 32 bytes with your private key - if you sign a transaction this RLP encodes the data fields and then hashes it to "convert" it to 32 bytes). However, if you expose the `eth_sign` method this allows to sign any arbitrary data: an attacked could setup that you sign the arbitrary data which sends all your balance to the attacker. Since you just sign these 32 bytes it is thus unknown to the user what they are signing.

EIP 712 solves this. I have not taken a deep look but the key element is that the pre-pad whatever you are signing (so could be a tx hash which sends all the balance to an attacker) with "Ethereum signed message" (see EIP for exact encoding). This new message is not 32 bytes (it is usually longer) and is thus hashed again. This thus prevents that users sign tx hashes.

This is definitely an RPC endpoint, but we could technically also add this in `util` I'd say.

**Comment by acolytec3** [comment]
> This is an RPC endpoint on the client. Normally you would sign arbitrary data (i.e. you sign 32 bytes with your private key - if you sign a transaction this RLP encodes the data fields and then hashes it to "convert" it to 32 bytes). However, if you expose the `eth_sign` method this allows to sign any arbitrary data: an attacked could setup that you sign the arbitrary data which sends all your balance to the attacker. Since you just sign these 32 bytes it is thus unknown to the user what they are signing.
> 
> EIP 712 solves this. I have not taken a deep look but the key element is that the pre-pad whatever you are signing (so could be a tx hash which sends all the balance to an attacker) with "Ethereum signed message" (see EIP for exact encoding). This new message is not 32 bytes (it is usually longer) and is thus hashed again. This thus prevents that users sign tx hashes.
> 
> This is definitely an RPC endpoint, but we could technically also add this in `util` I'd say.

And more fundamentally, "typed data" isn't a transaction at all, but just a message, encoded in a specific way according to the EIP spec.  So, if you construct the data  according to the EIP and hash it, you can then just use the  `util.ecsign` method from `@ethereumjs/util` to sign the hash.

**Comment by CodeOfLight** [comment]
Thank you. I wasn't as familiar with some of the terms you were using here, but now after reading both of your statements a few times and doing some homework I do understand and agree it's not part of the tx package. 

I guess I am a little surprised thought that this monorepo does not yet contain a reference implementation for the encoding process of EIP-712. It was my understanding that teams like metamask etc would use this repo as a reference model, but I guess in this case they have gone ahead and implemented to the EIP spec ahead of this. 

Just like RLP encoding and hashing to get to that 32 bytes, I'd like to avoid doing that myself. Perhaps someone else has written a shim library that I could use in the meantime. I'll poke around and report back on what I find.

**Comment by acolytec3** [comment]
check out `ethers` - https://docs.ethers.org/v5/api/signer/#Signer-signTypedData

**Comment by jochem-brouwer** [comment]
@CodeOfLight I suggest you use `ethers` for this. I will close here for now, please re-open if you disagree or have related questions.
