### ISSUE TITLE
Misleading OOG/codesize error message

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ethereumjs-monorepo#2466]
[This error condition](https://github.com/ethereumjs/ethereumjs-monorepo/blob/7e1bc94e79ca73d189b29ab58d40ec9c82683743/packages/evm/src/evm.ts#L573) is used to report both out of gas execptions as well as code deposit size limit errors and can be very misleading.  While the `evm` debug logs do report that it could be either OOG or code size, the error returned by the `txResult` object is just the code size violation and this could be incorrect.  We should update this error check to through the correct error based on whether the issue is OOG vs code size.

**Comment by holgerd77** [comment]
Some context: error separation was introduced in #2239, actually with the goal to clearly *do* a separation between the errors here. We should have a close look and grasp the whole context before we do additional changes here.

**Comment by jochem-brouwer** [comment]
CC @davidmurdoch we have addressed this and it will be available in our next breaking releases (~July this year)
