### ISSUE TITLE
Client: Interrupt with CTRL-C not possible

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#2472]
Currently when the client is run (tested `mainnet` with `npm run client:start`) it seems not possible any more to interrupt the sync with the normal CTRL-C key combinations ("Caught interrupt signal." is displayed but the client just contines).

This should be investigated and fixed, currently it is necessary to just kill the process manually which is unhealthy and complicated and can corrupt the DB.

**Comment by g11tech** [comment]
closing as addressed in https://github.com/ethereumjs/ethereumjs-monorepo/pull/2477 :+1:
