### ISSUE TITLE
Reactivate and fix Codecov

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#2482]
We have overlooked code coverage to a great extend recently and we should slowly start to reactivate and reintegrate into our everyday workflow, to not deviate here too much over time and keep the basic standard of not (substantially) dropping here along a PR.

Someone should have a general look, eventually on some own PR and see if things "are all right" and then report back on this.

Codecov is actually at least to some extend off the charts right now, realized this when reviewing #2478, the associated codecov/patch [overview](https://app.codecov.io/gh/ethereumjs/ethereumjs-monorepo/pull/2478) is totally off the charts on the impacted files:

<img width="898" alt="grafik" src="https://user-images.githubusercontent.com/931137/211759847-7e1e2878-9d8e-474f-bb88-98061867102d.png">

This seems to have nothing to do with the PR, I checked #2474 as a cross-check and there reported files are similarly off.

**Comment by scorbajio** [comment]
Looking into this at #2878

**Comment by holgerd77** [comment]
Closed by #2878
