### ISSUE TITLE
Interop EIP-4844 Tracking Issue

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#2494]
Tracking issue for the EthereumJS Client joining the EIP-4844 related Interop test networks (see milestone [docs](https://notes.ethereum.org/@djrtwo/edelweiss-4844-tracker)).

EthereumJS branch used: [master](https://github.com/ethereumjs/ethereumjs-monorepo)
Config/Interop folder: `packages/client/devnets/4844-interop`

## EIP-4844 Implementation & Updates

Main [EIP-4844](https://eips.ethereum.org/EIPS/eip-4844) working branch: #2349 (merged)

## Manual EthereumJS Client Installation

1. Node.js (`v18` recommended) and npm need to be installed, see e.g. [npm docs](https://docs.npmjs.com/downloading-and-installing-node-js-and-npm)
2. Clone the EthereumJS monorepo with `git clone https://github.com/ethereumjs/ethereumjs-monorepo.git`
3. Run `npm i` from the root folder to install dependencies and build
4. Now the client can be run from the `packages/client` folder with `npm run client:start`
5. Run `npm run client:start -- --help` for help on the CLI parameters

## EIP-4844 Devnet 4

https://eip4844-devnet-4.ethpandaops.io/

`devnet-4`, started Wednesday, January 25, 2023
Build on top of Shanghai, Withdrawal Harmonization (Gwei)

### EthereumJS Setup

Use manual install from above (TODO: Docker image?).

We assume working from the `packages/client` folder within the EthereumJS monorepo with a cloned EthPandaOps [4844-testnet](https://github.com/ethpandaops/4844-testnet.git) repo, a directory `sd4` symlinked to the config (`ln -s ./withdrawals-testnet/withdrawal-devnet-4/ wd4`) folder for easier reference, and a dedicated subdirectory for each client combination runs for the client data. The following instructions give a summary:

```shell
cd packages/client
git clone https://github.com/ethpandaops/4844-testnet
mkdir sd4
cd sd4
ln -s ../4844-testnet/network-configs/devnet-4 config
mkdir [CLIENT_COMBINATION_DATA_DIRECTORY] // e.g. mkdir ethjs_lodestar
```

Run the EthereumJS Client with the following command (from `packages/client`, so `cd` one above):

```shell
npm run client:start -- --dataDir=sd4/ethjs_lodestar/el_data \
--gethGenesis=sd4/config/genesis.json \
--rpc --rpcEngine \
--bootnodes=enode://8488a57c323d5e5bef1c40c5cb2330cb0bd75d900afad5e7f50a47ecc1ae7683fb664f509908c6b978633b9af75788e943f26e9b64989504d189ae7b3278ede3@161.35.91.184:30303
```

**Note:** We aligned EthereumJS client CLI option spelling to `lowerCaseStartingCamelCase` during a PR merge on 2023-01-24, please make sure to run latest `master` for the above command to work! (To check on your installation run the `npm run client:start -- --help` command and e.g. check on the `--loglevel` -> `--logLevel` change.)

For a more verbose debugging level, you can add  `--logLevel=debug` for a deeper level of normal log messages and additionally `--rpcDebug` for a (very verbose) RPC debugging.

#### Lodestar

Install Lodestar from source following [these docs](https://chainsafe.github.io/lodestar/install/source/). 
An installation of the `lodestar` directory parallel to the `ethereumjs-monorepo` directory is assumed and symlink `wd4` within the `lodestar` directory to the EthereumJS `wd4` directory.

Relevant Lodestar branch: `dapplion/eip-4844`

```shell
cd lodestar
git fetch origin dapplion/eip-4844
git checkout dapplion/eip-4844
ln -s ../ethereumjs-monorepo/packages/client/sd4 sd4
```

Run Lodestar with:

```shell
./lodestar beacon \
  --dataDir=sd4/ethjs_lodestar/cl_data \
  --paramsFile=sd4/config/config.yaml \
  --genesisStateFile=sd4/config/genesis.ssz \
  --execution.urls=http://localhost:8551 \
  --jwt-secret=sd4/ethjs_lodestar/el_data/jwtsecret  \
  --network.connectToDiscv5Bootnodes \
  --bootnodes="enr:-Iq4QAw-ZQb0IiosZgDDcK5ehLs1XmwT0BWU1E1W3ZnhlAAwAE3I46dgCsCbeB5QUwcpDmpFfveTfKF7-tiIg0KWGjqGAYXoIfe6gmlkgnY0gmlwhKEjXcqJc2VjcDI1NmsxoQN4HpB2GMFY2MzwO9hGFjqRG47OX4hGDliAG-mJNWkEr4N1ZHCCIyk"
```

See [packages/client/devnets/4844-interop](https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/client/devnets/4844-interop) folder for CL client setup instructions (OUTDATED).

**Comment by acolytec3** [comment]
To run `ethjs` <> `prysm` on devnet-4:

Build `prysm`

```sh
$ git clone https://github.com/prysmaticlabs/prysm.git
$ cd prysm
$ git checkout eip4844
$ bazel build //cmd/prysmctl
$ bazel build //cmd/beacon-chain
$ bazel build //cmd/validator
$ cd ../
```

Setup and run Ethereumjs using commands above in the Lodestar instructions:

Then run the below command from the `prysm` directory root and replace the paths with the ones from your clone of the devnet-config.

```
bazel run //cmd/beacon-chain -- \
    --datadir=[ethereumjs-monorepo-root]/packages/client/sd4/ethjs_prysm/cl_data \
    --min-sync-peers=1 \
    --genesis-state=[ethereumjs-monorepo-root]/packages/client/sd4/config/genesis.ssz \
    --bootstrap-node=enr:-Iq4QAw-ZQb0IiosZgDDcK5ehLs1XmwT0BWU1E1W3ZnhlAAwAE3I46dgCsCbeB5QUwcpDmpFfveTfKF7-tiIg0KWGjqGAYXoIfe6gmlkgnY0gmlwhKEjXcqJc2VjcDI1NmsxoQN4HpB2GMFY2MzwO9hGFjqRG47OX4hGDliAG-mJNWkEr4N1ZHCCIyk \
    --chain-config-file=[ethereumjs-monorepo-root]//packages/client/sd4/config/config.yaml \
    --chain-id=4844001004 \
    --accept-terms-of-use \
    --jwt-secret=[ethereumjs-monorepo-root]/packages/client/sd4/ethjs_prysm/el_data/jwtsecret \
    --verbosity debug
```

**Comment by ScottyPoi** [comment]
Prysm/EthJS stuck here for a while:

Prysm:
```
DEBUG powchain: Latest eth1 chain event blockHash=0xb844dda029ad9ff288a6fec709a988555973f6df5cb0308572035a65634a3499 
blockNumber=1167
```

EthJs:
`eth_getBlockByNumber([ 'latest', false ])`
```
  result: {
    number: '0x48f',
    hash: '0xb844dda029ad9ff288a6fec709a988555973f6df5cb0308572035a65634a3499',
    parentHash: '0x2bdd47ecef2b4d9185cc7f6b8d8c7614ff50a7d8723afb0d8ab17b43ea89828d',
    mixHash: '0x7b5f28449f0091c9075510d30a7f5025b4a1fe2ad0f4dad5437f04aaf3a5cc54',
    nonce: '0x0000000000000000',
    sha3Uncles: '0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347',
    logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'... 414 more characters,
    transactionsRoot: '0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421',
    stateRoot: '0x7701723d0437a791fc36955db1e2c5df7e8ce9b30f8adba067715e591d8c2f01',
    receiptsRoot: '0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421',
    miner: '0xf97e180c050e5ab072211ad2c213eb5aee4df134',
    difficulty: '0x0',
    totalDifficulty: '0x1',
    extraData: '0xd883010b00846765746888676f312e31392e33856c696e7578',
    size: '0x5c2',
    gasLimit: '0xc7e1c9',
    gasUsed: '0x0',
    timestamp: '0x63d13304',
    transactions: [],
    uncles: [],
    baseFeePerGas: '0x7',
    withdrawalsRoot: '0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421',
    withdrawals: [],
    excessDataGas: '0xc0000'
  }
```

**Comment by acolytec3** [comment]
Closing for now. Further interop with can be tracked under a new devnet6 issue as needed.
