### ISSUE TITLE
`getBlock` throws when block not found by hash

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ethereumjs-monorepo#2511]
`getBlock` is currently typed to return a [`block` or `null`](https://github.com/ethereumjs/ethereumjs-monorepo/blob/7fa64079578b24e791c62be3fe3d6e634bb10f13/packages/blockchain/src/types.ts#L29) according to the `blockchain` interface.  In our implementation, if you look up a block by its hash and the corresponding DB key isn't in the database, the underlying `level` database throws a `NotFound` error and the dbManager doesn't handle this per the type so we get an exception instead.  

We should discuss whether to fix our implementation to match the interface or else change the interface since our general goal in recent history has to move away from returning `null`  but rather throwing an error or else returning undefined in these cases.  At a minimum, we should catch the error and then throw something more descriptive since `NotFound` doesn't tell the library consumer what is going on and is against the type suggestions provided.

**Comment by jochem-brouwer** [comment]
To do so, we should review all cases where we `getBlock` and see if any behavior diverges if we return `null` instead of throw. I honestly think that indeed returning `null` makes more sense than throwing.

**Comment by ScottyPoi** [comment]
Started working on this.

**Comment by ScottyPoi** [comment]
> To do so, we should review all cases where we `getBlock` and see if any behavior diverges if we return `null` instead of throw. I honestly think that indeed returning `null` makes more sense than throwing.

I think I addressed all of the calls to `getBlock`, which required a bunch of `if (block === null) throw new Error("Block Not Found")`, or ` if (block === null) return undefined`

I don't know whether it feels like an improvement or not.

**Comment by gabrocheleau** [comment]
Linking to to #2516

**Comment by gabrocheleau** [comment]
Marking this as closed as this was reported as fixed in #2516
