### ISSUE TITLE
EIP 3074 is outdated

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/ethereumjs-monorepo#2512]
For `AUTH` we take 3 stack items, while 4 should be taken. This EIP should be updated to the latest spec.

**Comment by SamWilsn** [comment]
The current version of 3074 only has three stack items, and four memory items.

**Comment by holgerd77** [comment]
Can't completely "read" the current state from the two comments, does this mean we are up-to-date (and can close the issue) or are there some updates needed to the implementation?
