### ISSUE TITLE
merge at genesis oddities

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ethereumjs-monorepo#2517]
When we start the client with genesis parameters that have the merge at the genesis block, I have observed a couple of oddities with how the client responds to RPC calls that should be addressed.
- `eth_syncing` - When `eth_syncing` is called, if merge is at genesis and running as a solo EL/CL pair, the client throws [this error](https://github.com/ethereumjs/ethereumjs-monorepo/blob/52dbfc2026ae42ba6e607d287d616a23aa21bbe5/packages/client/lib/rpc/modules/eth.ts#L996) since there will never be another EL layer peer to sync with.  We should either add a new option to the CLI for running solo client pairs (i.e. local devnet) or else find another way to address this one (maybe add a check to see if we're using `BeaconSync` vs one of the other synchronizers?
- `eth_sendRawTransaction` - [Here](https://github.com/ethereumjs/ethereumjs-monorepo/blob/52dbfc2026ae42ba6e607d287d616a23aa21bbe5/packages/client/lib/rpc/modules/eth.ts#L874) - when a transaction is submitted, the client throws an error about not knowing the current chain height.  If merge is at genesis, it seems like we should just assume height = 0 until a paired CL client provides a FcU and accept the transaction.

**Comment by jochem-brouwer** [comment]
There are also some problems in our client which are caught by hive tests regarding this (these are not listed in op) #2498
