### ISSUE TITLE
Module not found: Can't resolve 'c-kzg' in '/home/pooh/rodelspace/metasalt/NFT_Marketplace/node_modules/@ethereumjs/tx/dist/utils'

### ISSUE THREAD

**Issue by rodel-daroy** [ethereumjs/ethereumjs-monorepo#2551]
![image](https://user-images.githubusercontent.com/92417026/221225048-b9693dcf-464a-48ee-8443-a33f2371427a.png)

**Comment by acolytec3** [comment]
Thanks for highlighting this.  Do you have an example repo I can clone to verify the issue?  I think I know what it is but need to verify before we can push a patch fix on this release.

**Comment by rodel-daroy** [comment]
It's difficult to share my project.

**Comment by rodel-daroy** [comment]
blobHelper has require('c-kzg'), but c-kzg module doesn't exist.

**Comment by acolytec3** [comment]
No worries, I think I have an idea how to recreate it.  I know what the root issue is and we just missed fixing that import when we did the latest round of releases.  Will get it patched and tested today so hopefully can get a fix out shortly.

**Comment by acolytec3** [comment]
No need.  I've got the same issue in one of my own repos so can work from that.  Thanks!

**Comment by kuzdogan** [comment]
Ah already posted. Referencing here anyway: https://github.com/ethereumjs/ethereumjs-monorepo/issues/2553

**Comment by acolytec3** [comment]
No worries and thanks for reporting!  `c-kzg` is indeed intended to be an optional dependency and we intended to patch this so it wouldn't be required (since `c-kzg` don't work in browser).  Fix forthcoming as soon as I validate some changes.

**Comment by rodel-daroy** [comment]
Once the issue is fixed finally, let me know.

**Comment by rodel-daroy** [comment]
![image](https://user-images.githubusercontent.com/92417026/221248144-3bd102e8-1aed-4d7b-8740-8ab4528370e0.png)

The issue is still remained.

**Comment by acolytec3** [comment]
For now, just pin your dependency in package json to 4.0.2.  We're not going to have a release out today.

**Comment by rodel-daroy** [comment]
v4.0.2 has same error.

**Comment by rodel-daroy** [comment]
![image](https://user-images.githubusercontent.com/92417026/221256446-16ea9c62-41ea-4be4-a129-02babde615e6.png)

**Comment by acolytec3** [comment]
Did you delete `node_modules` and reinstall everything?  v4.0.2 shouldn't have that c-kzg dependency.

**Comment by vietstar87** [comment]
Fixed:
You need edit in yard.lock

"@ethereumjs/tx@^4.0.2":
  version "4.0.2"
  resolved "https://registry.yarnpkg.com/@ethereumjs/tx/-/tx-4.0.2.tgz#082b0f95fe9a61c70277ee1bfeb65d6f27a723bb"
  integrity sha512-6GoKVK3MVcAFFn4qSLIIDZ1vrKSLn7W5L80Pvae1BJFgchu+11R2iOqQyVGUSGbaXllh4xliUy/7+x5pYwRY8Q==
  dependencies:
    "@ethereumjs/common" "^3.0.2"
    "@ethereumjs/rlp" "^4.0.0"
    "@ethereumjs/util" "^8.0.3"
    ethereum-cryptography "^1.1.2"
    ethers "^5.7.1"

**Comment by keon** [comment]
having same issues in our deployment pipeline

**Comment by kuzdogan** [comment]
For those having the problem, you can make sure which version is installed with
```
npm ls @ethereumjs/tx
```

`npm install` might try to install the latest versions. You need to use `npm ci` to stick to the declared versions in `package-lock.json`.

**Comment by holgerd77** [comment]
Hi guys, issue should be mitigated by a hotfix release on all affected library (particularly the tx library, but other upstream libraries as well), can you/someone please confirm that things work? Thanks! 🙂 🙏
