### ISSUE TITLE
Switch `ethers` to peer dependency in `block`/`tx` and upgrade to v6

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ethereumjs-monorepo#2559]
We currently import `ethers` in `block`, `tx`, and `statemanager` and have it pinned to version 5.7.  We should do the following:
- Move ethers to an optional peer dependency in `block` and `tx`
- Update the `fromEthersProvider` static constructors in `block` and `tx` to check if `ethers` is instantiated and throw a helpful error message if not (i.e. 'please install Ethers to use this function')
- Update Ethers to v6 (and make any necessary changes based on the updated API - probably most substantial in `statemanager`)

**Comment by gabrocheleau** [comment]
Have some time today and have some familiarity with v6, can begin tackling this.

**Comment by acolytec3** [comment]
Closing this as it's legally obsolete. We'll update ethers to v6 in statemanager as part of the breaking releases.
