### ISSUE TITLE
Consider switching/upgrading `rustbn.js` dependency

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ethereumjs-monorepo#2580]
We currently use the [`rustbn.js`](https://github.com/ethereumjs/rustbn.js) dependency in the EC Multiplication and EC Pairing precompile functions in the `evm` library and and this library is nearly 4 years old and essentially unmaintained at this point.  The `rustbn.js` library requires `buffers` as inputs to the functions we use from it and this is a blocker for migrating from `buffer` to `Uint8Array` so we need to determine how to either recompile `rustbn.js` to WASM (possibly using `wasm-bindgen`) and ensure it accepts `Uint8Array` inputs or else find another `bn128`/`bn254` pairing library.

**Comment by acolytec3** [comment]
cc @holgerd77  cc @paulmillr

**Comment by paulmillr** [comment]
Before starting non-trivial work on adding bn254 pairings to noble-curves, it's important to understand how performance-conscious the curve must be. JS implementations would be much slower than WASM. I know WASM isn't currently used; asm.js is.

Existing bls12-381 does only 50-70 pairings per second. BN may be slightly faster.

Could someone prepare a benchmark of current bn precompiles?

**Comment by acolytec3** [comment]
Done for now (just updated `rustbn.js` to remove the buffers from the JS wrapper.
