### ISSUE TITLE
Just tried to upgrade but the new version will not work in a chrome extension

### ISSUE THREAD

**Issue by richtera** [ethereumjs/ethereumjs-monorepo#2587]
It looks like the latest minor upgrade uses @chainsafe/as-sha256 as a dependency which is not compatible with manifest 3 chrome extensions, because it loads the wasm using new Module() passing it as a string. This is equivalent to requiring the wasm-unsafe-eval permission which is not something that can be provided inside of manifest 3. We had to switch back. It's a bit unfortunate that this upgrade happened in a minor upgrade, because going back requires a bit of yarn.lock hacking.

**Comment by meeh0w** [comment]
Encountered the same issue with `@ethereumjs/util`.

`@chainsafe/ssz` added as a dependency [here](https://github.com/ethereumjs/ethereumjs-monorepo/commit/6508bf9213d32929e0e2456c9c4fcfabe4e9d3c6#diff-299359f2bbf7c3b40bc731073d8f787f581121e8dacab6db10c282ee43905492R86) depends on `@chainsafe/as-sha256` which is a WebAssembly module.

It prevents the client apps from working in the extension realm (Chrome's manifest V3 does not allow wasm):
<img width="637" alt="image" src="https://user-images.githubusercontent.com/3853033/225307912-6a379c1c-34c3-43ab-825c-9df3fc4cb299.png">
_(no, you can't just override this particular part of the CSP, Chrome won't allow that)_

**Comment by richtera** [comment]
I think if the wasm was imported from a file instead of being passed as a string to new Module() it could possibly work

**Comment by acolytec3** [comment]
Thanks for reporting. We're going to discuss with chainsafe on a way forward.

**Comment by meeh0w** [comment]
I just found out that you can add `script-src 'self' 'wasm-unsafe-eval';` to the CSP and it makes it work, Manifest v3 allows that. So it becomes a matter of wether it's something one wants to allow.

**Comment by paulmillr** [comment]
https://github.com/ChainSafe/ssz/issues/313

**Comment by holgerd77** [comment]
Addressed right now in #2721 

Release likely in 1-2 weeks

**Comment by holgerd77** [comment]
This has been released, will close.
