### ISSUE TITLE
Question: Is there an existing solidity verifier for proofs created with @ethereumjs/trie?

### ISSUE THREAD

**Issue by sebastiendan** [ethereumjs/ethereumjs-monorepo#2596]
Hi,

In combination with using `@ethereumjs/trie` in the browser to create merkle proofs against transaction tries, I'm looking for a compatible on-chain verifier. It's pretty hard to find an existing contract out there that would work out of the box with the type/format of merkle proofs created with `@ethereumjs/trie` (so many unfinished/abandoned projects).

Would you know if such a compatible on-chain verifier (contract) exist?

Thanks!

**Comment by jochem-brouwer** [comment]
This seems to me what you are looking for: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/cryptography/MerkleProof.sol

**Comment by sebastiendan** [comment]
@jochem-brouwer This is for standard merkle trees only, no? I was expecting the verification of merkle proofs for merkle patricia tries to be incompatible for the one for merkle trees.

**Comment by jochem-brouwer** [comment]
This should work also for MPTs. The gotcha here is that this is a "normal" Merkle tree but the data inside the tree is encoded as Patricia tree.

**Comment by jochem-brouwer** [comment]
I might have been a bit too fast to reply here, but I will investigate a bit further for you, because I would expect that an EVM/Solidity implementation of MPT proofs are readily available.
