### ISSUE TITLE
Merge wallet package into monorepo

### ISSUE THREAD

**Issue by paulmillr** [ethereumjs/ethereumjs-monorepo#2611]
Just a tracking issue for the merge of https://github.com/ethereumjs/ethereumjs-wallet into monorepo. After that we'll need to publish a new wallet version.

**Comment by paulmillr** [comment]
Saw this in a wallet that's gaining popularity, Frame: https://github.com/floating/frame/blob/3af513c24ff44c35e23070fb2069754e7a63954c/main/signers/hot/RingSigner/index.js#LL3C53-L3C70

They are still using old, bad version of wallet.

@holgerd77 would be great to have this merged

**Comment by paulmillr** [comment]
https://www.npmjs.com/package/ethereumjs-wallet?activeTab=readme The package is actually getting less and less popular. Maybe it's worth releasing 2.0.0 as unscoped and then track the downloads, re-evaluate.

**Comment by acolytec3** [comment]
This is under way.  #2729 
Will close this and open a new tracking issue with a list of todos (since there are several)
