### ISSUE TITLE
Error using Transaction.fromTxData

### ISSUE THREAD

**Issue by erc2107** [ethereumjs/ethereumjs-monorepo#2624]
```
const tx = {
  nonce: '0x0',
  maxPriorityFeePerGas: '0x3b9aca00',
  maxFeePerGas: '0x174876e800',
  gasLimit: '0x5208',
  to: '0x90eb2a81f38e9e99ddffd378f6231eee42d83f56',
  value: '0xf1230b1b7c2000',
  chainId: 5,
  v: '0x0',
  r: '0xa7aab7c3f76b6af02f423482627b4cf0d5fead3e3171f0776e6e2caa8937ce7b',
  s: '0x3078cc10321438e666d9bc16c3ee79b039655f9d043af850aa88fcbf4f8e3ab5'
}

let s = Transaction.fromTxData(tx)

```

Error:

```
throw new Error(`Legacy txs need either v = 27/28 or v >= 37 (EIP-155 replay protection), got v = ${v}`);
Error: Legacy txs need either v = 27/28 or v >= 37 (EIP-155 replay protection), got v = 0
```

Using latest @ethereumjs/tx (4.1.1)

**Comment by jochem-brouwer** [comment]
What network is this (etherscan URL?)? Do you have a transaction hash?

**Comment by erc2107** [comment]
@jochem-brouwer I am trying to convert that to a raw tx in order to broadcast it. Doing the same thing using tx params with gasPrice works fine. But when I put maxPriorityFeePerGas & maxFeePerGas it causes this error. Is ethereumjs not supporting eip1559 tx?

**Comment by erc2107** [comment]
@jochem-brouwer   Goerli test network

**Comment by acolytec3** [comment]
> @jochem-brouwer   Goerli test network

Try replacing `Transaction` with `FeeMarketEIP1559Transaction`. That should resolve the issue regarding `v`.

**Comment by erc2107** [comment]
@acolytec3 @jochem-brouwer Using FeeMarketEIP1559Transaction works!! Thnx. I have another Q's. Once I get that result and serialize it etc, if I want to decode that serialized tx I was using before `Transaction.fromSerializedTx(s)` so I would assume now I should use instead `FeeMarketEIP1559Transaction` as well here instead of `Transaction`. That returns an Error: `/node_modules/@ethereumjs/tx/dist/eip1559Transaction.js:92
        if (!serialized.slice(0, 1).equals(TRANSACTION_TYPE_BUFFER)) {
TypeError: serialized.slice(...).equals is not a function
    at FeeMarketEIP1559Transaction.fromSerializedTx`
