### ISSUE TITLE
Error using FeeMarketEIP1559Transaction.fromSerializedTx

### ISSUE THREAD

**Issue by erc2107** [ethereumjs/ethereumjs-monorepo#2625]
```s_tx = "0x02f8720580843b9aca0085174876e8008252089490eb2a81f38e9e99ddffd378f6231eee42d83f5687f1230b1b7c200080c080a0a7aab7c3f76b6af02f423482627b4cf0d5fead3e3171f0776e6e2caa8937ce7ba03078cc10321438e666d9bc16c3ee79b039655f9d043af850aa88fcbf4f8e3ab5"```
```decode = FeeMarketEIP1559Transaction.fromSerializedTx(s_tx)```

causes Error:
```
/node_modules/@ethereumjs/tx/dist/eip1559Transaction.js:92
        if (!serialized.slice(0, 1).equals(TRANSACTION_TYPE_BUFFER)) {
TypeError: serialized.slice(...).equals is not a function
    at FeeMarketEIP1559Transaction.fromSerializedTx
```

**Comment by jochem-brouwer** [comment]
You should convert it to a Buffer first. Are you using typescript?

**Comment by erc2107** [comment]
@jochem-brouwer I am using js

**Comment by erc2107** [comment]
@jochem-brouwer The old method Transaction.fromSerializedTx I think took a hex input instead. I tried converting it to buffer & got this error now: ```
Error: Invalid serialized tx input: not an EIP-1559 transaction (wrong tx type, expected: 2, received: 
    at FeeMarketEIP1559Transaction.fromSerializedTx
```

**Comment by erc2107** [comment]
comment updated

**Comment by acolytec3** [comment]
> ```s_tx = "0x02f8720580843b9aca0085174876e8008252089490eb2a81f38e9e99ddffd378f6231eee42d83f5687f1230b1b7c200080c080a0a7aab7c3f76b6af02f423482627b4cf0d5fead3e3171f0776e6e2caa8937ce7ba03078cc10321438e666d9bc16c3ee79b039655f9d043af850aa88fcbf4f8e3ab5"```
> ```decode = FeeMarketEIP1559Transaction.fromSerializedTx(s_tx)```
> 
> causes Error:
> ```
> /node_modules/@ethereumjs/tx/dist/eip1559Transaction.js:92
>         if (!serialized.slice(0, 1).equals(TRANSACTION_TYPE_BUFFER)) {
> TypeError: serialized.slice(...).equals is not a function
>     at FeeMarketEIP1559Transaction.fromSerializedTx
> ```

Try this `TransactionFactory.fromSerializedTx(Buffer.from(s_tx.slice(2),'hex')` and report back. I think that will take care of it

**Comment by erc2107** [comment]
@acolytec3 I can confirm that `TransactionFactory` method works!! `TransactionFactory.fromSerializedData()`
