### ISSUE TITLE
Switch secp256k1 backend to noble-curves in the monorepo

### ISSUE THREAD

**Issue by paulmillr** [ethereumjs/ethereumjs-monorepo#2627]
1. https://github.com/ethereum/js-ethereum-cryptography/pull/74 is reviewed and merged, switching backend from noble-secp256k1 to more secure noble-curves (audit was in feb)
2. ethereum-cryptography 2.0.0 is released
3. I will make a monorepo PR upgrading to curves

Main API differences are `sign()` return type (`{r, s, recovery}` instead of ui8a), `recoverPublicKey` has been moved to `Signature#recoverPublicKey`; default keys became compressed.

Seems there are minor releases around the corner. Assuming the monorepo PR is good, and reviewed; could this get in before minor release? It's not great to have to wait a bunch of months for security improvement which curves posess.

**Comment by jochem-brouwer** [comment]
First thought: I think we can do this in a maintenance release on `master`. WDYT @holgerd77 ? :smile:

**Comment by holgerd77** [comment]
Does this support both ESM and CJS?

**Comment by paulmillr** [comment]
https://github.com/ethereumjs/ethereumjs-monorepo/pull/2639

**Comment by holgerd77** [comment]
> curves: yes, just like secp module did before
> 
> ethereum-cryptography: no, just like before. we've been talking on adding esm to the repo, can do this if you push

Ah ok, yeah, I was rather wondering the other way around, if it would be "ESM only" (which would be a blocker I guess).
