### ISSUE TITLE
Revisit `EthersStateManager` implementation

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ethereumjs-monorepo#2632]
We should review the implementation of the `EthersStateManager` in light of `develop-v7` and how the caching is done and think through the following:
- The use of the `accountCache` 
- What should the `copy()` method do in terms of copying the cache objects
- Should we finish out the `ForkedProvider` PR #2442

**Comment by holgerd77** [comment]
Yes, I thought so as well along the refactoring work, guess some stuff in EthersStateManager can now stripped down a bit. Maybe this also helps on the performance side to build upon the existing and now more extensive cache structure.

**Comment by holgerd77** [comment]
I will already close here for better issue oversight.

Account cache is already in use, copy() method finds some adoption in #2720 and the `ForkedProvider` has its own PR (and is generally not breaking I guess?).
