### ISSUE TITLE
Opcodes not running

### ISSUE THREAD

**Issue by stan7123** [ethereumjs/ethereumjs-monorepo#2654]
I'm trying to run arbitrary opcodes based on the code from the example.
The thing is that when running the code from separate project in pure JS and with packages installed via npm it works, while when I clone the monorepo and create the file in `packages/evm/benchmarks/` directory I get no output while EVM steps further.
I have a feeling that this might be related to how the modules are imported.

In monorepo code (which is not processing opcodes), I have:
```
const { ArgumentParser } = require('argparse')
import { Block } from '../../block/dist'
import { Blockchain } from '../../blockchain/dist'
import { Common, Hardfork, ConsensusType, ConsensusAlgorithm } from '../../common/dist'
import { MemoryLevel } from 'memory-level'
import { EEI } from '../../vm/dist'
import { EVM, EVMInterface } from '../dist'
import { DefaultStateManager } from '../../statemanager/dist'
import { Address, MAX_INTEGER_BIGINT, KECCAK256_RLP_ARRAY } from '../../util/dist'
import type { AbstractLevel } from 'abstract-level';

sync function main () {
  const parser = new ArgumentParser({ description: 'Benchmark arbitrary bytecode.' })
  parser.add_argument('bytecode', { help: 'Bytecode to run', type: 'str' })
  let args = parser.parse_args()
  let opcodes = args.bytecode
  const common = Common.custom(
      {
        chainId: 1234,
        networkId: 1234,
        defaultHardfork: Hardfork.Shanghai,
        consensus: {
          type: ConsensusType.ProofOfStake,
          algorithm: ConsensusAlgorithm.Casper,
        },
        genesis: {
            gasLimit: 10000000000,
            difficulty: 1,
            nonce: "0x0000000000000000",
            extraData: '0x0',
        },
        comment: 'Custom empty chain for benchmarks',
        bootstrapNodes: [],
        dnsNetworks: [],
      })
  const stateManager = new DefaultStateManager() //Creates in memory MapDB
  const db = new MemoryLevel() as AbstractLevel<string | Buffer | Uint8Array, string | Buffer, string | Buffer>

  const blockchain = await Blockchain.create({common, db})
  const eei = new EEI(stateManager, common, blockchain)
  const evm = new EVM({common, eei})
  evm.events.on('step', function (data) {
    console.log(`Opcode: ${data.opcode.name}\tStack: ${data.stack}`)
  })
  evm
    .runCode({
      code: Buffer.from(opcodes, 'hex'),
      gasLimit: BigInt(0xffff),
    })
    .then((results) => {
      console.log(`Returned: ${results.returnValue.toString('hex')}`)
      console.log(`gasUsed: ${results.executionGasUsed.toString()}`)

      console.log(process.memoryUsage());
    })
    .catch(console.error)
}
main()
  .then(() => {
    process.exit(0)
  })
  .catch((e: Error) => {
    throw e
  })
```

And in a separate project in pure JS:
```
import { Address } from '@ethereumjs/util'
import { Blockchain } from '@ethereumjs/blockchain'
import { Chain, Common, Hardfork, ConsensusType, ConsensusAlgorithm } from '@ethereumjs/common'
import { MemoryLevel } from 'memory-level'
import { EEI } from '@ethereumjs/vm'
import { EVM } from '@ethereumjs/evm'
import { DefaultStateManager } from '@ethereumjs/statemanager'

...SAME CODE AS IN THE FIRST EXAMPLE...
```

What am I doing wrong in monorepo case?

**Comment by acolytec3** [comment]
Thank you for reporting this issue.  I'm able to reproduce your result (which seems to potentially indicate an odd edge case in our code) though let me recommend an easier way of getting to your desired outcome.  This below variation on your script can be run from with `ethereumjs-monorepo/packages/evm` and produces the desired outcome.  The main change is to use `runCall` instead of `runCode` which as is documented in the method notes, isn't intended to be called directly from the `evm` class.  `runCall` is the preferred way to execute raw bytecode in the `evm` with minimal fuss.

```js
const { ArgumentParser } = require('argparse')
import { Blockchain } from '@ethereumjs/blockchain'
import { Common, Hardfork, ConsensusType, ConsensusAlgorithm } from '@ethereumjs/common'
import { MemoryLevel } from 'memory-level'
import { EEI } from '@ethereumjs/vm'
import { EVM } from '@ethereumjs/evm'
import { DefaultStateManager } from '@ethereumjs/statemanager'
import { Trie } from '@ethereumjs/trie'
import { Address } from '@ethereumjs/util'

async function main() {
  const parser = new ArgumentParser({ description: 'Benchmark arbitrary bytecode.' })
  parser.add_argument('bytecode', { help: 'Bytecode to run', type: 'str' })
  let args = parser.parse_args()
  let opcodes = args.bytecode

  const common = Common.custom({
    chainId: 1234,
    networkId: 1234,
    defaultHardfork: Hardfork.Shanghai,
    consensus: {
      type: ConsensusType.ProofOfStake,
      algorithm: ConsensusAlgorithm.Casper,
    },
    genesis: {
      gasLimit: 10000000000,
      difficulty: 1,
      nonce: '0x0000000000000000',
      extraData: '0x0',
    },
    comment: 'Custom empty chain for benchmarks',
    bootstrapNodes: [],
    dnsNetworks: [],
  })
  const db = new MemoryLevel() as any

  const stateManager = new DefaultStateManager() //Creates in memory MapDB

  const blockchain = await Blockchain.create({ common, db })
  const eei = new EEI(stateManager, common, blockchain)
  const evm = new EVM({ common, eei })
  evm.events.on('step', async function (data) {
    console.log(`Opcode: ${data.opcode.name}\tStack: ${data.stack}`)
  })
  try {
    const results = await evm.runCall({
      code: Buffer.from(opcodes, 'hex'),
      gasLimit: BigInt(0xffff),
      to: Address.fromPrivateKey(Buffer.allocUnsafe(32)),
    })

    console.log(`Returned: ${results.execResult.returnValue.toString('hex')}`)
    console.log(`gasUsed: ${results.execResult.executionGasUsed.toString()}`)
    console.log(process.memoryUsage())
  } catch (err) {
    console.log(err)
  }
}
void main()
```

Assuming your script is still placed in `ethereumjs-monorepo/packages/evm/benchmarks/` - run the script using `npx ts-node benchmarks/script.ts -- [your bytecode here]`

On the question of importing directly from the various `dist` folders, you can certainly do that though no need as using the namespaced imports (e.g. `import { Address } from '@ethereumjs/utli'` still works since our monorepo uses `npm workspaces` which automatically symlinks all the packages in the monorepo into the npm global package cache.

**Comment by stan7123** [comment]
@acolytec3 Thank you for the response.
After looking around this example, I realized that in my example I was not waiting for `runCode` to finish thus `main` was finishing immediately.

What I want to achieve is to run bytecode on EVM as efficiently as possible. From what I explored, I saw that `runCode` runs less overhead code before executing operations on the interpreter object, so I think I will be using this method.
From the diagram on the repository main page I see that EVM depends only on `Common`, but yet in the example we have to create blockchain and EEI objects. Do you think there's an easier way to set up EVM to run bytecode?

Anyway, thanks for your code, and remark about imports. It gave me more paths to explore and debug.

**Comment by acolytec3** [comment]
>From the diagram on the repository main page I see that EVM depends only on Common, but yet in the example we have to create blockchain and EEI objects. 

I don't think those diagrams are accurate to our current implementation. Without Blockchain and EEI, you have no access to the correct environmental data for such things as the `BLOCKHASH` opcode.

**Comment by jochem-brouwer** [comment]
The diagram is right, there is no dependency on blockchain/EEI (EEI is in the VM package). This is because EVM expects an interface to these objects, so it has no dependency on the package itself.
