### ISSUE TITLE
how to dependencies the monorepo in other project

### ISSUE THREAD

**Issue by f5cs** [ethereumjs/ethereumjs-monorepo#2714]
"dependencies": {
      "@ethereumjs/client":"^0.7.1",
}
**I had try it,but get the error:**
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c npm run binWorkaround
npm ERR! > @ethereumjs/client@0.7.1 binWorkaround
npm ERR! > test -f dist/bin/cli.js || echo 'install fails if bin script does not exist (https://github.com/npm/cli/issues/2632), creating placeholder file at "dist/bin/cli.js"' && mkdir -p 'dist/bin' && touch dist/bin/cli.js
npm ERR!
npm ERR! 'install fails if bin script does not exist (https://github.com/npm/cli/issues/2632), creating placeholder file at "dist/bin/cli.js"'

**Comment by holgerd77** [comment]
Our client is meant to be used as a standalone product and not as a library. Do you really need respectively want to import functionality from the client package? We do have 13 different packages (see `packages` folder) which you can import separately, you might want to have another look what functionality you need.

Will close here for now.
