### ISSUE TITLE
v7: test tree-shaking thoroughly

### ISSUE THREAD

**Issue by paulmillr** [ethereumjs/ethereumjs-monorepo#2718]
v7 is near and it would be great to test / optimize tree-shaking with ESM. I've used the following approach to reduce bundle size by 20%:

1. Create input.js with some basic imports. Execute the command

```ts
npm init -y
npm i esbuild
npx esbuild --bundle input.js --outfile=output.js
```

2. Check output.js and see which imports are unnecessary.
3. Add PURE annotations and executable closures to pure exports which look impure to bundlers. This one may be important. See https://github.com/paulmillr/noble-curves/commit/ff5b231e31a2785fdce0e5e55b380a3b303aac64
4. Build again and check for improvements.

**Comment by holgerd77** [comment]
That makes a lot of sense, thanks for the instruction on this to get started! 🤩

Short procedural note: we have now merged the `develop-v7` branch into `master` (so now basically all we do (unless it goes to `maintenance-v6`) will make it into the breaking releases, so the `target: develop-v7` label is now obsolete.

Will re-label here a bit and delete this label and generally do a quick PR on the docs to make this more clear!

**Comment by roninjin10** [comment]
Please let me know if there is anything I can jump in and help with. Happy to contribute

**Comment by roninjin10** [comment]
🤣

**Comment by holgerd77** [comment]
Superseeded by #3446, will close.
