### ISSUE TITLE
Tx: Replace TypedTransaction type with generic Interface

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#2726]
When working on improving Optimism Bedrock compatibiliy in #2713 I realized that we still have got this unholy [TypedTransaction](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/tx/src/types.ts#L100) type being used as a generic basis for tx input in the upper libraries, e.g. [here](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/block/src/block.ts#L371) as constructor option typing in the `Block` library.

This is how this type looks like, so it is just a junction of all tx types we have got implemented so far.

```typescript
export type TypedTransaction =
  | Transaction
  | AccessListEIP2930Transaction
  | FeeMarketEIP1559Transaction
  | BlobEIP4844Transaction
```

This is very much not sustainable and severly limits the possibility to use custom tx types in our other libraries, particularly the `Block`, `Blockchain` and `VM` libraries, `Client` is a bit more secondary but should be updated nevertheless.

This type should be completely removed and updated with a proper interface as we have for the StateManager (recently moved and now in the `@ethereumjs/common` package [here](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/common/src/interfaces.ts#L41)).

This interface should expose a common set of shared methods, randomly citing `raw()`, `isSigned()`, `hash()` as safe candidates - optimally the (shared) static constructors like `fromValuesArray()` as well (not sure, is this possible?) - but safe to say various others as well.

Larger part of typing in the mentioned upstream libraries should then be updated to use this new interface, basically all use cases where things should generically work for the various tx types.

Here are the most prominent update cases I can think of right now:

- As mentioned, constructor options (e.g. [here](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/block/src/block.ts#L371)) for the `Block` library
- VM [runTx options](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/vm/src/types.ts#L317), various others
- VM [block builder](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/vm/src/buildBlock.ts)
- Client: everything in [tx pool](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/client/src/service/txpool.ts), various others

It would be great if *this* could still make in the breaking release round, since this would free us for various ideas and expansions, already have some in mind 🙂, and would be a first important step towards a more generic and flexible-to-use tx package. I think this should be doable though, at the end this should be a very much manageable amount of work.

Note that this is likely not completely a simple update task. I would expect that this will uncover some inconsistencies in the tx API, respectively we should take the occasion to fix if we (re-)discover these.

I can't remember myself why we did the following e.g. respectively how the following signature evolved but I would very much say that method signature definitions like

```typescript
validate(): boolean
validate(stringError: false): boolean
validate(stringError: true): string[]
validate(stringError: boolean = false): boolean | string[] {
```

would very much deserve a simplification along this work, just to name an example. 🙂

Maybe some selected methods (eventually some signature related ones?) might also be due for a rename, better be a bit cautious with this though.

**Comment by scorbajio** [comment]
I can take a look into this one if no one else has started working on it.
