### ISSUE TITLE
Simplify blob transaction network wrapper constructor

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ethereumjs-monorepo#2751]
We should update the `fromTxData` static constructor for 4844 transactions to allow just the data for associated blobs to be passed as part of the `txData` opts in the constructor and then generate the blobs, commitments, and versioned hashes inside the constructor rather than forcing the user to take 3 extra steps to generate each of these data elements when it's just boilerplate than can be done by our libary.  An ideal solution would have the following:
1. The `fromTxData` constructor on `EIP4844BlobTransaction` adds a new option called something like `blobData[]` which is just an array of strings. 
2. If this field is populated, check to verify that `blobs`, `commitments`, and `versionedHashes` are all undefined (and throw if they aren't).
3. If `blobData` contains blob data, generate the `blobs`, `commitments`, and `versionedHashes`, and then populate these fields in the transaction.

**Comment by holgerd77** [comment]
Without even trying to understand the task here: since there *was* some work on constructors (I guess?) lately from Block, Tx has this been addressed? If not: would this change here be breaking and we should therefore do soonish?

**Comment by acolytec3** [comment]
Oh, sorry, this is actually already done. Don't remember the PR number off hand but we merged this a couple of weeks ago. I obviously forgot to link it to this issue.
