### ISSUE TITLE
implement debug_traceCall

### ISSUE THREAD

**Issue by drortirosh** [ethereumjs/ethereumjs-monorepo#2753]
allow the use of debug_traceCall()
This is required for ERC4337 implementation

**Comment by holgerd77** [comment]
I have not enough context on this issue, maybe @acolytec3 can shed a light here? Didn't you have implemented some trace RPC call lately? 🤔 Is this the same/related/whatever?

**Comment by acolytec3** [comment]
Are you possibly referring to [`debug_traceCall`](https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-debug#debug_traceCall)? I don't see anything regarding debug tracing in the `eth_call` docs.

**Comment by holgerd77** [comment]
Yes.

How close is this to the requested feature? Is this just a small integration?

(again, completely can't judge)

**Comment by acolytec3** [comment]
Ah, sorry, shouldn't try to respond to questions before coffee...my instinct is this should be pretty simple to build out.  I can put it on the todo list.

**Comment by acolytec3** [comment]
@drortirosh 6 weeks late but I've started on this.  Hopefully won't be too much of a lift to get tests implemented and then get this integrated.,
