### ISSUE TITLE
v, r and s ignored when doing tx.getSenderAddress

### ISSUE THREAD

**Issue by cyrusadkisson** [ethereumjs/ethereumjs-monorepo#2759]
I'm using the following script which produces a sender address.

```
var { Transaction } = require('@ethereumjs/tx');
var { bufferToHex } = require('@ethereumjs/util');
var txData = {
    nonce: 0,
    gasPrice: 50000000000, 
    gasLimit: 1000000,
    to: "0x064b73510a0d3ddcf56056a2d159a1d6035bbafd",
    value: 1000000000000000, 
    data: "0x0a98c1ff00000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000010", // the ABI-encoded data
    v: 27,
    r: '0x2222222222222222222222222222222222222222222222222222222222222222',
    s: '0x2222222222222222222222222222222222222222222222222222222222222222'
};

var tx = Transaction.fromTxData(txData, { chain: "goerli" });

if (tx.verifySignature()) {
    console.log('Signature checks out!');
    console.log('This transaction is signed by: ' + bufferToHex(tx.getSenderAddress()));
} else {
    console.log('Invalid signature');
}
```
If I change any of the parameters _except_ v, r and s, the resulting sender address changes, as expected.

However, if I change v, r, and s, the resulting sender does not change, which is _not_ expected.

If v, r, and s are being ignored, then on what basis is the resulting address being generated?

Any idea what's going on here? Am I misunderstanding the function of tx.getSenderAddress()?

**Comment by jochem-brouwer** [comment]
I cannot reproduce this. Can you give two example scripts which give the behavior which you describe, plus the versions of your packages which you are using?

**Comment by cyrusadkisson** [comment]
I can't reproduce this either, now. Very strange. Maybe a "const" declared somewhere?

Sincere apologies. Closing.
