### ISSUE TITLE
checkpoint/reverting with the EthersStateManager doens't work

### ISSUE THREAD

**Issue by yann300** [ethereumjs/ethereumjs-monorepo#2766]
using checkpoint/revert with EthersStateManager doesn't seem to work:
```
private contractCache: Map<string, Buffer>
private storageCache: Map<string, Map<string, Buffer>>
```

these values aren't actually being reverted.

**Comment by acolytec3** [comment]
Unfortunately, the initial version of the `etherStateManager` has a very primitive caching mechanism that doesn't support contract storage. In our next breaking release, we've completely refactored the caching mechanism and it should work correctly.

**Comment by yann300** [comment]
ok thanks for the prompt reply, do you think there's a workaround so we don't have to wait for the breaking release?
or when do you plan this release?

**Comment by acolytec3** [comment]
The current goal is to get out a release candidate in the next 2-4 weeks. In the meanwhile, you could point your dependency in package.json to the head commit of our current master branch and build from source if you want to experiment. I'm not aware of any more changes planned to the `statemanager` API. Do note though that this release has some pretty big breaking changes to be aware of, most notable that we switch `Buffer` to `Uint8Array`. We are also still working through offering full ESM and CJS builds.

**Comment by holgerd77** [comment]
Our breaking releases are now really imminent, with pre-releases (RC1) intended to be released this Thursday. Will therefore close here as wont-fix, the effort to port this back is just too high.

**Comment by holgerd77** [comment]
(@acolytec3 side note: you claim that this will work in the breaking releases? Are we sure on this? 🤔 Might it make sense to add a few test cases here? (or see if we already have some, would rather think not though))

**Comment by acolytec3** [comment]
I'll take a look. Should be easy enough to expand our existing test suite for ethersStateManager.

**Comment by acolytec3** [comment]
We did have a couple of gaps in the `EthersStateManager` logic as far as checkpointing and reverting cached values.  These should be fixed with

**Comment by Yasaica2015** [comment]
D
