### ISSUE TITLE
Copy() -> shallowCopy() Copy Method Renaming for State Containing Libraries

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#2823]
Ah, going over PRs I am just realizing that #2795 is very much only a small part of the copy-method renaming and this renaming should be extended to all state containing (and: copying libraries), I would also be pretty much sure that we discussed this along these lines in the respective calls.

So from my first look this would be:

- VM
- StateManager
- Blockchain
- Trie
- Update: Ethash not (no copy() method)
- Update: EVM as well

This list should get a cross-check though both on if libraries added make sense as well as if there might be a library missing. I am 88% confident though that this "gets it". 😋

Will assign @scorbajio since he already did the first-round task here. Task would have some urgency, so this would need to be finished during the week so that this is ready for the (pre-)releases.

**Comment by scorbajio** [comment]
> Ah, going over PRs I am just realizing that #2795 is very much only a small part of the copy-method renaming and this renaming should be extended to all state containing (and: copying libraries), I would also be pretty much sure that we discussed this along these lines in the respective calls.
> 
> So from my first look this would be:
> 
>     * VM
> 
>     * StateManager
> 
>     * Blockchain
> 
>     * Trie
> 
>     * (not so important, but maybe: Ethash?)
> 
> 
> This list should get a cross-check though both on if libraries added make sense as well as if there might be a library missing. I am 88% confident though that this "gets it". yum
> 
> Will assign @scorbajio since he already did the first-round task here. Task would have some urgency, so this would need to be finished during the week so that this is ready for the (pre-)releases.

I can confirm all of the listed ones are shallow copying. I was not able to locate a copy function for Ethash.

**Comment by TimDaub** [comment]
Actually this confused me in the ethereumjs/trie library and I think this is a pitfall issue.

https://github.com/ethereumjs/ethereumjs-monorepo/blob/499c49677bb6994df13a2642e4d04403f77bf42d/packages/trie/src/trie.ts#L900 trie.copy() mandates db.copy(), but then all the examples https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/trie/examples don't use shallowCopy, they use copy.

**Comment by jochem-brouwer** [comment]
@TimDaub thanks for reporting. It seems that we do not run example tests in our trie library.

We should ensure that all packages which have examples test those. (Note, today I actually tried this on devp2p on another task, but these examples never end so we cannot test those... Or we should add a timeout there)

**Comment by scorbajio** [comment]
I updated the examples to reflect the naming changes but yes some of our examples can use tests.

**Comment by jochem-brouwer** [comment]
We have this running on CI:

`npm run examples` (from monorepo root)

It will run examples on a package if the `examples` script is there in package.json (see for instance VM: `"examples": "ts-node ../../scripts/examples-runner.ts -- vm"`). Worth adding to packages which have example dirs (can be done in a different PR)
