### ISSUE TITLE
Monorepo: Node version tests failing

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#2829]
Currently the daily Node version tests are failing, see e.g. [this run](https://github.com/ethereumjs/ethereumjs-monorepo/actions/runs/5384850991/jobs/9773249946).

This should be fixed before we do the RC releases. 🙂 

It actually seems from the logs this is browser test related.

I wonder why we run the browser tests *at all* in this Node.js context?

So my initial cautious suggestion would be that we just limit this to `npm run test:node` runs for all libraries we test?

**Comment by jochem-brouwer** [comment]
Will take a look at this now
