### ISSUE TITLE
Remove Last Remaining Node.js Primitives

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#2837]
I played a lot with bundlers today (Rollup, Parcel, Vite), and where these constantly have problems are our remaining Node.js primitives.

So Rollup was breaking in Util already, using the `https` Node module for the fetcher, Vite in EVM using Node.js native `promisify`.

I would therefore make a strong pledge that we remove these last remaining few Node.js primitive usages.

Will confirm below once I have them together, but from my impression no usage is life-critical here so we should consider to replace or in a worst case remove. Just not worth to sacrifice browser compatibility for some nice side functionality or performance gain.

So, following occurrences:

'https' in `Util.provider`:
Replace or remove the functionality

'util.promisify' in `EVM` (`evm.ts`)
'util.promisify' in `VM` (`vm.ts`)
Replace or take performance loss into account (stated as "huge", would be good to have some numbers/relation here).

Ah, uh, yeah. Seems these are already the 2 left cases. Ok, this should be a some easy grasp.

**Comment by jochem-brouwer** [comment]
`util.promisify` is removed in https://github.com/ethereumjs/ethereumjs-monorepo/pull/2835 (except that it is still in the RLP tests, but this should not be a problem for the bundlers (?))

**Comment by holgerd77** [comment]
Yes, tests do not matter.

**Comment by holgerd77** [comment]
Can confirm that it's removed for both EVM and VM.

**Comment by holgerd77** [comment]
Closing in favor of #2850
