### ISSUE TITLE
Util/Monorepo: Clean-Up bytes module Usage / Remove ethereum-cryptography helper usage

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#2843]
With the new releases the `@ethereumjs/util` `bytes` module helper methods like `prefixedHexStringToBytes()` will get an extremely prominent role when using our library.

We should therefore make sure, that things are really consistent here and this provides a consistent basis for conversions with a stable API to use.

Not a super big job, we are mostly there and Andrew laid out great foundations here.

Nevertheless some left over TODOs I realized when writing release notes and bringing this together in #2832:

- [x] (1) Maybe the biggest one: we use and also re-export in Util some helper methods from `ethereum-cryptography`, namely `bytesToHex`, `bytesToUtf8`, `concatBytes`, `equalsBytes`, `utf8ToByte`. Throughout our libraries we nevertheless have a wild mix of using these methods directly by importing from `ethereum-cryptography`, so e.g. by having `import { bytesToHex, equalsBytes, hexToBytes } from 'ethereum-cryptography/utils.js'` in `Blockchain`, just to give a random example. This should be unified and cleaned up to only use the imports from `Util`, so that this doesn't establish as a common practice to do this wild mix here
- [x] (2) The `bytesToHex` re-exported from `ethereum-cryptography` is (somewhat) redundant respectively inconsistent with our `0x` prefix handing and current naming scheme. The re-export should be removed in favor of a `prefixedHexStringToBytes` usage (I have looked through the occurrences, a lot of places a "just" console.log() or debug outputs and can be easily converted, some usages need some relatively close look though to not miss something (should nevertheless be done), e.g. if hex strings are used as keys for a cache (needs some close look on both all writes and accesses so to make sure that cache keys are accidentally never found again by always looking for the unprefixed version at some place))
- [x] (3) The methods `bytesToBigInt`, `bigIntToBytes`, `bytesToInt` are misplaced (in the `bytes` module) and should be moved up and re-ordered properly
- [x] (4) Function declaration format is a wild mix of the short and `function` containing format, this should be unified to the `() => {}` format (so e.g. `export const bigIntToBytes = (num: bigint): Uint8Array => {...}`
- [x] (5) Discussion: is the `concatBytesNoTypeCheck()` method really worth to keep? 🤔 From the code docs: "Can give small performance gains on large arrays". From the formulation this sounds like an eventual not so worth trade off, can't judge on this though, might be also just a formulation thing and gains are more significant in reality. Likely @acolytec3 can shed a light here -> Update: decision to simplify (only use the concatBytesNoCheck method, rename this to concatBytes and skip the re-export from ethereum-cryptography), see thread below
- [x] (6) The `toUtf8()` method doesn't fit into the naming scheme and is not used anywhere in the code base. I would pledge to have this removed
- [x] (7) `bigIntToHex()` name is inconsistent and might need to be renamed to `bigIntToPrefixedHexString()` (pending the below discussion)
- [x] (8) The `compareBytes()` method seems to be not used within the whole code base. Is this necessary?

That should be it. Lol. 😋

And *then* - since we now have a unifed way of working with 0x-prefixed hex strings within the whole code base we can finally discuss (came to this in a second round after writing this together)`:

Do we *now* actually want to simplify these `bytesToPrefixedHexString()` names again and go with the shorter version? 🤔

So this would be:

- `bytesToPrefixedHexString()` -> `bytesToHex()`
- `prefixedHexStringToBytes()` -> `hexToBytes()`
- `intToPrefixedHexString()` -> `intToHex()`
- `unpadHexString()` -> `unpadHex()` (a bit optional maybe)
- `bigIntToHex()` -> can then stay this way! 🙂

I think this would *then* be ok if we have this consistent in the code base and these other names really are "monsters" to deal with. 😆 (So I would have a relatively strong tendency to do)

Side note: I would nevertheless highly recommend to sequentially go through the TODO steps before. This is not so much more extra work and otherwise there is a high danger to not do this right (e.g. by forgetting to go from non-prefixed to prefixed for `bytesToHex` in the first round.

**Comment by acolytec3** [comment]
As far as the `concatBytesNoCheck`, method goes, I ran the issue during the Uint8Array conversion. In the version of this function in `ethereum-cryptography`, every element of the input is checked to verify it's a Uint8Array before concatenating and this check happens via a Array.map call which pushes each element on to the main JS stack. For `ethash`, where we concatenate very large arrays of bytes, this check was breaking things. Hence the need for a byte concatenation function that didn't check elements for type safety ahead of time.

**Comment by holgerd77** [comment]
> As far as the `concatBytesNoCheck`, method goes, I ran the issue during the Uint8Array conversion. In the version of this function in `ethereum-cryptography`, every element of the input is checked to verify it's a Uint8Array before concatenating and this check happens via a Array.map call which pushes each element on to the main JS stack. For `ethash`, where we concatenate very large arrays of bytes, this check was breaking things. Hence the need for a byte concatenation function that didn't check elements for type safety ahead of time.

Ah ok, interesting.

Just to loot out, not deeply enough in to have an own judgement on this: would it eventually be an option to simplify here by *only* use the `concatBytesNoCheck` method, rename this to `concatBytes` and skip the re-export from `ethereum-cryptography`? Or would this have other major disadvantages (can't completely judge what one is "loosing" without these checks and if this is significant or not)? 🤔

**Comment by acolytec3** [comment]
In my opinion, we're don't lose much by just using our version. Internally, we should trust typescript to warn us about any possible instances is passing the wrong input to the helper. If somebody is using our helpers outside of our code base, they should be responsible for managing their inputs.

**Comment by holgerd77** [comment]
> In my opinion, we're don't lose much by just using our version. Internally, we should trust typescript to warn us about any possible instances is passing the wrong input to the helper. If somebody is using our helpers outside of our code base, they should be responsible for managing their inputs.

Ok, will add to the TODO list above.

**Comment by jochem-brouwer** [comment]
Note: I use `compareBytes` in create trie range proof, see https://github.com/ethereumjs/ethereumjs-monorepo/pull/2821

**Comment by jochem-brouwer** [comment]
I will go ahead and tackle 1,3,4,5,6,8. (others have pending discussion)
