### ISSUE TITLE
Devp2p: Consolidate Types/Interfaces in types.ts

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#2849]
In the `devp2p` package the various exported types and interfaces are still cluttered throughout the library, e.g. `DPTOptions` directly in the `dpt.ts` module.

These should be consolidated and put into a unifed `src/types.ts` file as we have in the other packages.

So this would go for 1) exported types/interaces which are 2) somewhat "important"[tm] (to be judged by implementer) for the user, so this goes for all types/interfaces I guess which are part of the public API (e.g. like `DPTOptions`) and so used as either input or output value for a publicly callable method or constructor or similar.

**Comment by holgerd77** [comment]
Update: and the `Peer` constructor `constructor(options: any)` should urgently get a type. 😳

**Comment by holgerd77** [comment]
another update: events should also be typed (so e.g. `.on('peer:added', function (peer: any)`), but only if it doesn't get too laborious, we have done something similar in the client, maybe this can serve as a source for inspiration or one can directly take over.

**Comment by holgerd77** [comment]
Bonus task 2: 

There are various `any` typings also in other parts of the code, theoretically a no-go for such a sensitive library where one bug can mean the breakdown of the whole peer connection.

Optimally all `any` occurrences should be replaced, not sure if this getting too extensive here though.

**Comment by jochem-brouwer** [comment]
`devp2p/eth.ts`:

```typescript
  sendMessage(code: ETH.MESSAGE_CODES, payload: any) {
    const logData = formatLogData(bytesToHex(RLP.encode(payload)), this._verbose)
    if (this.DEBUG) {
      const messageName = this.getMsgPrefix(code)
      const debugMsg = `Send ${messageName} message to ${this._peer._socket.remoteAddress}:${this._peer._socket.remotePort}: ${logData}`

      this.debug(messageName, debugMsg)
    }
```

This is super expensive, we RLP encode the payload, then bytesToHex, then format it - even if we do not debug 😅

So, extra task here: review devp2p for these kind-of 'low hanging fruit' performance issues.
