### ISSUE TITLE
Monorepo: Add automatic examples Run to all Packages

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#2851]
Discussions around a Trie example issue https://github.com/ethereumjs/ethereumjs-monorepo/issues/2823#issuecomment-1616728740 revealed that we do not run all examples in CI which is not optimal.

@jochem-brouwer explained the mechanism below:

> We have this running on CI:
> 
> `npm run examples` (from monorepo root)
> 
> It will run examples on a package if the `examples` script is there in package.json (see for instance VM: `"examples": "ts-node ../../scripts/examples-runner.ts -- vm"`). Worth adding to packages which have example dirs (can be done in a different PR)

To have this solved "once and for all" we should simply add this `examples` script command to every package, having it a file already in the `examples` folder or not. 

Just tested, this simply exits if no example present and has no side effects, with no significant delay or something.

![grafik](https://github.com/ethereumjs/ethereumjs-monorepo/assets/931137/7222dcc6-c302-4685-8f9b-0b9b61525109)

Then we are on the safe side that also all new examples just get included, otherwise chances are high that this will got forgotten again and again on adding new examples to packages.

This will - relatively - likely also reveal issues in examples. These should be fixed along the way! 🙂

**Comment by scorbajio** [comment]
Working on this at #2862.
