### ISSUE TITLE
Remove mcl-wasm

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/ethereumjs-monorepo#2858]
Also remove EVM.create()

**Comment by holgerd77** [comment]
Just a quick note, that this doesn't get forgotten, would also be good if we get this into the pre-releases on Thursday.

**Comment by holgerd77** [comment]
Thanks! 🙏 I guess at the end this should be a relatively smallish PR with not more than 2 hours work, or do I underestimate?

Would actually be good if you could prioritize this a bit (maybe latest tomorrow?). I would love to do a browser size bundle estimate on the EVM before the RC releases and this would be necessarily be included to get accurate numbers.

**Comment by jochem-brouwer** [comment]
Yes, this should not be much work. I will start on this now :smile:

**Comment by holgerd77** [comment]
Ah, thanks! That actually really helps me! 👍

**Comment by jochem-brouwer** [comment]
Note: branch `monorepo-with-bls` or commit 364e80450d73d9e05b572f8f6d0713abc354d36f has monorepo state pre-this-PR if we ever want to re-introduce BLS.
