### ISSUE TITLE
EVM: Consolidate EVMRunCallOpts/EVMRunCodeOpts types

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#2860]
Small clean-up task: above option types are highly redundand and should be unified by inheritance or something.

(do not have the 100%-full picture: if it is necessary to create one base option type for this this artificial type should *not* be exported, not sure though, only necessary if one-way inheritance doesn't work because there might be distinct properties on each type)

**Comment by holgerd77** [comment]
Also, small note, maybe to clarify by @jochem-brouwer: I am not getting this `evm` optional parameter for `EVMRunCodeOpts`. One can pass an evm to an evm here? 🤔

**Comment by jochem-brouwer** [comment]
I just checked, it seems to have no references anywhere, so it can be safely removed. (The option indeed also makes no sense, if we could pass a custom EVM then the `runCode` should be made static as well...)

**Comment by holgerd77** [comment]
Ok cool, can you take this? 🙂

**Comment by jochem-brouwer** [comment]
Yup!
