### ISSUE TITLE
Node 18/20 Nightly CI Tests failing

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#2865]
Currently the Node 20 tests from the respective [node-versions.yml](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/.github/workflows/node-versions.yml) workflow running nightly are [failing](https://github.com/ethereumjs/ethereumjs-monorepo/actions/runs/5470665981/jobs/9961007079) with:

![grafik](https://github.com/ethereumjs/ethereumjs-monorepo/assets/931137/2265c68d-8f9b-4f8f-88e6-e5484f53b683)

This should be examined and fixed. 🙂 

Procedural note: it works best to temporarily add the workflow to the PR run, otherwise it is really hard to decide (or rather: not really possible) if things are really working (or if someone has an alternative (better) approach, please drop a note below).

**Comment by jochem-brouwer** [comment]
(should we add a prio urgent here?)

**Comment by holgerd77** [comment]
@jochem-brouwer seems we *need* to add a prio urgent here, otherwise noone is picking this up, yes. 😂

And - yes - this should really be adressed before we do the releases. Making sure that our libraries run with the current latest Node versions is something we should at least substantially *try* to achieve. Sometimes there are blockers but this might in fact be a small thing.

Have no idea though. Needs some investigation.

**Comment by holgerd77** [comment]
So, and - yes - CI still failing, [here](https://github.com/ethereumjs/ethereumjs-monorepo/actions/runs/5503134068) is the latest run.

**Comment by jochem-brouwer** [comment]
This is weird, I thought I addressed this, and did a search:

https://github.com/ethereumjs/ethereumjs-monorepo/issues/2829

https://github.com/ethereumjs/ethereumjs-monorepo/pull/2839

So something re-broke?

**Comment by holgerd77** [comment]
This issue is from 4 days ago. 😋

**Comment by holgerd77** [comment]
(so, yes, something likely re-broke, but which is really not unlikely, we just did so many changes in the last 2 weeks)

**Comment by scorbajio** [comment]
Should keep an eye out on tests to see if relaxing timing constraints results in less time outs on test runs.

**Comment by holgerd77** [comment]
Closed by #2928
