### ISSUE TITLE
What does the VM do to code before putContractCode is called

### ISSUE THREAD

**Issue by skilesare** [ethereumjs/ethereumjs-monorepo#289]
I used an example I found(https://github.com/ethereumjs/ethereumjs-vm/issues/128) to deploy code using vm.runTX

The code is super simple.  Solidity:

    pragma solidity ^0.4.15;

    contract TestTime {

    function ayear() constant returns (uint256){
      return 1 years;
    }
   }

Remix outputs this as the code:

    code = "0x60606040523415600e57600080fd5b60a28061001c6000396000f300606060405260043610603f576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff168063257c8c89146044575b600080fd5b3415604e57600080fd5b6054606a565b6040518082815260200191505060405180910390f35b60006301e133809050905600a165627a7a723058202e0505c5235858e9b30b642de84fb21c102bdd86b3f7dfbdda1a1f80fb90fd900029"

I added a console.log to the saveCode method of the runCall function to output exactly what was being written to the chain:

    console.log('saving this code:')
    console.log(vmResults.return.toString('hex'))

It outputs the following code:
0x606060405260043610603f576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff168063257c8c89146044575b600080fd5b3415604e57600080fd5b6054606a565b6040518082815260200191505060405180910390f35b60006301e133809050905600a165627a7a723058202e0505c5235858e9b30b642de84fb21c102bdd86b3f7dfbdda1a1f80fb90fd900029

It looks like 23 bytes "3415600e57600080fd5b60a28061001c6000396000f3006060604052" are taken out of the code when it is written to the tree.

The reason I need this I'm trying to sideload some code and storage into the evm without having to run the transactions.

I tried directly loading the original code with

    vm.stateManager.putContractCode "ca35b7d915458ef540ade6068dfe2f44e8fa733c", codeHex ,(contractError, contractTx) =>

When I do this and then run the code the return ends up being the original code!

If I switch out to the code with the missing 23 bytes it works like a champ. What am I missing about these 23 bytes?  Are they the opcode that saves the code to the blockchain?  If so, how do I remove them when I'm trying to move code from remix?  Will they always be the same so I can just find replace?

What am I missing?

**Comment by skilesare** [comment]
I may have answered my own question.

Looks like I need the 'runtime bytecode' section instead of the 'bytecode' section.  Would still love to hear what the differences are conceptually id anyone has any insight.

**Comment by skilesare** [comment]
The other thing I had to do to get this to work was to uncomment the following line from the stageManager.putAccount function. Not sure why it was commented out.

   self.trie.put(addressHex, account.serialize(), cb)
   //cb()

**Comment by Nathapon8899** [comment]
#128
#289

**Comment by holgerd77** [comment]
For reference for everyone who wants to dig into this: the line mentioned above is still [commented out](https://github.com/ethereumjs/ethereumjs-vm/blob/master/lib/state/stateManager.ts#L107), have no first-sight context though.

**Comment by holgerd77** [comment]
Another update: line in `StateManager.putAccount()` still [commented out](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/vm/lib/state/stateManager.ts#L101), updated with the new reference link working in the monorepo context with changed paths.

**Comment by holgerd77** [comment]
Will close here as suggested by @jochem-brouwer, thanks for this detailed explanation.
