### ISSUE TITLE
Failed to compile when creating new Trie in ReactJs

### ISSUE THREAD

**Issue by zengzengzenghuy** [ethereumjs/ethereumjs-monorepo#2890]
I tried to create `new Trie()` in Reatjs .tsx file, but it shows the error
```
./node_modules/@ethereumjs/trie/dist/db/map.js 10:31
Module parse failed: Unexpected token (10:31)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| class MapDB {
|   constructor(database) {
>     this._database = database ?? new Map();
|   }
|
```

I assume I need to setup database, but I tried it without setting a database in usual Typescript project which works fine. 

I've tried to changed the `tsconfig.json` to   
```
"compilerOptions": {
    "target": "es6",
    "lib": ["DOM", "ES6", "DOM.Iterable"],
```
but the error still occurs.

**Version**
@ethereumjs/trie": "^5.1.0"
"react": "^17.0.2",

**Comment by acolytec3** [comment]
Without having a full repo to work with, it looks like the issue here is the `??` nullish coalescing operator.  Are you able to upgrade your React version to 18 and try again? If not, I can probably get you a repo template that will work with 17 but might take some additional work.

**Comment by zengzengzenghuy** [comment]
Thanks for the response @acolytec3. Here is the full repo: https://github.com/zengzengzenghuy/Safe-on-Hashi-App.
I decided to create a backend for Merkle Proof logic here https://github.com/zengzengzenghuy/Safe-on-Hashi-App/tree/main/server.

> I can probably get you a repo template that will work with 17 but might take some additional work

Yeah that would be great! Appreciate that!

**Comment by acolytec3** [comment]
Are you only having issues on the react side or also with the backend server?  I compiled the server and didn't have any issues instantiating a trie with it.

**Comment by ScottyPoi** [comment]
> Are you only having issues on the react side or also with the backend server? I compiled the server and didn't have any issues instantiating a trie with it.

I have also been unable to replicate your error :thinking:

**Comment by holgerd77** [comment]
Will close due to inactivity here.
