### ISSUE TITLE
Fix Security Vulnerabilities

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#2903]
Currently when installing npm packages with `npm i` from monorepo root we have 12 high severe security vulnerabilities reported:

<img width="476" alt="grafik" src="https://github.com/ethereumjs/ethereumjs-monorepo/assets/931137/391ba908-f186-422c-9df1-daec6d2fc0bf">

Even while most of these will likely "only" occur in dev dependencies, we should nevertheless try to fix most - optimally all - of them, also for the reason to get a better picture and actually not *loose* any of the production dependency vulnerabilities.

If someone tackles, bonus task *would* actually be to find out if there is a good/easy way (especially regarding our more complex monorepo setup), to separate the reporting in a way that we at least have the possibility to just get a report on the production dependencies, so that we can run *that* more frequently and imminently fix if there is some vulnerability showing up.

**Comment by ScottyPoi** [comment]
On this :muscle:

**Comment by holgerd77** [comment]
I would call this sufficiently addressed and there is this one more specific issue Scotty opened on a remaining dependency in client.

Will close here.
