### ISSUE TITLE
Client Options CLI Test Suite

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#2906]
For the client we are still in the situation that too often things at the very usage level (CLI) break unnoticed, especially starting the client in different configurations and with different options do not always trigger one of the unit tests, and if so, this is mostly somewhat accidentally (which is better than nothing).

We noticed this last round with the `--rpc` flag - see #2902. While for this specific issue it turned out that our client CLI tests were just not running *at all* (haha, sigh) atm this kind of breakage could literally happen with all other not tested option (combinations).

We should therefore slowly (or quickly 😋) build up a somewhat complete CLI options test suite.

We *do* have working CLI tests for the client in `test/cli/`, e.g. [test/cli/cli-rpc.spec.ts](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/client/test/cli/cli-rpc.spec.ts).

The RPC test setup already provides some working boilerplate on how to test a CLI option.

We should expand this to have at least a basic on/off test for basically all options we have, to *minimally* ensure that the client is not completely breaking if an option is used. Better if at least some part of the functionality is also confirmed of course though if easily possible.

I think it would likely make sense to group these tests not in a single file but just somewhat by loose topics, somewhat like "networking", "rpc", "engine", "logs" - eventually 1-3 more - and so then `networking.spec.ts` (as a side task we should really remove the redundand `cli-*` name part for these test files respectively rename with git).

(another side-side task: it would be *generally* good if our options would get some grouping. Not sure if this can be done with the current CLI parser library. If it can it might make sense to directly integrate into this work here and *then* align the grouping from the help command `npm run client:start -- --help` (so this would be ideal if options are grouped there) with the groupings from the tests)

Another thing to consider: it is essential to make sure that these CLI runs do not trigger actual sync processes (with the eventual exception of 1-2 tests for the live sync iteself).

Currently I think (might need confirmation) this is achieved by using the `--dev` flag - see `cli-rpc.spec.ts`. It might be more robust and is likely more transparent on what the effect is to use `'--sync=none'` (sometimes maybe also `'--execution=false'`), now that we have these option selections.

**Comment by acolytec3** [comment]
One comment here, using `--dev` by itself just has the client start in the default mainnet setting (which isn't ideal).  You have to pass it a parameter like `--dev=poa` for it to actually start the devnet.  I think another improvement might be to have the client throw an error if `--dev` is passed without an option.
