### ISSUE TITLE
Monorepo: ESLint rule for file extensions on imports incomplete

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#2910]
The current custom linting rule for adding file extensions we have seems to be incomplete, following case is not detected:

<img width="343" alt="grafik" src="https://github.com/ethereumjs/ethereumjs-monorepo/assets/931137/4f38e210-4aa3-4df3-a0bb-b86e45d16ddd">

**Comment by acolytec3** [comment]
The lint rule unfortunately doesn't have a  "fix" feature.  It just makes it a lint error to not have a file extension.  That said, if you are using VS Code and are autocompleting imports, it should add the correct extension.  Are you looking for a lint rule to autocomplete this by adding the file extension?

**Comment by holgerd77** [comment]
No, it's just that the lint rule detects the one case (for `./enums`) but not the other (for `./types`).

**Comment by acolytec3** [comment]
Ah, I see now.  I bet it's not looking at `import type...` imports.  Let me look at the rule a little further.

**Comment by holgerd77** [comment]
Can be closed, exchanged on this in the chat, the type import won't make it into the final JS files in the distribution, so not relevant.
