### ISSUE TITLE
StateManager: Re-use proof Trie / static Proof Functionality

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#2927]
In the DefaultStateManager `verifyProof()` implementation a Trie object is newly created on two occasions each time the method is called.

This can and should be optimized I guess by one-time-instantiate a `_proofTrie` as a protected member of DefaultStateManager and re-use this trie object for the calls.

Another thought line I had was if it would rather make sense to make both Trie and SM `verifyProof()` methods static, didn't completely followed the thought but that might be an alternative option.

**Comment by jochem-brouwer** [comment]
By #2932 it seems like this should be re-opened? Will do.

**Comment by holgerd77** [comment]
Issue description is relatively short and generic, and proof functionality has been reworked on some broad basis in mentioned PRs, will close.

If there are follow-up needs please open a more specific issue.
