### ISSUE TITLE
FeeMarketEIP1559Transaction broadcast error: Web3ValidatorError:  must pass bytes validation

### ISSUE THREAD

**Issue by nfttrader00** [ethereumjs/ethereumjs-monorepo#2956]
hi everyone,

I'm trying to broadcast an tx to avalanche fuji test network but I am getting this error:

`
Web3ValidatorError: Web3 validator found 1 error[s]:
value "0x2,248,70,130,168,105,2,128,128,128,148,56,122,114,3,185,219,145,97,5,108,165,164,191,208,92,109,192,38,18,58,128,164,160,113,45,104,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,192,128,128,128" at "/0" must pass "bytes" validation
    at Validator.validate (.../api/node_modules/web3-validator/lib/commonjs/validator.js:48:23)
    at Web3Validator.validate (.../api/node_modules/web3-validator/lib/commonjs/web3_validator.js:35:32)
    at bytesToUint8Array (.../api/node_modules/web3-utils/lib/commonjs/converters.js:69:32)
    at hexToBytes (.../api/node_modules/web3-utils/lib/commonjs/converters.js:114:42)
    at Object.<anonymous> (.../api/node_modules/web3-eth/lib/commonjs/rpc_method_wrappers.js:427:171)
    at Generator.next (<anonymous>)
    at .../api/node_modules/web3-eth/lib/commonjs/rpc_method_wrappers.js:24:71
    at new Promise (<anonymous>)
    at __awaiter (.../api/node_modules/web3-eth/lib/commonjs/rpc_method_wrappers.js:20:12)
    at .../api/node_modules/web3-eth/lib/commonjs/rpc_method_wrappers.js:424:20 {
  innerError: undefined,
  code: 1100,
  errors: [
    {
      keyword: 'data["0"]',
      instancePath: '/0',
      schemaPath: '#',
      params: {
        value: '0x2,248,70,130,168,105,2,128,128,128,148,56,122,114,3,185,219,145,97,5,108,165,164,191,208,92,109,192,38,18,58,128,164,160,113,45,104,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,192,128,128,128'
      },
      message: 'must pass "bytes" validation'
    }
  ]
}
`

my code snippet is here: 

`
```

let currPrice = await web3.eth.getGasPrice();
// console.log(gasprice);
currPrice = web3.utils.toWei(currPrice.toString(), 'gwei');
const myData = contract.methods.mint(mintedAmount).encodeABI();
const rawTx = {
  from: '0x..',
  to: '0x...',
  data: myData,
  gasPrice: web3.utils.toHex(currPrice),
  nonce:Number(currNonce) + 1,
  chainId:'0xa869'

}


const tx =  FeeMarketEIP1559Transaction.fromTxData(rawTx );
tx.sign(hexToBytes(process.env.TEST_WALLET_PRIVATE_KEY))
const serializedTx = tx.serialize();
const raw = "0x" + serializedTx.toString("hex");
console.log(raw)
```
`

how can I solve this error?

pls, can u help me?

thk u,

**Comment by holgerd77** [comment]
On what line of your code snippet is this error occurring?

Also, can you paste what you have as `rawTx` in between (by inserting `console.log(rawTx)`)?

**Comment by gabrocheleau** [comment]
Can we close this?

**Comment by holgerd77** [comment]
No follow-up, will close.
