### ISSUE TITLE
Client: Block/tx profiling doesn't work with --executeBlocks flag

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#3008]
Currently the profiling output is not provided when the client is run with the `--executeBlocks` flag, this would be very helpful though to re-execute on already synced block ranges for repeated runs and would be therefore be good if we can quickly (I guess, should be pretty simple I would assume?) add.

Here is an example run I used which didn't work:

```shell
npm run client:start -- --executeBlocks=300000-300005 --vmProfileBlocks
```

**Comment by acolytec3** [comment]
Would you want the profiling output to run by default or only when specified by the `enablePrfofiler` param?

**Comment by holgerd77** [comment]
Not completely sure, just followed the code flow a bit in client, the fact that this *does not* work right now might eventually have something to do with that the VM is copied in the client `bin/cli.ts` file in `executeBlocks()`:

```typescript
async executeBlocks(first: number, last: number, txHashes: string[]) {
    this.config.logger.info('Preparing for block execution (debug mode, no services started)...')
    const vm = await this.vm.shallowCopy()
    //...
}
```

So might be that the profiler options are not passed through correctly on the VM/EVM copy methods?

At least I am not finding another source of error at first look.

**Comment by holgerd77** [comment]
Ah, got it. It's even more mundane, I have just selected a block range with no contract txs (including value transfering txs though).

Lol.

I guess we nevertheless want to improve here by simply printing out something like "Nothing to profile here" or whatever, will have a short look. This is otherwise confusing and misleading.

**Comment by acolytec3** [comment]
Is this solved then?

I was imagining it was something where the vmProfiler settings weren't being propagated to the instantiated client but looks like it was something different?

**Comment by holgerd77** [comment]
Yes, solved, will close.
