### ISSUE TITLE
StateManager: add (persistent) Code Cache

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#3021]
StateManager (SM) caches have gotten a large rewrite in #2630 (maybe not such a good point of reference since a bit intimidating due to the sheer size of code changes, so just for eventually getting some loose overview on code parts touched eventually), followed by several PRs with bug fixes.

This work introduced more intelligent caches for accounts and storage data, which can be used in a persistent way in the client, reaching over the span of a single tx or block. Caches are now also more resistent to attacks like where a lot of data (e.g.: new accounts) is added throughout EVM execution and at the end things are reverted. This is by adding a new `diffCache` layer which only stores the proper differences between StateManager checkpoints and on a commit things are persistet in the upper layer and on a revert things are thrown away.

The respective cache tests in SM provide a lot of scenarios and examples in which the diff cache is used.

While we now have these two proper caches, one cache is still not updated and exists still in its rudimentary form in `stateManager.ts`: the code cache.

This issue is for triggering a change here. 😋

The code cache should be added in a similar way like the other two caches, so that this complements our cache suite, and then so having a new `cache/code.ts` or so file with the cache which is being called into from `stateManager.ts` and (I guess?) EthersStateManager as well in a second round.

The account cache should be structurally more similar than the storage cache and is therefore likely best suited as a boilerplate for the new cache (storage cache is more complex).

So this cache element can likely remain very much unchanged (apart from renaming things obviously):

```typescript
type AccountCacheElement = {
  accountRLP: Uint8Array | undefined
}
```

One main thing to notice is the double role of `undefined` in this definition together with the two cache typings:

```typescript
_lruCache: LRUCache<string, AccountCacheElement> | undefined
_orderedMapCache: OrderedMap<string, AccountCacheElement> | undefined
```

`undefined` in the above type means: for this account the cache in the fitting point in time knows that the element is *not in the state* (and if that respective account is accessed with `getAccount()` or something `undefined` can be returned).

`undefined` for caches typings below means (particularly in diff cache context): at this point in time (so, e.g.: after checkpoint number x) it is known that the element was not in the cache (therefore: the cache - at that point - don't know anything about this account (and a respective account access like the above would need to trigger a trie read).

To understand this difference is somewhat key for the implementation.

I would cautiously say: the whole `cache/account.ts` can structurally more or less taken over 1:1, since cache data structure is the same, the way diffs are handle should be as well. Same goes for `test/account.ts` (-> `test/code.ts`). And then one is already half through the implementation. 🙂

Then one can go into `stateManager.ts` itself and do the switch.

A gentle way to do this might actually be to in a first iteration just keep the "old" cache structures and continue to use them but in parallel put things in the new cache and read values as well.

Then one can create a new (more general) `checkpointing.code.spec.ts` file.

If I am not mistaken one should be able to generate this while still using the *old* existing cache structure and tests should work for this. And then one can switch over and see if things still work or not (even during that it might make sense to keep both structures since then one can compare the values).

Also possible to do some live runs (e.g. in the client) in between.

And *then* one can finally delete the old caching structure. 🎉

Ah, and, for sure: we need performance tests on this once we have that! 

(so a last part would also to add this as a client option and integrate in the client, see e.g. original PR or the current code base).

**Comment by acolytec3** [comment]
I have a maybe ignorant question on this. Other than self destruct, when does code ever change? Do we need anything more than a simple key value map for this?

**Comment by holgerd77** [comment]
@acolytec3 Totally no ignorant question! No code (for a certain hash / account) does not change. What *does* happen though are certain attacks on mainnet (again: Shanghai) that a lot of code is created during a transaction run with CREATE-related opcodes and then at the end of the tx everthing is reverted. This bloats these simple structures and quickly renders them useless, because this is then filled with not-reused artificial code parts.

So it is good if we get this in the somewhat more complex diff structure. Then we can mitigate these things. (and the datastructure itself is indeed a simple key value map anyhow. But this is true for the other caches as well. So this is more about change management).

**Comment by scorbajio** [comment]
Can this issue be closed?

**Comment by holgerd77** [comment]
Yes 🙂, will do.
