### ISSUE TITLE
Client doesn't throw on unknown CLI params

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ethereumjs-monorepo#3025]
As reported on Discord, the client does not throw when unknown commands are passed to it, despite having the option enabled [here](https://github.com/ethereumjs/ethereumjs-monorepo/blob/8ca49a1c346eb7aa61acf550f8fe213445ef71ab/packages/client/bin/cli.ts#L362) in `yargs` to do so.  This issue should be researched and resolved.

**Comment by scorbajio** [comment]
It seems like unknown keyword arguments are being caught as expected but positional ones are not.

**Comment by acolytec3** [comment]
Have opened an issue on `yargs` to get clarity.  It's not obvious to me if this is a configuration issue on our side or if there's a bug in the underlying parsing logic.
