### ISSUE TITLE
Add configuration option for RPC to return actual error message when an RPC call fails

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ethereumjs-monorepo#3044]
Currently, if an error occurs when an RPC call is made, unless there is specific handling for a given error (either in input validation or elsewhere inside specific RPC method handlers), the RPC returns a generic `internal error` message that gives no hints as to what went wrong. We should figure out how to have the RPC return the actual error that caused the issue and a stack trace and then setup a new CLI flag to turn on this RPC Debug feature (or else have this driven by the `--rpcDebug` flag).

**Comment by jochem-brouwer** [comment]
Should we not enable this by default? :thinking:

**Comment by holgerd77** [comment]
> Should we not enable this by default? 🤔

Yes, would think as well, any downsides of this?

**Comment by acolytec3** [comment]
The main one I can think of is if an RPC consumer expects the `internal error` message versus the very debug-oriented "Here's the error and its complete stack trace" response proposed above.

**Comment by scorbajio** [comment]
I've dealt with this before, can take a look. 

One downside I can think of for keeping the rpc debug option enabled by default is that client users could forget to disable it in production, which could result in security issues since the stack trace would reveal details to an attacker.
