### ISSUE TITLE
Finish typing cleanup for CLI params

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ethereumjs-monorepo#3045]
Our client CLI params is currently [`@ts-ignore`](https://github.com/ethereumjs/ethereumjs-monorepo/blob/acd1bbbcb436f8e3f137e06b7f85271424e5cd09/packages/client/bin/cli.ts#L50)d because of at least 2 issues related to how `yargs` parses params that are configured with `array: true`.

Both `bootnodes` and `transports` are currently defined as being array params and `yargs` parses these as a type `(string | number)[] | undefined`.

In the case of `transports`, it really doesn't even make sense to have this as an array since we only support `rlpx`. We should rework this option so that it is a simple boolean param and starts up an `RLPXServer` inside `client/src/config.ts` if this param isn't passed (or is passed as true) and start the client with no servers if `--transports=false` is passed.

In both cases, the typing should be cleaned up and we ensure we can remove this `@ts-ignore` without Typescript complaining about type mismatches.

**Comment by holgerd77** [comment]
Then rename to --networking or otherwise plain ---rlpx (maybe networking is easier, guess there are a lot of people who are not so firm with networking topology) might be a more intuitive version.

**Comment by acolytec3** [comment]
The `transports` part of this was dealt with in #3069
