### ISSUE TITLE
Signing and sending Legacy Tx to custom chain (Ganache)

### ISSUE THREAD

**Issue by vdamle** [ethereumjs/ethereumjs-monorepo#3055]
I've hitting issues attempting to sign and send a Legacy transaction to a local chain such as Ganache/Hardhat:

* If I use the `ecsign()` method (ideally, this is the one I want to figure out because I'm interested in replacing the `ecsign()` call with an external wallet to sign the transaction), the `from` address as seen in Ganache _is different_ from the EOA that is used to sign the transaction -- which results in `insufficient balance` error on Ganache.
  * Note that in this case, I am able to `verifySignature()` locally before sending the transaction without error.
  * I am also able to `ecrecover()` using the `chainId`, `R`, `S` and `V` values which are returned from `ecsign()` and subsequently call `Address.fromPublicKey()` to make sure that the sender address matches with the EOA address.
* If I use the `.sign()` method to provide the private key to the library to sign the transaction, the `v` value in the transaction is not what I expect to see for a custom chain ( `chainId * 2 + 35` or `chainId * 2 + 36` ). The `v` value corresponds to something signed for `Chain.Mainnet` which leads me to think that `Custom.custom({ chainId: 1337 })` configuration is not applied as expected?
* I tried using both `Hardfork.Berlin` and `Hardfork.Istanbul` and don't see any different result.

I am including the simple program I am using for this. The code does have a Ganache generated private key and associated EOA address. I've included this mainly to show a log from Ganache that indicates that the `from` address as deduced by Ganache is different from the EOA that is signing the transaction. Note that I attempted both Ganache and Hardhat and I see an error on both nodes.

#### Sample Code to sign and submit tx

* Package versions:

```
    "@ethereumjs/tx": "^5.0.0",
    "@ethereumjs/util": "^9.0.0",
    "@ethereumjs/rlp": "^5.0.0",
    "@ethereumjs/devp2p": "^6.0.0"
```

```
const { Web3 } = require("web3");
const web3 = new Web3("http://127.0.0.1:7545");
const { LegacyTransaction, TransactionFactory } = require("@ethereumjs/tx");
const { Common, Hardfork } = require("@ethereumjs/common");
const { bytesToHex, hexToBytes, ecsign, ecrecover, toBytes, Address, } = require("@ethereumjs/util");
const { ethers } = require("ethers");

const KEY_WALLET_1 = "0xe9be2b031726e1675ab3b9ab3ed35a2489481f33b98db9dc7e4368892d306ceb";
const ADDRESS_1 = "0x309559c9CE006915A0e30fFfe647D0127f95Cc85";
const KEY_WALLET_2 = "";
const ADDRESS_2 = "0xa5411deC249187862D1fd3C082BEFA7D22887F5a";

async function sendTxn() {

  const gasPrice = await web3.eth.getGasPrice();
  let count = await web3.eth.getTransactionCount(ADDRESS_1, "latest");
  const chainId = 1337;

  const transferAmountValue = web3.utils.numberToHex(web3.utils.toWei(0.001, "ether"));
  console.log(`Transfer amount value: ${transferAmountValue}, gas price: ${gasPrice}`);
  let rawTxn = {
    nonce: count,
    gasPrice: gasPrice,
    gasLimit: 3000000,
    to: ADDRESS_2,
    value: transferAmountValue,
    data: '0x'
  };
  const common = Common.custom({ chainId: chainId, networkId: chainId, hardfork: Hardfork.Berlin })
  const tx = LegacyTransaction.fromTxData(rawTxn, common);
  // this returns the keccak256 hash of the RLP encoded message
  let unsignedTxHash = tx.getHashedMessageToSign();

//   let signedTxFromPrivateKey = tx.sign(toBytes(KEY_WALLET_1))
//   let txHash = signedTxFromPrivateKey.hash();
//   if (signedTxFromPrivateKey.verifySignature()) {
//     console.log("Signature verified");
//   }
//   console.log(`Signature values in signed transaction: R: ${signedTxFromPrivateKey.r}, S: ${signedTxFromPrivateKey.s}, v: ${signedTxFromPrivateKey.v}`);
//   let txRPC = bytesToHex(signedTxFromPrivateKey.serialize());

  let { r, s, v } = ecsign(unsignedTxHash, hexToBytes(KEY_WALLET_1), chainId);
  console.log(`R: ${bytesToHex(r)}, S: ${bytesToHex(s)}, V: ${v}`);
  let sender = Address.fromPublicKey(ecrecover(unsignedTxHash, BigInt(v), r, s, BigInt(chainId)));
  console.log(`Sender address: ${sender}`);

  rawTxn = { ...rawTxn, r: bytesToHex(r), s: bytesToHex(s), v: toBytes(v) };
  let signedTx = TransactionFactory.fromTxData(rawTxn, common);
  if (signedTx.verifySignature()) {
    console.log("Signature verified");
  }
  let txHash = signedTx.hash();
  let txRPC = bytesToHex(signedTx.serialize());

  console.log(`Transaction hash: ${bytesToHex(txHash)}`);
  console.log(`Transaction send payload: ${txRPC}`);

  try {
    await web3.eth.sendSignedTransaction(txRPC)
    console.log("🎉 The hash of your transaction is: ", bytesToHex(txHash), "\n Check to view the status of your transaction!");
  } catch (err) {
    console.log("❗Something went wrong while submitting your transaction:", err)
  }
}

sendTxn()
```

* RPC call logged in Ganache shows a different `from` address:

```
[2023/09/22 11:24:45.510] -    >  eth_getTransactionCount: [
   >   "0x309559c9CE006915A0e30fFfe647D0127f95Cc85",
   >   "latest"
   > ]
[2023/09/22 11:24:45.546] -    >  eth_call: [
   >   {
   >     "nonce": "0x0",
   >     "gasPrice": "0x4a817c800",
   >     "to": "0xa5411dec249187862d1fd3c082befa7d22887f5a",
   >     "value": "0x38d7ea4c68000",
   >     "data": "0x",
   >     "v": "0xa96",
   >     "r": "0x6eaec2ad977a4781b18b0880e24df7a830db9e4196a6506dd8d32085af52358e",
   >     "s": "0x304f4d29ef53aae3151580f6356544b045a20f996937e92f7b82be2a3f880718",
   >     "from": "0xda9400a549877658e438fc5d4beec19d1b688bb3",
   >     "gas": "0x2dc6c0"
   >   },
   >   "latest"
   > ]
```

**Comment by gabrocheleau** [comment]
Hi @vdamle!
I've tried reproducing the issue you're encountering by creating a test case with the same code, and noticed that there are couple issues in the code above. Notably:

- There is no `hardfork` param in `Common.custom`. There is `defaultHardfork` and `hardforks`. That shouldn't matter in the context of what you're doing though.
- The second argument of `LegacyTransaction.fromTxData` is an object that can contain different options, one of them being `common`. The code should therefore be `const tx = LegacyTransaction.fromTxData(txData, { common })` rather than `const tx = LegacyTransaction.fromTxData(txData, common)`
- Same thing for `TransactionFactory.fromTxData(rawTxn, common)` -> `TransactionFactory.fromTxData(rawTxn, { common });`

Could you check if addressing those fixes the issue?

**Comment by vdamle** [comment]
@gabrocheleau Thank you for taking a look!

> There is no hardfork param in Common.custom. There is only defaultHardfork and hardforks. That shouldn't matter in the context of what you're doing though.

Ok, understood. Will fix that regardless.

> The second argument of LegacyTransaction.fromTxData is an object that can contain different options, one of them being common.

🤦🏼‍♂️ Gotcha! I confirm that after fixing the call with `common` as part of an object, I'm able to send the Tx and have it mined successfully.

**Comment by gabrocheleau** [comment]
> @gabrocheleau Thank you for taking a look!
> 
> > There is no hardfork param in Common.custom. There is only defaultHardfork and hardforks. That shouldn't matter in the context of what you're doing though.
> 
> Ok, understood. Will fix that regardless.
> 
> > The second argument of LegacyTransaction.fromTxData is an object that can contain different options, one of them being common.
> 
> 🤦🏼‍♂️ Gotcha! I confirm that after fixing the call with `common` as part of an object, I'm able to send the Tx and have it mined successfully.

Nice, thanks for reporting back. Will close since the issue is now resolved.
