### ISSUE TITLE
Missing "@types/debug" dependency in packages that require it, like `evm`

### ISSUE THREAD

**Issue by davidmurdoch** [ethereumjs/ethereumjs-monorepo#3071]
Since one of the packages does have it in its package.json everything works fine from within the monorepo, but when a package that exports the `debug` module's types is used on its own the type will be missing and invalid in some scenarios.

Example of a problematic type is the `PrecompileInput` type, which exports the `debug` type on the `_debug` property.

If you want to export the `debug` type anywhere I think you'll need to add the `@types/debug` package as a (production) dependency.

**Comment by acolytec3** [comment]
Thanks for raising this.  Looks like this happens in a number of places across the monorepo.  Will take a look and see if we can address.

**Comment by acolytec3** [comment]
I've reviewed all the places where a property of type `debug` or `debugger` (or other references to the `debug` package in general are used) and it looks like you've found the one place where it's not a `private` or `protected` property of one of our classes.  It just so happens that in this `PrecompileInput` interface, someone might actually need to provide a debugger to print debug logs if implementing a custom precompile.  Thanks again for raising this.

**Comment by jochem-brouwer** [comment]
Closed by #3072 (?)
