### ISSUE TITLE
Monorepo install should not require downloading browser binaries

### ISSUE THREAD

**Issue by paulmillr** [ethereumjs/ethereumjs-monorepo#3073]
If someone clones monorepo and tries to install dependencies, during the process it would download huge opaque binaries from three domains: `*.t-msedge.net, *.*.akamai.net, *.v0cdn.net` because of playwright dependency.

1. Downloading such binaries should be optional, it's only useful if browser tests are executed. There are different ways to make it optional, such as using a subfolder.
2. It is a security risk: if the binaries are infected with malware, you won't see it. Malware could modify .js output and make it seem like the tests are passing. Security story of "playwright" itself is also not straight even though it's MSFT, I will keep investigating

Removing playwright from root package.json fixes the issue.

**Comment by acolytec3** [comment]
That's a good point. We can add it to the optional dependencies list line `c-kzg`. I've got an existing PR updating some other deps so we can add it there.

**Comment by acolytec3** [comment]
@paulmillr I think #3075 will deal with this once I finish a few more changes. Is there anything different you would do as far as not required browser binaries?

**Comment by paulmillr** [comment]
@acolytec3 if it finishes `npm install` and I can run node tests, it's all good then.

**Comment by holgerd77** [comment]
Closed by #3075
