### ISSUE TITLE
Combining @ethereumjs/tx and @ethereumjs/common to send a LegacyTransaction

### ISSUE THREAD

**Issue by M0cK1nG-b1Rd** [ethereumjs/ethereumjs-monorepo#3116]
hello, I am trying to migrate from older ethereumjs-common and ethereumjs-tx to newer packages. My previous code works fine and it shows like this 

```js
//"ethereumjs-common": "^1.5.2",
//"ethereumjs-tx": "^2.1.2",
//"web3": "^1.7.0"

const Web3 = require('web3');
const Tx = require('ethereumjs-tx').Transaction;
const Common = require('ethereumjs-common').default;


const customCommon = Common.forCustomChain(
    'mainnet',
    {
        name: 'Binance Smart Chain Mainnet',
        networkId: 56,
        chainId: 56
    },
    'istanbul',
);

async function test() {
    let accountNonce = await web3.eth.getTransactionCount(recipient, 'pending');
    accountNonce = Number(accountNonce)
	rawSellTx = {
			'nonce': web3.utils.toHex(accountNonce),
			'gasPrice': web3.utils.toHex(gasPrice),
			'gasLimit': web3.utils.toHex(3000000),
			'to': myRouterAddress,
			'value': web3.utils.toHex(0),
			'data': webMyRouter.methods.test(test1, test2, test3, test4).encodeABI()
		}
	}

	let sellTx = new Tx(rawSellTx, { 'common': customCommon });
	sellTx.sign(Buffer.from(privatekey, 'hex'));
	accountNonce = accountNonce + 1;
    try {
        const result = await web3.eth.sendSignedTransaction('0x' + sellTx.serialize().toString('hex'));
    } catch (error) {
        console.log(error)
    }
}

test()
```

now I go through the newest document and trying to update like this
```js
//"@ethereumjs/common": "^4.0.0",
//"@ethereumjs/tx": "^5.0.0",
//"web3": "^4.2.0"

const { Web3 } = require('web3');
const { LegacyTransaction } = require('@ethereumjs/tx')
const { Common, Chain, Hardfork } = require('@ethereumjs/common');


const customCommon = new Common({
    chain: Chain.Mainnet,
    name: 'Binance Smart Chain Mainnet',
    networkId: 56,
    chainId: 56,
    hardfork: Hardfork.Istanbul
})

async function test() {
    let accountNonce = await web3.eth.getTransactionCount(recipient, 'pending');
    accountNonce = Number(accountNonce)
	const rawBuyTx = {
		'nonce': web3.utils.toHex(accountNonce),
		'gasPrice': web3.utils.toHex(gasPrice),
		'gasLimit': web3.utils.toHex(3000000),
		'to': myRouterAddress,
		'value': web3.utils.toHex(0),
		'data': webMyRouter.methods.test(param1, param2, param3, param4, param5).encodeABI()
	}
    const buyTx = LegacyTransaction.fromTxData(rawBuyTx, { customCommon })
    const signedTx = buyTx.sign(Buffer.from(privatekey, 'hex'));
    accountNonce = accountNonce + 1;
    try {
        const result = await web3.eth.sendSignedTransaction(signedTx.serialize());

    } catch (error) {
        console.log(error)
    }
}

test()
```
but get the following error:
+++++++++++++++++++++++++++++
InvalidResponseError: Returned error: invalid sender
    at Web3RequestManager._processJsonRpcResponse (C:\Users\admin\Desktop\test\node_modules\web3-core\lib\commonjs\web3_request_manager.js:258:23)
    at Web3RequestManager.<anonymous> (C:\Users\admin\Desktop\test\node_modules\web3-core\lib\commonjs\web3_request_manager.js:156:29)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\admin\Desktop\test\node_modules\web3-core\lib\commonjs\web3_request_manager.js:21:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  innerError: { code: -32000, message: 'invalid sender' },
  code: 101,
  data: undefined,
  request: {
    jsonrpc: '2.0',
    id: 'd5c86a3c-e107-4eb3-b8d9-25456480cc2a',
    method: 'eth_sendRawTransaction',
    params: [
      '0xf9010b820xxxxxxxxxxxxxxxxxxx03fc4e795f862b044e5283832779fa9ecd80b8a47b84bc540000000000000000000000001xxxxxxxxxxxxxxxxxxxxxxxx6024e000000000000000000000000bb4cdxxxxxxxxxxxxxxc095c000000000000000000000000ae843fbf8ebxxxxxxxxxxxxxxxxxxxxx000000000000000000000000000000000000005af3107a40000000000000000000000000000000000000000000000041c3bc2xxxxxxxxxxxxxxxxxx35c825aa789e5ec51b7742762xxxxxxxxxxxxxxxxxxxxxx5c6b39f0b6108fd2e1'
    ]
  }
}
++++++++++++++++++++++++++++
I couldn't figure out what is going on, can someone help?

**Comment by holgerd77** [comment]
Ugh.

You are doing a dramatic transition here. A lot has changed from the versions you are upgrading from (including Web3.js).

So rather prepare for several rounds here (please figure out most of it yourself 😋), I would - roughly - assume that you have got 5-10+ places where things needs to be updated.

So you need to go this step-by-step respectively line-by-line. Wanting the whole example to work at once is far too much.

So the current failure you have is still on the Web3.js side. So you need to get this to work first, so requesting the tx. There should be tutorials out there.

Some stuff on the EthereumJS side:
- Rather use the new [Common.custom()](https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/common#basic-chain-customization--predefined-custom-chains) API for initializing your custom chain.

LegacyTransaction.fromTxData(rawBuyTx, { customCommon }) ->
LegacyTransaction.fromTxData(rawBuyTx, { common: customCommon })

buyTx.sign(Buffer.from(privatekey, 'hex'))
We do not use Buffer any more but Uint8Array (see tx library docs)

That's the stuff I can spot on first go. 🙂 

Happy updating! 🎉

**Comment by M0cK1nG-b1Rd** [comment]
heyyyy, thank you for your kind answer, the problem is now solved. I follow your instruction to make some change in the code and now it works. Here's my code to serve as an example to help someone needed.
```js
//"@ethereumjs/common": "^4.0.0",
//"@ethereumjs/tx": "^5.0.0",
//"@ethereumjs/util": "^9.0.0"
//"web3": "^4.2.0"

const { Web3 } = require('web3');
const { LegacyTransaction } = require('@ethereumjs/tx')
const { Common, Chain, Hardfork } = require('@ethereumjs/common');
const { hexToBytes } = require('@ethereumjs/util')

const customCommon = Common.custom({
    chain: Chain.Mainnet,
    name: 'Binance Smart Chain Mainnet',
    networkId: 56,
    chainId: 56,
    hardfork: Hardfork.Istanbul
})

async function test() {
    let accountNonce = await web3.eth.getTransactionCount(recipient, 'pending');
    accountNonce = Number(accountNonce)
	const rawBuyTx = {
		'nonce': web3.utils.toHex(accountNonce),
		'gasPrice': web3.utils.toHex(gasPrice),
		'gasLimit': web3.utils.toHex(3000000),
		'to': myRouterAddress,
		'value': web3.utils.toHex(0),
		'data': webMyRouter.methods.test(param1, param2, param3, param4, param5).encodeABI()
	}
    const buyTx = LegacyTransaction.fromTxData(rawBuyTx, { common: customCommon })
    // privatekey should have "0x" now
    const signedTx = buyTx.sign(hexToBytes(privatekey));
    accountNonce = accountNonce + 1;
    try {
        const result = await web3.eth.sendSignedTransaction(signedTx.serialize());

    } catch (error) {
        console.log(error)
    }
}

test()
```

**Comment by holgerd77** [comment]
Cool, glad that you solved! 🤩
