### ISSUE TITLE
Dumping storage from a deployed contract

### ISSUE THREAD

**Issue by kaliubuntu0206** [ethereumjs/ethereumjs-monorepo#3128]
Hello,

I would like to know if it is possible to dump storage allocation from a deployed contract ( Used for creating alloc data for genesis.json )

Thanks!

**Comment by kaliubuntu0206** [comment]
Related: https://github.com/NomicFoundation/hardhat/issues/3599

**Comment by jochem-brouwer** [comment]
This is not directly possible, since you only have access to the hashed keys and not the keys itself. You would need to know the preimage of the hash in order to setup the alloc data.
