### ISSUE TITLE
CodeCov challenges

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ethereumjs-monorepo#3134]
We are currently having some challenges with CodeCov reports being incomplete or not loading correctly.

- CodeCov is unable to process the coverage reports for `rlp` and  `ethash`  and gives an error like below:
![image](https://github.com/ethereumjs/ethereumjs-monorepo/assets/17355484/37eadd06-30e3-4fa9-a9e8-f9bd91ff2025)
I've inspected the reports and they appear to follow the same format as our other coverage reports so it's not obvious what the issue is here.

- `genesis` and `wallet` are not populating coverage reports at all so we should add this to their CI jobs and see if we can get CodeCov to include them in its reporting.

**Comment by holgerd77** [comment]
This seems to be getting adressed by latest codecov work from @scorbajio and generally issue is somewhat old, will close.
