### ISSUE TITLE
Add viemStateManager

### ISSUE THREAD

**Issue by roninjin10** [ethereumjs/ethereumjs-monorepo#3145]
## Description

Ethereumjs currently has an [ethers.js state manager](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/statemanager/src/ethersStateManager.ts) that fetches state using ethers. It requires an ethers provider and works similar to anvil reading state from cache normally but fetching state remotely otherwise. Viem is gaining popularity and it would be a very small lift to implement a viem version.

## Context

I want this feature because I am currently building [EVMts](https://github.com/evmts/evmts-monorepo). EVMts runs a vm in javascript that is meant to work similar to anvil. I will be wrapping ethereumjs in a way to support forge scripting and other features that can then be used by frontends and node.js/bun apps to build applications tightly with the EVM. EVMts is viem based but currently [using ethers.js for the vm only](https://github.com/evmts/evmts-monorepo/blob/main/packages/evmts/src/evmts.ts#L96). Since the rest of EVMts is mostly viem based and I need to add a lot of extra custom state functionality I plan on making my own EVMts specific version of the StateManager that is based on viem. Before ipmlementing the custom functionality though I plan on just reimplementing ethers.js in viem and would love to upstream it to ethereumjs (the simple version) before adding my custom functionality.

## Tasks

- [ ] Add viem state manager
- [ ] Add tests
- [ ] Add docs

**Comment by roninjin10** [comment]
I added this in this pr https://github.com/evmts/evmts-monorepo/pull/652/files. Happy to upstream it

**Comment by acolytec3** [comment]
@holgerd77 what do you think?  I'm not sure if we have the appetite to maintain multiple state managers like this or not?  Our original motiviation for the `ethers` one was our association with the `ethers` maintainer and while I'm not opposed to adding another implementation, feels like it could be an extra maintenance burden for us whenever `viem` makes major breaking changes (and I have no familiarity with `viem` though I'm sure it's a perfectly fine library.

**Comment by holgerd77** [comment]
Sorry for the late answer.

I would be a big fan of integrating, no reasons to prefer Ethers here and by now `viem` seems to have gotten to the point to be a perfectly accepted library as well.

Just wondering: @roninjin10 the code you linked seems highly redundant with the EthersSM code. If we want to integrate we should largely reduce and "do it right" [TM] from the beginning. @roninjin10 @acolytec3 Would it be a way to add a `ProviderStateManager` layer in between (likely as an abstract class) where also the `EthersStateManager` inherits from and which can then be also used by the ViemStateManager? 🤔

**Comment by roninjin10** [comment]
> Sorry for the late answer.
> 
> I would be a big fan of integrating, no reasons to prefer Ethers here and by now `viem` seems to have gotten to the point to be a perfectly accepted library as well.
> 
> Just wondering: @roninjin10 the code you linked seems highly redundant with the EthersSM code. If we want to integrate we should largely reduce and "do it right" [TM] from the beginning. @roninjin10 @acolytec3 Would it be a way to add a `ProviderStateManager` layer in between (likely as an abstract class) where also the `EthersStateManager` inherits from and which can then be also used by the ViemStateManager? 🤔

Yea it's a good callout. What do you think about instead of this we make a Provider abstract class that is basically an adapter between viem/ethers and ethereumjs? If viem/ethers ever gets used anywhere else in ethers.js it can use this generic provider class. And then we turn ethers/viem state manager into a generic RPCStateManager or whatever we want to call a state manager that is proxying to an rpc that simply takes a Provider as a dependency

**Comment by roninjin10** [comment]
```typescript
abstract class Provider {
  abstract getByteCode: (options) => BigInt

  abstract getStorageAtt
}
```

```typescript
class ViemProvider extends Provider {
  getStorageAt = ...
}
```

```typescript
import {RpcStateManager} from '@ethereumjs/state'
import {ViemProvider} from '@ethereumjs/viem'

const stateManager = new RpcStateManager({
   provider: new ViemProvider({ client: createPublicClient() }),
   blockTag: 420n
})
```

**Comment by acolytec3** [comment]
> ```ts
> abstract class Provider {
>   abstract getByteCode: (options) => BigInt
> 
>   abstract getStorageAtt
> }
> ```
> 
> ```ts
> class ViemProvider extends Provider {
>   getStorageAt = ...
> }
> ```
> 
> ```ts
> import {RpcStateManager} from '@ethereumjs/state'
> import {ViemProvider} from '@ethereumjs/provider'
> 
> const stateManager = new RpcStateManager({
>    provider: new ViemProvider({ client: createPublicClient() }),
>    blockTag: 420n
> })
> ```

This could work.  Though I'm not sure it really gains us anything over just having concrete implementations of the state manager interface.  I took a brief skim of your code and it feels different enough that I'm not really sure what building our own abstract provider class gains us on top of just upstreaming your `viemtStateManager` alongside the `EthersStateManager`.  If we're going to build an `RPCStateManager`, I'd be more inclined to drop all provider dependencies and just use native `fetch` calls to retrieve data from the RPC endpoint since that's ultimately what it's doing and our State Manager doesn't really use any of the additional functionality provided by various libraries/providers.

**Comment by acolytec3** [comment]
@roninjin10 what do you think of this #3167? I'm moving to remove the ethers dependency and replace it with pure fetch calls to an RPC endpoint. I'm not that familiar with `viem` so not sure if this would work out if the box with your project? Also, it includes an update with a simple blockchain interface. We identified recently that the the current implementation breaks the `BLOCKHASH` op code since there was no way for the EVM to access the rpc from our blockchain class. You'll likely need to do something similar in your state manager unless you have otherwise accounted for this.

**Comment by acolytec3** [comment]
Fyi, just merged https://github.com/ethereumjs/ethereumjs-monorepo/pull/3167

**Comment by holgerd77** [comment]
@roninjin10 With #3167 being merged, does this completely "solve" you needs regarding viem integration respectively can you purely update to the new code or do you need something else? Also: do you need a quick release on this respectively would this help (could do eventually)? Happy to hear you feedback once you get to make an update on this! 🙏

**Comment by acolytec3** [comment]
Correct, I'm not aware of any project using this in anything other than a research capacity so far.

**Comment by roninjin10** [comment]
Absolutely no problems. I added ethereumjs monorepo as a submodule to make it so I can really quickly debug any issues as they come up. So far it's worked pretty seemlessly playing with it but haven't used it in a more complex applicaiton yet.

If curious this repo has the most recent work. [this test](https://github.com/evmts/EVMts-VM-example/blob/main/src/index.spec.ts#L8) uses the state manager.

Unrelated to the state manager [this functionality is pretty wild](https://github.com/evmts/evmts-monorepo/pull/728/files#diff-808ed1972eb794e1777c588478c8aa560edb642ecf997ebe497a86aeb4ebdc38R7). Basically adds javascript fs.readFile and fs.writeFile as predeploys so you can write solidity scripts that use file system

**Comment by roninjin10** [comment]
I need to dig into tracing etc. for ethereumjs to see if I can offer a developer tool for debugging why contract calls are failing
