### ISSUE TITLE
Add nx to ethereumjs for monorepo management

### ISSUE THREAD

**Issue by roninjin10** [ethereumjs/ethereumjs-monorepo#3175]
Adding nx to ethereumjs monorepo will greatly improve the dx of anybody working with ethereumjs. I opened a pr more details here for illustrative purposes: https://github.com/ethereumjs/ethereumjs-monorepo/pull/3174

**Comment by roninjin10** [comment]
Closing this because it makes sense ethereumjs is keeping deps to a min

**Comment by holgerd77** [comment]
Yeah, I’m really really really undecided on this, I definitely also see the advantages! At least thanks a lot for exploring this in such a deep manner! 🙏❤️
