### ISSUE TITLE
Common: Internalize `crc` Dependency

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#3217]
Had another look at dependencies we have in our libraries, starting from the bottom (Util, RLP, Common) of our stack. In `@ethereumjs/common` we have this one `crc` dependency in [package.json](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/common/package.json), which is only used for fork hash calculation.

Have followed the code path, so this is coming from [here](https://github.com/alexgorbatchev/crc), and we only use the `crc32` functionality mainly implemented [here](https://github.com/alexgorbatchev/crc/blob/master/src/calculators/crc32.ts), which we can easily "internalize" (take over the code with a source and license reference), since this is MIT licensed.

So we should do as we have done with the `k-bucket` dependency in this commit https://github.com/ethereumjs/ethereumjs-monorepo/pull/2685/commits/ed398ec712b8f917430cf16c2f67b50b0dd5f5fb, to further reduce the supply chain attack surface in our libraries.

I think it's good if we keep/take this as a convention for such cases to always create an `ext` folder in `src` with an additional `index.ts`, then we have this consistent.

**Comment by scorbajio** [comment]
Fixed by #3224.
