### ISSUE TITLE
Donating Funds to Ethereumjs-Monorepo

### ISSUE THREAD

**Issue by Lfada** [ethereumjs/ethereumjs-monorepo#3251]
Hi Ethereumjs-monorepo maintainers. I'm Lucas, a core contributor to the Drips project (https://www.drips.network/). I help recipients of donations through their learning and onboarding process.

[OpenZeppelin](https://www.openzeppelin.com/) has been using https://github.com/ethereumjs/ethereumjs-monorepo. It's one of their most critical dependencies!

OpenZeppelin core contributors appreciate your work and want to ensure you are all well-funded to keep doing it. For that reason, they have decided to donate some funds to your project through [Drips](https://www.drips.network/).

Who can I talk to about it?

cc: @holgerd77 @ryanio @jochem-brouwer

**Comment by ScottyPoi** [comment]
Hi @Lfada, thanks for letting us know!
So glad to know that you appreciate our work :smile: 

@holgerd77 is our fearless leader, so I will direct this message his way.

**Comment by holgerd77** [comment]
> @holgerd77 is our fearless leader, so I will direct this message his way.

😂

New properties attributed by the day.

@Lfada Yes, you can DM me, Discord would work well (same user name).

**Comment by jochem-brouwer** [comment]
Here is our discord: https://discord.gg/TNwARpR

Holgers username is holgerd77

**Comment by holgerd77** [comment]
Decided to not do/join for now, will close.
