### ISSUE TITLE
`Block.fromJsonRpcProvider` returns incorrect block hash following Cancun activation

### ISSUE THREAD

**Issue by solimander** [ethereumjs/ethereumjs-monorepo#3282]
The following snippet logs the incorrect block hash (`0xcb1e2df469e3dde16f918cbb29f9a24be08da9a93f5ee4eef1f628b7250dedf0`).

It should be: `0x327169120b64c5604814e732a65d29c5e3f13e9009a457585fc0003567251e57 `

```ts
const block = await Block.fromJsonRpcProvider(RPC_URL, 10536893n, {
  common: new Common({ chain: Chain.Goerli, hardfork: Hardfork.Cancun })
});
console.log(bytesToHex(block.hash()));
```

**Comment by jochem-brouwer** [comment]
Yup, thanks for reporting, #3283 :smile:
