### ISSUE TITLE
Type errors in src/common.ts

### ISSUE THREAD

**Issue by 0xpolarzero** [ethereumjs/ethereumjs-monorepo#3306]
## Description

Vercel fails to build a project using ethereumjs, because of some type errors in `@ethereumjs/common@4.2.0`.

## 1. Operator '>' cannot be applied to types 'string | number' and 'bigint'.

[This line](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/common/src/common.ts#L359) is causing the failure.

This is due to the fact that `hf.timestamp` might be a `string`, as stated in [this type](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/common/src/types.ts#L57).

### Logs

```
Failed to compile.

./node_modules/.pnpm/@ethereumjs+common@4.2.0/node_modules/@ethereumjs/common/src/common.ts:358:67
Type error: Operator '>' cannot be applied to types 'string | number' and 'bigint'.

   356 |           hf.block !== null &&
   357 |           BigInt(hf.block) > (blockNumber as bigint)) ||
 > 358 |         (timestamp !== undefined && hf.timestamp !== undefined && hf.timestamp > timestamp)
       |                                                                   ^
   359 |     )
   360 |
   361 |     if (hfIndex === -1) {
 ELIFECYCLE  Command failed with exit code 1.
Error: Command "pnpm build" exited with 1
```

## 2. Type 'bigint | null' is not assignable to type 'null'.

[This line](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/common/src/common.ts#L611) is causing the failure.

Just because [value right above](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/common/src/common.ts#L604) is initialized as `null`, so it's not expected to be assigned a `bigint`.

### Logs (after patching the first issue)

```
Failed to compile.

./node_modules/.pnpm/@ethereumjs+common@4.2.0_patch_hash=4xpdojes4lgpyvdqrqmrp7oc5m/node_modules/@ethereumjs/common/src/common.ts:653:11
Type error: Type 'bigint | null' is not assignable to type 'null'.

  Type 'bigint' is not assignable to type 'null'.
  651 |         for (const eip of hfEIPs!) {
  652 |           const valueEIP = this.paramByEIP(topic, name, eip);
> 653 |           value = typeof valueEIP === 'bigint' ? valueEIP : value;
      |           ^
  654 |         }
  655 |         // Parameter-inlining HF config (e.g. for istanbul)
  656 |       } else {
```

**Comment by holgerd77** [comment]
(and generally sorry for that, our Common library typing is not so optimal and could need some refactoring (things would likely be breaking, so unfortunately cannot be done on the sideline))

**Comment by holgerd77** [comment]
(I wonder a bit why our own TypeScript build compilation is not catching this. Maybe its another TypeScript version? 🤔)

**Comment by 0xpolarzero** [comment]
@holgerd77 Thanks for the quick fix, and nothing to worry about; that really just took 5 min to patch while waiting. The fix works perfectly for me.

And actually, that's with the latest 5.4.2 Typescript version (from 2 days ago), maybe that's it? My bad for not checking with a few versions before submitting the issue, to add some context.
