### ISSUE TITLE
Add support for `eth_blobBaseFee` RPC endpoint

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ethereumjs-monorepo#3309]
There's a new `blobBaseFee` RPC endpoint in the [execution API specs](https://ethereum.github.io/execution-apis/api-documentation/) and we should add support for it.

**Comment by acolytec3** [comment]
> You've linked the Wormhole Airdrop (could be worse). 😂 😂 😂

:shushing_face: It's my secret master plan to get us free tokens!

**Comment by scorbajio** [comment]
Found a reference implementation: https://github.com/ethereum/go-ethereum/issues/29139

**Comment by roninjin10** [comment]
Nice came looking for this. I had no idea how to calculate the blob base fee.

**Comment by acolytec3** [comment]
It's a pretty trivial addition as we already have the code for it (I think in `block`). Just need to expose it via the rpc

**Comment by roninjin10** [comment]
Oh I see it does exist on block/common just not named baseFee https://github.com/ethereumjs/ethereumjs-monorepo/blob/1dceddf26d9c610a6a7ad787b1c654f42da9887d/packages/block/src/header.ts#L623

**Comment by acolytec3** [comment]
@roninjin10 PR in flight.  It's pretty trivial but might do some additional test cleanup before we merge.  But this gives you an idea of how to implement it using our code if you want to add something similar in `tevm.`
