### ISSUE TITLE
Module not found: Package path ./src/precompiles is not exported from package 

### ISSUE THREAD

**Issue by hananbeer** [ethereumjs/ethereumjs-monorepo#3319]
I'm trying to import this from @ethereumjs/evm@2.2.1:

```typescript
import { getActivePrecompiles } from '@ethereumjs/evm/src/precompiles'
```

but I keep getting an error in nextjs:
```
Module not found: Package path ./src/precompiles is not exported from package 
```

all other files are imported successfully, just this one files has this issue.
everything looks to be exported and even the linter finds the functions exported from this file with no problem, but at runtime this error always occurs.

update:
this seems to be a global issue to all of ethereumjs/evm version 2.x. downgrading to 1.4.0 worked but I need dencun upgrade.

**Comment by acolytec3** [comment]
You should be able to import this directly without the need for a deep import like above. So do something like `import { getActivePrecompiles } from '@ethereumjs/evm'`

Deep imports won't work since we're using the `exports` property in our package.json

**Comment by holgerd77** [comment]
Can confirm that this works, just tested on CL. Will close, feel free to reopen if you have still issues regarding the import.
