### ISSUE TITLE
Polygon Amoy Testnet does not supported

### ISSUE THREAD

**Issue by Parth2412** [ethereumjs/ethereumjs-monorepo#3379]
As Polygon Mumbai Testnet is deprecated by the Polygon team and launched 2 new testnets called Amoy and Cardona.

**Comment by holgerd77** [comment]
We won't hardcode any specific L2s into our Common package any more starting with the upcoming breaking releases but advise to use a generic `createCustomCommon()` initialization with the respective chain ID.

Will close here (also associated PR closed).
