### ISSUE TITLE
Client: Add some small Verkle section in docs

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#3453]
I think being able to test Verkle and run the test networks is a strong selling factor for our client being used as a research client, and we should point this out in the [docs](https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/client).

So we should give this a small section in the main README to both make the integration more visible and assist people who want to experiment.

This does not need to be long and can very well link to existing write-ups in PRs or issues (but it might also make sense to just directly copy them over completely to have some more persistent place for them).

There should also be a cross-link to the Verkle package somewhere in these docs.

**Comment by foufrix** [comment]
For futur ref : [merkle integration stage](https://github.com/ethereumjs/ethereumjs-monorepo/issues/3417)

Hey I just tried the code provided in https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/verkle/README.md#usage

It's deployed here : https://replit.com/@foufrix/ethereum-merkle#index.ts

Apparently there is an issue there :
https://github.com/ethereumjs/ethereumjs-monorepo/blob/bcb0a84f24afada45cb574ac3e9e4cc501d65681/packages/verkle/src/verkleTree.ts#L118-L121

@holgerd77 do you know if it an issue from the package itself or the example being outdated?

The `put` function here
https://github.com/ethereumjs/ethereumjs-monorepo/blob/bcb0a84f24afada45cb574ac3e9e4cc501d65681/packages/verkle/src/verkleTree.ts#L218
 expect what's provided in the example

**Comment by acolytec3** [comment]
Responses in line.

> Hey I just tried the code provided in https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/verkle/README.md#usage

This is cloned from the `trie` package and probably doesn't work out of the box.

> It's deployed here : https://replit.com/@foufrix/ethereum-merkle#index.ts
> 
> Apparently there is an issue there :
> 
> https://github.com/ethereumjs/ethereumjs-monorepo/blob/bcb0a84f24afada45cb574ac3e9e4cc501d65681/packages/verkle/src/verkleTree.ts#L118-L121
> 
> @holgerd77 do you know if it an issue from the package itself or the example being outdated?
> 
> The `put` function here
> 
> https://github.com/ethereumjs/ethereumjs-monorepo/blob/bcb0a84f24afada45cb574ac3e9e4cc501d65681/packages/verkle/src/verkleTree.ts#L218
> 
> 

The problem here is that I believe `replit` is pulling from our published modules on NPM and the latest version there does not contain our verkle trie implementation.  You'll have to build our monorepo locally in order to experiment with the latest verkle code.  You can look at some of the tests I wrote in `[repo root directory]packages/verkle/test/verkle.spec.ts` for inspiration on how verkle trees get instantiated and used.  It's similar to our mpt but still has some rough edges.

**Comment by holgerd77** [comment]
Somewhat adressed by latest PRs from @gabrocheleau, will close.
