### ISSUE TITLE
Monorepo -> Tree Shaking Refactor: Turn sideEffect setting in package.json

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#3457]
Part of #3446 

**Earliest start together with official breaking release work!**

Small issue to not get over it since it seems important, citing from @tmm from here https://github.com/ethereumjs/ethereumjs-monorepo/issues/3446#issuecomment-2168318241 :

> In addition to what @roninjin10 described, "sideEffects": false should be added to package.json files for maximum tree-shakability.
> 
> Without "sideEffects" switched off build systems aren't able to properly eliminate dead code (e.g. Next.js) and could still contain unused code even if they are unused.
> 
> More info: https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free

As an additional note, this *might* actually need some analysis *if* we do have side effects in our packages, so this would be using things in a global context and the like.

If we do it is likely a good idea to refactor along that these go away!

**Comment by holgerd77** [comment]
Closed by #3497

**Comment by roninjin10** [comment]
Let’s go! I’ll share how big of a difference this made in Tevm based apps when this goes live
