### ISSUE TITLE
Monorepo -> Tree Shaking Refactor: Replace Static Class Constructors

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#3487]
Part of #3446 

**Earliest start together with official breaking release work!**

As stated by Will in the original issue static constructors of classes cannot be tree-shaked out, see e.g. this Rollup issue https://github.com/rollup/rollup/issues/349 which was closed at the end with "won't fix" after a long discussion with various explanations on why JavaScripts dynamic nature makes it difficult to realize.

We have static constructors all over the place and for e.g. block or tx I looked through the code and the code from these constructors make up up to 30-50% of the overall class code base, e.g. for the various `from*` constructors for the tx types. So while this is - a bit - tedious for users and one of the more invasive changes, I would make a strong pledge that we should adopt here. For users this is a one-time simple search-and-replace adjustment and this would significantly improve our structural setup.

Solution here would be to simply do normal/simple static top level methods replacing the constructors, guess we can go with a naming scheme just simply "switching around the wording a bit":

- `1559FeeMarketTx.fromValuesArray()` -> `create1559TxFromValuesArray()` (not sure if to keep `FeeMarket` or not)
- `Block.fromBlockData()` -> `createBlockFromBlockData()`
- `Block.fromExecutionPayload()` -> `createBlockFromExecutionPayload()`

So these two libraries are the super obvious ones.

The main `create()` constructors for (more or less) all libraries might deserve a second round of thinking, but on first round I would think: why not?

So:

- `EVM.create()` -> `createEVM()`
- `Blockchain.create()` -> `createBlockchain()`

And so on.

Guess we can just do a first round PR on Block/Tx and then we already have some more in-depth view if there might be some side-effects we didn't anticipate.

A monorepo-wide search on the words `public static` close to plainly reveals all static method instances.

Guess we can actually replace them all, since there is simply no benefit apart form this syntactic sugar and at the same time having these concrete downsides.

Some more candidates: `AccessLists` in tx, `Withdrawals`, `Requests`, `Accounts`, `Wallet` constructors (why not? not much additional work.)

**Comment by jochem-brouwer** [comment]
Monorepo-wide naming conventions: (from: https://github.com/ethereumjs/ethereumjs-monorepo/pull/3524#pullrequestreview-2190327056)

- `createAccountFromAccountData()` -> `createAccount()`
- `create1559FeeMarketTxFromTxData()` -> `create1559FeeMarketTx()`
(here I would value some additional opinion also from others if we would want to drop or keep the `FeeMarket` naming addition, the names get somewhat long, on the other hand this helps on expressiveness and code readability. I have some slight tendency to keep, but would have me overvoted)
- `createBlockFromBlockData()` -> `createBlock()`

**Comment by holgerd77** [comment]
We have the clean-up issue specifying the last TODOs still open #3560, so guess we can close this one
