### ISSUE TITLE
Breaking Trie/Statemanager -> Consolidate nibbles <-> bytes utility methods

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ethereumjs-monorepo#3521]
While working on #3519, we discovered a set of duplicative utility methods with slightly different APIs `nibblesToBytes`/`bytesToNibbles`/`nibbleTypeToPackedBytes` and `nibblestoBytes`/`bytesToNibbles` in the `trie` package.

We need to consolidate these into a single pair of `nibblesToBytes` and `bytesToNibbles` utility methods that accept a key in the format of the first term in the utility name and returns the second.  This will also require some adaptation of surrounding code as these duplicative methods are used in various places.

**Comment by scorbajio** [comment]
Will start working on this after #3519 is merged since this issue has a non-blocking dependency on it.
