### ISSUE TITLE
Monorepo -> Tree Shaking: Remaining Static Constructor Tasks & Clean-Up

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#3560]
Ok, this is a issue to finalize on #3487, will go through all the libaries and give a write-up of the remaining constructor refactors + some additional clean-up/refactoring tasks:

### Block

- Kill off `from-rpc.ts`, `header-from-rpc.ts` files, move code within function blocks of `constructors.ts`
- Create `block` and `header` directories, move `block.ts` and `header.ts` over, create `index.ts` file, split `constructors.ts` into the block and header methods and move over respectively (if this full TODO item is controversial we can also give a quick discussion, I would find it a useful better organizing structure)
- Rename `createBlockFromValuesArray` -> `createBlockFromBytesArray`
- Rename `createBlockHeaderFromValuesArray` -> `createBlockHeaderFromBytesArray`

### Util

Withdrawal still missing, accustomed naming scheme:

- `createWithdrawal()`
- `createWithdrawalFromBytesArray()`

No extra file, all in `withdrawal.ts`

Same with Request (rename `requests.ts` to `request.ts` along for consistency, separate commit):

- `createDepositRequest()`
- `createDepositRequestFromJSON()`
- `createWithdrawalRequest()`
- `createWithdrawalRequestFromJSON()`

### Verkle

- New `constructors.ts` file
- `createVerkleTree()`

### VM

Yes, I know, only one (same as Verkle). But we should nevertheless do now for both consistency and extensibility reasons, so the moment we want to add a second constructor we would otherwise be stuck with a mixed scheme.

That should be it. One or separate PRs, as preferred, should both be ok! 🙂

**Comment by ScottyPoi** [comment]
Closing with all tasks completed

**Comment by holgerd77** [comment]
🎉
