### ISSUE TITLE
Add missing admin_peers JSON-RPC

### ISSUE THREAD

**Issue by barnabasbusa** [ethereumjs/ethereumjs-monorepo#3565]
Currently we use `admin_peers` to fetch the number of peers connected to a client in dora. 

Admin_peers seems to be missing from ethereumjs. Related issue: https://github.com/ethereumjs/ethereumjs-monorepo/issues/1114

**Comment by acolytec3** [comment]
This is still WIP (since I need to add tests) but does this give you enough detail for Dora?

#3570
