### ISSUE TITLE
Monorepo: Json/JSON and Rpc/RPC Namining inconsistencies

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#3632]
Is it fun? Who knows. 😂 

But one of the broadest inconsistencies in naming throughout our libraries is still the more or less randomly chosen use of capitalized vs camel-case JSON/Json and RPC/Rpc.

I would suggest that we eliminate this once and for all and go for one version, I guess (?, cc @jochem-brouwer ) we can then add the non-allowed versions (e.g. `Rpc`, `Json`) even to the spell checker (does the spell checker takes capitalization into account?), which would allow us to fully get rid of this.

(side question: another such pair anyone can think of?)

Current stand (monorepo-wide search is):
- JSON: 749 usages, Json: 285 usages
- RPC: 417 usages, Rpc: 331 usages

I would have a preference to take the capitalized versions here, since both are abbreviations with every letter standing for a separate word ("JavaScript Object Notation", "Remote Procedure Call"), so it's somewhat already camel-case condensed 🙂, and so I think keeping everything capitalized is somewhat more logical.

**Comment by gabrocheleau** [comment]
> Is it fun? Who knows. 😂
> 
> But one of the broadest inconsistencies in naming throughout our libraries is still the more or less randomly chosen use of capitalized vs camel-case JSON/Json and RPC/Rpc.
> 
> I would suggest that we eliminate this once and for all and go for one version, I guess (?, cc @jochem-brouwer ) we can then add the non-allowed versions (e.g. `Rpc`, `Json`) even to the spell checker (does the spell checker takes capitalization into account?), which would allow us to fully get rid of this.
> 
> (side question: another such pair anyone can think of?)
> 
> Current stand (monorepo-wide search is):
> 
> * JSON: 749 usages, Json: 285 usages
> * RPC: 417 usages, Rpc: 331 usages
> 
> I would have a preference to take the capitalized versions here, since both are abbreviations with every letter standing for a separate word ("JavaScript Object Notation", "Remote Procedure Call"), so it's somewhat already camel-case condensed 🙂, and so I think keeping everything capitalized is somewhat more logical.

I agree with you about keeping the capital-letters version (so JSON/RPC rather than Json/Rpc). They are also more common in the repo as you've pointed out. I can take this one.

**Comment by holgerd77** [comment]
> I agree with you about keeping the capital-letters version (so JSON/RPC rather than Json/Rpc). They are also more common in the repo as you've pointed out. I can take this one.

Cool! 👍 🙂 Rather some side stuff, but nevertheless reoccuringly annoying!
