### ISSUE TITLE
Monorepo: Consistent DEBUG logger README docs & DEBUG=ethjs,* guarding

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#3634]
For various packages (EVM, StateManager, Trie,...) we use the debug logger for verbose debug developer output. To not pollute end user debug sessions we guard runs with `DEBUG=ethjs,*` (so: `ethjs` needs to be added for logs to be visible) for EthereumJS library debugging.

As per comment from @acolytec3 in the chat...

<img width="825" alt="grafik" src="https://github.com/user-attachments/assets/98590697-b05b-4446-bdd8-440949e647d3">

...we seem to not have done this consistently. We should go through the libraries where the debug logger is used and complete this to have this consistent. This can generally also be confusing, @g11tech stumbled upon this interpreting the non-logged out stuff as "simply not running", things like that are unlucky side effects.

As some second complementary task: for most debug logger usages we have per-package documentation sections like for [devp2p](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/devp2p/README.md#debugging) or for [EVM](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/devp2p/README.md#debugging), for some we have not though. We should look through the libraries where debug is used and add respective sections, both for ourselves as well as other users of the libraries.

**Comment by scorbajio** [comment]
Addressed by #3663 and #3654 and will be closed when the latter is merged.
