### ISSUE TITLE
Monorepo: Node 22 Support

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#3644]
Node.js 22 has been released quite some months ago (April 2024) as is soon becoming the active LTS release (end of October, see [release matrix](https://nodejs.org/en/about/previous-releases)).

Before we do the breaking releases we should definitely add this to the [Node versions](https://github.com/ethereumjs/ethereumjs-monorepo/actions/workflows/node-versions.yml) workflow and do eventual fixes.

Maybe it's also time to switch our normal CI runs to use Node.js 22 as default (guess we'll want here the "currently most poplar version" [tm] (at least roughly following).

And lastly I think we should also add Node.js 22 support to the `maintenance-v8` branch, we'll still be supporting this for some couple of months and so it would make sense to give this some love from this side as well.

**Comment by gabrocheleau** [comment]
I think as a guideline, it would make sense to always stick with the "Active" LTS version. It also matches with what Node recommends in their docs:
"Production applications should only use Active LTS or Maintenance LTS releases."

By staying up-to-date with the Active, then we give ourselves a maintenance buffer to update our codebase if there are breaking changes that require significant updates on our side.

**Comment by holgerd77** [comment]
Yeah, that makes sense, I just wonder in this particular case: does it make sense to switch 1-2 months "too early" just for practical reasons, so when we are adding Node 22 anyhow and this can be done along (and we normally just "never" [tm] get this "to the point" (so, switching 1-3 weeks around the active switch date) anyhow).

(I would cautiously vote for "let's just directly switch", but absolutely no strong opinion)

**Comment by ScottyPoi** [comment]
Started working on this.  Turns out our "node versions" workflow was not actually testing different versions :thinking:

**Comment by holgerd77** [comment]
Closed by #3669
