### ISSUE TITLE
Monorepo: KZG/Kzg Naming Inconsistencies

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#3656]
Guess we want the same as in #3632 for KZG (so: Kzg -> KZG + add to spell check)! 😋 

@gabrocheleau Can you do that (as well)? 🙂

**Comment by gabrocheleau** [comment]
One limitation for KZG renaming will be that some of the actual methods live in another package (https://github.com/ethereumjs/kzg-wasm) @acolytec3  would you be able to do the renaming on that side & publish a new release? I can then update the monorepo dep and adjust.

**Comment by holgerd77** [comment]
Sure

**Comment by gabrocheleau** [comment]
This has been addressed (with one exception as mentioned above by @acolytec3 ) by #3674, therefore closing this.
