### ISSUE TITLE
VM: Contribute missing EIP-1153 Transient Storage Test to execution-spec-tests

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#3666]
We soon have our new `t8ntool` for the [execution-spec-tests](https://github.com/shemnon/execution-spec-tests) repo finalized (see #3603) thanks to the great work from @jochem-brouwer! 🤩 

I would like to give this a first test by trying to come up with a test for the EIP-1153 bug we had (see #3625, so: transient storage not cleared). I just tested this by filling the 1153 tests with Jochem's instructions with:

```shell
fill -vv -x --evm-bin=../ethereumjs-monorepo/packages/vm/test/t8n/ethereumjs-t8ntool.sh --fork=Cancun tests/cancun/eip1153_tstore
```

This passes with on our current `master` but it passes also if one is doing the respective code change (or actually: reverse) in the EVM from the bugfix PR (so: delete the `this.postMessageCleanup()` call and (!) rebuild the EVM) and then run the test filler again.

So this scenario is apparently not tested yet in the collected tests.

If I get things together correctly I would assume this can be tested by running two txs in a block, the first doing some `TSTORE` and writing something to transient storage and the second tx reading from the same position. So we should come up with a scenario here which *does* fail when re-adding the bug to the code base and passes if the fix code is in.

Also, if I get correctly, I assume that this type of test (with 2 txs) needs a `BlockchainTestFiller`, I looked a bit around and [this EIP-7685 test](https://github.com/ethereum/execution-spec-tests/blob/061e41cce851e5d4d7de1d0612c84349f78b492e/tests/prague/eip7685_general_purpose_el_requests/test_deposits_withdrawals_consolidations.py#L237) seems to be a somewhat simple blueprint on how to setup such a test, maybe used as an inspiration together with a simple state test like the [access list test file](https://github.com/ethereum/execution-spec-tests/blob/main/tests/berlin/eip2930_access_list/test_acl.py) as well as having some look at how other [1153 tests](https://github.com/shemnon/execution-spec-tests/tree/0f3a388656f2f9f46ad6481b5e25f265fbee2f82/tests/cancun/eip1153_tstore) are done.

I would like to have the above confirmed by @jochem-brouwer (Jochem can you do that?), so that it's clear that all thest assumptions make sense!

Eventually I try to do this myself, or we make this a joint effort, or someone else takes the lead. The main thing should be that this is *not done too quickly* 😋 and rather in a step-by-step way over the next week or so so that this can serve as some educational project for the team on how to write these kind of tests! 🙂

**Comment by jochem-brouwer** [comment]
Hi Holger, you are correct. If this test case was actually in the tests, our CI would have reported the bug, and the bug would never be there :)

To setup the test which should trigger this test, you need two transactions:

The first is a CREATE transaction (so with a `to: null` field). This should TSTORE something. (Let's TSTORE 1 in slot 1). After this transaction, the new transaction should call into the **deployed contract** (which the previous transaction deployed). The code itself should now TLOAD slot 1, and then SSTORE this value into some slot (lets take slot 2). The expectation is that this stores 0 into the slot 2, so it does nothing for the state output. However, if we revert the change on master (so remove the `postMessageCleanup`) it will actually store 1 in slot 2.

So this test might look somewhat easy to make, it is a bit tricky, since tx 1 does two things, it should (1) TSTORE and (2) deploy the code for tx 2.

**Comment by jochem-brouwer** [comment]
As a side note, I actually wanted to add this test to the execution-spec-tests, it's super great that this issue is opened, thanks a lot :+1: We should indeed document the steps so we can provide more tests later on!

**Comment by jochem-brouwer** [comment]
Have assigned this to myself, will write down the process here.

**Comment by jochem-brouwer** [comment]
Process to add test: (will edit this)

Handy: https://ethereum.github.io/execution-spec-tests/writing_tests/code_standards/

**Comment by jochem-brouwer** [comment]
Ok, I'm sorry, I am doing this wayyy too quickly. It might be worth to setup maybe a quick meeting next week to do some pair programming and step through these steps?

**Comment by holgerd77** [comment]
> Ok, I'm sorry, I am doing this wayyy too quickly. It might be worth to setup maybe a meeting next week to do some pair programming and step through these steps for those who are interested?

Ah, so for met that's ok! 😄 I think it's generally a good idea that *you* actually do this test, guess that is in fact quickest/easiest (also these somewhat complex CREATE constallations you mentioned), but generally just also put a somewhat stronger emphasis on the docs part and generally taking us with you! 🙂 The above was already a really good start! 👍

**Comment by jochem-brouwer** [comment]
I will update the comment with further additions! :smile:

**Comment by jochem-brouwer** [comment]
I have updated the comment with a full breakdown on the test and how to write it, hope this helps :smile: :+1:

**Comment by jochem-brouwer** [comment]
The TSTORE tests have been merged into `execution-spec-tests`, so I will close this one!

However is there somewhere a place I can copy / pin this comment: https://github.com/ethereumjs/ethereumjs-monorepo/issues/3666#issuecomment-2349611424 for future references to write tests?

**Comment by holgerd77** [comment]
🤩 👍 

I would create a new section in https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/vm/test/t8n and it would also be good if we link to respectively mention the whole document in https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/vm#development .
