### ISSUE TITLE
New package: "trusted-setups"?

### ISSUE THREAD

**Issue by paulmillr** [ethereumjs/ethereumjs-monorepo#3670]
I've created this: https://github.com/paulmillr/trusted-setups. It weighs 1.3MB gzipped.

Perhaps we should publish it under `@ethereumjs/trusted-setups`? I don't really want to publish it in my namespace.

The files in it can be used in c-kzg and in wasm version as well

**Comment by holgerd77** [comment]
I would prefer it being external, then this has some more neutral place and becomes better reusable, e.g. I don't think the viem guys want to have dependencies in which are a bit on the same mid-level stack level (we e.g. also had Ethers as a dependency at some point and didn't have too good experiences with it, and generally feels somewhat wrong).

What about the original plan of adding this to `micro-eth-signer`?

**Comment by paulmillr** [comment]
ok, I will publish it then

> What about the original plan of adding this to micro-eth-signer?

I’ve decided against it:

1. the signer is 200 Kb (compressed) today
2. Adding trusted setup will increase it to 1Mb+, 5x+. There are at least 5 big files: simple.js, fast.js, esm versions, json.
3. Trusted setup is most likely NOT used by 99/100 client side devs, this is more of a backend thing, used by rollups
4. It does not make sense to increase pkg size 5x for everyone. Think of everyone, who has slow internet, including working on the go, or poor countries.

**Comment by holgerd77** [comment]
Question: have you considered publishing under `@noble`? Isn't this something generic and crypto related? Or is this not generic enough, since at the end an Ethereum specific setup?

**Comment by paulmillr** [comment]
noble is high-quality cryptography, and this is just a bunch of text files.

**Comment by holgerd77** [comment]
haha, makes sense 😄 👍

**Comment by holgerd77** [comment]
(will close here, integration at #3674 which is more or less merged)
