### ISSUE TITLE
Blockchain: Add debug Logger

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#3671]
When working on the debug logger docs here #3663 we (re-)discovered that the `blockchain` package has not even a basic debug logger for the core functionality.

Since blockchain is also a very procedural library it makes a lot of sense to add at least some basic debug logging to at least the core steps of the longer methods like (that's totally in the center) the `putBlocks` flow and maybe the validation methods. For the others (methods) I would suggest a bit spare and not overdo, maybe one for `delBlock()` or so, surely not for things like `getIteratorHead()` (at least I would think so?).

I think if we have these basic logging functionality in some few additional logging lines not added in this first round will then also add naturally if someone looks into something and then misses some output.

**Comment by scorbajio** [comment]
Closed by #3676
