### ISSUE TITLE
NPM package omits many exports that are present in the monorepo

### ISSUE THREAD

**Issue by andreachello** [ethereumjs/ethereumjs-monorepo#3715]
The examples do not use the latest version:

[./examples/run-blockchain](https://github.com/ethereumjs/ethereumjs-monorepo/blob/HEAD/examples/run-blockchain.ts): Loads tests data, including accounts and blocks, and runs all of them in the VM.
[./examples/run-solidity-contract](https://github.com/ethereumjs/ethereumjs-monorepo/blob/HEAD/examples/run-solidity-contract.ts): Compiles a Solidity contract, and calls constant and non-constant functions.

**Comment by andreachello** [comment]
The issue is related to the fact that there are inconsistencies in what the monorepo exports and what the npm package exports:

Monorepo for VM: src/index

`export { Bloom } from './bloom/index.js'
export { BlockBuilder, BuildStatus } from './buildBlock.js'
export { buildBlock } from './buildBlock.js'
export * from './constructors.js'
export * from './params.js'
export { encodeReceipt } from './runBlock.js'
export { runBlock } from './runBlock.js'
export { runTx } from './runTx.js'
export * from './types.js'
export { VM } from './vm.js'
`

NPM Package for VM instead:

`export { Bloom } from './bloom/index.js'
export { BlockBuilder, BuildStatus } from './buildBlock.js'
export { encodeReceipt } from './runBlock.js'
export * from './types.js'
export { VM } from './vm.js'`

**Comment by acolytec3** [comment]
We are in the late stages of a major breaking release round so our monorepo code is almost a year ahead of the last major version release on `npm`.  We're hoping to get this next round out this month or next and then the published packaged should closely align with the current examples.

**Comment by andreachello** [comment]
Thanks for the update!
