### ISSUE TITLE
Tx: Class names not fully consistent yet

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#3723]
Following tx type class names still needs shortening from `Transaction` to `Tx` to be consistent with the other class names. 🙂 

- `AccessList2930Transaction`
- `EOACode7702Transaction`

Correct example: `FeeMarketEIP1559Transaction` -> `FeeMarket1559Tx`

**Comment by jochem-brouwer** [comment]
I will address this among the refactor PR(s). (Might break up the refactor in multiple PRs)

**Comment by jochem-brouwer** [comment]
Ok, interesting how we missed this one, because you are right, for EIP1559 and for EIP4844 the names are correct :thinking:
