### ISSUE TITLE
Make Verkle instantiation easier

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ethereumjs-monorepo#3763]
We have a few rough edges in how we initialize `verkle` trees at the moment. As long as you use the `createVerkleTree` constructor function, it's pretty straight forward.  However, we should make a few changes:

- Have the constructor default to instantiate a `MapDB` if none is provided
- The `_createRootNode` function should be made public.
- We should just get rid of the `database` function all together.  There's no need for an independent DB setter/getter as this should be part of the constructor process

**Comment by gabrocheleau** [comment]
Have some time this PM so will tackle this one
