### ISSUE TITLE
?

### ISSUE THREAD

**Issue by sudojapt** [ethereumjs/ethereumjs-monorepo#3764]

**Comment by holgerd77** [comment]
The relationship from private to public key is deterministic, so this will result in the one public key corresponding to your private key. Note that the cited examples are pretty old and likely need some modification.

**Comment by gabrocheleau** [comment]
Closing this as the issue has been edited out. 

For reference, to turn a private key into a public key, you can use the following helper: https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/util/src/account.ts#L586

If what you mean is turning a private key into an actual Ethereum 20-byte address, you can use the following helper: https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/util/src/address.ts#L119, which will return an Address object. The Address.toString() helper will then output a readable 0x-prefixed string
