### ISSUE TITLE
Move over verkleCrypto handling into common

### ISSUE THREAD

**Issue by gabrocheleau** [ethereumjs/ethereumjs-monorepo#3774]
We currently are in a situation where we are passing `verkleCrypto` around in the VM/EVM/StateManager. With the latest AccessWitness work from #3770, we are now getting the verkleCrypto instantiation from stateManager, which is a bit roundabout and counterintuitive. As suggested by Holger in this comment: https://github.com/ethereumjs/ethereumjs-monorepo/pull/3770#discussion_r1818569641, we could instead move it into Common.

**Comment by holgerd77** [comment]
Ok, I think I remember that the main argument @acolytec3 had against this is that we would need `Common` to be added to the Verkle library. 🤔 

Guess I am still somewhat in favor, might become necessary in the future along additional Verkle HFs anyhow and Common is in many cases already there and therefore also easily be used to carry this Verkle crypto around as we do with the other stuff.
