### ISSUE TITLE
Improve linting: it takes 1 minute to run

### ISSUE THREAD

**Issue by paulmillr** [ethereumjs/ethereumjs-monorepo#3784]
As a rare contributor to the repo, it feels really painful. I can only imagine how it feels to regular contributors. 1-2 minutes of dev time wasted on every commit, multiplied by dev count = lots of money wasted.

Improving that would definitely make it more fun to contribute for outside collaborators.

I've heard [Biome](https://biomejs.dev) is new, fast and native linter. Perhaps it should be worth a look? Related: #3762

**Comment by acolytec3** [comment]
I feel your pain. The downside of all the fast new linters is they don't use the Typescript APIs for type aware lint rules, which is mainly where running the full linter is helpful. I'm exploring the idea of a two stage linter that uses biome or something similar for local linting and then the eslint one on CI

**Comment by paulmillr** [comment]
That should help!

**Comment by jochem-brouwer** [comment]
Just want to chime in, I use the linter only on the specific packages which I've changed, and only do so when I want to push things

**Comment by jochem-brouwer** [comment]
Related, for the linter I would like to see these rules (back?)

- Do not allow importing `hexToBytes` and `bytesToHex` from `ethereum-cryptography` (it default to that package for me, but `bytesToHex` returns unprefixed hex which we dont want)
- Ensure bigints are instantiated as `BigInt(200)` instead of `200n`

**Comment by acolytec3** [comment]
Will add this to my to-do list!

-------- Original Message --------

**Comment by acolytec3** [comment]
I believe #3794 (and followups) address this sufficiently for now.  We're not ready to move fully to biome for linting but running the linter from the repo root with the streamlined rule set I configured makes this much less painful.
