### ISSUE TITLE
Integrate project example questions into docs (code?) of VM and related libs

### ISSUE THREAD

**Issue by alcuadrado** [ethereumjs/ethereumjs-monorepo#440]
Hi,

I'm trying to create a simple script that initializes an in-memory blockchain with a bunch of funded accounts, and processes a few transactions, creating a new block per transaction. 

My goal is to generate execution traces of the transactions, but I'm having problems initializing a very simple example. 

My confusion is mostly around how to initialize a custom blockchain, how do I add new blocks into it, and how can I inspect it.

This is my best attempt so far, with 10 inlined questions:

```js
const util = require("util");
const VM = require("ethereumjs-vm");
const EthereumTx = require("ethereumjs-tx");
const Block = require("ethereumjs-block");
const ethUtil = VM.deps.ethUtil;
const levelMem = require("level-mem");
const Blockchain = require("ethereumjs-blockchain");
const Trie = require("merkle-patricia-tree/secure");

const accounts = [
  {
    privateKey: Buffer.from(
      "3cd7232cd6f3fc66a57a6bedc1a8ed6c228fff0a327e169c2bcc5e869ed49511",
      "hex"
    ),
    balance: "0xDE0B6B3A7640000"
  },
  {
    privateKey: Buffer.from(
      "3cd7232cd6f3fc66a57a6bedc1a8ed6c228fff0a327e169c2bcc5e869ed49512",
      "hex"
    ),
    balance: "0xDE0B6B3A7640000"
  }
];

async function main() {
  const blockchainDB = levelMem();
  const state = new Trie();
  const blockchain = new Blockchain(blockchainDB);

  const vm = new VM({
    state: state,
    blockchain: blockchain,
    activatePrecompiles: true
  });

  const pvm = promisifyAllMethods(vm);
  const pstatemanager = promisifyAllMethods(vm.stateManager);
  const pblockchain = promisifyAllMethods(blockchain);

  const genesisBlock = new Block();

  console.log("blockchain.meta #0", blockchain.meta);

  // QUESTION #1: I want to have a genesis block quite similar to the mainnet one, except for the initial account,
  // block gas limit, hardfork and things like that. Should I create an ethereumjs-common object? Or is this OK?

  genesisBlock.header.timestamp = null;
  genesisBlock.header.gasLimit = 8000000;
  genesisBlock.header.difficulty = 17179869184;
  genesisBlock.header.extraData =
    "0x0000000000000000000000000000000000000000000000000000000000000000";
  genesisBlock.header.nonce = "0x0000000000000042";
  genesisBlock.header.number = Buffer.from([]);

  // This is an attempt at having a set of funded accounts in the genesis block.

  for (const account of accounts) {
    // QUESTION #2: This changes the blockchain.meta value, setting a rawHead. Why/How?
    await pstatemanager.putAccount(
      ethUtil.privateToAddress(account.privateKey),
      new VM.deps.Account({ balance: account.balance })
    );
  }

  // QUESTION #3: How should I get a root for the genesis block? Using this state manager?
  // QUESTION #4: This changes the blockchain.meta value, setting a rawHead and genesis. Why? I see no relationship
  // between genesisBlock and the rest of the system yet.
  const stateRoot = await pstatemanager.getStateRoot();

  // Same here, this changes it
  genesisBlock.header.stateRoot = stateRoot;

  console.log("blockchain.meta #1", blockchain.meta);

  // I'd expect this to be the first place that changes blockchain.meta
  await pblockchain.putGenesis(genesisBlock);

  console.log("blockchain.meta #2", blockchain.meta); // Same as #1

  // QUESTION #5: This seems to ignore the genesis block. Is this a special case? Or how does it work? Isn't it just to
  // iterate through the blocks?
  await new Promise(resolve => {
    vm.blockchain.iterator(
      "",
      (block, reorg, cb) => {
        console.log("Iteration");
        console.log("Block", block);
        console.log("Regorg", reorg); // Q: What's this?
        cb();
      },
      resolve
    );
  });

  console.log("Done iterating");

  // We try to add a new block with a single value transfer tx

  const block = new Block();

  block.header.gasLimit = 8000000;
  block.header.extraData =
    "0x0000000000000000000000000000000000000000000000000000000000000000";
  block.header.nonce = "0x0000000000000042";
  block.header.number = Buffer.from([1]);
  block.header.parentHash = genesisBlock.hash();
  block.header.timestamp = Math.ceil(new Date().getTime() / 1000);

  // QUESTION #6: Is this mandatory? If I don't do this I get an error. 
  block.header.difficulty = block.header.canonicalDifficulty(genesisBlock);

  // Just a tx from one of the initialized accounts
  const txParams = {
    nonce: "0x00",
    gasPrice: "0x1",
    gasLimit: "0xE0000",
    to: "0x0000000000000000000000000000000000000000",
    value: "0xDE",
    data: "",
    chainId: 1
  };

  const tx = new EthereumTx(txParams);

  tx.sign(accounts[0].privateKey);

  block.transactions.push(tx);

  // This seems to run fine
  const result = await pvm.runBlock({
    block,
    generate: true,
    // QUESTION #7: The doc seems to indicate that `generate : true` skips the state trie validation, but it doesn't. Am I doing something wrong?
    skipBlockValidation: true
  });

  // QUESTION #8: blockchain.meta isn't updated. Why? Doesn't runBlock modify the blockchain?
  // QUESTION #9: blockchain.meta.heads is always {}, is this fine?
  console.log(blockchain.meta);

  // QUESTION #10: This gives me the genesis block. See question #8
  const latestBlock = await pblockchain.getLatestBlock();
  console.log(latestBlock.header.hash());
}

main().catch(console.error);

// Just a utility function to avoid passing callbacks and promisify entire objects
function promisifyAllMethods(object) {
  const pobject = {};

  for (const key in object) {
    const prop = object[key];
    if (prop instanceof Function) {
      pobject[key] = util.promisify(prop.bind(object));
    } else {
      pobject[key] = prop;
    }
  }

  return pobject;
}
```

Could you please help me with this?

Thanks!

**Comment by alcuadrado** [comment]
I think my confusion came from not understanding the purpose of `ethereumjs-blockchain`, my current understanding is that it's independent from the actual execution, but used for loading, validating and storing blocks.

I'm closing this issue, as the questions here are really broad and not very useful. Hopefully, I'll have the time to do a small writeup of my learnings of ethereumjs.

**Comment by s1na** [comment]
Sorry for not getting to this earlier. Given as you put it the "broad" questions, I was intending to sit down and go through your example at an appropriate time and try to answer the questions. But it seems they've been already somewhat clarified.

Yes, `ethereumjs-blockchain` is the data structure that stores information about a series of blocks, validates them and acts also as a wrapper for storing and fetching this data from the db. If you're looking for the actual evm bytecode execution, have a look at [runCode](https://github.com/ethereumjs/ethereumjs-vm/blob/master/lib/runCode.js), or [vm](https://github.com/ethereumjs/ethereumjs-vm/tree/master/lib/vm).

If you had further questions, I'd also like to refer you to our [gitter](https://gitter.im/ethereum/ethereumjs). Maybe you can also tell us about your experience with ethereumjs, and if there were any painpoints that we could address :)

**Comment by holgerd77** [comment]
Hi @alcuadrado, thanks for the detailed example write-up, this is really valuable as a thought-through real world usage example! 👍 😄 

We should really take some time and go through the questions a bit more detailed and take some time to think where there should be changes (docs/code/code docs) so that the questions don't have to be asked again and become self-explanatory.

@alcuadrado If you don't mind - I have adopted your title and reopened the issue to tackle this.

**Comment by holgerd77** [comment]
@alcuadrado If you can actually extract some PRs (e.g. on docs) or also more specific issues from you investigations that would for sure pretty helpful and very much welcome! 😄

**Comment by alcuadrado** [comment]
I'm copying some more questions I originally posted on gitter, as requested by Holger:

1) If I use the fakeBlockchain from ethereumjs-vm, I can't validate blocks when using runBlock or I get this error:
```
    TypeError: Cannot read property 'number' of undefined
        at /Users/pato/projects/buidler/inprocess-node/node_modules/ethereumjs-block/header.js:227:46
        at Object.getBlock (/Users/pato/projects/buidler/inprocess-node/node_modules/ethereumjs-vm/dist/fakeBlockChain.js:26:5)
        at module.exports.BlockHeader.validate (/Users/pato/projects/buidler/inprocess-node/node_modules/ethereumjs-block/header.js:219:14)
        at /Users/pato/projects/buidler/inprocess-node/node_modules/async/dist/async.js:3880:24
        at eachOfArrayLike (/Users/pato/projects/buidler/inprocess-node/node_modules/async/dist/async.js:1069:9)
        at eachOf (/Users/pato/projects/buidler/inprocess-node/node_modules/async/dist/async.js:1117:5)
        at _parallel (/Users/pato/projects/buidler/inprocess-node/node_modules/async/dist/async.js:3879:5)
        at Object.parallelLimit [as parallel] (/Users/pato/projects/buidler/inprocess-node/node_modules/async/dist/async.js:3962:5)
        at module.exports.Block.validate (/Users/pato/projects/buidler/inprocess-node/node_modules/ethereumjs-block/index.js:197:9)
        at validateBlock (/Users/pato/projects/buidler/inprocess-node/node_modules/ethereumjs-vm/dist/runBlock.js:85:15)
```
1.1) What validations am I missing?
1.2) Can I enable them? Do I have to use the full ethereumjs-blockchain for that? Should I make another fake blockchain? I won't have reorgs, so it should be easy.

2) It's hard to understand which validations are made in ethereumjs-vm and which ones in ethereumjs-blockchain.

3) I'm still confused about ethereumjs-common. Some packages accept a common, but the VM doesn't

4) Is the state modified if runBlock fails? I think it doesn't but can't find it in the docs.

5) Is EIP155 validated? Where?

6) I'm confused about when to use buffers, hex strings, and if they should have a 0x prefix or not. Is there a policy about this?



Self answer for 1.2: I made my own fake blockchain that tracks and returns actual blocks. Now I don't need to disable validations when running runBlock. Now I'm wondering about which validations I'm skipping apart from POW.


About 5: my code is definitely not validating EIP155 But may that's because I'm using mainnet's Common and my blocknumbers are super low.

This may sound somewhat confusing, because ethereumjs-tx does implement EIP155. What doesn't seem to be implemented is validating the signature v value when a tx was signed according to that EIP. I was expecting that validation from ethereumjs-vm.

**Comment by holgerd77** [comment]
Will leave this open for now, I think it will be interesting to go through these points some day and do some resume where we got along the way with the changes being done throughout the last months. 😄

**Comment by holgerd77** [comment]
I think various of these points here have been addressed in the one or the other way. If some specific aspect is still not solved on a satisfactory level a dedicated issue can be opened instead. Will close here.
