### ISSUE TITLE
Is state checkpointing in runBlock necessary?

### ISSUE THREAD

**Issue by s1na** [ethereumjs/ethereumjs-monorepo#622]
`runBlock` checkpoints the state before processing the block and reverts on errors. I'm not sure if this is necessary. I think it should throw if there's any error.

The state transition unit in Eth1 is the transaction. There we should revert state on failure. But a block is only a collection of txes which themselves handle checkpointing. If something fails on the block level it's a bug in our code and it shouldn't revert the state.

Also had a quick look at geth and couldn't find this revert on block processing failure. Maybe I'm missing something, but if others agree we should remove this.

**Comment by ryanio** [comment]
Lines for reference: https://github.com/ethereumjs/ethereumjs-vm/blob/master/lib/runBlock.ts#L99-L107

**Comment by holgerd77** [comment]
On the block level uncle and miner rewards are attributed and the state updated accordingly. We experimented with removing checkpointing in #1017, but it turned out to be necessary. Will close.
