### ISSUE TITLE
Discussion to implement semantic-release

### ISSUE THREAD

**Issue by ryanio** [ethereumjs/ethereumjs-monorepo#625]
This issue is a discussion to weigh the merits of using [semantic-release](https://github.com/semantic-release/semantic-release) in this repository.

> semantic-release automates the whole package release workflow including: determining the next version number, generating the release notes and publishing the package.
> This removes the immediate connection between human emotions and version numbers, strictly following the Semantic Versioning specification.

https://semantic-release.gitbook.io/semantic-release/

For our use case as a lerna monorepo, [lerna-semantic-release](https://github.com/atlassian/lerna-semantic-release) may be best.

**Comment by holgerd77** [comment]
I guess I am very much used to our current release process and like to rewrite and tweak release notes to give these some more user oriented touch. At the same time this issue has not been touched for quite some time.

Will therefore close for now.
