### ISSUE TITLE
Test reporting for State/Blockchain failures on GH Actions

### ISSUE THREAD

**Issue by evertonfraga** [ethereumjs/ethereumjs-monorepo#632]
#616 added test reporting for CircleCI, and it would be nice to have the same sort of benefits with GH Actions. State/Blockchain tests are so dense, it is quite bad to have to scroll through them to find the failing ones.

There's a range of solutions, some suggestions:
- Parse TAP output and display failing tests at the end
- Upload the test metadata
- Automatic comment with the failing tests on the PR

**Comment by ryanio** [comment]
Links for reference:
* Upload test metadata: https://github.com/actions/upload-artifact
* Automatic comment on PR: https://github.com/unsplash/comment-on-pr

**Comment by jochem-brouwer** [comment]
This is solved right? If there are any errors in the CI, then at the end of the test run, all tests which are failed are reported at the end of all tests, including the relevant error message. @ryanio

See [here](https://github.com/ethereumjs/ethereumjs-monorepo/blob/bffbc0385d0aef62097fd1bffeb9abdecdaa344d/packages/vm/tests/tester/index.ts#L204).

**Comment by ryanio** [comment]
yep! thanks
