### ISSUE TITLE
Repository admin log

### ISSUE THREAD

**Issue by evertonfraga** [ethereumjs/ethereumjs-monorepo#722]
**This is a special issue that aims to track internal changes to the repository that are not present in the git history.**

---

**LOG1**:  Waffle.io has gone away, so I am removing its webhook for this repository.

![79568620-28fe1500-8084-11ea-8ec0-8d171cba76c7](https://user-images.githubusercontent.com/47108/79568779-78444580-8084-11ea-9d46-64c1584db1be.png)

**Comment by holgerd77** [comment]
Oh, that's a clever way of making admin changes explicit, nice.

**Comment by evertonfraga** [comment]
The CI job names changed after #735. I just made the correspondent changes to the required checks, from: 

```
  test-api
  test-blockchain
  test-state
```

to: 

```
  test-vm-api
  test-vm-blockchain
  test-vm-state
```

**Comment by holgerd77** [comment]
Never picked up, even if idea was nice, will close for now.

Feel free to reopen if you plan to integrate into everyday usage.
