### ISSUE TITLE
Common: Add isPrecompiled method

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#727]
The `isPrecompiled` method is currently [being removed](https://github.com/ethereumjs/ethereumjs-util/pull/242) from the `ethereumjs-util` library, since the library has no notion of a "hardfork" and the method is therefore pretty error-prone.

Instead `isPrecompiled` might be a better fit in the `Common` class and give out the respective answers depending on the HF set on the common instance.

Not sure if this is needed or if there is a strong demand, just drop this here for some eventual discussion and/or remembrance.

**Comment by jochem-brouwer** [comment]
This should have been exposed in [this PR](https://github.com/ethereumjs/ethereumjs-vm/pull/783). It is trivial, I'll add it.

**Comment by jochem-brouwer** [comment]
Actually it is not trivial where we should expose this function. Should we expose this on top of the VM? This only has things like `runCall`, `runBlock`, etc. Feels a bit weird to put this "utility" function there. It feels more natural to put it in the EVM, but the VM does not appear to have a pointer to the EVM? Where should we expose this function?

I think it is good to think about this, as we might get demand for some more of these utility-like functions. We need to know where to place those.

**Comment by holgerd77** [comment]
Ah - attention! 😄  - this is an issue associated to the `Common` library, so "here" means "Common" in this case.

So this would be a utility function in `Common` to return the precompile status of an account based on some precompile info which would need to be added to the HF files.

Not sure if it's worth to be added right now tbh, would be nice to have but also some significant effort to integrate.

**Comment by jochem-brouwer** [comment]
Oops - I didn't see that this was actually the Common package.

We have a slight problem here as currently the hardforks are hard-coded (hah!) in `index.ts` of [precompiles](https://github.com/ethereumjs/ethereumjs-vm/blob/55c4a1eb56e3439e2364e9ee067e8da0331de9f1/packages/vm/lib/evm/precompiles/index.ts#L43). It would make more sense to let the precompiles call into Common: `getPrecompile` actually has access to `Common` now so this should not be a problem.

I currently don't know how we should do this in a clean way. We could maybe create a map in common where we loop over each fork, latest first, and either return a precompile (I guess this should be an enum so we can support different precompiles at the same address if this happens at some point (?)) or we return that no precompile exists at this address? And then build the trivial `isPrecompiled` on top of that.

**Comment by jochem-brouwer** [comment]
I am not sure if this is possible in Common anymore, since we now have custom precompiles, which Common is not aware of?

**Comment by holgerd77** [comment]
I will close this issue for now since it is open for 2+ years and was in discussion respectively not completely clear if wanted/needed from the beginning.

Fell free to re-open if the need (re-)arises.
