### ISSUE TITLE
stateManager: add modifyAccountFields method

### ISSUE THREAD

**Issue by s1na** [ethereumjs/ethereumjs-monorepo#731]
Discussing the API with @jochem-brouwer we thought it might be easier from a developer PoV to have a `modifyAccountFields` that internally fetches an account from the trie, modify the given fields and then do a `putAccount`. This is to avoid users having to to the `getAccount` everytime they want to change an account. The method should probably throw if account doesn't exist.

**Comment by holgerd77** [comment]
This is still open (I would also say still useful?) and a potentially good first issue for some trie-releated `StateManager`/`VM` work.

Please assign yourself if you want to take and also add a test case testing the new method.

**Comment by emersonmacro** [comment]
I can try to tackle this
