### ISSUE TITLE
Mock ethereumjs-blockchain in ethereumjs-block tests

### ISSUE THREAD

**Issue by evertonfraga** [ethereumjs/ethereumjs-monorepo#746]
https://github.com/ethereumjs/ethereumjs-block/pull/93 aimed to increase test coverage, but it introduced a circular dependency, breaking the monorepo workflow with Lerna. This commit has removed it: https://github.com/ethereumjs/ethereumjs-vm/pull/682/commits/4cba1bac75acdc493e5de8b56f9df77710a6e208.

We should be able to unit-test Block by mocking or faking `ethereumjs-blockchain` behavior, in order to increase coverage for the Block test suite.

**Comment by holgerd77** [comment]
Can't find the reference PR but checked on `master` and this has been solved, will close.
