### ISSUE TITLE
VM: RunCode() and runCall() edits state

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/ethereumjs-monorepo#799]
As opposed to what I would expect, `RunCode` and `RunCall` actually edits the state. When coming from the `web3` world, where one can `call`/`send`, we know that if we `call` then the state does not change, but if we `send` and the transaction gets mined, then the state does change.

I know that we are talking about the context of Transactions in the `web3` variant, but I think the assumption that `runCall` / `runCode` does not change state is a logical one when coming from the `web3` world.

I therefore propose that we add a flag to `RunCodeOpts` and `RunCallOpts` which is `false` by default: `editState` or something similar would this option be called. When set to `true`, the state is `committed` at the end of `runCode` / `runCall`, if not, the state is rolled back at the end of those function calls. Of course, if this happens internally in the VM, we set this option to `true`.

Related: #613, I think we could merge these two issues into a single PR after we had a discussion here.

**Comment by holgerd77** [comment]
As mentioned, related to #613, can very well be part of an eventual solution space if needed, but will close here for simplicity.
