### ISSUE TITLE
Upgrade nyc to v15

### ISSUE THREAD

**Issue by evertonfraga** [ethereumjs/ethereumjs-monorepo#832]

**Comment by holgerd77** [comment]
This is a relatively beginner friendly issue (there might nevertheless be unexpected glitches on these kind of updates though). If someone wants to take please assign yourself to the issue.

**Comment by holgerd77** [comment]
Additional note: maybe wait for some answer from @ryanio on [this question](https://github.com/ethereumjs/ethereumjs-monorepo/pull/1297#discussion_r651542625) from the config transition PR in #1297 on the correct placement of the config developer dependencies.

**Comment by ryanio** [comment]
Actually we are already on nyc v14 in the monorepo with the exception of the `vm` which is on `v12` for some compatibility reasons (maybe this can be investigated if this is still needed, as with lerna hoisting it is best to have all versions aligned)

I added this note to the new config readme:

> Shared config `devDependencies` across all packages can go in the root `package.json`. However, if a package needs access to the dependency's `bin` (e.g. `eslint` or `nyc`) then it must be defined in the child packages' `package.json`.

**Comment by holgerd77** [comment]
@ryanio ah great, thanks, actually didn't know about this `bin` rule at all yet! 😅
