### ISSUE TITLE
Project suggestion: rewrite ethash (merge with node-ethash)

### ISSUE THREAD

**Issue by axic** [ethereumjs/ethereumjs-monorepo#845]
This is explained in more detail in https://github.com/ethereumjs/node-ethash/issues/1 and especially https://github.com/ethereumjs/node-ethash/issues/1#issuecomment-405692741.

**Comment by holgerd77** [comment]
Have moved this over to the monorepo, think this is a better fit and will get a better chance to followed-up upon. In the `organization` repo it is a bit unexpected.

**Comment by holgerd77** [comment]
Likely no more ressources attributed to this due to the Merge, will close.
