### ISSUE TITLE
VM: Add BLS precompile support for browsers

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/ethereumjs-monorepo#862]
[PR 785](https://github.com/ethereumjs/ethereumjs-vm/pull/785) introduces the BLS curves, but these do not seem to work in browser. Fixing that seems to be a rather complicated process. If this PR gets merged then we have BLS support, but it does not work in browser, we should add this support.

**Comment by holgerd77** [comment]
There seems to be some renewed interest on the associated EIP https://github.com/ethereum/pm/issues/343 and there is some likelyhodd this gets included in the (one) next feature fork, so we should pick up at some point here.

**Comment by dapplion** [comment]
@holgerd77 Take a look at https://github.com/fetchai/blst-ts/pull/1 :eyes: potential support for browsers of blst which is the lib used by all consensus clients in production over Herumi

**Comment by paulmillr** [comment]
I heard someone wanted to utilize noble-bls12-381: it is 5-10x slower than blst.wasm, so not sure if it's worth it. Also there have been no audits.
