### ISSUE TITLE
Possible way to stabilize CI's benchmark measurements

### ISSUE THREAD

**Issue by cgewecke** [ethereumjs/ethereumjs-monorepo#897]
In the last team meeting, the question of the CI benchmark's variability was mentioned - it's common to see large-ish performance diffs from change sets that don't seem like they'd have much impact. 

Per [comment in the benchmark actions repo][1] this might be caused by comparing runs which have been executed on  different physical machines in the cloud.

An alternative to comparing the current run against a previously cached version is to:
+ run current branch benchmark --> save to file `A`
+ checkout master
+ run master benchmark --> save to file `B`
+ compare `A` and `B`

That strategy proposed and implemented here:
+ [clap-rs/clap benchmark discussion][2]
+ [clap-rs/clap benchmark actions yml][3]

[1]: https://github.com/rhysd/github-action-benchmark/issues/21
[2]: https://github.com/clap-rs/clap/pull/1755#issuecomment-601683195
[3]: https://github.com/clap-rs/clap/blob/master/.github/workflows/benchmark.yml

**Comment by ryanio** [comment]
I started down this path but actually our data looks pretty stable according to the [benchmark page](http://ethereumjs.github.io/ethereumjs-vm/dev/bench/).

Since others have expressed that the commit comments are a bit verbose though, I will disable `comment-always` and decrease the alert threshold from `200%` to `150%` so we will only get alert comments if it exceeds. PR: https://github.com/ethereumjs/ethereumjs-vm/pull/899

**Comment by cgewecke** [comment]
Out of curiosity what does that threshold mean in practice? That a change has been introduced which results in a 50% slowdown?

**Comment by ryanio** [comment]
yes so for the first benchmarked block 9,422,905 around 1,700 ops/sec it would have to exceed 2,550 ops/sec to trigger an alert comment.

**Comment by ryanio** [comment]
actually that being the most stable one, the blocks with higher amplitudes (like 9,422,912) may trigger it pretty often. what do you think of keeping it at the default of 200%?

**Comment by holgerd77** [comment]
This issue is referenced in #1204, will close here to reduce redundancy.
