### ISSUE TITLE
Sources for source-maps are missing in distributed packages

### ISSUE THREAD

**Issue by rumkin** [ethereumjs/ethereumjs-monorepo#902]
Due to current `package.json` configuration all packages import only `dist` folder. But source map files maps to `src` (or `lib`) directory. You can see it on [unpkg.com](https://unpkg.com/browse/ethereumjs-vm@4.2.0/dist/index.js.map) at the first line: `"sources":["../lib/index.ts"]`. Thus source maps couldn't be loaded what makes them useless. It requires to change`package.json#files` record to include `/dist` and `/src` or `/lib` folders respectively into package distribution.

**Comment by rumkin** [comment]
Also there is the same PR for RLP library: https://github.com/ethereumjs/rlp/pull/97.

**Comment by holgerd77** [comment]
Ah, just left a comment on the RLP issue linked above, of course relevant here as well. Please everyone answer there so that we have one unclustered discussion. Thanks!

**Comment by holgerd77** [comment]
There is a new issue (same request) opened on this where the discussion is continued, will close here.
