### ISSUE TITLE
v5 Releases Community and Testing Feedback

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#923]
We are currently closing in on a major release series on all monorepo packages including the VM. These releases bring a pack of modernization changes (TypeScript, Promises, ES6) as well as major rewrites of substantial parts of various libraries. Also important to note that we switch to a new package naming scheme with scoped package names along this process, e.g.:

`ethereumjs-vm` -> `@ethereumjs/vm`

All this is the culmination of 6+ months of work from the whole team and since changes are so broad we are going through a somewhat more preparatory/cautious release process than normal with now having two beta release series out and - if everything goes well - closing in with a `RC` and then a final release, planned dates are:

- 19.11. (Thursday): **rc.1 Releases** with to-be-considered final versions
- 24.11. (Tuesday the follow-up weeek): **Final Releases**

On the time of writing these are the latest releases done, `beta` releases contain extensive release notes:

- [@ethereumjs/common v2.0.0-beta.2](https://github.com/ethereumjs/ethereumjs-vm/releases/tag/%40ethereumjs%2Fcommon%402.0.0-beta.2)
- [@ethereumjs/tx v3.0.0-beta.2](https://github.com/ethereumjs/ethereumjs-vm/releases/tag/%40ethereumjs%2Ftx%403.0.0-beta.2)
- [@ethereumjs/block v3.0.0-beta.2](https://github.com/ethereumjs/ethereumjs-vm/releases/tag/%40ethereumjs%2Fblock%403.0.0-beta.2)
- [@ethereumjs/blockchain v5.0.0-beta.2](https://github.com/ethereumjs/ethereumjs-vm/releases/tag/%40ethereumjs%2Fblockchain%405.0.0-beta.2)
- [@ethereumjs/vm v5.0.0-beta.2](https://github.com/ethereumjs/ethereumjs-vm/releases/tag/%40ethereumjs%2Fvm%405.0.0-beta.2)

We encourage everyone - both the direct consumers of our libraries and the interested Ethereum JavaScript community - to have an early look and see if all the design decisions we made there play well with how you use our libraries. For feedback you can best use our [Discord](https://discord.gg/TNwARpR), you will also find some dedicated explainer articles on the new releases in the #announcements channel.

**Comment by cgewecke** [comment]
(Not sure if this is the right issue to file this under) 

Am working on a trial upgrade of the ethereumjs stack to V5 at ganache-core as part of beta testing.  Will open separate issues for any issues found.

**Comment by alcuadrado** [comment]
When focusing on the launch of Hardat, I fell out of the loop of v5 a bit, and I'd love to get some experience on what would it take to upgrade the vm in HH, so I can give better feedback. What's the best place to get back in sync?

**Comment by ryanio** [comment]
@alcuadrado I'd say start with the changelogs, they are pretty comprehensive.

**Comment by holgerd77** [comment]
Have updated the initial post here.

I would especially encourage the following people to give a look:

- @davidmurdoch (Ganache/Truffle)
- @alcuadrado (Hardhat)
- @rekmarks (Metamask)
- @yann300 (Remix)
- @samajammin (Ethereum.org)

If someone has other people to loop in please mention in follow-up comments.

**Comment by jochem-brouwer** [comment]
Our client uses `_getTd` which is now marked `private` in `blockchain`, would make sense to create a public method to get the total difficulty.

**Comment by davidmurdoch** [comment]
Thanks for the tag, @holgerd77. I'll try to take a peek and run some tests next week!

**Comment by davidmurdoch** [comment]
Oh, how's the performance now? I noticed some changes in the way block and transaction props are being handled and they look like they might greatly improve performance.

**Comment by holgerd77** [comment]
@davidmurdoch that would be a great side effect 😄 , we haven't optimized for performance though on this release, our `benchmarking` CI check we [do have](https://github.com/ethereumjs/ethereumjs-vm/pull/939/checks?check_run_id=1387144258) in the meantime for the VM is unfortunately not as expressive yet as we hoped for and this needs further refinements. But there is structural simplification all over the place (and especially in the block and tx libraries) along these major releases, might very well be that this has also streamlined/optimized execution (but to be plain honest: this might be the overlay picture and it is very well possible that some changes also decreased performance, we just don't have a transparent picture here).

**Comment by holgerd77** [comment]
Will leave this a bit open for now for people who want to give general feedback on the final releases, have adopted the title accordingly.

Anyone with a dedicated issue you are perceiving or a potential bug, feel also free to open a separate issue if more appropriate!

**Comment by holgerd77** [comment]
v5 is now out for more than 2 months, will close here, anyone stumbling upon v5 issues feel free to open a dedicated issue.
