### ISSUE TITLE
Ethash: check possible invalid RLP input data in tests

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/ethereumjs-monorepo#943]
`validBlockRlp` from `ethash_block_rlp_tests.json` has a lot of `extraData` (>32 bytes) if you try to create the block. The block number is 1 so it is not a Genesis block. This RLP should be invalid. What is the purpose of this extra data? Why is there an invalid block used as test in ethash?

**Comment by holgerd77** [comment]
These kind of smaller issues should be validated and/or tackled at some point so that they don't lay around forever. 😛
