### ISSUE TITLE
Blockchain/Block: move Block validation methods to Blockchain

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/ethereumjs-monorepo#947]
Currently, `BlockHeader` validates data in the constructor (except `extraData` length which seems to have to do with an (invalid?) Ethash test, #943). For some reason, `Block` does not do this in the constructor, but instead validates this data (which is readily available in the constructor) in the `validate` method. Besides that, in both `Block` and `BlockHeader`, `validate` also validates the header/block which depends on other blocks (which thus depends on blockchain).

As raised by @holgerd77 in #935, it is an idea to explore the idea of instead validating this in `blockchain`, instead of `block`. We should also figure out why `header` validates data in the constructor and `block` does not.

**Comment by holgerd77** [comment]
Have added this to the v6 release planning notes in #1024

**Comment by holgerd77** [comment]
Super-seded  by #1879, will close
