### ISSUE TITLE
Client: Feature Requests Tracking Issue

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/ethereumjs-monorepo#960]
This issue tracks feature requests which we need from the client.

**VM**

- [ ] TODO

**Blockchain**

- [x] `iterator`: add `maxBlocks` parameter to allow running the iterator for at most `maxBlocks` blocks. Closed in #965 

 This is necessary because we want to only run one block from the client, and don't want to run the entire chain (because this keeps the DB locked). 

- [x] The specific API which we would also need is a `setHead(tag: string, headHash: Buffer)`, so we can set the head of a certain `tag`. Related: #691. Closed in #965

**Comment by holgerd77** [comment]
Is it ok if we widen this issue to track feature requests for all monorepo libraries?

**Comment by jochem-brouwer** [comment]
Sure!
