### ISSUE TITLE
Client JSON-RPC Support

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#982]
#### Description

Implementation of the ``JSON-RPC`` interface as described in https://github.com/ethereum/wiki/wiki/JSON-RPC.

This encompasses a server implementation and the implementation of the various API calls.

#### Possible Implementation

It probably best to start with an early-on implementation of 2-3 exemplary API calls and then refine this for some time to work out a good internal structure to build upon and extend with the further calls.

There are various Javascript libraries [out there](https://github.com/search?l=JavaScript&q=ethereum+rpc&type=Repositories) touching the topic, not sure if any can be of help here or be integrated/used, this should be examined more closely.

#### UI

The RPC server should be constantly running and be available via some configured address and port.

### Implement all JSON-RPC Endpoints

Update (2018-07-10): This has been adressed in https://github.com/ethereumjs/ethereumjs-client/pull/30 by @yurenju, providing a very solid structure for implementation and testing. It is now possible to implement the single RPC endpoints (limited by the functionality already implemented in the core client code).

Checklist of endpoints to support, and which are supported in master or pull requests (taken from [Py-EVM](https://github.com/ethereum/py-evm/issues/835):

- [x] Support all the web_* methods
  - [x] web3_clientVersion
  - [x] web3_sha3

---

- [x] support all the net_* methods
  - [x] net_listening
  - [x] net_peerCount
  - [x] net_version #840

---

- [ ] support all the eth_* write methods
  - [ ] make list of methods

---

- [ ] support all the eth_* read-only methods
  - [x] eth_protocolVersion
  - [ ] eth_syncing
  - [ ] eth_coinbase
  - [ ] eth_mining
  - [ ] eth_hashrate
  - [ ] eth_gasPrice
  - [ ] eth_accounts
  - [x] eth_blockNumber
  - [ ] eth_getBalance
  - [ ] eth_getStorageAt
  - [ ] eth_getTransactionCount
  - [ ] eth_getBlockTransactionCountByHash
  - [ ] eth_getBlockTransactionCountByNumber
  - [ ] eth_getUncleCountByBlockHash
  - [ ] eth_getUncleCountByBlockNumber block int
  - [ ] eth_getUncleCountByBlockNumber block string
  - [ ] eth_getCode
  - [ ] eth_call
  - [ ] eth_estimateGas
  - [x] eth_getBlockByHash
  - [x] eth_getBlockByNumber block int
  - [ ] eth_getBlockByNumber block string
  - [ ] eth_getTransactionByHash
  - [x] eth_getTransactionByBlockHashAndIndex
  - [x] eth_getTransactionByBlockNumberAndIndex
  - [ ] eth_getTransactionReceipt
  - [ ] eth_getUncleByBlockHashAndIndex
  - [ ] eth_getUncleByBlockNumberAndIndex block int
  - [ ] eth_getUncleByBlockNumberAndIndex block string
  - [ ] eth_getCompilers
  - [ ] eth_getLogs
  - [ ] eth_getWork

Note: On a first round I've just copied over all calls, this might be limited by functionality which eventually shall not be implemented in the client (mining related stuff e.g.).

#### Reference Implementations / Links

- [Py-EVM trinity RPC implementation](https://github.com/ethereum/py-evm/tree/master/trinity/rpc)

**Comment by holgerd77** [comment]
@ryanio I've read in some internal chats - I think from someone from the geth team - that RPC methods would be valuable for debugging and comparing results when clients are joining the Yolo testnet. So if you are not sure what to work on next adding (some) RPC methods is always a good candidate I guess. Maybe you want to have a closer look what might be the more useful ones to have, not sure, haven't given this any thought yet (others can suggest as well of course).

**Comment by ryanio** [comment]
@holgerd77 sounds good, I really like the setup of the RPC modules code with the methods on the classes, it makes it natural to use in TypeScript. I'm seeing that it's currently callback based though, I can start with a PR updating it to async/promises then start adding some useful methods.

I started a tracking table in #1114 to visualize some more namespaces I found.

**Comment by holgerd77** [comment]
Ok, great! 😄 

Will then close here in favor of #1114
