### ISSUE TITLE
Client Hive setup

### ISSUE THREAD

**Issue by vpulim** [ethereumjs/ethereumjs-monorepo#986]
Create a hive configuration for client so we can have a test environment for chain syncing and block validation.

**Comment by evertonfraga** [comment]
Do we have the artifacts from @PhilippLgh work here?

**Comment by holgerd77** [comment]
I think there hasn't been further work on this, not sure, we down-prioritized this somewhat down the road anyhow. So we'll see if we want to continue here or rather put this aside for now.

**Comment by holgerd77** [comment]
Added in https://github.com/ethereum/hive/pull/510, will close.
