### ISSUE TITLE
Client: refactor bin/cli.ts to TS (and add basic client test)

### ISSUE THREAD

**Issue by cgewecke** [ethereumjs/ethereumjs-monorepo#997]
`bin/cli.ts` still needs its imports and types worked through.

Would also be nice to have a simple test in CI that runs the client and listens for errors / makes sure blocks are being downloaded...
```
tsc -p tsconfig.prod.json && node dist/bin/cli.js
```

**Comment by holgerd77** [comment]
Fixed by #160 and #176, will close.
