### ISSUE TITLE
Client: Logger Improvement Discussion

### ISSUE THREAD

**Issue by rumkin** [ethereumjs/ethereumjs-monorepo#998]
#### Description

I'm working on ethereumjs/ethereumjs-vm#995 issue and exactly on PR ethereumjs/ethereumjs-client#168 to update winston logger package. I've opened git comparison of changes made from [v3.1.0 to 3.3.3](https://github.com/winstonjs/winston/compare/3.1.0...v3.3.3) and found a lot of things to be audited:
* Dependencies: **7**
* LOC: **657**

I think an audit of all the changes would be pretty hard and actually is out of scope of EthereumJS development. I believe we need to reduce audit process complexity by reducing number of dependencies where it is possible. This is why I propose to remove winston, replace internal logger with some sort of shim and let users to bring their own logger in some predictable and convenient way.

### Proposal

1. Replace winston with a simplified logger. This logger should provide log-level, message, and props values, like this:
   ```ts
   logger.warn('Peer error', {error, peer}) 
   ```
3. Distribute client with Geth-compatible logger. Optional.
4. Create EthereumJS Client config file (maybe `ethereumjs.config.js`) by analogy with webpack or eslint config files (`webpack.config.js`, `.eslint.js`)  to let users to configure ethereumjs client and bring their own logger if they need it, for example JSON-logger to use with enterprise-level log analyzing tools like [Elastic Stack](https://www.elastic.co/elastic-stack) , or [Prometheus](https://prometheus.io/); or to use binary logger to effectively store logged data.

### Pros

1. Reduced cumulative complexity and simplified audit.
2. Reduced installation size.
3. Logger params are presented as an JS Values not a strings, what allows to convert logged values to multiple data formats based on target output, preserve error log for log records like `Peer error`: https://github.com/ethereumjs/ethereumjs-client/blob/6deddf59afe3b7b6e91c8939f13e44f217e70bb3/lib/net/peerpool.ts#L147.

### Cons

1. It's a breaking change.

**Comment by holgerd77** [comment]
I assume this won't be prioritized anytime soon, will close.
